package com.born.insurance.webui.control;

/**
 *
 * <p>Title: javascript function of the calendar control</p>
 * <p>Description: javascript function of the calendar control</p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: bornsoft</p>
 * @author: �ᴺ��
 * @version 1.0
 */
public class CalendarJS {

  /**
   * <p><B>Description: get javascript functions of the calendar control</B></p>
   * @param path: path of the javascript file
   * @return: the reference of the javascript file
   * <p>OFBIZCalendar_getValue</p>
   * <b>param:</b> calendarId, <b>paramType:</b>String
   * <p>OFBIZCalendar_setValue</p>
   * <b>param:</b> calendarId, <b>paramType:</b>String
   * <b>param:</b> dateStr, <b>paramType:</b>String, <b>description:���ڱ�����ȷ</b>
   * <p>OFBIZCalendar_setProperty</p>
   * <b>param:</b> calendarId, <b>paramType:</b>String
   * <b>param:</b> property, <b>paramType:</b>String, <b>description:�������Ե�������ƣ�Ϊwidth��necessary����readonly</b>
   * <b>param:</b> value, <b>paramType:</b>String or int, <b>description:�������Ե�ֵ��Ϊ����ת��Ϊbool�ͻ�int�͵��ַ��磺"true","3"</b>
   * <p>OFBIZCalendar_setFocus</p>
   * <b>param:</b> calendarId, <b>paramType:</b>String
   */
  public static String getCalendarJS(){
		JSTool jstool=new JSTool("CalendarJS.js");
		StringBuffer js = new StringBuffer();
		if(!jstool.util.isUpdateJsEveryTime())
		 {
			 return jstool.getComponentJS() ;//+ HashMapJS.getHashMapJS();
		 }
		js.append("		var OFBIZCalendar_ShortWeek = new Array(\"��\",\"һ\",\"��\",\"��\",\"��\",\"��\",\"��\");\r\n");
		js.append("		var OFBIZCalendar_Month = new Array(\"һ\" , \"��\" , \"��\" , \"��\" , \"��\" , \"��\", \"��\" , \"��\" , \"��\" , \"ʮ\" , \"ʮһ\" , \"ʮ��\");\r\n");
		js.append("		var daysInMonth = new Array(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31);\r\n");
		js.append("		var allowKeyPress = true;\r\n");
		js.append("        function OFBIZCalendar_getTop(calendarId, div)\r\n");
		js.append("		{\r\n");
		js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var o = textBox;\r\n");
		js.append("			iPos = 0;	\r\n");
		js.append("            		var popHeight = parseInt(calendar.getAttribute(\"popHeight\"));\r\n");
		js.append("            		document.body.appendChild(div);\r\n");
		js.append("           		while (o!=null) 	\r\n");
		js.append("			{	\r\n");
		js.append("				if(o.tagName == \"DIV\")\r\n");
		js.append("				{\r\n");
		js.append("					iPos += o[\"offsetTop\"] - o[\"scrollTop\"];	\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					iPos += o[\"offsetTop\"];	\r\n");
		js.append("				}\r\n");
		js.append("				o = o.offsetParent;\r\n");
		js.append("			}\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			var addHeight=0;\r\n");
		js.append("			var addTop=0;\r\n");
		js.append("			if(isViewTime==\"true\")\r\n");
		js.append("			{\r\n");
		js.append("				addHeight=-18;\r\n");
		js.append("				addTop=-30;\r\n");
		js.append("			}\r\n");
		js.append("			if(iPos + textBox.offsetHeight + 1 + popHeight - document.body.scrollTop > window.screen.availHeight - 200+addHeight)\r\n");
		js.append("			{\r\n");
		js.append("				iPos = iPos - popHeight - 1 - textBox.offsetHeight - 15+addTop;\r\n");
		js.append("				div.style.top = iPos;\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				iPos = iPos + textBox.offsetHeight + 1;\r\n");
		js.append("				div.style.top = iPos;\r\n");
		js.append("			}			\r\n");
		js.append("			return iPos;	\r\n");
		js.append("		}	\r\n");
		js.append("		\r\n");
		js.append("		function OFBIZCalendar_getLeft(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var o = textBox;\r\n");
		js.append("			iPos = 0;	\r\n");
		js.append("            var popWidth = parseInt(calendar.getAttribute(\"popWidth\"));\r\n");
		js.append("			while (o!=null) 	\r\n");
		js.append("			{	\r\n");
		js.append("				iPos += o[\"offsetLeft\"] - o[\"scrollLeft\"];	\r\n");
		js.append("				o = o.offsetParent;	\r\n");
		js.append("			}\r\n");
		js.append("			iPos += document.body.scrollLeft;\r\n");
		js.append("			if(iPos + 16 + popWidth > window.screen.width)	\r\n");
		js.append("			{\r\n");
		js.append("				iPos = iPos + 16 + textBox.offsetWidth - popWidth;\r\n");
		js.append("			}\r\n");
		js.append("			return iPos + 2;	\r\n");
		js.append("		}\r\n");
		js.append("		\r\n");
		js.append("		function OFBIZCalendar_showPop(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var textBox = document.getElementById(calendarId + \"_textBox\")\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var div = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
		js.append("          	 if(div.getAttribute(\"popShow\") == \"false\")\r\n");
		js.append("           	{\r\n");
		js.append("            	  div.setAttribute(\"popShow\", \"true\");\r\n");
		js.append("          	 }\r\n");
		js.append("           	else\r\n");
		js.append("           	{\r\n");
		js.append("            	  div.setAttribute(\"popShow\", \"false\");\r\n");
		js.append("            	  return;\r\n");
		js.append("          	 }\r\n");
		js.append("			var height = calendar.getAttribute(\"popHeight\");\r\n");
		js.append("			var width = calendar.getAttribute(\"popWidth\");\r\n");
		js.append("			\r\n");
		js.append("			var left = OFBIZCalendar_getLeft(calendarId);\r\n");
		js.append("			div.style.left = left;\r\n");
		js.append("			var top = OFBIZCalendar_getTop(calendarId, div);\r\n");
		js.append("			div.innerHTML = OFBIZCalendar_setPop(calendarId);			\r\n");
		js.append("			div.style.visibility = \"visible\";\r\n");
		js.append("			div.style.width = width;\r\n");
		js.append("			div.style.height = height;\r\n");
		js.append("			hideElement(\"select\",div);\r\n");
		js.append("			hideElement(\"applet\",div);\r\n");
		js.append("			//hideOtherDiv(div);\r\n");
		js.append("			div.setActive();\r\n");
		js.append("			\r\n");
		js.append("		}		\r\n");
		js.append("		function hideOtherDiv(divObj)\r\n");
		js.append("		{\r\n");
		js.append("			for(var index = 0; index<document.getElementsByTagName(\"div\").length; index++)\r\n");
		js.append("			{\r\n");
		js.append("				var otherDiv = document.getElementsByTagName(\"div\")[index];\r\n");
		js.append("				if(otherDiv.getAttribute(\"type\")==\"calendar_pop\" && otherDiv.id != divObj.id)\r\n");
		js.append("				{\r\n");
		js.append("					hiddenDiv(otherDiv);\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					continue;\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("		}			\r\n");
		js.append("		function OFBIZCalendar_setPop(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var textBox = document.getElementById(calendarId);\r\n");
		js.append("			var today = OFBIZCalendar_getToday(calendarId);		\r\n");
		js.append("			var title = OFBIZCalendar_getTitle(calendarId);\r\n");
		js.append("			var dayHeader = OFBIZCalendar_getDayHeader(calendarId);\r\n");
		js.append("			var cellsStr = OFBIZCalendar_getCells(calendarId);\r\n");
		js.append("			\r\n");
		js.append("			var html=new String();\r\n");
		js.append("			html += \"<font face='����'><table style=\\\"border-width:1px; border-color:black; border-style:solid;\\\">\";\r\n");
		js.append("			html += title;\r\n");
		js.append("			html += today;\r\n");
		js.append("			html += dayHeader;\r\n");
		js.append("			html += cellsStr;	\r\n");
		js.append("			\r\n");
		js.append("			return html;\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_getCurDate(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var curDateStr = calendar.getAttribute(\"curDate\");\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");			\r\n");
		js.append("			return OFBIZCalendar_parseToDate(curDateStr,isViewTime);\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_getDefaultDate(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var defaultDateStr = calendar.getAttribute(\"defaultDate\");\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			if(defaultDateStr == null)\r\n");
		js.append("			{\r\n");
		js.append("			    return null;\r\n");
		js.append("			}\r\n");
		js.append("			return OFBIZCalendar_parseToDate(defaultDateStr,isViewTime);\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_getSelectedDate(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var selectedDateStr = calendar.getAttribute(\"selectedDate\");		\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			if(selectedDateStr == null || selectedDateStr == \"\")\r\n");
		js.append("			{\r\n");
		js.append("			 	return null;\r\n");
		js.append("			}\r\n");
		js.append("			return OFBIZCalendar_parseToDate(selectedDateStr,isViewTime);\r\n");
		js.append("		}			\r\n");
		js.append("		function OFBIZCalendar_parseToDate(dateStr,isViewTime)\r\n");
		js.append("		{			\r\n");
		js.append("			if(dateStr==\"\"||dateStr==\" \")\r\n");
		js.append("			{\r\n");
		js.append("				var newDate = new Date();\r\n");
		js.append("				return newDate;	\r\n");
		js.append("			}\r\n");
		js.append("			var dateArr = dateStr.split(\"-\");\r\n");
		js.append("			var year = OFBIZCalendar_getIntData(dateArr[0]);\r\n");
		js.append("			var month = OFBIZCalendar_getIntData(dateArr[1]) - 1;						\r\n");
		js.append("			var day=dateArr[2].split(\" \");\r\n");
		js.append("			var date = OFBIZCalendar_getIntData(day[0]);\r\n");
		js.append("			var newDate = new Date();\r\n");
		js.append("			newDate.setFullYear(year , month , date);\r\n");
		js.append("			if(isViewTime==\"true\"&&dateArr[2].indexOf(\":\")>-1)  \r\n");
		js.append("			{\r\n");
		js.append("				var timeArray=day[1].split(\":\");\r\n");
		js.append("				if(timeArray[0]==\"00\")\r\n");
		js.append("				{\r\n");
		js.append("					newDate.setHours(0);\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					newDate.setHours(OFBIZCalendar_getIntData(timeArray[0]));\r\n");
		js.append("				}\r\n");
		js.append("				if(timeArray[1]==\"00\")\r\n");
		js.append("				{\r\n");
		js.append("					newDate.setMinutes(0);\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					newDate.setMinutes(OFBIZCalendar_getIntData(timeArray[1]));\r\n");
		js.append("				}				\r\n");
		js.append("			}			\r\n");
		js.append("			return newDate;	\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZCalendar_getToday(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var html = new String();\r\n");
		js.append("			var curDate = OFBIZCalendar_getCurDate(calendarId);\r\n");
		js.append("			html += \"<tr style=\\\"background-color:white;  font-size:12px; text-align:center;\\\"><td colspan=7>&nbsp;&nbsp;<a href=\\\"#\\\" onclick=\\\"window.OFBIZchangeToCurDate(\";\r\n");
		js.append("			html += \"'\"+ calendarId +\"');\\\" style=\\\"text-align:center; color:black;\\\">����</a>��\";\r\n");
		js.append("			html += curDate.getFullYear() + \"��\";\r\n");
		js.append("			html += (parseInt(curDate.getMonth())+1) + \"��\";\r\n");
		js.append("			html += curDate.getDate() + \"��\" +\"&nbsp;</td></tr>\";\r\n");
		js.append("			return html;\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_getTitle(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var sDate = new Date();\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			sDate = OFBIZCalendar_getSelectedDate(calendarId);\r\n");
		js.append("			if(sDate == null||sDate == \"\" || sDate == \"NaN\")\r\n");
		js.append("			{\r\n");
		js.append("				sDate = OFBIZCalendar_getCurDate(calendarId);\r\n");
		js.append("			}\r\n");
		js.append("			var html=new String();\r\n");
		js.append("						\r\n");
		js.append("			html+=\"	<tr style=\\\"background-color:#c1c7de;  font-size:12px;\\\">\";\r\n");
		js.append("			html+= \"<td colspan=7 style=\\\"text-align:center;\\\">\"\r\n");
		js.append("			html+=\"<table style=\\\"width:100%;\\\"><tr  style=\\\" font-size:12px;\\\">\";\r\n");
		js.append("			html+=\"	<td style=\\\"text-align:left;\\\"><a href=\\\"#\\\" style=\\\"color:black;\\\" onclick=\\\"window.OFBIZsetSelectedMonth(-1 ,'\";\r\n");
		js.append("			html+=calendarId;\r\n");
		js.append("			html+=\"');\\\" hidefocus></a>&nbsp;&nbsp;\";\r\n");
		js.append("			html+=\"</td>\";\r\n");
		js.append("			html+=\"<td style=\\\"text-align:center;\\\"><input type=\\\"text\\\" id=\\\"\" + calendarId + \"_yearText\\\" style=\\\"width:40px; font-size:12px;\\\" value=\\\"\" + sDate.getFullYear() + \"\\\" maxlength=\\\"4\\\"\";\r\n");
		js.append("			html+=\"onkeydown=\\\"window.validateKey(this)\\\" onkeypress=\\\"return OFBIZJudgeKeyPress();\\\" onblur=\\\"window.OFBIZchangeYearByTextBox(this,'\" + calendarId + \"')\\\">\"\r\n");
		js.append("			html+=\"<DIV style=\\\"DISPLAY: inline; WIDTH: 18px; HEIGHT: 11px\\\" ms_positioning=\\\"FlowLayout\\\">\"\r\n");
		js.append("			html+=\"<INPUT id=\\\"Button2\\\" style=\\\"WIDTH: 18px; HEIGHT: 10px; font-size:5px\\\" type=\\\"button\\\" value=\\\"��\\\" name=\\\"Button2\\\" onclick=\\\"window.OFBIZchangeYear(1 ,\"+sDate.getFullYear()+\",'\";\r\n");
		js.append("			html+=calendarId;\r\n");
		js.append("			html+=\"')\\\">\"\r\n");
		js.append("			html+=\"<INPUT id=\\\"Button1\\\" style=\\\"WIDTH: 18px; HEIGHT: 10px; font-size:5px\\\" type=\\\"button\\\" value=\\\"&#9660;\\\" name=\\\"Button1\\\" onclick=\\\"window.OFBIZchangeYear(-1 ,\"+sDate.getFullYear()+\",'\";\r\n");
		js.append("			html+=calendarId;\r\n");
		js.append("			html+=\"')\\\"></DIV>\"\r\n");
		js.append("			html+=\"��\"\r\n");
		js.append("			html+=\"<select style=\\\"width:50px; font-size:12px;\\\" id=\\\"\"+calendar.getAttribute(\"popDiv\")+\"_select\\\"  onchange = \\\"window.OFBIZchangeMonth(this , '\";\r\n");
		js.append("			html+=calendarId;\r\n");
		js.append("			html+=\"');\\\">\";\r\n");
		js.append("			for(i=0; i<12 ; i++)\r\n");
		js.append("			{\r\n");
		js.append("				if(i == sDate.getMonth())\r\n");
		js.append("				{\r\n");
		js.append("					html+=\"<option style=\\\"font-size:12px\\\" selected=\\\"true\\\">\" + OFBIZCalendar_Month[i] + \"</option>\";\r\n");
		js.append("					continue;\r\n");
		js.append("				}\r\n");
		js.append("				html+=\"<option style=\\\"font-size:12px\\\">\" + OFBIZCalendar_Month[i] + \"</option>\"\r\n");
		js.append("			}\r\n");
		js.append("			html+=\"</select>\";\r\n");
		js.append("			html+=\"��</td>\"\r\n");
		js.append("			html+=\"	<td  style=\\\"text-align:right;\\\">\";\r\n");
		js.append("			html+=\"	<a href=\\\"#\\\" style=\\\"color:black;\\\" onclick=\\\"window.OFBIZsetSelectedMonth(1 , '\";\r\n");
		js.append("			html+=calendarId;\r\n");
		js.append("			html+=\"');\\\" hidefocus></a>&nbsp;\";\r\n");
		js.append("			html+=\"</td>\";\r\n");
		js.append("			html+=\"</tr>\";\r\n");
		js.append("			html+=\"</table>\";\r\n");
		js.append("			html+=\"</td>\";\r\n");
		js.append("			html+=\"</tr>\";			\r\n");
		js.append("			return html;\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_getDayHeader()\r\n");
		js.append("		{\r\n");
		js.append("			var html=new String();\r\n");
		js.append("			html+=\"<tr style=\\\"background-color:#c1c7de; font-size:12px;\\\">\";\r\n");
		js.append("			\r\n");
		js.append("			for(var i=0;i<7;i++)\r\n");
		js.append("			{\r\n");
		js.append("				html+=\"<td style=\\\"text-align:center;\\\">\" + OFBIZCalendar_ShortWeek[i] + \"</td>\"\r\n");
		js.append("			}\r\n");
		js.append("			html+=\"</tr>\";\r\n");
		js.append("			return html;\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_getCells(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var loopLength = 6;\r\n");
		js.append("			var sDate = OFBIZCalendar_getSelectedDate(calendarId);\r\n");
		js.append("			if(sDate == null || sDate == \"\" || sDate == \"NaN\")\r\n");
		js.append("			{\r\n");
		js.append("				sDate = OFBIZCalendar_getCurDate(calendarId);\r\n");
		js.append("			}\r\n");
		js.append("			var temp=new Date(sDate.getFullYear(),sDate.getMonth(),1);\r\n");
		js.append("			var temp1 = new Date(sDate.getFullYear() , parseInt(sDate.getMonth()) + 1 , 1);\r\n");
		js.append("			temp1.setDate(parseInt(temp1.getDate()) - 1);\r\n");
		js.append("			var dateLength = temp1.getDate();\r\n");
		js.append("			var begin=temp.getDay();\r\n");
		js.append("			temp.setMonth(temp.getMonth()+1);			\r\n");
		js.append("			temp.setDate(temp.getDate()-1);\r\n");
		js.append("			var end=getDays(temp.getMonth(),temp.getFullYear());			\r\n");
		js.append("			var html=new String();			\r\n");
		js.append("			for(var i=0;i<loopLength ;i++)\r\n");
		js.append("			{\r\n");
		js.append("				html+=\"<tr style=\\\"font-size:12px;\\\">\";\r\n");
		js.append("				for(var j=0;j<7;j++)\r\n");
		js.append("				{				\r\n");
		js.append("					html+=OFBIZCalendar_getCell(sDate , OFBIZCalendar_getCurDate(calendarId) , begin , end ,i*7+j, calendarId);\r\n");
		js.append("				}\r\n");
		js.append("				html+=\"</tr>\";\r\n");
		js.append("			}			\r\n");
		js.append("			var calendar = document.getElementById(calendarId);			\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");//+OFBIZCalendar_getTime(calendarId)+\r\n");
		js.append("			if(\"true\"==isViewTime)\r\n");
		js.append("			{\r\n");
		js.append("				//html+=\"<select><option/></select>\";\r\n");
		js.append("				html+=\"<tr>\";\r\n");
		js.append("				html+=\"<td colspan=\\\"7\\\" align=\\\"center\\\">\"+OFBIZCalendar_getTime(calendarId)+\"</td>\";\r\n");
		js.append("				html+=\"</tr>\";\r\n");
		js.append("			}		\r\n");
		js.append("			html += \"</table></font>\";						\r\n");
		js.append("			return html;\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZCalendar_intFormat(intValue)\r\n");
		js.append("		{\r\n");
		js.append("			if(intValue<10)\r\n");
		js.append("			{\r\n");
		js.append("				return \"0\"+intValue;\r\n");
		js.append("			}\r\n");
		js.append("			return intValue;\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZCalendar_getTime(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var sDate = OFBIZCalendar_getSelectedDate(calendarId);\r\n");
		js.append("			var html=\"\";			\r\n");
		js.append("			var minute;\r\n");
		js.append("			var hour;			\r\n");
		js.append("			if(sDate!=null)\r\n");
		js.append("			{\r\n");
		js.append("				minute=sDate.getMinutes();\r\n");
		js.append("				hour=sDate.getHours();				\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				var cuDate=new Date();\r\n");
		js.append("				minute=cuDate.getMinutes();\r\n");
		js.append("				hour=cuDate.getHours();				\r\n");
		js.append("			}			\r\n");
		js.append("			minute=OFBIZCalendar_intFormat(minute);				\r\n");
		js.append("			html+=\"<table>\";\r\n");
		js.append("			html+=\"<tr><td ><select id=\\\"\"+calendarId+\"_div_hourSelect\\\" name=\\\"\"+calendarId+\"_div_hourSelect\\\" style=\\\"width:40px; font-size:12px;\\\" onchange=\\\"OFBIZchangeDate('\"+calendarId+\"')\\\">\";\r\n");
		js.append("			for(var i=0;i<24;i++)\r\n");
		js.append("			{\r\n");
		js.append("				var text=OFBIZCalendar_intFormat(i);\r\n");
		js.append("				if(hour==i)\r\n");
		js.append("				{\r\n");
		js.append("					html+=\"<option  value=\\\"\"+text+\"\\\" selected>\"+text+\"</option>\";\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					html+=\"<option  value=\\\"\"+text+\"\\\">\"+text+\"</option>\";\r\n");
		js.append("				}				\r\n");
		js.append("			}		\r\n");
		js.append("			html+=\"</select></td>\";									\r\n");
		js.append("			html+=\"<td>ʱ</td>\";			\r\n");
		js.append("			html+=\"<td ><input type='text' id='\"+calendarId+\"_minute' name='\"+calendarId+\"_minute' value='\"+minute+\"' maxlength='2' Style='width:18px' onkeydown=\\\"window.validateKey(this)\\\" onkeypress=\\\"return OFBIZJudgeKeyPress();\\\" onblur=\\\"OFBIZCalendar_validateTime(this,'\"+calendarId+\"')\\\"></td><td>��</td></tr>\";			\r\n");
		js.append("			html+=\"</table>\";		\r\n");
		js.append("			return html;		\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZCalendar_validateTime(obj,calId)\r\n");
		js.append(" 		{\r\n");
		js.append("		    var textbox = obj;\r\n");
		js.append("			 var minute = textbox.value;\r\n");
		js.append("			 var size = minute.length;\r\n");
		js.append("			 var minuteFront;\r\n");
		js.append("			 var minuteLast;\r\n");
		js.append("			 if(size == 1)\r\n");
		js.append("			 {\r\n");
		js.append("				if(minute<=9 && minute>=0)\r\n");
		js.append("				{\r\n");
		js.append("					textbox.value = '0'+ minute;\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					textbox.value = '00';\r\n");
		js.append("					alert('����������!');       \r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("		     else\r\n");
		js.append("		     {\r\n");
		js.append("			       minuteFront = minute.substring(0,1);\r\n");
		js.append("			       minuteLast = minute.substring(1);\r\n");
		js.append("			       if(minuteFront<=9&&minuteFront>=0&&minuteLast<=9&&minuteLast>=0)\r\n");
		js.append("			       {\r\n");
		js.append("				         if(minuteFront>6)\r\n");
		js.append("				         {\r\n");
		js.append("				           textbox.value = '00';\r\n");
		js.append("				           alert('�������뷶Χ��0 - 60֮��!');\r\n");
		js.append("				         }\r\n");
		js.append("				         if(minuteFront==6 && minuteLast>=0)\r\n");
		js.append("				        {\r\n");
		js.append("				          textbox.value = '00';\r\n");
		js.append("				          alert('�������뷶Χ��0 - 60֮��!');\r\n");
		js.append("				        }\r\n");
		js.append("			      }\r\n");
		js.append("			      else\r\n");
		js.append("			      {\r\n");
		js.append("				      textbox.value = '00';\r\n");
		js.append("				      alert('����������!');\r\n");
		js.append("			      }\r\n");
		js.append("	   		}\r\n");
		js.append("	   		OFBIZchangeDate(calId);\r\n");
		js.append("	  	}\r\n");
		js.append("		function OFBIZCalendar_getCell(selectedDate , curDate , begin , end , num, calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var html = new String();\r\n");
		js.append("			var curStyle = \"\\\"\";\r\n");
		js.append("			if(curDate.getMonth()==selectedDate.getMonth()&&curDate.getFullYear()==selectedDate.getFullYear()&&(num-begin+1)==curDate.getDate())\r\n");
		js.append("			{\r\n");
		js.append("				curStyle=\"\\\"background-color:#ababab;\";\r\n");
		js.append("			}	\r\n");
		js.append("			if(num%7==0||(num+1)%7==0)\r\n");
		js.append("			{\r\n");
		js.append("				curStyle=\"\\\"\";\r\n");
		js.append("			}\r\n");
		js.append("			if((num-begin+1)==selectedDate.getDate())\r\n");
		js.append("			{\r\n");
		js.append("				curStyle=\"\\\"\";\r\n");
		js.append("			}\r\n");
		js.append("			if(num<begin||(num-begin+1)>end)\r\n");
		js.append("			{\r\n");
		js.append("				curStyle=\"\\\"color:#9c9c9c;\";\r\n");
		js.append("			}\r\n");
		js.append("			if(num-begin+1 == selectedDate.getDate())\r\n");
		js.append("			{\r\n");
		js.append("				curStyle=\"\\\"background-color:#e5e5e6;\"\r\n");
		js.append("			}\r\n");
		js.append("			html+=\"	<td style=\"+curStyle+ \"text-Align:center;\\\" onmouseover=\\\"this.style.cursor='hand';this.style.textDecoration = 'underline';\\\"  onmouseout=\\\"this.style.textDecoration='none'\\\">\";\r\n");
		js.append("			if(num<begin)\r\n");
		js.append("			{\r\n");
		js.append("				var mid=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),selectedDate.getDate());\r\n");
		js.append("				mid.setDate(num-begin+1);\r\n");
		js.append("				html+=\"		<a  style=\\\"width:100%; color:#c0c0c0\\\" onclick=\\\"window.OFBIZsetPreMonthDay(-1 , this.innerHTML , '\";\r\n");
		js.append("				html+=calendarId;\r\n");
		js.append("				html+=\"');\\\">\"+mid.getDate()+\"</a>\";\r\n");
		js.append("			}\r\n");
		js.append("			else if((num-begin+1)>end)\r\n");
		js.append("			{\r\n");
		js.append("				var mid=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),selectedDate.getDate());\r\n");
		js.append("				mid.setDate(num-begin+1);\r\n");
		js.append("				html+=\"		<a  style=\\\"width:100%;color:#c0c0c0\\\" onclick=\\\"window.OFBIZsetPreMonthDay(1 , this.innerHTML ,'\";\r\n");
		js.append("				html+=calendarId;\r\n");
		js.append("				html+=\"');\\\">\"+mid.getDate()+\"</a>\";\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				html+=\"		<a  style=\\\"width:100%;\\\" onclick=\\\"window.OFBIZsetPreMonthDay(0 , this.innerHTML , '\";\r\n");
		js.append("				html+=calendarId;\r\n");
		js.append("				html+=\"');\\\">\"+(num-begin+1)+\"</a>\";\r\n");
		js.append("			}\r\n");
		js.append("			html+=\" </td>\";\r\n");
		js.append("			return html;\r\n");
		js.append("		}		\r\n");
		js.append("		function getDays(month, year)	\r\n");
		js.append("		{	\r\n");
		js.append("			if (1 == month)	\r\n");
		js.append("				return ((0 == year % 4) && (0 != (year % 100))) || (0 == year % 400) ? 29 : 28;	\r\n");
		js.append("			else	\r\n");
		js.append("				return daysInMonth[month];	\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZJudgeKey(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var keyCodes = new Array(109 , 8 , 189 , 27 , 46 , 45 , 39);\r\n");
		js.append("			var inKeyCodes = false;\r\n");
		js.append("			var isNum = false;\r\n");
		js.append("			var isCon = false;\r\n");
		js.append("			if(event.keyCode == 13)\r\n");
		js.append("			{\r\n");
		js.append("				OFBIZJudgeBlur(calendarId);\r\n");
		js.append("			}\r\n");
		js.append("			if((event.keyCode >=96 && event.keyCode <= 105)||(event.keyCode >=48 && event.keyCode <= 57))\r\n");
		js.append("			{\r\n");
		js.append("				isNum = true;\r\n");
		js.append("			}\r\n");
		js.append("			if(event.keyCode >=35 && event.keyCode <= 37)\r\n");
		js.append("			{\r\n");
		js.append("				isCon = true;\r\n");
		js.append("			}\r\n");
		js.append("			for(i = 0; i<keyCodes.length; i++)\r\n");
		js.append("			{\r\n");
		js.append("				if(event.keyCode == keyCodes[i])\r\n");
		js.append("				{\r\n");
		js.append("					inKeyCodes = true;\r\n");
		js.append("					break;\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("			if(inKeyCodes || isCon || isNum)\r\n");
		js.append("			{\r\n");
		js.append("				allowKeyPress = true;\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				allowKeyPress = false;\r\n");
		js.append("			}\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZJudgeKeyPress()\r\n");
		js.append("		{\r\n");
		js.append("			if(allowKeyPress)\r\n");
		js.append("			{\r\n");
		js.append("				return true;\r\n");
		js.append("			}\r\n");
		js.append("			return false;\r\n");
		js.append("		}	\r\n");
		js.append("		function OFBIZJudgeBlur(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
		js.append("			var calendar = document.getElementById(calendarId);			\r\n");
		js.append("			var dateArr = textBox.value.split(\"-\");\r\n");
		js.append("			var year = OFBIZCalendar_getIntData(dateArr[0]);\r\n");
		js.append("			var month = OFBIZCalendar_getIntData(dateArr[1]) - 1;\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			var timeVal=new Array();\r\n");
		js.append("			var date=null;\r\n");
		js.append("			if(\"true\"==isViewTime&&dateArr[2]!=null)\r\n");
		js.append("			{\r\n");
		js.append("				var timeArray=dateArr[2].split(\" \");\r\n");
		js.append("				date = OFBIZCalendar_getIntData(timeArray[0]);\r\n");
		js.append("				if(timeArray.length>1)\r\n");
		js.append("				{\r\n");
		js.append("					var times=timeArray[1].split(\":\");\r\n");
		js.append("					timeVal[0]=OFBIZCalendar_getIntData(times[0]);\r\n");
		js.append("					timeVal[1]=OFBIZCalendar_getIntData(times[1]);\r\n");
		js.append("				}				\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				date = OFBIZCalendar_getIntData(dateArr[2]);\r\n");
		js.append("			}			\r\n");
		js.append("			var popDiv = document.getElementById(calendar.getAttribute(\"popDiv\"));\r\n");
		js.append("			\r\n");
		js.append("			var defaultDate = OFBIZCalendar_getDefaultDate(calendarId);\r\n");
		js.append("			var defaultDateStr = calendar.getAttribute(\"defaultDate\");\r\n");
		js.append("			\r\n");
		js.append("			var oldSelectedDate = OFBIZCalendar_getSelectedDate(calendarId)\r\n");
		js.append("			var newDate = null;\r\n");
		js.append("			if(\"true\"!=isViewTime||dateArr[2]==null)\r\n");
		js.append("			{\r\n");
		js.append("				newDate=OFBIZCalendar_getNewDate(year, month, date);\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				newDate=OFBIZCalendar_getNewDate(year, month, date,times[0],times[1]);\r\n");
		js.append("			}			\r\n");
		js.append("			if(newDate.getFullYear() != year || newDate.getMonth() != month || newDate.getDate() != date || dateArr[0].length >= 5)\r\n");
		js.append("			{\r\n");
		js.append("				if(defaultDate != null)\r\n");
		js.append("				{\r\n");
		js.append("					if(calendar.getAttribute(\"necessary\") == \"false\")\r\n");
		js.append("					{\r\n");
		js.append("					    OFBIZCalendar_ChangeDate(calendarId , \" \");\r\n");
		js.append("					}\r\n");
		js.append("					else\r\n");
		js.append("					{\r\n");
		js.append("					     if(defaultDateStr == \" \")\r\n");
		js.append("					     {\r\n");
		js.append("					          calendar.setAttribute(\"defaultDate\", calendar.getAttribute(\"curDate\"))\r\n");
		js.append("					          OFBIZCalendar_ChangeDate(calendarId,  calendar.getAttribute(\"curDate\"))\r\n");
		js.append("					     }\r\n");
		js.append("					     else\r\n");
		js.append("					     {\r\n");
		js.append("					           OFBIZCalendar_ChangeDate(calendarId , defaultDateStr);\r\n");
		js.append("					     }\r\n");
		js.append("					 }\r\n");
		js.append("				}				\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("				OFBIZCalendar_ChangeDate(calendarId ,OFBIZCalendar_parseToStr(newDate,isViewTime));\r\n");
		js.append("			}\r\n");
		js.append("			if(popDiv.innerHTML.length > 0)\r\n");
		js.append("			{\r\n");
		js.append("				\r\n");
		js.append("				hiddenDiv(popDiv);\r\n");
		js.append("				calendar.appendChild(popDiv);\r\n");
		js.append("				OFBIZCalendar_showPop(calendarId);\r\n");
		js.append("			}\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_parseToStr(curDate,isViewTime)\r\n");
		js.append("		{\r\n");
		js.append("			var year = parseInt(curDate.getFullYear());\r\n");
		js.append("			var month = parseInt(curDate.getMonth()) + 1;\r\n");
		js.append("			var date = parseInt(curDate.getDate());\r\n");
		js.append("			var dateStr = year + \"-\" + month + \"-\" + date;\r\n");
		js.append("			if(\"true\"==isViewTime)\r\n");
		js.append("			{				\r\n");
		js.append("				dateStr+=\" \"+OFBIZCalendar_intFormat(curDate.getHours())+\":\"+OFBIZCalendar_intFormat(curDate.getMinutes());\r\n");
		js.append("			}\r\n");
		js.append("			return dateStr;\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZCalendar_getHour(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var hour=document.getElementById(calendarId+\"_div_hourSelect\").value;	\r\n");
		js.append("			if(hour==\"00\")return 0;\r\n");
		js.append("				\r\n");
		js.append("			return OFBIZCalendar_getIntData(hour);\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZCalendar_getMinute(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var minute=document.getElementById(calendarId+\"_minute\").value;		\r\n");
		js.append("			if(minute==\"00\")return 0;	\r\n");
		js.append("			return OFBIZCalendar_getIntData(minute);\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZsetPreMonthDay(monthoffset , day , calendarId)\r\n");
		js.append("		{			\r\n");
		js.append("			var calendar = document.getElementById(calendarId);          		\r\n");
		js.append("			var sDate = OFBIZCalendar_getSelectedDate(calendarId);\r\n");
		js.append("			sDate=getCalendarDate(calendarId,sDate);\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			if(\"true\"==isViewTime)\r\n");
		js.append("			{\r\n");
		js.append("				sDate.setHours(OFBIZCalendar_getHour(calendarId));\r\n");
		js.append("				sDate.setMinutes(OFBIZCalendar_getMinute(calendarId));			\r\n");
		js.append("			}\r\n");
		js.append("			var newDate = OFBIZCalendar_getNewDate(sDate.getFullYear(), sDate.getMonth() + monthoffset, day,sDate.getHours(),sDate.getMinutes());			\r\n");
		js.append("			var newDateStr = OFBIZCalendar_parseToStr(newDate,isViewTime);\r\n");
		js.append("			OFBIZCalendar_ChangeDate(calendarId, newDateStr);\r\n");
		js.append("			var div = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
		js.append("			hiddenDiv(div);\r\n");
		js.append("			calendar.appendChild(div);						\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_ChangeDate(calendarId, dateStr)\r\n");
		js.append("		{\r\n");
		js.append("	        if(dateStr == \" \")\r\n");
		js.append("	        {\r\n");
		js.append("	               dateStr = \"\";\r\n");
		js.append("	        }\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
		js.append("			var oldDateStr = calendar.getAttribute(\"selectedDate\");\r\n");
		js.append("	        if(oldDateStr == null)\r\n");
		js.append("	        {\r\n");
		js.append("	               oldDateStr = ''\r\n");
		js.append("	        }		        			\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			var isChanged = OFBIZCalendar_DateChanged(oldDateStr, dateStr,isViewTime);\r\n");
		js.append("			calendar.setAttribute(\"selectedDate\",dateStr);\r\n");
		js.append("			textBox.value = dateStr;\r\n");
		js.append("			textBox.title = dateStr;\r\n");
		js.append("			if(isChanged && calendar.getAttribute(\"ondatechange\") != \"\" && calendar.getAttribute(\"ondatechange\") != null)\r\n");
		js.append("			{\r\n");
		js.append("				var onchangeStr = calendar.getAttribute(\"ondatechange\");\r\n");
		js.append("				eval(onchangeStr);\r\n");
		js.append("			}\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_DateChanged(oldDateStr, newDateStr,isViewTime)\r\n");
		js.append("		{\r\n");
		js.append("			if(oldDateStr==\"\"&&newDateStr!=\"\")\r\n");
		js.append("			{\r\n");
		js.append("				return true;");
		js.append("			}");		
		js.append("			var oldDate = OFBIZCalendar_parseToDate(oldDateStr,isViewTime);\r\n");
		js.append("			var newDate = OFBIZCalendar_parseToDate(newDateStr,isViewTime);\r\n");
		js.append("			var oldString = OFBIZCalendar_parseToStr(oldDate,isViewTime);\r\n");
		js.append("			var newString = OFBIZCalendar_parseToStr(newDate,isViewTime);\r\n");
		js.append("			if(oldString != newString)\r\n");
		js.append("			{\r\n");
		js.append("				return true;\r\n");
		js.append("			}\r\n");
		js.append("			return false;\r\n");
		js.append("		}\r\n");
		js.append("		function getCalendarDate(calendarId,sDate)\r\n");
		js.append("		{\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var defaultDate = OFBIZCalendar_getDefaultDate(calendarId);\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var necessary = calendar.getAttribute(\"necessary\");\r\n");
		js.append("			var curDate = OFBIZCalendar_getCurDate(calendarId);\r\n");
		js.append("			if(sDate == null || sDate == \"NaN\")\r\n");
		js.append("			{\r\n");
		js.append("			       if(defaultDate == null || defaultDate == \"NaN\"  || necessary==\"false\")\r\n");
		js.append("			       {\r\n");
		js.append("			             sDate = curDate;\r\n");
		js.append("			       }\r\n");
		js.append("			}\r\n");
		js.append("			if((sDate == null || sDate == \"\") && necessary == \"true\")\r\n");
		js.append("			{\r\n");
		js.append("				sDate = defaultDate;\r\n");
		js.append("			}\r\n");
		js.append("			return sDate;\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZchangeMonth(selectObj, calendarId)\r\n");
		js.append("		{				\r\n");
		js.append("			var calendar = document.getElementById(calendarId);		\r\n");
		js.append("			var selectedDate = OFBIZCalendar_getSelectedDate(calendarId)			\r\n");
		js.append("			var sDate = selectedDate;			\r\n");
		js.append("			sDate=getCalendarDate(calendarId,sDate);\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			if(\"true\"==isViewTime)\r\n");
		js.append("			{\r\n");
		js.append("				sDate.setHours(OFBIZCalendar_getHour(calendarId));\r\n");
		js.append("				sDate.setMinutes(OFBIZCalendar_getMinute(calendarId));\r\n");
		js.append("			}\r\n");
		js.append("			var newDate = OFBIZCalendar_getNewDate(sDate.getFullYear(), selectObj.selectedIndex, sDate.getDate(),sDate.getHours(),sDate.getMinutes());\r\n");
		js.append("			while(newDate.getMonth() != selectObj.selectedIndex)\r\n");
		js.append("			{\r\n");
		js.append("				newDate.setDate(newDate.getDate() - 1);\r\n");
		js.append("			}\r\n");
		js.append("			OFBIZCalendar_changeAndShow(calendarId, newDate)\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZsetSelectedMonth(monthoffset , calendarId)\r\n");
		js.append("		{						\r\n");
		js.append("			var calendar = document.getElementById(calendarId);           \r\n");
		js.append("			var selectedDate = OFBIZCalendar_getSelectedDate(calendarId)			\r\n");
		js.append("			var sDate= selectedDate;			\r\n");
		js.append("			sDate=getCalendarDate(calendarId,sDate);\r\n");
		js.append("			if(\"true\"==isViewTime)\r\n");
		js.append("			{\r\n");
		js.append("				sDate.setHours(OFBIZCalendar_getHour(calendarId));\r\n");
		js.append("				sDate.setMinutes(OFBIZCalendar_getMinute(calendarId));\r\n");
		js.append("			}\r\n");
		js.append("			var newDate = OFBIZCalendar_getNewDate(sDate.getFullYear(), sDate.getMonth() + monthoffset, sDate.getDate(),sDate.getHours(),sDate.getMinutes());\r\n");
		js.append("			while(newDate.getMonth() == sDate.getMonth())\r\n");
		js.append("			{\r\n");
		js.append("				newDate.setDate(newDate.getDate() - 1);\r\n");
		js.append("			}\r\n");
		js.append("			OFBIZCalendar_changeAndShow(calendarId, newDate)\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZchangeDate(calendarId)\r\n");
		js.append("		{		\r\n");
		js.append("			var calendar = document.getElementById(calendarId);        \r\n");
		js.append("			var selectedDate = OFBIZCalendar_getSelectedDate(calendarId);		\r\n");
		js.append("			var sDate = selectedDate;			\r\n");
		js.append("			if(sDate==null)\r\n");
		js.append("			{\r\n");
		js.append("				sDate= new Date();\r\n");
		js.append("			}\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			if(\"true\"==isViewTime)\r\n");
		js.append("			{				\r\n");
		js.append("				sDate.setHours(OFBIZCalendar_getHour(calendarId));\r\n");
		js.append("				sDate.setMinutes(OFBIZCalendar_getMinute(calendarId));\r\n");
		js.append("			}\r\n");
		js.append("			var newDate = OFBIZCalendar_getNewDate(sDate.getFullYear(), sDate.getMonth(), sDate.getDate(),sDate.getHours(),sDate.getMinutes());						\r\n");
		js.append("			OFBIZchangePopDiv(calendarId,calendar,newDate);         \r\n");
		js.append("		}				\r\n");
		js.append("		function OFBIZchangeToCurDate(calendarId)\r\n");
		js.append("		{			\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var curDate = OFBIZCalendar_getCurDate(calendarId);\r\n");
		js.append("			var newDate = curDate;\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			var newDateStr = OFBIZCalendar_parseToStr(newDate,isViewTime);\r\n");
		js.append("			OFBIZCalendar_ChangeDate(calendarId, newDateStr);\r\n");
		js.append("			var div = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
		js.append("			hiddenDiv(div);\r\n");
		js.append("			calendar.appendChild(div);\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZchangeYearByTextBox(yearTextBox, calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var year = yearTextBox.value;			\r\n");
		js.append("			var calendar = document.getElementById(calendarId);            \r\n");
		js.append("			var selectedDate = OFBIZCalendar_getSelectedDate(calendarId);			\r\n");
		js.append("			var sDate = selectedDate;	\r\n");
		js.append("			sDate=getCalendarDate(calendarId,sDate);\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			if(\"true\"==isViewTime)\r\n");
		js.append("			{\r\n");
		js.append("				sDate.setHours(OFBIZCalendar_getHour(calendarId));\r\n");
		js.append("				sDate.setMinutes(OFBIZCalendar_getMinute(calendarId));\r\n");
		js.append("			}\r\n");
		js.append("			var newDate = OFBIZCalendar_getNewDate(year, sDate.getMonth(), sDate.getDate(),sDate.getHours(),sDate.getMinutes());\r\n");
		js.append("			while(newDate.getMonth() != sDate.getMonth())\r\n");
		js.append("			{\r\n");
		js.append("				newDate.setDate(newDate.getDate() - 1);\r\n");
		js.append("			}\r\n");
		js.append("			OFBIZchangePopDiv(calendarId,calendar,newDate);            \r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZchangePopDiv(calendarId,calendar,newDate)\r\n");
		js.append("		{\r\n");
		js.append("			OFBIZCalendar_changeAndShow(calendarId, newDate);\r\n");
		js.append("			var popDiv = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
		js.append("            if(Calendar_mouseInObj(event.x,event.y,popDiv))\r\n");
		js.append("            {\r\n");
		js.append("                popDiv.setActive();\r\n");
		js.append("            }\r\n");
		js.append("            else\r\n");
		js.append("            {\r\n");
		js.append("            	hiddenDiv(popDiv);\r\n");
		js.append("            	calendar.appendChild(popDiv);\r\n");
		js.append("            }\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZchangeYear(off , value , calendarId)\r\n");
		js.append("		{			\r\n");
		js.append("			var calendar = document.getElementById(calendarId);           	\r\n");
		js.append("			var selectedDate = OFBIZCalendar_getSelectedDate(calendarId)			\r\n");
		js.append("			var sDate = selectedDate;\r\n");
		js.append("			sDate=getCalendarDate(calendarId,sDate);\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			if(\"true\"==isViewTime)\r\n");
		js.append("			{\r\n");
		js.append("				sDate.setHours(OFBIZCalendar_getHour(calendarId));\r\n");
		js.append("				sDate.setMinutes(OFBIZCalendar_getMinute(calendarId));\r\n");
		js.append("			}\r\n");
		js.append("			var newDate = OFBIZCalendar_getNewDate(value+off, sDate.getMonth(), sDate.getDate(),sDate.getHours(),sDate.getMinutes());\r\n");
		js.append("			while(newDate.getMonth() != sDate.getMonth())\r\n");
		js.append("			{\r\n");
		js.append("				newDate.setDate(newDate.getDate() - 1);\r\n");
		js.append("			}\r\n");
		js.append("			OFBIZCalendar_changeAndShow(calendarId, newDate)\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_changeAndShow(calendarId, newDate)\r\n");
		js.append("		{\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var isViewTime = calendar.getAttribute(\"isViewTime\");\r\n");
		js.append("			var newDateStr = OFBIZCalendar_parseToStr(newDate,isViewTime);\r\n");
		js.append("			OFBIZCalendar_ChangeDate(calendarId, newDateStr);\r\n");
		js.append("			var div = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
		js.append("			hiddenDiv(div);\r\n");
		js.append("			calendar.appendChild(div);\r\n");
		js.append("			OFBIZCalendar_showPop(calendarId);\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_getNewDate(year,month,day,hour,minutes)\r\n");
		js.append("		{\r\n");
		js.append("			var newDate = new Date();\r\n");
		js.append("			newDate.setFullYear(year, month, day);			\r\n");
		js.append("			if(hour!=null)\r\n");
		js.append("			{\r\n");
		js.append("				\r\n");
		js.append("				newDate.setHours(hour)\r\n");
		js.append("				newDate.setMinutes(minutes)\r\n");
		js.append("			}\r\n");
		js.append("			return newDate;\r\n");
		js.append("		}		\r\n");
		js.append("		function OFBIZCalendar_setValue(calendarId, dateStr)\r\n");
		js.append("		{\r\n");
		js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("           textBox.value = dateStr;\r\n");
		js.append("           textBox.title = dateStr;\r\n");
		js.append("           calendar.setAttribute(\"selectedDate\",dateStr);\r\n");
		js.append("		}		\r\n");
		js.append("		function hiddenDiv(divObj)\r\n");
		js.append("		{\r\n");
		js.append("		    divObj.setAttribute(\"popShow\", \"false\")\r\n");
		js.append("			divObj.style.visibility = \"hidden\";\r\n");
		js.append("			divObj.innerHTML = \"\";\r\n");
		js.append("			divObj.style.width = 0;\r\n");
		js.append("			divObj.style.height = 0;\r\n");
		js.append("			showElement(\"select\");\r\n");
		js.append("			showElement(\"applet\");\r\n");
		js.append("		}		\r\n");
		js.append("		function validateKey(textBox)\r\n");
		js.append("		{\r\n");
		js.append("			if(event.keyCode == 13)\r\n");
		js.append("			{\r\n");
		js.append("				textBox.blur();\r\n");
		js.append("				return;\r\n");
		js.append("			}\r\n");
		js.append("			if(((event.keyCode >=96 && event.keyCode <= 105)||(event.keyCode >=48 && event.keyCode <= 57)) && !event.shiftKey)\r\n");
		js.append("			{\r\n");
		js.append("				allowKeyPress = true;\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				allowKeyPress = false;\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZCalendar_closePop(calendarId)\r\n");
		js.append("		{\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("			var popDiv = document.getElementById(calendar.getAttribute(\"popDiv\"));\r\n");
		js.append("			hiddenDiv(popDiv);\r\n");
		js.append("			calendar.appendChild(popDiv);\r\n");
		js.append("			//hiddenDiv(popDiv)\r\n");
		js.append("		}\r\n");
		js.append("		function hideElement( elmID, overDiv )\r\n");
		js.append("		{\r\n");
		js.append("			var divLeft = 0;\r\n");
		js.append("			var divTop = 0;\r\n");
		js.append("			o = overDiv;\r\n");
		js.append("			while( o != null )\r\n");
		js.append("			{\r\n");
		js.append("				divLeft += o.offsetLeft;\r\n");
		js.append("				divTop   += o.offsetTop;\r\n");
		js.append("				o = o.offsetParent;\r\n");
		js.append("			}\r\n");
		js.append("			for( i = 0; i < document.getElementsByTagName( elmID ).length; i++ )\r\n");
		js.append("			{\r\n");
		js.append("				obj = document.getElementsByTagName(elmID)[i];\r\n");
		js.append("				if( !obj || !obj.offsetParent || obj.id == overDiv.id + \"_select\"||obj.id == overDiv.id + \"_hourSelect\")\r\n");
		js.append("				{\r\n");
		js.append("					continue;\r\n");
		js.append("				}\r\n");
		js.append("				// Find the element's offsetTop and offsetLeft relative to the BODY tag.\r\n");
		js.append("				objLeft   = obj.offsetLeft;\r\n");
		js.append("				objTop    = obj.offsetTop;\r\n");
		js.append("				objParent = obj.offsetParent;\r\n");
		js.append("		    \r\n");
		js.append("				while( objParent.tagName.toUpperCase() != \"BODY\" )\r\n");
		js.append("				{\r\n");
		js.append("					objLeft  += objParent.offsetLeft;\r\n");
		js.append("					objTop   += objParent.offsetTop;\r\n");
		js.append("					objParent = objParent.offsetParent;\r\n");
		js.append("				}		\r\n");
		js.append("				objHeight = obj.offsetHeight;\r\n");
		js.append("				objWidth = obj.offsetWidth;				\r\n");
		js.append("				if(( divLeft + overDiv.offsetWidth ) <= objLeft );\r\n");
		js.append("				else if(( divTop + overDiv.offsetHeight ) <= objTop );\r\n");
		js.append("				else if( divTop >= ( objTop + objHeight ));\r\n");
		js.append("				else if( divLeft >= ( objLeft + objWidth ));\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					obj.style.visibility = \"hidden\";\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("		}		\r\n");
		js.append("		function showElement( elmID )\r\n");
		js.append("		{\r\n");
		js.append("		    for( i = 0; i < document.getElementsByTagName( elmID ).length; i++ )\r\n");
		js.append("			{\r\n");
		js.append("	          obj = document.getElementsByTagName( elmID )[i];\r\n");
		js.append("              if( !obj || !obj.offsetParent )\r\n");
		js.append("			  {\r\n");
		js.append("				continue;\r\n");
		js.append("			  }\r\n");
		js.append("              obj.style.visibility = \"\";\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		function OFBIZCalendar_getIntData(dataStr)\r\n");
		js.append("		{\r\n");
		js.append("			if(dataStr == null)\r\n");
		js.append("			{\r\n");
		js.append("				return;\r\n");
		js.append("			}\r\n");
		js.append("			var startIndex = 0;\r\n");
		js.append("			for(var index = 0; index < dataStr.length; index++)\r\n");
		js.append("			{\r\n");
		js.append("			        if(dataStr.substring(index,index+1) != \"0\")\r\n");
		js.append("			        {\r\n");
		js.append("			                break;\r\n");
		js.append("			        }\r\n");
		js.append("			        else\r\n");
		js.append("			        {\r\n");
		js.append("			                startIndex = index + 1;\r\n");
		js.append("			        }\r\n");
		js.append("			}\r\n");
		js.append("			var newStr = dataStr.substring(startIndex, dataStr.length);\r\n");
		js.append("			return parseInt(newStr);\r\n");
		js.append("		}\r\n");
		js.append("	   	function Calendar_popDivBlur(calendarId)\r\n");
		js.append("        {        	\r\n");
		js.append("            var calendar = document.getElementById(calendarId)\r\n");
		js.append("            var popDiv = document.getElementById(calendar.getAttribute(\"popDiv\"));\r\n");
		js.append("            var yearText = document.getElementById(calendarId + \"_yearText\");\r\n");
		js.append("            var minuteText = document.getElementById(calendarId + \"_minute\");\r\n");
		js.append("            var imgBtn = document.getElementById(calendarId + \"_img\");\r\n");
		js.append("            var showCalendar = false;\r\n");
		js.append("            if(Calendar_mouseInObj(event.x,event.y,yearText) == true)\r\n");
		js.append("            {\r\n");
		js.append("                  showCalendar = true;\r\n");
		js.append("                  return;\r\n");
		js.append("            }\r\n");
		js.append("            if(minuteText!=null&&Calendar_mouseInObj(event.x,event.y,minuteText) == true)\r\n");
		js.append("            {\r\n");
		js.append("                  showCalendar = true;\r\n");
		js.append("                  return;\r\n");
		js.append("            }\r\n");
		js.append("            if(Calendar_mouseInObj(event.x,event.y,popDiv)==true)\r\n");
		js.append("            {\r\n");
		js.append("            	showCalendar = true;\r\n");
		js.append("                    popDiv.setActive();\r\n");
		js.append("                    return ;\r\n");
		js.append("            }\r\n");
		js.append("            if(!showCalendar)\r\n");
		js.append("            {\r\n");
		js.append("            	hiddenDiv(popDiv);\r\n");
		js.append("            	calendar.appendChild(popDiv);\r\n");
		js.append("            }\r\n");
		js.append("            \r\n");
		js.append("            if(Calendar_mouseInObj(event.x,event.y,imgBtn)==true)\r\n");
		js.append("            {\r\n");
		js.append("                    popDiv.setAttribute(\"popShow\",\"true\");\r\n");
		js.append("            }\r\n");
		js.append("        }	        \r\n");
		js.append("        function Calendar_mouseInObj(x, y , obj)\r\n");
		js.append("        {\r\n");
		js.append("			if(obj == null)\r\n");
		js.append("			{\r\n");
		js.append("				return false;\r\n");
		js.append("			}\r\n");
		js.append("            var rect;\r\n");
		js.append("            var winRect;\r\n");
		js.append("            rect = obj.getClientRects(); \r\n");
		js.append("            winRect=window.document.body.getClientRects();\r\n");
		js.append("            intLeft=rect[0].left-winRect[0].left;\r\n");
		js.append("            intTop=rect[0].top-winRect[0].top;\r\n");
		js.append("            intRight=rect[0].right-winRect[0].left;\r\n");
		js.append("            intBottom=rect[0].bottom-winRect[0].top;\r\n");
		js.append("            if (!((x>=intLeft) && (x<=intRight))) return false;  \r\n");
		js.append("            if (!((y>=intTop) && (y<=intBottom))) return false;\r\n");
		js.append("            return true;\r\n");
		js.append("			}\r\n");
		js.append("        function OFBIZCalendar_getValue(calendarId)\r\n");
		js.append("        {\r\n");
		js.append("            var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
		js.append("			//OFBIZJudgeBlur(calendarId);\r\n");
		js.append("            return textBox.value;\r\n");
		js.append("        }\r\n");
		js.append("        function OFBIZCalendar_setProperty(calendarId, property, value)\r\n");
		js.append("        {\r\n");
		js.append("			var calendar = document.getElementById(calendarId);\r\n");
		js.append("            var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
		js.append("            var button = document.getElementById(calendarId + \"_img\");\r\n");
		js.append("            if(property.toLowerCase() == \"readonly\")\r\n");
		js.append("            {\r\n");
		js.append("				if(value.toLowerCase() == \"true\")\r\n");
		js.append("				{\r\n");
		js.append("					textBox.readOnly = true;\r\n");
		js.append("					button.disabled = true;\r\n");
		js.append("					var src = calendar.getAttribute(\"dissrc\");\r\n");
		js.append("					button.src = src;\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					textBox.readOnly = false;\r\n");
		js.append("					button.disabled = false;\r\n");
		js.append("					var src = calendar.getAttribute(\"src\");\r\n");
		js.append("					button.src = src;\r\n");
		js.append("				}\r\n");
		js.append("            }\r\n");
		js.append("            else if(property.toLowerCase() == \"necessary\")\r\n");
		js.append("            {\r\n");
		js.append("				if(value.toLowerCase() == \"true\")\r\n");
		js.append("				{\r\n");
		js.append("				        textBox.style.backgroundColor = \"yellow\";\r\n");
		js.append("				        calendar.setAttribute(\"necessary\",\"true\");\r\n");
		js.append("				        OFBIZJudgeBlur(calendarId);\r\n");
		js.append("				}\r\n");
		js.append("				else if(value.toLowerCase() == \"false\")\r\n");
		js.append("				{\r\n");
		js.append("				        textBox.style.backgroundColor = \"white\";\r\n");
		js.append("				        calendar.setAttribute(\"necessary\", \"false\");\r\n");
		js.append("				}\r\n");
		js.append("            }\r\n");
		js.append("            else if(property.toLowerCase() == \"width\")\r\n");
		js.append("            {\r\n");
		js.append("               if(value < 18)\r\n");
		js.append("               {\r\n");
		js.append("                     return;\r\n");
		js.append("               }\r\n");
		js.append("               textBox.style.width = value - 18;\r\n");
		js.append("            }\r\n");
		js.append("        }\r\n");
		js.append("        function OFBIZCalendar_setFocus(calendarId)\r\n");
		js.append("        {\r\n");
		js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
		js.append("			textBox.focus();\r\n");
		js.append("		}");		
		jstool.js=js;
      	return jstool.getComponentJS();
  }

}