package com.born.insurance.webui.control;

/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */

public class CalendarJsForMozila {
  /**
   * <p><B>Description: get javascript functions of the calendar control</B></p>
   * @param path: path of the javascript file
   * @return: the reference of the javascript file
   * <p>GACalendar_getValue</p>
   * <b>param:</b> calendarId, <b>paramType:</b>String
   * <p>GACalendar_setValue</p>
   * <b>param:</b> calendarId, <b>paramType:</b>String
   * <b>param:</b> dateStr, <b>paramType:</b>String, <b>description:���ڱ�����ȷ</b>
   * <p>GACalendar_setProperty</p>
   * <b>param:</b> calendarId, <b>paramType:</b>String
   * <b>param:</b> property, <b>paramType:</b>String, <b>description:�������Ե�������ƣ�Ϊwidth��necessary����readonly</b>
   * <b>param:</b> value, <b>paramType:</b>String or int, <b>description:�������Ե�ֵ��Ϊ����ת��Ϊbool�ͻ�int�͵��ַ��磺"true","3"</b>
   * <p>GACalendar_setFocus</p>
   * <b>param:</b> calendarId, <b>paramType:</b>String
   */
  public static String getCalendarJS(){
     JSTool jstool=new JSTool("CalendarJsForMozila.js");
     StringBuffer js = new StringBuffer();
     js.append("		var GACalendar_ShortWeek = new Array(\"��\",\"һ\",\"��\",\"��\",\"��\",\"��\",\"��\");\r\n");
     js.append("		var GACalendar_Month = new Array(\"һ\" , \"��\" , \"��\" , \"��\" , \"��\" , \"��\", \"��\" , \"��\" , \"��\" , \"ʮ\" , \"ʮһ\" , \"ʮ��\");\r\n");
     js.append("		var daysInMonth = new Array(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31);\r\n");
     js.append("		var allowKeyPress = true;\r\n");
     js.append("\r\n");
     js.append("		function GACalendar_getTop(calendarId, div)\r\n");
     js.append("		{\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var o = textBox;\r\n");
     js.append("			var isDiv = false;\r\n");
     js.append("			var  o1 = textBox;\r\n");
     js.append("			var outerDiv = null;\r\n");
     js.append("			iPos = 0;	\r\n");
     js.append("            		var popHeight = parseInt(calendar.getAttribute(\"popHeight\"));\r\n");
     js.append("            		while (o!=null && o.tagName != null) 	\r\n");
     js.append("			{	\r\n");
     js.append("				if(o.tagName == \"DIV\")\r\n");
     js.append("			        {	\r\n");
     js.append("			             outerDiv = o;\r\n");
     js.append("			             isDiv = true;\r\n");
     js.append("			             break;	\r\n");
     js.append("			        }	\r\n");
     js.append("				o = o.parentNode;\r\n");
     js.append("			}\r\n");
     js.append("			o = textBox;\r\n");
     js.append("			while(o != null)\r\n");
     js.append("			{\r\n");
     js.append("				iPos += o[\"offsetTop\"];\r\n");
     js.append("				o = o.offsetParent;\r\n");
     js.append("			}	\r\n");
     js.append("			if(isDiv)\r\n");
     js.append("			{\r\n");
     js.append("				var divOffset = 0;\r\n");
     js.append("				o = outerDiv;\r\n");
     js.append("				while(o != null)\r\n");
     js.append("				{\r\n");
     js.append("					divOffset += o[\"offsetTop\"];\r\n");
     js.append("					o = o.offsetParent;\r\n");
     js.append("				}\r\n");
     js.append("				iPos = iPos + textBox.offsetHeight + 1;\r\n");
     js.append("				div.style.top = iPos;\r\n");
     js.append("				div.style.visibility = \"visible\";\r\n");
     js.append("				if(iPos + textBox.offsetHeight + 31 + popHeight > outerDiv.offsetHeight + divOffset)\r\n");
     js.append("				{\r\n");
     js.append("				     document.body.appendChild(div);\r\n");
     js.append("				}\r\n");
     js.append("			}\r\n");
     js.append("			else if(iPos + textBox.offsetHeight + 1 + popHeight > window.innerHeight + window.document.body.scrollTop - 5)\r\n");
     js.append("			{\r\n");
     js.append("				iPos = iPos - popHeight - 1;\r\n");
     js.append("				div.style.top = iPos;\r\n");
     js.append("				div.style.visibility = \"visible\";\r\n");
     js.append("			}\r\n");
     js.append("			else\r\n");
     js.append("			{\r\n");
     js.append("				iPos = iPos + textBox.offsetHeight + 1;\r\n");
     js.append("				div.style.top = iPos;\r\n");
     js.append("				div.style.visibility = \"visible\";\r\n");
     js.append("			}\r\n");
     js.append("			return iPos;	\r\n");
     js.append("		}");
     js.append("		function GACalendar_getLeft(calendarId, div)\r\n");
     js.append("		{\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var o = textBox;\r\n");
     js.append("			var isDiv = false;\r\n");
     js.append("			iPos = 0;	\r\n");
     js.append("            		var popWidth = parseInt(calendar.getAttribute(\"popWidth\"));\r\n");
     js.append("			while (o!=null && o.tagName != null) 	\r\n");
     js.append("			{	\r\n");
     js.append("				if(o.tagName == \"DIV\")\r\n");
     js.append("			        {	\r\n");
     js.append("			             isDiv = true;\r\n");
     js.append("			             break;	\r\n");
     js.append("			        }	\r\n");
     js.append("				o = o.parentNode;\r\n");
     js.append("			}\r\n");
     js.append("			o = textBox;\r\n");
     js.append("			while(o != null)\r\n");
     js.append("			{\r\n");
     js.append("				if(o.tagName == \"DIV\")\r\n");
     js.append("			        {	\r\n");
     js.append("			             break;	\r\n");
     js.append("			        }\r\n");
     js.append("				iPos += o[\"offsetLeft\"];\r\n");
     js.append("				if(isDiv)\r\n");
     js.append("				{\r\n");
     js.append("					o = o.parentNode;\r\n");
     js.append("				}\r\n");
     js.append("				else\r\n");
     js.append("				{\r\n");
     js.append("					o = o.offsetParent;\r\n");
     js.append("				}\r\n");
     js.append("			}\r\n");
     js.append("			iPos -= document.body.scrollLeft;\r\n");
     js.append("			if(o != null && o.tagName == \"DIV\")	\r\n");
     js.append("			{\r\n");
     js.append("				if(iPos + 16 + popWidth > o.offsetWidth)	\r\n");
     js.append("				{\r\n");
     js.append("					iPos = iPos + 16 + textBox.offsetWidth - popWidth;\r\n");
     js.append("				}\r\n");
     js.append("			}\r\n");
     js.append("			iPos += window.pageXOffset;\r\n");
     js.append("			div.style.left = iPos;\r\n");
     js.append("			return iPos;	\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_showPop(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var img = document.getElementById(calendarId + \"_img\")\r\n");
     js.append("			if(img.getAttribute(\"disabled\") == \"true\")\r\n");
     js.append("			{\r\n");
     js.append("				return;\r\n");
     js.append("			}\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\")\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var div = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
     js.append("		     if(div.getAttribute(\"popShow\") == \"true\")\r\n");
     js.append("		     {\r\n");
     js.append("		               GACalendar_closePop(calendarId);\r\n");
     js.append("		               div.setAttribute(\"popShow\", \"false\");\r\n");
     js.append("		               return;\r\n");
     js.append("		      }\r\n");
     js.append("		     else\r\n");
     js.append("		     {\r\n");
     js.append("		               div.setAttribute(\"popShow\", \"true\");\r\n");
     js.append("		     }\r\n");
     js.append("			calendar.setAttribute(\"isSelected\",\"true\");\r\n");
     js.append("			div.innerHTML = GACalendar_setPop(calendarId);\r\n");
     js.append("			var height = calendar.getAttribute(\"popHeight\");\r\n");
     js.append("			var width = calendar.getAttribute(\"popWidth\");\r\n");
     js.append("			div.style.width = width;\r\n");
     js.append("			div.style.height = height;\r\n");
     js.append("			var left = GACalendar_getLeft(calendarId, div);\r\n");
     js.append("			var top = GACalendar_getTop(calendarId, div);\r\n");
     js.append("			hideElement(\"select\",div);\r\n");
     js.append("			hideElement(\"applet\",div);\r\n");
     js.append("			hideOtherDiv(div);\r\n");
     js.append("						\r\n");
     js.append("		}");
     js.append("		\r\n");
     js.append("		function hideOtherDiv(divObj)\r\n");
     js.append("		{\r\n");
     js.append("			for(var index = 0; index<document.getElementsByTagName(\"div\").length; index++)\r\n");
     js.append("			{\r\n");
     js.append("				var otherDiv = document.getElementsByTagName(\"div\")[index];\r\n");
     js.append("				if(otherDiv.getAttribute(\"type\")==\"calendar_pop\" && otherDiv.id != divObj.id)\r\n");
     js.append("				{\r\n");
     js.append("					hiddenODiv(otherDiv);\r\n");
     js.append("				}\r\n");
     js.append("				else\r\n");
     js.append("				{\r\n");
     js.append("					continue;\r\n");
     js.append("				}\r\n");
     js.append("			}\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("	\r\n");
     js.append("						\r\n");
     js.append("		function GACalendar_setPop(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var textBox = document.getElementById(calendarId);\r\n");
     js.append("			var today = GACalendar_getToday(calendarId);		\r\n");
     js.append("			var title = GACalendar_getTitle(calendarId);\r\n");
     js.append("			var dayHeader = GACalendar_getDayHeader(calendarId);\r\n");
     js.append("			var cellsStr = GACalendar_getCells(calendarId);\r\n");
     js.append("			\r\n");
     js.append("			var html=new String();\r\n");
     js.append("			html += \"<font face='����'><table style=\\\"border-width:1px; border-color:black; border-style:solid;\\\">\";\r\n");
     js.append("			html += title;\r\n");
     js.append("			html += today;\r\n");
     js.append("			html += dayHeader;\r\n");
     js.append("			html += cellsStr;\r\n");
     js.append("			html += \"</table></font>\";\r\n");
     js.append("			return html;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_getCurDate(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var curDateStr = calendar.getAttribute(\"curDate\");\r\n");
     js.append("			return GACalendar_parseToDate(curDateStr);\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_getDefaultDate(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var defaultDateStr = calendar.getAttribute(\"defaultDate\");\r\n");
     js.append("			if(defaultDateStr == null)\r\n");
     js.append("			{\r\n");
     js.append("			    return null;\r\n");
     js.append("			}\r\n");
     js.append("			return GACalendar_parseToDate(defaultDateStr);\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_getSelectedDate(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var selectedDateStr = calendar.getAttribute(\"selectedDate\");\r\n");
     js.append("			if(selectedDateStr == null || selectedDateStr == \"\")\r\n");
     js.append("            {\r\n");
     js.append("                 return \"\";\r\n");
     js.append("            }\r\n");
     js.append("            return GACalendar_parseToDate(selectedDateStr);\r\n");
     js.append("		}\r\n");
     js.append("			\r\n");
     js.append("		function GACalendar_parseToDate(dateStr)\r\n");
     js.append("		{\r\n");
     js.append("			var dateArr = dateStr.split(\"-\");\r\n");
     js.append("			var year = GACalendar_getIntData(dateArr[0]);\r\n");
     js.append("			var month = GACalendar_getIntData(dateArr[1]) - 1;\r\n");
     js.append("			var date = GACalendar_getIntData(dateArr[2]);\r\n");
     js.append("			var newDate = new Date();\r\n");
     js.append("			newDate.setFullYear(year , month , date);\r\n");
     js.append("			return newDate;	\r\n");
     js.append("		}\r\n");
     js.append("			\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_getToday(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var html = new String();\r\n");
     js.append("			var curDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			html += \"<tr style=\\\"background-color:white;  font-size:12px; text-align:center;\\\"><td colspan=7>&nbsp;&nbsp;<a onclick=\\\"GAchangeToCurDate(\";\r\n");
     js.append("			html += \"'\"+ calendarId +\"');\\\" onmouseover=\\\"this.style.textDecoration = 'underline'\\\"  onmouseout=\\\"this.style.textDecoration = 'none'\\\" style=\\\"text-align:center; color:black; cursor:default;\\\">����</a>��\";\r\n");
     js.append("			html += curDate.getFullYear() + \"��\";\r\n");
     js.append("			html += (parseInt(curDate.getMonth())+1) + \"��\";\r\n");
     js.append("			html += curDate.getDate() + \"��\" +\"&nbsp;&nbsp;</td></tr>\";\r\n");
     js.append("			return html;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_getTitle(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var sDate = new Date();\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			sDate = GACalendar_getSelectedDate(calendarId);\r\n");
     js.append("			if(sDate == null||sDate == \"\" || sDate == \"NaN\")\r\n");
     js.append("			{\r\n");
     js.append("				sDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			}\r\n");
     js.append("			var html=new String();\r\n");
     js.append("						\r\n");
     js.append("			html+=\"	<tr style=\\\"background-color:#c0c9d1;  font-size:12px;\\\">\";\r\n");
     js.append("			html+= \"<td colspan=7 style=\\\"text-align:center;\\\">\"\r\n");
     js.append("			html+=\"<table style=\\\"width:100%;\\\"><tr  style=\\\" font-size:12px;\\\">\";\r\n");
     js.append("			html+=\"	<td style=\\\"text-align:left;\\\"><a  onmouseover=\\\"this.style.textDecoration = 'underline'\\\"  onmouseout=\\\"this.style.textDecoration = 'none'\\\"  style=\\\"cursor:default; color:black;\\\" onclick=\\\"window.parent.GAsetSelectedMonth(-1 ,'\";\r\n");
     js.append("			html+=calendarId;\r\n");
     js.append("			html+=\"');\\\" hidefocus><</a>\";\r\n");
     js.append("			html+=\"</td>\";\r\n");
     js.append("			html+=\"<td style=\\\"text-align:center; vertical-align:bottom\\\" ><input type=\\\"text\\\" id=\\\"\" + calendarId + \"_yearText\\\" style=\\\"width:40px; font-size:12px;\\\" value=\\\"\" + sDate.getFullYear() + \"\\\" maxlength=\\\"4\\\"\";\r\n");
     js.append("			html+=\"onblur=\\\"GAchangeYearByTextBox(this, '\" + calendarId + \"', event)\\\">\"\r\n");
     js.append("			html+=\"<table style=\\\"DISPLAY: inline; WIDTH: 19px; HEIGHT: 11px; vertical-align:bottom\\\" ms_positioning=\\\"FlowLayout\\\" cellspacing=0 cellpadding=0 border=0><tr><td>\"\r\n");
     js.append("			html+=\"<INPUT id=\\\"Button2\\\" style=\\\"WIDTH: 18px; HEIGHT: 10px; font-size:5px\\\" type=\\\"button\\\" value=\\\"��\\\" name=\\\"Button2\\\" onclick=\\\"GAchangeYear(1 ,\"+sDate.getFullYear()+\",'\";\r\n");
     js.append("			html+=calendarId;\r\n");
     js.append("			html+=\"')\\\"></td></tr><tr><td>\"\r\n");
     js.append("			html+=\"<INPUT id=\\\"Button1\\\" style=\\\"WIDTH: 18px; HEIGHT: 10px; font-size:5px\\\" type=\\\"button\\\" value=\\\"��\\\" name=\\\"Button1\\\" onclick=\\\"GAchangeYear(-1 ,\"+sDate.getFullYear()+\",'\";\r\n");
     js.append("			html+=calendarId;\r\n");
     js.append("			html+=\"')\\\"></DIV></td></tr></table>\"\r\n");
     js.append("			html+=\"��\"\r\n");
     js.append("			html+=\"<select style=\\\"width:50px; font-size:12px;\\\"  id=\\\"\"+calendar.getAttribute(\"popDiv\")+\"_select\\\"  onchange = \\\"GAchangeMonth(this , '\";\r\n");
     js.append("			html+=calendarId;\r\n");
     js.append("			html+=\"');\\\">\";\r\n");
     js.append("			for(i=0; i<12 ; i++)\r\n");
     js.append("			{\r\n");
     js.append("				if(i == sDate.getMonth())\r\n");
     js.append("				{\r\n");
     js.append("					html+=\"<option style=\\\"font-size:12px\\\" selected=\\\"true\\\">\" + GACalendar_Month[i] + \"</option>\";\r\n");
     js.append("					continue;\r\n");
     js.append("				}\r\n");
     js.append("				html+=\"<option style=\\\"font-size:12px\\\">\" + GACalendar_Month[i] + \"</option>\"\r\n");
     js.append("			}\r\n");
     js.append("			html+=\"</select>\";\r\n");
     js.append("			html+=\"��</td>\"\r\n");
     js.append("			html+=\"	<td  style=\\\"text-align:right;\\\">\";\r\n");
     js.append("			html+=\"	<a  onmouseover=\\\"this.style.textDecoration = 'underline'\\\"  onmouseout=\\\"this.style.textDecoration = 'none'\\\" style=\\\"color:black; cursor:default; \\\" onclick=\\\"GAsetSelectedMonth(1 , '\";\r\n");
     js.append("			html+=calendarId;\r\n");
     js.append("			html+=\"');\\\" hidefocus>></a>\";\r\n");
     js.append("			html+=\"</td>\";\r\n");
     js.append("			html+=\"	<td  style=\\\"text-align:right;\\\">\";\r\n");
     js.append("			html+=\"	<a   onmouseover=\\\"this.style.textDecoration = 'underline'\\\"  onmouseout=\\\"this.style.textDecoration = 'none'\\\" style=\\\"color:black; cursor:default; font-weight:bold; font-size:6pt;\\\" onmouseover=\\\"this.style.\\\" onclick=\\\"GACalendar_closePop('\";\r\n");
     js.append("			html+=calendarId;\r\n");
     js.append("			html+=\"');\\\" hidefocus>�w</a>\";\r\n");
     js.append("			html+=\"</td>\";\r\n");
     js.append("			html+=\"</tr>\";\r\n");
     js.append("			html+=\"</table>\";\r\n");
     js.append("			html+=\"</td>\";\r\n");
     js.append("			html+=\"	</tr>\";\r\n");
     js.append("			\r\n");
     js.append("			return html;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_getDayHeader()\r\n");
     js.append("		{\r\n");
     js.append("				var html=new String();\r\n");
     js.append("				html+=\"<tr style=\\\"background-color:#c0c9d1; font-size:12px;\\\">\";\r\n");
     js.append("				\r\n");
     js.append("				for(var i=0;i<7;i++)\r\n");
     js.append("				{\r\n");
     js.append("					html+=\"<td style=\\\"text-align:center;\\\">\" + GACalendar_ShortWeek[i] + \"</td>\"\r\n");
     js.append("				}\r\n");
     js.append("				html+=\"</tr>\";\r\n");
     js.append("				return html;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_getCells(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var loopLength = 6;\r\n");
     js.append("			var sDate = GACalendar_getSelectedDate(calendarId);\r\n");
     js.append("			if(sDate == null || sDate == \"\" || sDate == \"NaN\")\r\n");
     js.append("			{\r\n");
     js.append("				sDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			}\r\n");
     js.append("			var temp=new Date(sDate.getFullYear(),sDate.getMonth(),1);\r\n");
     js.append("			var temp1 = new Date(sDate.getFullYear() , parseInt(sDate.getMonth()) + 1 , 1);\r\n");
     js.append("			temp1.setDate(parseInt(temp1.getDate()) - 1);\r\n");
     js.append("			var dateLength = temp1.getDate();\r\n");
     js.append("			var begin=temp.getDay();\r\n");
     js.append("			temp.setMonth(temp.getMonth()+1);\r\n");
     js.append("			\r\n");
     js.append("			temp.setDate(temp.getDate()-1);\r\n");
     js.append("			var end=getDays(temp.getMonth(),temp.getFullYear());\r\n");
     js.append("			\r\n");
     js.append("			var html=new String();\r\n");
     js.append("			\r\n");
     js.append("			for(var i=0;i<loopLength ;i++)\r\n");
     js.append("			{\r\n");
     js.append("				html+=\"<tr style=\\\"font-size:12px;\\\">\";\r\n");
     js.append("				for(var j=0;j<7;j++)\r\n");
     js.append("				{\r\n");
     js.append("				\r\n");
     js.append("					html+=GACalendar_getCell(sDate , GACalendar_getCurDate(calendarId) , begin , end ,i*7+j, calendarId);\r\n");
     js.append("				}\r\n");
     js.append("				html+=\"</tr>\";\r\n");
     js.append("			}\r\n");
     js.append("			return html;\r\n");
     js.append("		}\r\n");
     js.append("\r\n");
     js.append("		function GACalendar_getCell(selectedDate , curDate , begin , end , num, calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var html = new String();\r\n");
     js.append("			var curStyle = \"\\\"\";\r\n");
     js.append("			if(curDate.getMonth()==selectedDate.getMonth()&&curDate.getFullYear()==selectedDate.getFullYear()&&(num-begin+1)==curDate.getDate())\r\n");
     js.append("			{\r\n");
     js.append("				curStyle=\"\\\"background-color:#ababab;\";\r\n");
     js.append("			}	\r\n");
     js.append("			if(num%7==0||(num+1)%7==0)\r\n");
     js.append("			{\r\n");
     js.append("				curStyle=\"\\\"\";\r\n");
     js.append("			}\r\n");
     js.append("			if((num-begin+1)==selectedDate.getDate())\r\n");
     js.append("			{\r\n");
     js.append("				curStyle=\"\\\"\";\r\n");
     js.append("			}\r\n");
     js.append("			if(num<begin||(num-begin+1)>end)\r\n");
     js.append("			{\r\n");
     js.append("				curStyle=\"\\\"color:#9c9c9c;\";\r\n");
     js.append("			}\r\n");
     js.append("			if(num-begin+1 == selectedDate.getDate())\r\n");
     js.append("			{\r\n");
     js.append("				curStyle=\"\\\"background-color:#e5e5e6;\"\r\n");
     js.append("			}\r\n");
     js.append("			html+=\"	<td style=\"+curStyle+ \"text-Align:center;\\\" onmouseover=\\\"this.style.cursor='default';this.style.textDecoration = 'underline';\\\"  onmouseout=\\\"this.style.textDecoration='none'\\\">\";\r\n");
     js.append("			if(num<begin)\r\n");
     js.append("			{\r\n");
     js.append("				var mid=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),selectedDate.getDate());\r\n");
     js.append("				mid.setDate(num-begin+1);\r\n");
     js.append("				html+=\"		<a  style=\\\"width:100%\\\" onclick=\\\"GAsetPreMonthDay(-1 , this.innerHTML , '\";\r\n");
     js.append("				html+=calendarId;\r\n");
     js.append("				html+=\"');\\\">\"+mid.getDate()+\"</a>\";\r\n");
     js.append("			}\r\n");
     js.append("			else if((num-begin+1)>end)\r\n");
     js.append("			{\r\n");
     js.append("				var mid=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),selectedDate.getDate());\r\n");
     js.append("				mid.setDate(num-begin+1);\r\n");
     js.append("				html+=\"		<a  style=\\\"width:100%\\\" onclick=\\\"GAsetPreMonthDay(1 , this.innerHTML ,'\";\r\n");
     js.append("				html+=calendarId;\r\n");
     js.append("				html+=\"');\\\">\"+mid.getDate()+\"</a>\";\r\n");
     js.append("			}\r\n");
     js.append("			else\r\n");
     js.append("			{\r\n");
     js.append("				html+=\"		<a  style=\\\"width:100%\\\" onclick=\\\"GAsetPreMonthDay(0 , this.innerHTML , '\";\r\n");
     js.append("				html+=calendarId;\r\n");
     js.append("				html+=\"');\\\">\"+(num-begin+1)+\"</a>\";\r\n");
     js.append("			}\r\n");
     js.append("			html+=\" </td>\";\r\n");
     js.append("			return html;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function getDays(month, year)	\r\n");
     js.append("		{	\r\n");
     js.append("			if (1 == month)	\r\n");
     js.append("				return ((0 == year % 4) && (0 != (year % 100))) || (0 == year % 400) ? 29 : 28;	\r\n");
     js.append("			else	\r\n");
     js.append("				return daysInMonth[month];	\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAJudgeKey(event)\r\n");
     js.append("		{\r\n");
     js.append("			var keyCodes = new Array(109 , 8 , 189 , 27 , 46 , 45 , 39);\r\n");
     js.append("			var inKeyCodes = false;\r\n");
     js.append("			var isNum = false;\r\n");
     js.append("			var isCon = false;\r\n");
     js.append("			if((event.keyCode >=96 && event.keyCode <= 105)||(event.keyCode >=48 && event.keyCode <= 57))\r\n");
     js.append("			{\r\n");
     js.append("				isNum = true;\r\n");
     js.append("			}\r\n");
     js.append("			if(event.keyCode >=35 && event.keyCode <= 37)\r\n");
     js.append("			{\r\n");
     js.append("				isCon = true;\r\n");
     js.append("			}\r\n");
     js.append("			for(i = 0; i<keyCodes.length; i++)\r\n");
     js.append("			{\r\n");
     js.append("				if(event.keyCode == keyCodes[i])\r\n");
     js.append("				{\r\n");
     js.append("					inKeyCodes = true;\r\n");
     js.append("					break;\r\n");
     js.append("				}\r\n");
     js.append("			}\r\n");
     js.append("			if(inKeyCodes || isCon || isNum)\r\n");
     js.append("			{\r\n");
     js.append("				allowKeyPress = true;\r\n");
     js.append("			}\r\n");
     js.append("			else\r\n");
     js.append("			{\r\n");
     js.append("				allowKeyPress = false;\r\n");
     js.append("			}\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAJudgeKeyPress(event)\r\n");
     js.append("		{\r\n");
     js.append("			if(allowKeyPress)\r\n");
     js.append("			{\r\n");
     js.append("				return true;\r\n");
     js.append("			}\r\n");
     js.append("			return false;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAJudgeBlur(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var dateArr = textBox.value.split(\"-\");\r\n");
     js.append("			var year = GACalendar_getIntData(dateArr[0]);\r\n");
     js.append("			var month = GACalendar_getIntData(dateArr[1]) - 1;\r\n");
     js.append("			var date = GACalendar_getIntData(dateArr[2]);\r\n");
     js.append("			var popDiv = document.getElementById(calendar.getAttribute(\"popDiv\"));\r\n");
     js.append("			\r\n");
     js.append("			var defaultDate = GACalendar_getDefaultDate(calendarId);\r\n");
     js.append("			var defaultDateStr = calendar.getAttribute(\"defaultDate\");\r\n");
     js.append("			\r\n");
     js.append("			var oldSelectedDate = GACalendar_getSelectedDate(calendarId)\r\n");
     js.append("			var newDate = GACalendar_getNewDate(year, month, date);\r\n");
     js.append("			if(calendar.getAttribute(\"isSelected\") == \"true\")\r\n");
     js.append("			{\r\n");
     js.append("				return;\r\n");
     js.append("			}\r\n");
     js.append("			if(newDate.getFullYear() != year || newDate.getMonth() != month || newDate.getDate() != date || dateArr[0].length >= 5)\r\n");
     js.append("			{\r\n");
     js.append("				if(defaultDate != null)\r\n");
     js.append("				{\r\n");
     js.append("					GACalendar_ChangeDate(calendarId , defaultDateStr);\r\n");
     js.append("				}\r\n");
     js.append("			}\r\n");
     js.append("			else\r\n");
     js.append("			{\r\n");
     js.append("				GACalendar_ChangeDate(calendarId ,GACalendar_parseToStr(newDate));\r\n");
     js.append("			}\r\n");
     js.append("			\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_parseToStr(curDate)\r\n");
     js.append("		{\r\n");
     js.append("			var year = parseInt(curDate.getFullYear());\r\n");
     js.append("			var month = parseInt(curDate.getMonth()) + 1;\r\n");
     js.append("			var date = parseInt(curDate.getDate());\r\n");
     js.append("			var dateStr = year + \"-\" + month + \"-\" + date;\r\n");
     js.append("			return dateStr;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAsetPreMonthDay(monthoffset , day , calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("            var necessary = calendar.getAttribute(\"necessary\");\r\n");
     js.append("			var defaultDate = GACalendar_getDefaultDate(calendarId);\r\n");
     js.append("			var selectedDate = GACalendar_getSelectedDate(calendarId);\r\n");
     js.append("			var sDate = GACalendar_getSelectedDate(calendarId);\r\n");
     js.append("			var curDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			if(sDate == null || sDate == \"NaN\" || sDate == \"\")\r\n");
     js.append("			{\r\n");
     js.append("			       if(defaultDate == null || defaultDate == \"NaN\" || necessary==\"false\")\r\n");
     js.append("			       {\r\n");
     js.append("			             sDate = curDate;\r\n");
     js.append("			       }\r\n");
     js.append("			}\r\n");
     js.append("			if((sDate == null || sDate == \"\") && necessary == \"true\")\r\n");
     js.append("			{\r\n");
     js.append("				sDate = defaultDate;\r\n");
     js.append("			}\r\n");
     js.append("			var newDate = GACalendar_getNewDate(sDate.getFullYear(), sDate.getMonth() + monthoffset, day);\r\n");
     js.append("			var newDateStr = GACalendar_parseToStr(newDate);\r\n");
     js.append("			GACalendar_ChangeDate(calendarId, newDateStr);\r\n");
     js.append("			var div = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
     js.append("			calendar.appendChild(div);\r\n");
     js.append("			hiddenDiv(div);\r\n");
     js.append("			calendar.setAttribute(\"isSelected\",\"false\");\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_ChangeDate(calendarId, dateStr)\r\n");
     js.append("		{\r\n");
     js.append("		        if(dateStr == \" \")\r\n");
     js.append("		        {\r\n");
     js.append("		               dateStr = ''\r\n");
     js.append("		        }\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			if(calendar.getAttribute(\"selectedDate\") == null)\r\n");
     js.append("			{\r\n");
     js.append("				calendar.setAttribute(\"selectedDate\" , \"\");\r\n");
     js.append("			}\r\n");
     js.append("			var oldDateStr = calendar.getAttribute(\"selectedDate\");\r\n");
     js.append("			var isChanged = GACalendar_DateChanged(oldDateStr, dateStr);\r\n");
     js.append("			calendar.setAttribute(\"selectedDate\",dateStr);\r\n");
     js.append("			textBox.value = dateStr;\r\n");
     js.append("			textBox.setAttribute(\"title\", dateStr);\r\n");
     js.append("			if(isChanged && calendar.getAttribute(\"ondatechange\") != \"\" && calendar.getAttribute(\"ondatechange\") != null)\r\n");
     js.append("			{\r\n");
     js.append("				eval(calendar.getAttribute(\"ondatechange\"));\r\n");
     js.append("			}\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_DateChanged(oldDateStr, newDateStr)\r\n");
     js.append("		{\r\n");
     js.append("			var oldDate = GACalendar_parseToDate(oldDateStr);\r\n");
     js.append("			var newDate = GACalendar_parseToDate(newDateStr);\r\n");
     js.append("			var oldString = GACalendar_parseToStr(oldDate);\r\n");
     js.append("			var newString = GACalendar_parseToStr(newDate);\r\n");
     js.append("			if(oldString != newString)\r\n");
     js.append("			{\r\n");
     js.append("				return true;\r\n");
     js.append("			}\r\n");
     js.append("			return false;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAchangeMonth(selectObj, calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("            var necessary = calendar.getAttribute(\"necessary\");\r\n");
     js.append("			var selectedDate = GACalendar_getSelectedDate(calendarId);\r\n");
     js.append("			var defaultDate = GACalendar_getDefaultDate(calendarId);\r\n");
     js.append("			var sDate = GACalendar_getSelectedDate(calendarId);\r\n");
     js.append("			var curDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			if(sDate == null || sDate == \"NaN\")\r\n");
     js.append("			{\r\n");
     js.append("			       if(defaultDate == null || defaultDate == \"NaN\" || necessary==\"false\")\r\n");
     js.append("			       {\r\n");
     js.append("			             sDate = curDate;\r\n");
     js.append("			       }\r\n");
     js.append("			}\r\n");
     js.append("			if((sDate == null || sDate == \"\") && necessary == \"true\")\r\n");
     js.append("			{\r\n");
     js.append("				sDate = defaultDate;\r\n");
     js.append("			}\r\n");
     js.append("			var newDate = GACalendar_getNewDate(sDate.getFullYear(), selectObj.selectedIndex, sDate.getDate());\r\n");
     js.append("			while(newDate.getMonth() != selectObj.selectedIndex)\r\n");
     js.append("			{\r\n");
     js.append("				newDate.setDate(newDate.getDate() - 1);\r\n");
     js.append("			}\r\n");
     js.append("			textBox.focus();\r\n");
     js.append("			GACalendar_changeAndShow(calendarId, newDate)\r\n");
     js.append("			//textBox.focus();\r\n");
     js.append("			\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAsetSelectedMonth(monthoffset , calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var sDate = new Date();\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("            var necessary = calendar.getAttribute(\"necessary\");\r\n");
     js.append("			var selectedDate = GACalendar_getSelectedDate(calendarId)\r\n");
     js.append("			var defaultDate = GACalendar_getDefaultDate(calendarId);\r\n");
     js.append("			sDate = selectedDate;\r\n");
     js.append("			var curDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			if(sDate == null || sDate == \"NaN\")\r\n");
     js.append("			{\r\n");
     js.append("			       if(defaultDate == null || defaultDate == \"NaN\" || necessary==\"false\")\r\n");
     js.append("			       {\r\n");
     js.append("			             sDate = curDate;\r\n");
     js.append("			       }\r\n");
     js.append("			}\r\n");
     js.append("			if((sDate == null || sDate == \"\") && necessary == \"true\")\r\n");
     js.append("			{\r\n");
     js.append("				sDate = defaultDate;\r\n");
     js.append("			}\r\n");
     js.append("			var newDate = GACalendar_getNewDate(sDate.getFullYear(), sDate.getMonth() + monthoffset, sDate.getDate())\r\n");
     js.append("			while(newDate.getMonth() == sDate.getMonth())\r\n");
     js.append("			{\r\n");
     js.append("				newDate.setDate(newDate.getDate() - 1);\r\n");
     js.append("			}\r\n");
     js.append("			GACalendar_changeAndShow(calendarId, newDate)\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAchangeToCurDate(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("\r\n");
     js.append("			var selectedDate = GACalendar_getSelectedDate(calendarId);\r\n");
     js.append("			var curDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			var newDate = curDate;\r\n");
     js.append("			var newDateStr = GACalendar_parseToStr(newDate);\r\n");
     js.append("			GACalendar_ChangeDate(calendarId, newDateStr);\r\n");
     js.append("			var div = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
     js.append("			calendar.appendChild(div);\r\n");
     js.append("			hiddenDiv(div);\r\n");
     js.append("			calendar.setAttribute(\"isSelected\",\"false\");\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAchangeYearByTextBox(yearTextBox, calendarId,event)\r\n");
     js.append("		{\r\n");
     js.append("			var year = yearTextBox.value;\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("            var necessary = calendar.getAttribute(\"necessary\");\r\n");
     js.append("			var selectedDate = GACalendar_getSelectedDate(calendarId);\r\n");
     js.append("			var defaultDate = GACalendar_getDefaultDate(calendarId);\r\n");
     js.append("			var sDate = new Date();\r\n");
     js.append("			sDate = selectedDate;\r\n");
     js.append("			var curDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			if(sDate == null || sDate == \"NaN\")\r\n");
     js.append("			{\r\n");
     js.append("			       if(defaultDate == null || defaultDate == \"NaN\" || necessary==\"false\")\r\n");
     js.append("			       {\r\n");
     js.append("			             sDate = curDate;\r\n");
     js.append("			       }\r\n");
     js.append("			}\r\n");
     js.append("			if((sDate == null || sDate == \"\") && necessary == \"true\")\r\n");
     js.append("			{\r\n");
     js.append("				sDate = defaultDate;\r\n");
     js.append("			}\r\n");
     js.append("			var newDate = GACalendar_getNewDate(year, sDate.getMonth(), sDate.getDate());\r\n");
     js.append("			while(newDate.getMonth() != sDate.getMonth())\r\n");
     js.append("			{\r\n");
     js.append("				newDate.setDate(newDate.getDate() - 1);\r\n");
     js.append("			}\r\n");
     js.append("			GACalendar_changeAndShow(calendarId, newDate)\r\n");
     js.append("			\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GAchangeYear(off , value , calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var sDate = new Date();\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("            var necessary = calendar.getAttribute(\"necessary\");\r\n");
     js.append("			var selectedDate = GACalendar_getSelectedDate(calendarId)\r\n");
     js.append("			var defaultDate = GACalendar_getDefaultDate(calendarId);\r\n");
     js.append("			sDate = selectedDate;\r\n");
     js.append("			var curDate = GACalendar_getCurDate(calendarId);\r\n");
     js.append("			if(sDate == null || sDate == \"NaN\" || sDate == \"\")\r\n");
     js.append("			{\r\n");
     js.append("			       if(defaultDate == null || defaultDate == \"NaN\" || necessary==\"false\")\r\n");
     js.append("			       {\r\n");
     js.append("			             sDate = curDate;\r\n");
     js.append("			       }\r\n");
     js.append("			}\r\n");
     js.append("			if((sDate == null || sDate == \"\") && necessary == \"true\")\r\n");
     js.append("			{\r\n");
     js.append("				sDate = defaultDate;\r\n");
     js.append("			}\r\n");
     js.append("			var newDate = GACalendar_getNewDate(value+off, sDate.getMonth(), sDate.getDate());\r\n");
     js.append("			while(newDate.getMonth() != sDate.getMonth())\r\n");
     js.append("			{\r\n");
     js.append("				newDate.setDate(newDate.getDate() - 1);\r\n");
     js.append("			}\r\n");
     js.append("			textBox.focus();\r\n");
     js.append("			GACalendar_changeAndShow(calendarId, newDate)\r\n");
     js.append("			\r\n");
     js.append("			\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_changeAndShow(calendarId, newDate)\r\n");
     js.append("		{\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var newDateStr = GACalendar_parseToStr(newDate);\r\n");
     js.append("			GACalendar_ChangeDate(calendarId, newDateStr);\r\n");
     js.append("			var div = document.getElementById(calendar.getAttribute(\"popdiv\"));\r\n");
     js.append("			calendar.appendChild(div);\r\n");
     js.append("			hiddenDiv(div);\r\n");
     js.append("			GACalendar_showPop(calendarId);\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_getNewDate(year,month,day)\r\n");
     js.append("		{\r\n");
     js.append("			var newDate = new Date();\r\n");
     js.append("			newDate.setFullYear(year, month, day);\r\n");
     js.append("			return newDate;\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_setValue(calendarId, dateStr)\r\n");
     js.append("		{\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("	                textBox.value = dateStr;\r\n");
     js.append("        	        textBox.title = dateStr;\r\n");
     js.append("                	calendar.setAttribute(\"selectedDate\",dateStr);\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function hiddenODiv(divObj)\r\n");
     js.append("		{\r\n");
     js.append("			divObj.style.visibility = \"hidden\";\r\n");
     js.append("			divObj.innerHTML = \"\";\r\n");
     js.append("			divObj.style.width = 0;\r\n");
     js.append("			divObj.style.height = 0;\r\n");
     js.append("			divObj.style.top = 0;\r\n");
     js.append("			divObj.style.left = 0;\r\n");
     js.append("			divObj.style.position = \"absolute\";\r\n");
     js.append("			showElement(\"select\");\r\n");
     js.append("			showElement(\"applet\");\r\n");
     js.append("		}\r\n");
     js.append("		function hiddenDiv(divObj)\r\n");
     js.append("		{\r\n");
     js.append("			divObj.style.visibility = \"hidden\";\r\n");
     js.append("			divObj.innerHTML = \"\";\r\n");
     js.append("			divObj.style.width = 0;\r\n");
     js.append("			divObj.style.height = 0;\r\n");
     js.append("			divObj.style.top = 0;\r\n");
     js.append("			divObj.style.left = 0;\r\n");
     js.append("			divObj.style.position = \"absolute\";\r\n");
     js.append("			divObj.setAttribute(\"popshow\", \"false\");\r\n");
     js.append("			showElement(\"select\");\r\n");
     js.append("			showElement(\"applet\");\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function validateKey(textBox)\r\n");
     js.append("		{\r\n");
     js.append("			if(event.keyCode == 13)\r\n");
     js.append("			{\r\n");
     js.append("				textBox.blur();\r\n");
     js.append("				return;\r\n");
     js.append("			}\r\n");
     js.append("			if((event.keyCode >=96 && event.keyCode <= 105)||(event.keyCode >=48 && event.keyCode <= 57))\r\n");
     js.append("			{\r\n");
     js.append("				allowKeyPress = true;\r\n");
     js.append("			}\r\n");
     js.append("			else\r\n");
     js.append("			{\r\n");
     js.append("				allowKeyPress = false;\r\n");
     js.append("			}\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function GACalendar_closePop(calendarId)\r\n");
     js.append("		{\r\n");
     js.append("			var calendar = document.getElementById(calendarId);\r\n");
     js.append("			var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("			var popDiv = document.getElementById(calendar.getAttribute(\"popDiv\"));\r\n");
     js.append("			calendar.setAttribute(\"isSelected\",\"false\");\r\n");
     js.append("			calendar.appendChild(popDiv);\r\n");
     js.append("			hiddenDiv(popDiv)\r\n");
     js.append("     			popDiv.setAttribute(\"popShow\",\"false\");\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function hideElement( elmID, overDiv )\r\n");
     js.append("		{\r\n");
     js.append("			for( i = 0; i < document.getElementsByTagName( elmID ).length; i++ )\r\n");
     js.append("		    {\r\n");
     js.append("				obj = document.getElementsByTagName(elmID)[i];\r\n");
     js.append("				if( !obj || !obj.offsetParent || obj.id == overDiv.id + \"_select\")\r\n");
     js.append("				{\r\n");
     js.append("					continue;\r\n");
     js.append("				}\r\n");
     js.append("      \r\n");
     js.append("				// Find the element's offsetTop and offsetLeft relative to the BODY tag.\r\n");
     js.append("				objLeft   = obj.offsetLeft;\r\n");
     js.append("				objTop    = obj.offsetTop;\r\n");
     js.append("				objParent = obj.offsetParent;\r\n");
     js.append("          \r\n");
     js.append("				while( objParent.tagName.toUpperCase() != \"BODY\" )\r\n");
     js.append("				{\r\n");
     js.append("					objLeft  += objParent.offsetLeft;\r\n");
     js.append("					objTop   += objParent.offsetTop;\r\n");
     js.append("					objParent = objParent.offsetParent;\r\n");
     js.append("				}\r\n");
     js.append("      \r\n");
     js.append("				objHeight = obj.offsetHeight;\r\n");
     js.append("				objWidth = obj.offsetWidth;\r\n");
     js.append("      \r\n");
     js.append("				if(( overDiv.offsetLeft + overDiv.offsetWidth ) <= objLeft );\r\n");
     js.append("				else if(( overDiv.offsetTop + overDiv.offsetHeight ) <= objTop );\r\n");
     js.append("				else if( overDiv.offsetTop >= ( objTop + objHeight ));\r\n");
     js.append("				else if( overDiv.offsetLeft >= ( objLeft + objWidth ));\r\n");
     js.append("				else\r\n");
     js.append("				{\r\n");
     js.append("					obj.style.visibility = \"hidden\";\r\n");
     js.append("				}\r\n");
     js.append("			}\r\n");
     js.append("		}\r\n");
     js.append("		\r\n");
     js.append("		function showElement( elmID )\r\n");
     js.append("		{\r\n");
     js.append("		    for( i = 0; i < document.getElementsByTagName( elmID ).length; i++ )\r\n");
     js.append("			{\r\n");
     js.append("	          obj = document.getElementsByTagName( elmID )[i];\r\n");
     js.append("              if( !obj || !obj.offsetParent )\r\n");
     js.append("			  {\r\n");
     js.append("				continue;\r\n");
     js.append("			  }\r\n");
     js.append("              obj.style.visibility = \"\";\r\n");
     js.append("			}\r\n");
     js.append("		}\r\n");
     js.append("		function GACalendar_getIntData(dataStr)\r\n");
     js.append("		{\r\n");
     js.append("		      if(dataStr == null)\r\n");
     js.append("		      {\r\n");
     js.append("		              return;\r\n");
     js.append("		      }\r\n");
     js.append("		        var startIndex = 0;\r\n");
     js.append("		        for(var index = 0; index < dataStr.length; index++)\r\n");
     js.append("		        {\r\n");
     js.append("		                if(dataStr.substring(index,index+1) != \"0\")\r\n");
     js.append("		                {\r\n");
     js.append("		                        break;\r\n");
     js.append("		                }\r\n");
     js.append("		                else\r\n");
     js.append("		                {\r\n");
     js.append("		                        startIndex = index + 1;\r\n");
     js.append("		                }\r\n");
     js.append("		        }\r\n");
     js.append("		        var newStr = dataStr.substring(startIndex, dataStr.length);\r\n");
     js.append("		        return parseInt(newStr);\r\n");
     js.append("		}\r\n");
     js.append("        \r\n");
     js.append("                function GACalendar_getValue(calendarId)\r\n");
     js.append("                {\r\n");
     js.append("                        var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("                        GAJudgeBlur(calendarId)\r\n");
     js.append("          		GACalendar_closePop(calendarId);\r\n");
     js.append("                        return textBox.value;\r\n");
     js.append("                }\r\n");
     js.append("                function GACalendar_setProperty(calendarId, property, value)\r\n");
     js.append("                {\r\n");
     js.append("						var calendar = document.getElementById(calendarId);\r\n");
     js.append("                        var textBox = document.getElementById(calendarId + \"_textBox\");\r\n");
     js.append("                        var button = document.getElementById(calendarId + \"_img\");\r\n");
     js.append("                        if(property.toLowerCase() == \"readonly\")\r\n");
     js.append("                        {\r\n");
     js.append("                              if(value.toLowerCase() == \"true\")\r\n");
     js.append("                              {\r\n");
     js.append("                                    textBox.readOnly = true;\r\n");
     js.append("                                    button.setAttribute(\"disabled\",\"true\");\r\n");
     js.append("                                    var src = calendar.getAttribute(\"dissrc\");\r\n");
     js.append("                                    button.src = src;\r\n");
     js.append("                              }\r\n");
     js.append("                              else\r\n");
     js.append("                              {\r\n");
     js.append("                                    textBox.readOnly = false;\r\n");
     js.append("                                    button.setAttribute(\"disabled\",\"false\");\r\n");
     js.append("                                    var src = calendar.getAttribute(\"src\");\r\n");
     js.append("                                    button.src = src;\r\n");
     js.append("                              }\r\n");
     js.append("                        }\r\n");
     js.append("                        else if(property.toLowerCase() == \"necessary\")\r\n");
     js.append("                        {\r\n");
     js.append("                                if(value.toLowerCase() == \"true\")\r\n");
     js.append("                                {\r\n");
     js.append("                                        textBox.style.backgroundColor = \"yellow\";\r\n");
     js.append("                                        calendar.setAttribute(\"necessary\",\"true\");\r\n");
     js.append("                                }\r\n");
     js.append("                                else if(value.toLowerCase() == \"false\")\r\n");
     js.append("                                {\r\n");
     js.append("                                        textBox.style.backgroundColor = \"white\";\r\n");
     js.append("                                        calendar.setAttribute(\"necessary\", \"false\");\r\n");
     js.append("                                }\r\n");
     js.append("                        }\r\n");
     js.append("                        else if(property.toLowerCase() == \"width\")\r\n");
     js.append("                        {\r\n");
     js.append("                                textBox.style.width = value - 18;\r\n");
     js.append("                        }\r\n");
     js.append("                }\r\n");
     js.append("                \r\n");
     js.append("\r\n");
     js.append("                \r\n");
     js.append("              \r\n");
     js.append("");

     jstool.js=js;
     return jstool.getComponentJS();
  }

}