package com.born.insurance.webui.control;

/**
 * Title:ColumnSetJS Class<br>
 * Description:��Ŀ���ö�Ӧ��JavaScript��<br>
 * Copyright: Copyright (c) 2003<br>
 * Company: bornsoft<br>
 * <br>�ͻ��˷������£�<br>
 * function setItemSelectedfun(componentid,functionname)<br>
 * ���ܣ�����ѡ��ʱ������ִ�е�JavaScript��<br>
 * ����componentid ���ID;functionname JavaScript������<br>
 * <br>
 * function getItemSelectedfun(componentid)<br>
 * ���ܣ�����ѡ��ʱ������ִ�е�JavaScript��<br>
 * ����componentid ���ID<br>
 * Retrun:JavaScript������<br>
 * <br>
 * function setItemChangedfun(componentid,functionname)<br>
 * ���ܣ���Ŀ���øı�ʱ������ִ�е�JavaScript��<br>
 * ����componentid ���ID;functionname JavaScript������<br>
 * <br>
 * function getItemChangedfun(componentid)<br>
 * ���ܣ���Ŀ���øı�ʱ������ִ�е�JavaScript��<br>
 * ����componentid ���ID<br>
 * Retrun:JavaScript������<br>
 * @author �ᴺ��
 * @version 1.0
 */
public class ColumnSetJS{
	/**
	 * ȡ��Ŀ���ö�Ӧ��JavaScript<br>
	 * @return String ��Ŀ���ö�Ӧ��JavaScript<br>
	 */
	public static String getColumnSetJS(){
		JSTool jstool=new JSTool("ColumnSet.js");
		if(!jstool.util.isUpdateJsEveryTime())
		 {
			 return jstool.getComponentJS() ;//+ HashMapJS.getHashMapJS();
		 }
		StringBuffer js = new StringBuffer();
		js.append("	function AddAllBtnClicked(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("		{\r\n");
		js.append("		if (addAllBtn.disabled)\r\n");
		js.append("			return;//compatible with mozilla\r\n");
		js.append("			SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');	\r\n");
		js.append("			var length=sourceBox.options.length;\r\n");
		js.append("			for(var index=0;index<length;index++)\r\n");
		js.append("			{\r\n");
		js.append("				selectBox.appendChild(sourceBox.options[0]);\r\n");
		js.append("				selectBox.selectedIndex=0;\r\n");
		js.append("			} \r\n");
		js.append("			Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("			if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("				eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("		}\r\n");
		js.append("	function optiondblClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if(sourceBox.selectedIndex==-1)\r\n");
		js.append("		{\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');	\r\n");
		js.append("		selectedIndex=sourceBox.selectedIndex;\r\n");
		js.append("		selectBox.appendChild(sourceBox.options[sourceBox.selectedIndex]);\r\n");
		js.append("		if(sourceBox.options.length==selectedIndex)\r\n");
		js.append("		{\r\n");
		js.append("			sourceBox.selectedIndex=sourceBox.options.length-1;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			sourceBox.selectedIndex=selectedIndex;\r\n");
		js.append("		}\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("			eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("	}\r\n");
		js.append("	function optionclick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if(sourceBox.selectedIndex==-1)\r\n");
		js.append("		{\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (selectedeventhidden.getAttribute(\"ItemSelected\")!=\"\"&&selectedeventhidden.getAttribute(\"ItemSelected\")!=null)\r\n");
		js.append("			eval(selectedeventhidden.getAttribute(\"ItemSelected\"));\r\n");
		js.append("	}\r\n");
		js.append("	function RemoveAllBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (removeAllBtn.disabled)\r\n");
		js.append("			return;//compatible with mozilla\r\n");
		js.append("		SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');	\r\n");
		js.append("		var length=selectBox.options.length;\r\n");
		js.append("		var SubIndex=0;\r\n");
		js.append("		for(var index=0;index<length;index++)\r\n");
		js.append("		{\r\n");
		js.append("			if(selectBox.options[SubIndex].getAttribute(\"flag\")==222||selectBox.options[SubIndex].getAttribute(\"flag\")==111||selectBox.options[SubIndex].getAttribute(\"flag\")==000)\r\n");
		js.append("			{\r\n");
		js.append("				SubIndex++;\r\n");
		js.append("				continue;\r\n");
		js.append("			}\r\n");
		js.append("			sourceBox.appendChild(selectBox.options[SubIndex]);\r\n");
		js.append("			sourceBox.selectedIndex=0;\r\n");
		js.append("		}\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("			eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("	}\r\n");
		js.append("	function RemoveOneBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (removeOneBtn.disabled)\r\n");
		js.append("			return;//compatible with mozilla\r\n");
		js.append("		SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');	\r\n");
		js.append("		selectedIndex=selectBox.selectedIndex;\r\n");
		js.append("		if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==000)\r\n");
		js.append("		{\r\n");
		js.append("		    if(!((myprompt.getAttribute(\"value0\")==\"\")||(myprompt.getAttribute(\"value0\")==null)))\r\n");
		js.append("		    {\r\n");
		js.append("				alert(myprompt.getAttribute(\"value0\"));\r\n");
		js.append("		    }\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		else if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==222)\r\n");
		js.append("		{\r\n");
		js.append("		    if(!((myprompt.getAttribute(\"value2\")==\"\")||(myprompt.getAttribute(\"value2\")==null)))\r\n");
		js.append("		    {\r\n");
		js.append("				alert(myprompt.getAttribute(\"value2\"));\r\n");
		js.append("		    }\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		else if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==111)\r\n");
		js.append("		{\r\n");
		js.append("		    if(!((myprompt.getAttribute(\"value1\")==\"\")||(myprompt.getAttribute(\"value1\")==null)))\r\n");
		js.append("		    {\r\n");
		js.append("				alert(myprompt.getAttribute(\"value1\"));\r\n");
		js.append("		    }\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		sourceBox.appendChild(selectBox.options[selectBox.selectedIndex]);\r\n");
		js.append("		if(selectBox.options.length==selectedIndex)\r\n");
		js.append("		{\r\n");
		js.append("			selectBox.selectedIndex=selectBox.options.length-1;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			selectBox.selectedIndex=selectedIndex;\r\n");
		js.append("		}\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("			eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("	}\r\n");
		js.append("	function AddOneBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (addOneBtn.disabled)\r\n");
		js.append("			return;//compatible with mozilla\r\n");
		js.append("		SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');	\r\n");
		js.append("		selectedIndex=sourceBox.selectedIndex;\r\n");
		js.append("		selectBox.appendChild(sourceBox.options[sourceBox.selectedIndex]);\r\n");
		js.append("		if(sourceBox.options.length==selectedIndex)\r\n");
		js.append("		{\r\n");
		js.append("			sourceBox.selectedIndex=sourceBox.options.length-1;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			sourceBox.selectedIndex=selectedIndex;\r\n");
		js.append("		}\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("			eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("	}\r\n");
		js.append("	function selectedoptionclick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if(selectBox.selectedIndex==-1)\r\n");
		js.append("		{\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (selectedeventhidden.getAttribute(\"ItemSelected\")!=\"\"&&selectedeventhidden.getAttribute(\"ItemSelected\")!=null)\r\n");
		js.append("			eval(selectedeventhidden.getAttribute(\"ItemSelected\"));\r\n");
		js.append("	}\r\n");
		js.append("	function selectedoptiondbclick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if(selectBox.selectedIndex==-1)\r\n");
		js.append("		{\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');	\r\n");
		js.append("		selectedIndex=selectBox.selectedIndex;\r\n");
		js.append("		if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==000)\r\n");
		js.append("		{\r\n");
		js.append("			if(!((myprompt.getAttribute(\"value0\")==\"\")||(myprompt.getAttribute(\"value0\")==null)))\r\n");
		js.append("			{\r\n");
		js.append("				alert(myprompt.getAttribute(\"value0\"));\r\n");
		js.append("			}\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		else if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==222)\r\n");
		js.append("		{\r\n");
		js.append("			if(!((myprompt.getAttribute(\"value2\")==\"\")||(myprompt.getAttribute(\"value2\")==null)))\r\n");
		js.append("			{\r\n");
		js.append("				alert(myprompt.getAttribute(\"value2\"));\r\n");
		js.append("			}\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		else if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==111)\r\n");
		js.append("		{\r\n");
		js.append("			if(!((myprompt.getAttribute(\"value1\")==\"\")||(myprompt.getAttribute(\"value1\")==null)))\r\n");
		js.append("			{\r\n");
		js.append("				alert(myprompt.getAttribute(\"value1\"));\r\n");
		js.append("			}\r\n");
		js.append("			return;\r\n");
		js.append("		}\r\n");
		js.append("		sourceBox.appendChild(selectBox.options[selectBox.selectedIndex]);\r\n");
		js.append("		if(selectBox.options.length==selectedIndex)\r\n");
		js.append("		{\r\n");
		js.append("			selectBox.selectedIndex=selectBox.options.length-1;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			selectBox.selectedIndex=selectedIndex;\r\n");
		js.append("		}\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("			eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("	}\r\n");
		js.append("	function Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		var IsEssentialItem=true;\r\n");
		js.append("		var FixItemsCount=0;\r\n");
		js.append("		var NoMoveItemsCount=0;\r\n");
		js.append("		for(index=0;index<selectBox.options.length;index++)\r\n");
		js.append("		{\r\n");
		js.append("			if(selectBox.options[index].getAttribute(\"flag\")!=222&&selectBox.options[index].getAttribute(\"flag\")!=111&&selectBox.options[index].getAttribute(\"flag\")!=000)\r\n");
		js.append("			{\r\n");
		js.append("				IsEssentialItem=false;\r\n");
		js.append("				continue;\r\n");
		js.append("			}\r\n");
		js.append("			else if(selectBox.options[index].getAttribute(\"flag\")==000)\r\n");
		js.append("			{\r\n");
		js.append("				FixItemsCount++;\r\n");
		js.append("				NoMoveItemsCount++;\r\n");
		js.append("			}\r\n");
		js.append("			else if(selectBox.options[index].getAttribute(\"flag\")==111)\r\n");
		js.append("			{\r\n");
		js.append("				FixItemsCount++;\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		if(sourceBox.selectedIndex==-1)\r\n");
		js.append("		{\r\n");
		js.append("			addOneBtn.disabled=true;	\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			addOneBtn.disabled=false;\r\n");
		js.append("		}\r\n");
		js.append("		if(sourceBox.options.length==0)\r\n");
		js.append("		{\r\n");
		js.append("			addAllBtn.disabled=true;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			addAllBtn.disabled=false;\r\n");
		js.append("		}\r\n");
		js.append("		if(selectBox.selectedIndex==-1||selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==222||selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==111||selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==000)\r\n");
		js.append("		{\r\n");
		js.append("			removeOneBtn.disabled=true;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("		removeOneBtn.disabled=false;\r\n");
		js.append("		}\r\n");
		js.append("	\r\n");
		js.append("		if(selectBox.options.length==0||IsEssentialItem)\r\n");
		js.append("		{	\r\n");
		js.append("			removeAllBtn.disabled=true;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			removeAllBtn.disabled=false;\r\n");
		js.append("		}\r\n");
		js.append("		if(selectBox.options.length<=1||selectBox.options.selectedIndex==-1)\r\n");
		js.append("		{\r\n");
		js.append("			preBtn.disabled=true;\r\n");
		js.append("			nextBtn.disabled=true;\r\n");
		js.append("		}\r\n");
		js.append("		else if(selectBox.selectedIndex==0)\r\n");
		js.append("		{\r\n");
		js.append("			preBtn.disabled=true;\r\n");
		js.append("			nextBtn.disabled = false;\r\n");
		js.append("			if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==000)\r\n");
		js.append("			{\r\n");
		js.append("				nextBtn.disabled=true;\r\n");
		js.append("			}\r\n");
		js.append("			if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==111)\r\n");
		js.append("			{\r\n");
		js.append("				if(FixItemsCount>NoMoveItemsCount+1)\r\n");
		js.append("				{\r\n");
		js.append("					nextBtn.disabled=false;\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					nextBtn.disabled=true;\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		else if(selectBox.selectedIndex==selectBox.options.length-1)\r\n");
		js.append("		{\r\n");
		js.append("			nextBtn.disabled=true;\r\n");
		js.append("			if(FixItemsCount==selectBox.options.length-1)\r\n");
		js.append("			{\r\n");
		js.append("				preBtn.disabled=true;\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{	\r\n");
		js.append("				preBtn.disabled=false;\r\n");
		js.append("			}\r\n");
		js.append("			\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==000)\r\n");
		js.append("			{\r\n");
		js.append("				preBtn.disabled=true;\r\n");
		js.append("				nextBtn.disabled=true;\r\n");
		js.append("			}\r\n");
		js.append("			else if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==111)\r\n");
		js.append("			{\r\n");
		js.append("				if(selectBox.selectedIndex<FixItemsCount-1&&selectBox.selectedIndex>NoMoveItemsCount)\r\n");
		js.append("				{\r\n");
		js.append("					preBtn.disabled=false;\r\n");
		js.append("					nextBtn.disabled=false;\r\n");
		js.append("				}\r\n");
		js.append("				else if(selectBox.selectedIndex >= FixItemsCount-1)\r\n");
		js.append("				{\r\n");
		js.append("					preBtn.disabled=false;\r\n");
		js.append("					nextBtn.disabled=true;\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					preBtn.disabled=true;\r\n");
		js.append("					nextBtn.disabled=false;\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				if(selectBox.selectedIndex>FixItemsCount)\r\n");
		js.append("				{\r\n");
		js.append("					preBtn.disabled=false;\r\n");
		js.append("					nextBtn.disabled=false;\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					preBtn.disabled=true;\r\n");
		js.append("					nextBtn.disabled=false;\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		if((wInput!=null)&&(wLab!=null))\r\n");
		js.append("		{\r\n");
		js.append("			WatchBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		}\r\n");
		js.append("		SetResult(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		SetBtnSrc(addOneBtn);\r\n");
		js.append("		SetBtnSrc(addAllBtn);\r\n");
		js.append("		SetBtnSrc(removeOneBtn);\r\n");
		js.append("		SetBtnSrc(removeAllBtn);\r\n");
		js.append("		if(preBtn.src != null)\r\n");
		js.append("			SetBtnSrc(preBtn);\r\n");
		js.append("		if(nextBtn.src != null)\r\n");
		js.append("			SetBtnSrc(nextBtn);\r\n");
		js.append("	}\r\n");
		js.append("	function PreviousBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (preBtn.disabled)\r\n");
		js.append("			return;//compatible with mozilla\r\n");
		js.append("		SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');	\r\n");
		js.append("		var nod=selectBox.options[selectBox.selectedIndex-1];\r\n");
		js.append("		selectBox.replaceChild(selectBox.options[selectBox.selectedIndex],selectBox.options[selectBox.selectedIndex-1]);\r\n");
		js.append("		selectBox.insertBefore(nod,selectBox.options[selectBox.selectedIndex+1]);\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("				eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("	}\r\n");
		js.append("	function NextBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (nextBtn.disabled)\r\n");
		js.append("			return;//compatible with mozilla\r\n");
		js.append("		SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');	\r\n");
		js.append("		var nod=selectBox.options[selectBox.selectedIndex+1];\r\n");
		js.append("		selectBox.replaceChild(selectBox.options[selectBox.selectedIndex],selectBox.options[selectBox.selectedIndex+1]);\r\n");
		js.append("		selectBox.insertBefore(nod,selectBox.options[selectBox.selectedIndex]);\r\n");
		js.append("		Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("		if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("				eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("	}\r\n");
		js.append("	function WatchBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if(selectBox.selectedIndex!=-1)\r\n");
		js.append("		{	\r\n");
		js.append("			curObj.value=selectBox.selectedIndex;\r\n");
		//js.append("			wInput.value=selectBox.options[selectBox.selectedIndex].text;\r\n");
		
		
		js.append("			var selecteditemid=selectBox.options[selectBox.selectedIndex].value;\r\n");
		
		js.append("			var columnSetId=sourceBox.id.substring(0,sourceBox.id.indexOf('_'));\r\n");
		js.append("			//alert(columnSetId);\r\n");
		js.append("			var widthset = document.getElementById(columnSetId+'_widthset');\r\n");
		js.append("			var width=HashtableManager_Get(selecteditemid,widthset);\r\n");
		
		js.append("			if(width!=null){ wInput.value=width}\r\n");
		js.append("			else{ wInput.value=0}\r\n");
		js.append("			if(selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==111||selectBox.options[selectBox.selectedIndex].getAttribute(\"flag\")==000)\r\n");
		js.append("			{\r\n");
		js.append("				if(selectBox.options[selectBox.selectedIndex].getAttribute(\"onlyread\")==\"true\")\r\n");
		js.append("				{\r\n");
		js.append("					wInput.disabled=true;\r\n");
		js.append("					wInput.readOnly=true;\r\n");
		js.append("					wLab.disabled=true;\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					wInput.disabled=false;\r\n");
		js.append("					wInput.readOnly=false;\r\n");
		js.append("					wLab.disabled=false;\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				wInput.disabled=false;\r\n");
		js.append("				wInput.readOnly=false;\r\n");
		js.append("				wLab.disabled=false;\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			wInput.value=\"\";\r\n");
		js.append("			wInput.disabled=true;\r\n");
		js.append("			wInput.readOnly=true;\r\n");
		js.append("			wLab.disabled=true;\r\n");
		js.append("			curObj.value=\"\";\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	function SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,blnIsChange)\r\n");
		js.append("	{\r\n");
		js.append("		if ((wInput!=null)&&(wLab!=null))\r\n");
		js.append("		{\r\n");
		js.append("			if(Trim(wInput.value)==\"\"||wInput.value==null)\r\n");
		js.append("			{\r\n");
		js.append("				if(curObj.value!=\"\")\r\n");
		js.append("				{\r\n");
		js.append("					if(!((myprompt.getAttribute(\"value3\")==\"\")||(myprompt.getAttribute(\"value3\")==null)))\r\n");
		js.append("					{\r\n");
		js.append("						alert(myprompt.getAttribute(\"value3\"));\r\n");
		js.append("					}\r\n");
		js.append("					selectBox.selectedIndex=curObj.value;\r\n");
		js.append("					return (\"-1\");\r\n");
		js.append("				}\r\n");
		js.append("				return (\"1\");\r\n");
		js.append("			}\r\n");
		js.append("			else if(wInput.value==\"ID\"||wInput.value==\"id\"||wInput.value==\"Id\"||wInput.value==\"iD\")\r\n");//||wInput.value==\"����\"||wInput.value==\"ͣ��\")\r\n");
		js.append("			{\r\n");
		js.append("				if(!((myprompt.getAttribute(\"value5\")==\"\")||(myprompt.getAttribute(\"value5\")==null)))\r\n");
		js.append("				{\r\n");
		js.append("					alert(myprompt.getAttribute(\"value5\")+wInput.value);\r\n");
		js.append("				}\r\n");
		js.append("				selectBox.selectedIndex=curObj.value;\r\n");
		js.append("				return (\"-1\");\r\n");
		js.append("			}\r\n");
		js.append("			if(selectBox.selectedIndex!=-1)\r\n");
		js.append("			{\r\n");
		js.append("				for(var index=0;index<selectBox.options.length;index++)\r\n");
		js.append("				{\r\n");
		js.append("					if(curObj.value==index)\r\n");
		js.append("					{\r\n");
		js.append("						continue;\r\n");
		js.append("					}\r\n");
		js.append("					if(selectBox.options[index].text==wInput.value)\r\n");
		js.append("					{\r\n");
		js.append("						if(!((myprompt.getAttribute(\"value4\")==\"\")||(myprompt.getAttribute(\"value4\")==null)))\r\n");
		js.append("						{\r\n");
		js.append("							alert(myprompt.getAttribute(\"value4\"));\r\n");
		js.append("						}\r\n");
		js.append("						return (\"-1\");\r\n");
		js.append("					}\r\n");
		js.append("				}\r\n");
		js.append("				for(var index=0;index<sourceBox.options.length;index++)\r\n");
		js.append("				{\r\n");
		js.append("					if(sourceBox.options[index].text==wInput.value)\r\n");
		js.append("					{\r\n");
		js.append("						if(!((myprompt.getAttribute(\"value4\")==\"\")||(myprompt.getAttribute(\"value4\")==null)))\r\n");
		js.append("						{\r\n");
		js.append("							alert(myprompt.getAttribute(\"value4\"));\r\n");
		js.append("						}\r\n");
		js.append("						return (\"-1\");\r\n");
		js.append("					}\r\n");
		js.append("				}\r\n");
		js.append("				//selectBox.options[curObj.value].text=wInput.value;\r\n");
		js.append("				if (blnIsChange=='true')\r\n");
		js.append("					if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("						eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				wInput.readonly=true;\r\n");
		js.append("				wLab.disabled=true;	\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	function SetResult(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		selectedresult.value=\"\";\r\n");
		js.append("		sourceresult.value=\"\";\r\n");
		js.append("		necessaryresult.value=\"\";\r\n");
		js.append("		fixedresult.value=\"\";\r\n");
		js.append("		var strValue=\"\";\r\n");
		js.append("		var strText=\"\";\r\n");
		js.append("		for(index_1=0;index_1<selectBox.options.length;index_1++)\r\n");
		js.append("		{\r\n");
		js.append("			strValue=selectBox.options[index_1].value;\r\n");
		js.append("			strText=selectBox.options[index_1].text;\r\n");
		js.append("			HashtableManager_Add(strValue,strText,selectedresult);\r\n");
		/*js.append("			var k_0=false\r\n");
		js.append("			var k_1=false\r\n");
		js.append("			if (index!=0)\r\n");
		js.append("				selectedresult.value+=\"*\"\r\n");
		js.append("			selectedresult.value+=selectBox.options[index].value\r\n");
		js.append("			selectedresult.value+=\"!\"\r\n");
		js.append("			selectedresult.value+=selectBox.options[index].text\r\n");*/		
		js.append("			if (selectBox.options[index_1].getAttribute(\"flag\")==111)/*{*/\r\n");
		js.append("				HashtableManager_Add(strValue,strText,fixedresult);\r\n");
		/*js.append("				if (k_0)\r\n");
		js.append("					fixedresult.value+=\"*\"\r\n");
		js.append("				k_0=true\r\n");
		js.append("				fixedresult.value+=selectBox.options[index].value\r\n");
		js.append("				fixedresult.value+=\"!\"\r\n");
		js.append("				fixedresult.value+=selectBox.options[index].text\r\n");
		js.append("			}\r\n");*/
		js.append("			if (selectBox.options[index_1].getAttribute(\"flag\")==222)/*{*/\r\n");
		js.append("				HashtableManager_Add(strValue,strText,necessaryresult);\r\n");
		/*js.append("				if (k_1)\r\n");
		js.append("					necessaryresult.value+=\"*\"\r\n");
		js.append("				k_1=true\r\n");
		js.append("				necessaryresult.value+=selectBox.options[index].value\r\n");
		js.append("				necessaryresult.value+=\"!\"\r\n");
		js.append("				necessaryresult.value+=selectBox.options[index].text\r\n");
		js.append("			}\r\n");*/
		js.append("		}\r\n");
		js.append("		for(Index_2=0;Index_2<sourceBox.options.length;Index_2++)\r\n");
		js.append("		{\r\n");
		js.append("			strValue=sourceBox.options[Index_2].value;\r\n");
		js.append("			strText=sourceBox.options[Index_2].text;\r\n");
		js.append("			HashtableManager_Add(strValue,strText,sourceresult);\r\n");
		/*js.append("			if (Index!=0)\r\n");
		js.append("				sourceresult.value+=\"*\"\r\n");
		js.append("			sourceresult.value+=sourceBox.options[Index].value\r\n");
		js.append("			sourceresult.value+=\"!\"\r\n");
		js.append("			sourceresult.value+=sourceBox.options[Index].text\r\n");*/
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	function ListBoxKeyPress(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (event.keyCode==32)\r\n");
		js.append("			Isdisable(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("	}\r\n");
		js.append("	function AddOneBtnKeyPress(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (event.keyCode==13)\r\n");
		js.append("			AddOneBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("	}\r\n");
		js.append("	function AddAllBtnKeyPress(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (event.keyCode==13)\r\n");
		js.append("			AddAllBtnClicked(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("	}\r\n");		
		js.append("	function RemoveOneBtnKeyPress(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (event.keyCode==13)\r\n");
		js.append("			RemoveOneBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("	}\r\n");		
		js.append("	function RemoveAllBtnKeyPress(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (event.keyCode==13)\r\n");
		js.append("			RemoveAllBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("	}\r\n");		
		js.append("	function PreviousBtnKeyPress(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (event.keyCode==13)\r\n");
		js.append("			PreviousBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("	}\r\n");		
		js.append("	function NextBtnKeyPress(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (event.keyCode==13)\r\n");
		js.append("			NextBtnClick(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden);\r\n");
		js.append("	}\r\n");			
		js.append("	function SetBtnSrc(Btn)\r\n");
		js.append("	{\r\n");
		js.append("		if(Btn.disabled)\r\n");
		js.append("		{\r\n");
		js.append("			var str1 = Btn.src;\r\n");
		js.append("			var s = str1.lastIndexOf(\"enabled\");\r\n");
		js.append("			if(s == -1)\r\n");
		js.append("				return;\r\n");
		js.append("			ss = str1.substring(0 , s);\r\n");
		js.append("			ss1 = str1.substring(s);\r\n");
		js.append("			ss1 = ss1.replace(\"enabled\" , \"disabled\");\r\n");
		js.append("			presrc = ss.concat(ss1);\r\n");
		js.append("			Btn.src = presrc;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			var str1 = Btn.src;\r\n");
		js.append("			var s = str1.lastIndexOf(\"disabled\");\r\n");
		js.append("			if(s == -1)\r\n");
		js.append("				return;\r\n");
		js.append("			ss = str1.substring(0 , s);\r\n");
		js.append("			ss1 = str1.substring(s);\r\n");
		js.append("			ss1 = ss1.replace(\"disabled\" , \"enabled\");\r\n");
		js.append("			presrc = ss.concat(ss1);\r\n");
		js.append("			Btn.src = presrc;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");		
		js.append("	function lTrim(str){\r\n");
		js.append("		if (str.charAt(0)==\" \")\r\n");
		js.append("		{\r\n");
		js.append("			str = str.substring(1, str.length);\r\n");
		js.append("			str=lTrim(str);\r\n");
		js.append("		}\r\n");
		js.append("	return str;\r\n");
		js.append("	}\r\n");		
		js.append("	function rTrim(str){\r\n");
		js.append("		if (str.charAt(str.length-1)==\" \")\r\n");
		js.append("		{\r\n");
		js.append("			str = str.substring(0, str.length-1);\r\n");
		js.append("			str=rTrim(str);\r\n");
		js.append("		}\r\n");
		js.append("	return str;\r\n");
		js.append("	}\r\n");	
		js.append("	function Trim(str){\r\n");
		js.append("		return lTrim(rTrim(str));\r\n");
		js.append("	}\r\n");											
		js.append("	function TextBoxInput(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden)\r\n");
		js.append("	{\r\n");
		js.append("		if (wInput!=null)\r\n");
		js.append("		{\r\n");
		js.append("			if (event.keyCode==13)\r\n");
		js.append("			{\r\n");
		js.append("				var result;\r\n");
		js.append("				result=SetListBoxContent(sourceBox,selectBox,addOneBtn,addAllBtn,removeOneBtn,removeAllBtn,preBtn,nextBtn,wLab,wInput,curObj,sourceresult,selectedresult,necessaryresult,fixedresult,myprompt,selectedeventhidden,itemchangedeventhidden,'false');\r\n");
		js.append("				if (result!=\"-1\")\r\n");
		js.append("				{\r\n");
		js.append("					wInput.blur();\r\n");
		/*js.append("					if (itemchangedeventhidden.getAttribute(\"ItemChanged\")!=\"\"&&itemchangedeventhidden.getAttribute(\"ItemChanged\")!=null)\r\n");
		js.append("						eval(itemchangedeventhidden.getAttribute(\"ItemChanged\"));\r\n");*/
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					wInput.focus();\r\n");
		js.append("					wInput.select();\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("			if(event.keyCode==222||event.keyCode==191||event.keyCode==192||event.keyCode==220)\r\n");
		js.append("			{\r\n");
		js.append("				event.keyCode=39;\r\n");
		js.append("			}\r\n");
		js.append("			else if(event.shiftKey)\r\n");
		js.append("			{\r\n");
		js.append("				if(event.keyCode==222||event.keyCode==191||event.keyCode==192||event.keyCode==220||event.keyCode==49||event.keyCode==50||event.keyCode==51||event.keyCode==52||event.keyCode==53||event.keyCode==55||event.keyCode==56)\r\n");
		js.append("				{\r\n");
		js.append("					event.keyCode=39;\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("			else if(event.ctrlKey||event.altKey)\r\n");
		js.append("			{\r\n");
		js.append("				event.keyCode=39;\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	function setItemSelectedfun(componentid,functionname)\r\n");
		js.append("	{\r\n");
		js.append("		document.getElementById(componentid+\"_hidden_6\").setAttribute(\"ItemSelected\",functionname);\r\n");
		js.append("	}\r\n");
		js.append("	function getItemSelectedfun(componentid)\r\n");
		js.append("	{\r\n");
		js.append("		if (document.getElementById(componentid+\"_hidden_6\").getAttribute(\"ItemSelected\")==null)\r\n");
		js.append("			return \"\";\r\n");
		js.append("		else\r\n");
		js.append("			return document.getElementById(componentid+\"_hidden_6\").getAttribute(\"ItemSelected\");\r\n");
		js.append("	}\r\n");
		js.append("	function setItemChangedfun(componentid,functionname)\r\n");
		js.append("	{\r\n");
		js.append("		document.getElementById(componentid+\"_hidden_7\").setAttribute(\"ItemChanged\",functionname);\r\n");
		js.append("	}\r\n");
		js.append("	function getItemChangedfun(componentid)\r\n");
		js.append("	{\r\n");
		js.append("		if (document.getElementById(componentid+\"_hidden_7\").getAttribute(\"ItemChanged\")==null)\r\n");
		js.append("			return \"\";\r\n");
		js.append("		else\r\n");
		js.append("			return document.getElementById(componentid+\"_hidden_7\").getAttribute(\"ItemChanged\");\r\n");
		js.append("	}\r\n");
		
		js.append("	function changeWidthSave(obj,componentid)\r\n");
		js.append("	{\r\n");
		js.append("		var selectBox=document.getElementById(componentid+'_select_1'); \r\n");
		js.append("		var itemId=selectBox.options[selectBox.selectedIndex].value;\r\n");
		js.append("		var widthset = document.getElementById(componentid+'_widthset');\r\n");
		js.append("		HashtableManager_Set(itemId,obj.value,widthset);\r\n");

		js.append("	}\r\n");
		
		
		js.append("\r\n");
		//System.out.println(js.toString());
		jstool.js=js;
		return jstool.getComponentJS()+ "\r\n" + HashMapJS.getHashMapJS();
	}
}
	