package com.born.insurance.webui.control;
/**
 * <p>Title: the class write javascript code to file</p>
 * <p>Description: js����д��DropDownJSForMozila.js�ļ�</p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: bornsoft</p>
 * @author not attributable
 * @version 1.0
 */

public class DropDownJsForMozila {
  /**
   * <p><B>Description: ����ļ�DropDownJS.js</B></p>
   * <P><B>ȡ��ǰ����ı�</B><P>
   * <B>function:DropDown_getText(dropDownId)</B></p>
   *    param dropDownId �ؼ�ID
   *    return ��ǰ���ı�
   * <P><B>ȡ��ǰ���ֵ</B><P>
   * <B>function:DropDown_getValue(dropDownId)</B></p>
   *    param dropDownId �ؼ�ID
   *    return ��ǰ���ֵ
   * <P><B>����ѡ�����ֵ</B><P>
   * <B>function:DropDown_setValue(dropDownId, text, value)</B></p>
   *    param dropDownId �ؼ�ID
   *    param text ѡ������ʾ�ı�
   *    param value ѡ����ʵ��ֵ
   * <P><B>����ֻ��</B><P>
   * <B>function:DropDown_setProperty(dropDownId, property, value)</B></p>
   *    param dropDownId �ؼ�ID
   *    param property ����
   *    param value ����ֵ
   * <P><B>��ȡֵ�б�</B><P>
   * <B>function:DropDown_getValueList(dropDownId)</B></p>
   *    param dropDownId �ؼ�ID
   *    return ֵ�б�
   * <p>
   */

  public static String getDropDownJS(){
    JSTool jstool = new JSTool("DropDownJSForMozila.js");
	if(!jstool.util.isUpdateJsEveryTime())
	 {
		 return jstool.getComponentJS() ;//+ HashMapJS.getHashMapJS();
	 }
    StringBuffer js = new StringBuffer();
    js.append("function DropDown_dropDown(dropDownId)\r\n");
    js.append("{	\r\n");
    js.append("	var popDivId = dropDownId + \"_popDiv\";\r\n");
    js.append("	var textBoxId = dropDownId  + \"_textBox\";\r\n");
    js.append("	var imgId = dropDownId + \"_divButton\";\r\n");
    js.append("	var textBox = document.getElementById(textBoxId);\r\n");
    js.append("	var img = document.getElementById(imgId);\r\n");
    js.append("	if(img.getAttribute(\"disabled\") == \"true\")\r\n");
    js.append("	{\r\n");
    js.append("		return;\r\n");
    js.append("	}\r\n");
    js.append("	var popDiv = document.getElementById(popDivId);\r\n");
    js.append("	if(popDiv.getAttribute(\"popShow\") == \"true\")\r\n");
    js.append("	{\r\n");
    js.append("		popDiv.style.visibility = \"hidden\";\r\n");
    js.append("		popDiv.setAttribute(\"popShow\", \"false\");\r\n");
    js.append("		return;\r\n");
    js.append("	}\r\n");
    js.append("	else\r\n");
    js.append("	{\r\n");
    js.append("		popDiv.setAttribute(\"popShow\", \"true\");\r\n");
    js.append("	}\r\n");
    js.append("	var innerHTML = DropDown_initOptions(dropDownId);\r\n");

    js.append("	popDiv.innerHTML = innerHTML;\r\n");
    js.append("	popDiv.style.width = textBox[\"offsetWidth\"] + 15;\r\n");
    js.append("	popDiv.style.height = 15*6;\r\n");
    js.append("	DropDown_changeSelectedIndex(dropDownId);\r\n");
    js.append("	DropDown_setSelectedIndex(dropDownId);\r\n");
    js.append(" var popTable = document.getElementById(dropDownId + \"_popTable\");\r\n");
    js.append("       if(popTable != null && 90 > popTable.offsetHeight)\r\n");
    js.append("       {\r\n");
    js.append("           popDiv.style.height = popTable.offsetHeight + 2;\r\n");
    js.append("       }\r\n");
    js.append("	DropDown_setDropDownPosition(popDiv, dropDownId)\r\n");
    js.append("	popDiv.style.visibility = \"visible\";\r\n");
    js.append("	DropDown_hideElement(\"select\", popDiv);\r\n");
    js.append("	DropDown_hideElement(\"applet\", popDiv);\r\n");
    js.append("}\r\n");
    js.append("function DropDown_initOptions(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var popDivId = dropDownId + \"_popDiv\";\r\n");
    js.append("	var popTableId = dropDownId + \"_popTable\";\r\n");
    js.append("	var values = DropDown_getKeyList(dropDownId);\r\n");
    js.append("	var texts = DropDown_getValueList(dropDownId);\r\n");
    js.append("	var html = new String();\r\n");
    js.append("      if(values.length == 0)\r\n");
    js.append("        {\r\n");
    js.append("                return \"\";\r\n");
    js.append("        }\r\n");
    js.append("	html += \"<table onmouseout = \\\"DropDown_hidePopDiv('\" + dropDownId + \"', document.getElementById('\"+popDivId+\"'),event)\\\" id=\\\"\" + popTableId + \"\\\" width='100%' cellpadding=0 cellspacing=0 border=0 UNSELECTABLE='on' >\";\r\n");
    js.append("	for(var index = 0; index < values.length; index++)\r\n");
    js.append("	{\r\n");
    js.append("		html += \"<tr  onmouseout = \\\"DropDown_hidePopDiv('\" + dropDownId + \"', document.getElementById('\"+popDivId+\"'),event)\\\" style=\\\"font-size:12px\\\" value=\\\"\" + values[index] + \"\\\" \";	\r\n");
    js.append("		html += \"inText=\\\"\"+texts[index]+\"\\\"  onmouseover=\\\"DropDown_overOption(this, '\"+dropDownId+\"')\\\" \";\r\n");
    js.append("		html += \"onclick=\\\"DropDown_selectOption(this, '\" + dropDownId + \"')\\\"\";\r\n");
    js.append("		html += \"title=\\\"\"+texts[index]+\"\\\"><td  onmouseout = \\\"DropDown_hidePopDiv('\" + dropDownId + \"', document.getElementById('\"+popDivId+\"'),event)\\\" nowrap=\\\"true\\\">\";\r\n");
    js.append("		html += texts[index] + \"</td></tr>\";\r\n");
    js.append("	}\r\n");
    js.append("	html += \"</table>\";\r\n");
    js.append("	return html;\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_getTop(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	iPos = 0;	\r\n");
    js.append("	var popDivId = dropDownId + \"_popDiv\";\r\n");
    js.append("	var textBoxId = dropDownId  + \"_textBox\";\r\n");
    js.append("	var textBox = document.getElementById(textBoxId);\r\n");
    js.append("	var popDiv = document.getElementById(popDivId);\r\n");
    js.append("	var isDiv = false;\r\n");
    js.append("       var popTable = document.getElementById(dropDownId + \"_popTable\");\r\n");
    js.append("       var popHeight = 15*6;	\r\n");
    js.append("       var outerDiv = null;		\r\n");
    js.append("       if(popTable != null && popHeight > popTable.offsetHeight)\r\n");
    js.append("       {\r\n");
    js.append("           popHeight = popTable.offsetHeight + 2;\r\n");
    js.append("       }\r\n");
    js.append("       o = textBox;\r\n");
    js.append("   	while (o!=null) 	\r\n");
    js.append("	{	\r\n");
    js.append("		if(o.tagName == \"DIV\" && o.id != dropDownId)\r\n");
    js.append("		{	\r\n");
    js.append("		     isDiv = true;\r\n");
    js.append("		     outerDiv = o;\r\n");
    js.append("		     break;	\r\n");
    js.append("		}	\r\n");
    js.append("		o = o.parentNode;	\r\n");
    js.append("	}	\r\n");
    js.append("	o = textBox;\r\n");
    js.append("	while (o!=null) 	\r\n");
    js.append("	{	\r\n");
    js.append("		iPos += o[\"offsetTop\"];\r\n");
    js.append("		o = o.offsetParent;	\r\n");
    js.append("	}\r\n");
    js.append("	var divoffset = 0;\r\n");
    js.append("		o = outerDiv;\r\n");
    js.append("		while (o!=null) 	\r\n");
    js.append("	{	\r\n");
    js.append("			divoffset += o[\"offsetTop\"];\r\n");
    js.append("			o = o.offsetParent;	\r\n");
    js.append("		}\r\n");
    js.append("	if(isDiv)	\r\n");
    js.append("	{\r\n");
    js.append("		iPos = iPos + textBox.offsetHeight + 1;\r\n");
    js.append("		popDiv.style.top = iPos;\r\n");
    js.append("		if(iPos  + popHeight + 1 > outerDiv.offsetHeight + divoffset - 16)\r\n");
    js.append("		{\r\n");
    js.append("			popDiv.style.top = iPos - textBox.offsetHeight - popHeight - 2;\r\n");
    js.append("		}\r\n");
    js.append("		return iPos;\r\n");
    js.append("	}\r\n");
    js.append("	else if(iPos + textBox.offsetHeight + 1 + popHeight - document.body.scrollTop > window.screen.height - 170)\r\n");
    js.append("	{\r\n");
    js.append("		iPos = iPos - popHeight - 2;\r\n");
    js.append("		popDiv.style.top = iPos;\r\n");
    js.append("	}\r\n");
    js.append("	else\r\n");
    js.append("	{\r\n");
    js.append("		iPos = iPos + textBox.offsetHeight + 1;\r\n");
    js.append("		popDiv.style.top = iPos;\r\n");
    js.append("	}\r\n");
    js.append("	return iPos;	\r\n");
    js.append("}");
    js.append("function DropDown_getLeft(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	iPos = 0;\r\n");
    js.append("	var popDivId = dropDownId + \"_popDiv\";\r\n");
    js.append("	var textBoxId = dropDownId  + \"_textBox\";\r\n");
    js.append("	var textBox = document.getElementById(textBoxId);\r\n");
    js.append("	var popDiv = document.getElementById(popDivId);\r\n");
    js.append("       o = textBox;\r\n");
    js.append("	while (o!=null) 	\r\n");
    js.append("	{	\r\n");
    js.append("		if(o.tagName == \"DIV\"  && o.id != dropDownId)\r\n");
    js.append("		{	\r\n");
    js.append("		      break;	\r\n");
    js.append("		}	\r\n");
    js.append("		iPos += o[\"offsetLeft\"];	\r\n");
    js.append("		o = o.offsetParent;	\r\n");
    js.append("	}	\r\n");
    js.append("	iPos += window.screen.left;\r\n");
    js.append("	popDiv.style.left = iPos;\r\n");
    js.append("	return iPos;	\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_setDropDownPosition(popDiv, dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	popDiv.style.position = \"absolute\";\r\n");
    js.append("	var top = DropDown_getTop(dropDownId);\r\n");
    js.append("	var left = DropDown_getLeft(dropDownId);\r\n");
    js.append("\r\n");
    js.append("}\r\n");
    js.append("function DropDown_overOption(option, dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var popTable = document.getElementById(dropDownId + \"_popTable\");\r\n");
    js.append("	for(var index = 0; index<popTable.rows.length; index++)\r\n");
    js.append("	{\r\n");
    js.append("		popTable.rows[index].style.backgroundColor = \"white\";\r\n");
    js.append("		popTable.rows[index].style.color = \"black\";\r\n");
    js.append("	}\r\n");
    js.append("	option.style.backgroundColor = \"#0A246A\";\r\n");
    js.append("	option.style.color = \"white\";\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_selectOption(option, dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var popDiv = document.getElementById(dropDownId + \"_popDiv\");\r\n");
    js.append("	var selectedIndex = option.rowIndex;\r\n");
    js.append("	var oldSelectedIndex = parseInt(textBox.getAttribute(\"selectedIndex\"));\r\n");
    js.append("	popDiv.style.visibility = \"hidden\";\r\n");
    js.append("	DropDown_showElement(\"select\");\r\n");
    js.append("	DropDown_showElement(\"applet\");\r\n");
    js.append("	textBox.setAttribute(\"selectedIndex\", selectedIndex);\r\n");
    js.append("	DropDown_changeValue(dropDownId, oldSelectedIndex);\r\n");
    js.append("	\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_optionKeyDown(dropDownId, event)\r\n");
    js.append("{\r\n");
    js.append("	var popDivId = dropDownId + \"_popDiv\";\r\n");
    js.append("	var popDiv = document.getElementById(popDivId);\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var popTableId = dropDownId + \"_popTable\";\r\n");
    js.append("	var popTable = document.getElementById(popTableId);\r\n");
    js.append("	var scrollTop = popDiv.scrollTop;\r\n");
    js.append("	var selectedIndex = textBox.getAttribute(\"selectedIndex\");\r\n");
    js.append("	var index = -1\r\n");
    js.append("	var preIndex = 0;\r\n");
    js.append("	var maxLength = popTable.rows.length - 1;\r\n");
    js.append("	if(event.keyCode == 38)\r\n");
    js.append("	{\r\n");
    js.append("		index = selectedIndex - 1;\r\n");
    js.append("		preIndex = index + 1;\r\n");
    js.append("	}\r\n");
    js.append("	else if(event.keyCode == 40)\r\n");
    js.append("	{\r\n");
    js.append("		index = selectedIndex + 1;\r\n");
    js.append("		if(selectedIndex == -1)\r\n");
    js.append("		{\r\n");
    js.append("			index = 1;\r\n");
    js.append("		}\r\n");
    js.append("		if(index > maxLength)\r\n");
    js.append("		{\r\n");
    js.append("			index = maxLength;\r\n");
    js.append("		}\r\n");
    js.append("		preIndex = index - 1;\r\n");
    js.append("	}\r\n");
    js.append("	      else if(event.keyCode == 27)\r\n");
    js.append("	{\r\n");
    js.append("	      popDiv.style.visibility = \"hidden\";\r\n");
    js.append("	      DropDown_showElement(\"select\");\r\n");
    js.append("	      DropDown_showElement(\"applet\");\r\n");
    js.append("	}\r\n");
    js.append("	else if(event.keyCode == 13)\r\n");
    js.append("	{\r\n");
    js.append("	        for(nIndex = 0; nIndex<popTable.rows.length; nIndex++)\r\n");
    js.append("	        {\r\n");
    js.append("	                if(popTable.rows[nIndex].style.backgroundColor.toLowerCase() == \"#0a246a\")\r\n");
    js.append("	                {\r\n");
    js.append("	                        DropDown_selectOption(popTable.rows[nIndex], dropDownId);\r\n");
    js.append("	                        return;\r\n");
    js.append("	                }\r\n");
    js.append("	        }\r\n");
    js.append("	}\r\n");
    js.append("	if(index != -1)\r\n");
    js.append("	{\r\n");
    js.append("	      for(nIndex = 0; nIndex<popTable.rows.length; nIndex++)\r\n");
    js.append("	        {\r\n");
    js.append("	                popTable.rows[nIndex].style.backgroundColor = \"white\";\r\n");
    js.append("	                popTable.rows[nIndex].style.color = \"black\";\r\n");
    js.append("	        }\r\n");
    js.append("		if(popTable.rows[index] != null)\r\n");
    js.append("		{\r\n");
    js.append("			popTable.rows[index].style.backgroundColor = \"#0A246A\";\r\n");
    js.append("			popTable.rows[index].style.color = \"white\";\r\n");
    js.append("			textBox.setAttribute(\"selectedIndex\", index);\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("	DropDown_changeValue(dropDownId, preIndex);\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_changeSelectedIndex(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var popTable = document.getElementById(dropDownId + \"_popTable\");\r\n");
    js.append("	var value = textBox.value;\r\n");
    js.append("	var texts = DropDown_getValueList(dropDownId); \r\n");
    js.append("	var selectedIndex = -1;\r\n");
    js.append("	for(index = 0; index < texts.length; index++)\r\n");
    js.append("	{\r\n");
    js.append("		if(texts[index].indexOf(value, 0) == 0)	\r\n");
    js.append("		{\r\n");
    js.append("			selectedIndex = index;\r\n");
    js.append("			break;\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("	textBox.setAttribute(\"selectedIndex\", selectedIndex);\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_setSelectedIndex(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var popTableId = dropDownId + \"_popTable\";\r\n");
    js.append("	var popDiv = document.getElementById(dropDownId + \"_popDiv\");\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var popTable = document.getElementById(popTableId);\r\n");
    js.append("	var selectedIndex = parseInt(textBox.getAttribute(\"selectedIndex\"));\r\n");
    js.append("	if(popTable == null || popTable.rows.length == 0)\r\n");
    js.append("	{\r\n");
    js.append("		return;\r\n");
    js.append("	}\r\n");
    js.append("	var index = 0;\r\n");
    js.append("	if(selectedIndex != -1)\r\n");
    js.append("	{\r\n");
    js.append("		index = selectedIndex;\r\n");
    js.append("	}\r\n");
    js.append("	popTable.rows[index].style.backgroundColor = \"#0A246A\";\r\n");
    js.append("	popTable.rows[index].style.color = \"white\";\r\n");
    js.append("	var height = popDiv.scrollHeight - popDiv.offsetHeight;\r\n");
    js.append("	var perHeight = height/popTable.rows.length;\r\n");
    js.append("	if(index != 0)\r\n");
    js.append("	{\r\n");
    js.append("		popDiv.scrollTop = perHeight * (index + 1);\r\n");
    js.append("	}\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_changeValueByTextBox(dropDownId, ischange)\r\n");
    js.append("{\r\n");
    js.append("	var texts = DropDown_getValueList(dropDownId); \r\n");
    js.append("	var values = DropDown_getKeyList(dropDownId); \r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var textHidden = document.getElementById(dropDownId + \"_selectedText\");\r\n");
    js.append("	var valueHidden = document.getElementById(dropDownId + \"_selectedValue\");\r\n");
    js.append("	var text = null;\r\n");
    js.append("	var value = null;\r\n");
    js.append("	var oldSelectedIndex = parseInt(textBox.getAttribute(\"selectedIndex\"));\r\n");
    js.append("	var selectedIndex = -1;\r\n");
    js.append("	if(textBox.value == textHidden.value)\r\n");
    js.append("	{\r\n");
    js.append("		return;\r\n");
    js.append("	}\r\n");
    js.append("	if(textBox.getAttribute(\"DropDownType\") == \"2\")\r\n");
    js.append("	{\r\n");
    js.append("		if(textBox.value == '')\r\n");
    js.append("		{\r\n");
    js.append("			textHidden.value = '';\r\n");
    js.append("			valueHidden.value = '';\r\n");
    js.append("			return;\r\n");
    js.append("		}\r\n");
    js.append("		for(index = 0; index < texts.length; index++)\r\n");
    js.append("		{\r\n");
    js.append("			if(texts[index].search(textBox.value) == 0)	\r\n");
    js.append("			{\r\n");
    js.append("				selectedIndex = index;\r\n");
    js.append("				break;\r\n");
    js.append("			}\r\n");
    js.append("		}\r\n");
    js.append("		textBox.setAttribute(\"selectedIndex\", selectedIndex);\r\n");
    js.append("		if(selectedIndex == -1)\r\n");
    js.append("		{\r\n");
    js.append("			text = texts[0];\r\n");
    js.append("			value = values[0];\r\n");
    js.append("		}\r\n");
    js.append("		else\r\n");
    js.append("		{\r\n");
    js.append("			text = texts[selectedIndex];\r\n");
    js.append("			value = values[selectedIndex];\r\n");
    js.append("		}\r\n");
    js.append("	if(text == null)\r\n");
    js.append("	{\r\n");
    js.append("	        textBox.value = \"\";\r\n");
    js.append("	        textHidden.value = \"\";\r\n");
    js.append("	        valueHidden.value = \"\";\r\n");
    js.append("	}\r\n");
    js.append("	else\r\n");
    js.append("	{\r\n");
    js.append("			if(textHidden.value != text && valueHidden.value != value || textBox.value != text)\r\n");
    js.append("			{\r\n");
    js.append("				textBox.value = text;\r\n");
    js.append("				textHidden.value = text;\r\n");
    js.append("				valueHidden.value = value;\r\n");
    js.append("				DropDown_selectedChanged(dropDownId, value);\r\n");
    js.append("				return;\r\n");
    js.append("			}\r\n");
    js.append("	        \r\n");
    js.append("	}\r\n");
    js.append("		if(oldSelectedIndex != selectedIndex)\r\n");
    js.append("		{\r\n");
    js.append("			if(oldSelectedIndex == 0 || oldSelectedIndex == -1)\r\n");
    js.append("			{\r\n");
    js.append("				if(selectedIndex ==0 || selectedIndex == -1)\r\n");
    js.append("				{\r\n");
    js.append("					return;\r\n");
    js.append("				}\r\n");
    js.append("			}\r\n");
    js.append("			if(ischange)\r\n");
    js.append("			{\r\n");
    js.append("			    DropDown_selectedChanged(dropDownId, value);\r\n");
    js.append("			}\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("	else if(textBox.getAttribute(\"DropDownType\") == \"0\")\r\n");
    js.append("	{\r\n");
    js.append("		if(textHidden.value == textBox.value)\r\n");
    js.append("		{\r\n");
    js.append("			return;\r\n");
    js.append("		}\r\n");
    js.append("		textHidden.value = textBox.value;\r\n");
    js.append("		for(index = 0; index < texts.length; index++)\r\n");
    js.append("		{\r\n");
    js.append("			if(texts[index] == textBox.value)	\r\n");
    js.append("			{\r\n");
    js.append("				selectedIndex = index;\r\n");
    js.append("				break;\r\n");
    js.append("			}\r\n");
    js.append("		}\r\n");
    js.append("		if(selectedIndex != -1)\r\n");
    js.append("		{\r\n");
    js.append("			textBox.setAttribute(\"selectedIndex\", selectedIndex);\r\n");
    js.append("			valueHidden.value = values[selectedIndex];\r\n");
    js.append("			DropDown_selectedChanged(dropDownId, values[selectedIndex]);\r\n");
    js.append("		}\r\n");
    js.append("		else\r\n");
    js.append("		{\r\n");
    js.append("			valueHidden.value = \"\";\r\n");
    js.append("			DropDown_selectedChanged(dropDownId, \"\");\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("\r\n");
    js.append("function DropDown_changeValue(dropDownId, oldSelectedIndex)\r\n");
    js.append("{\r\n");
    js.append("	var popTable = document.getElementById(dropDownId + \"_popTable\");\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var textHidden = document.getElementById(dropDownId + \"_selectedText\");\r\n");
    js.append("    var dropDownType = textBox.getAttribute(\"DropDownType\");\r\n");
    js.append("	var valueHidden = document.getElementById(dropDownId + \"_selectedValue\");\r\n");
    js.append("	var selectedIndex = parseInt(textBox.getAttribute(\"selectedIndex\"));\r\n");
    js.append("	var text = popTable.rows[selectedIndex].getAttribute(\"inText\");\r\n");
    js.append("	var value = popTable.rows[selectedIndex].getAttribute(\"value\");\r\n");
    js.append("	if(textHidden.value != text && valueHidden.value != value)\r\n");
    js.append("	{\r\n");
    js.append("		   textBox.value = text;\r\n");
    js.append("		   textBox.title = text;\r\n");
    js.append("		   textHidden.value = text;\r\n");
    js.append("		   valueHidden.value = value;\r\n");
    js.append("		   DropDown_selectedChanged(dropDownId, value);\r\n");
    js.append("		   return;\r\n");
    js.append("	}\r\n");
    js.append("	if(dropDownType == \"0\")\r\n");
    js.append("	{\r\n");
    js.append("	       DropDown_selectedChanged(dropDownId, value);\r\n");
    js.append("	       return;\r\n");
    js.append("	}\r\n");
    js.append("	if(selectedIndex != oldSelectedIndex)\r\n");
    js.append("	{\r\n");
    js.append("		if(selectedIndex == 0 || selectedIndex == -1)\r\n");
    js.append("		{	\r\n");
    js.append("			if(oldSelectedIndex == 0 || oldSelectedIndex == -1)\r\n");
    js.append("			{\r\n");
    js.append("				return;\r\n");
    js.append("			}\r\n");
    js.append("		}\r\n");
    js.append("		DropDown_selectedChanged(dropDownId, value);\r\n");
    js.append("		\r\n");
    js.append("	}\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_selectedChanged(dropDownId , value)\r\n");
    js.append("{\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("       var control = document.getElementById(dropDownId);\r\n");
    js.append("	if(control.getAttribute(\"onselectedChange\") != null || control.getAttribute(\"onselectedChange\") != \"\")\r\n");
    js.append("	{\r\n");
    js.append("		eval(control.getAttribute(\"onselectedChange\"));\r\n");
    js.append("	}\r\n");
    js.append("	var filter = document.getElementById(dropDownId + \"_Filter_hidden\");\r\n");
    js.append("	var filterControls = null;\r\n");
    js.append("	if(filter != null)\r\n");
    js.append("	{\r\n");
    js.append("		filterControls = ListManager_Analysis(filter);\r\n");
    js.append("	}\r\n");
    js.append("	for(var index = 0; filterControls != null && index < filterControls.length; index++)\r\n");
    js.append("	{\r\n");
    js.append("		var obj = document.getElementById(filterControls[index] + \"_textBox\");\r\n");
    js.append("		obj.setAttribute(\"filterId\", value);\r\n");
    js.append("		var objcontainerHidden = document.getElementById(filterControls[index] + \"_containerTextId\");\r\n");
    js.append("		var objValueHidden = document.getElementById(filterControls[index] + \"_selectedValue\");\r\n");
    js.append("		var objTextHidden = document.getElementById(filterControls[index] + \"_selectedText\");\r\n");
    js.append("		var filterObj = document.getElementById(filterControls[index] + \"_\" + value + \"Hidden\");\r\n");
    js.append("		if(filterObj != null)\r\n");
    js.append("		{\r\n");
    js.append("			var filterTexts = HashtableManager_GetValueList(filterObj);\r\n");
    js.append("			var filterValues = HashtableManager_GetKeyList(filterObj);\r\n");
    js.append("			obj.value = filterTexts[0];\r\n");
    js.append("			objValueHidden.value = filterValues[0];\r\n");
    js.append("			objTextHidden.value = filterTexts[0];\r\n");
    js.append("			DropDown_selectedChanged(filterControls[index], filterValues[0]);\r\n");
    js.append("		}\r\n");
    js.append("		else\r\n");
    js.append("		{\r\n");
    js.append("			obj.value = \"\";	\r\n");
    js.append("			objValueHidden.value = \"\";\r\n");
    js.append("			objTextHidden.value = \"\";\r\n");
    js.append("			DropDown_selectedChanged(filterControls[index], \"\");\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_selecteOption(option, dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	DropDown_SetTextValue(option, dropDownId);\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_setValue(dropDownId, value)\r\n");
    js.append("{	\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var textHidden = document.getElementById(dropDownId + \"_selectedText\");\r\n");
    js.append("	var valueHidden = document.getElementById(dropDownId + \"_selectedValue\"); \r\n");
    js.append("	var containerHidden = document.getElementById(dropDownId + \"_containerValueId\");\r\n");
    js.append("	var texts = HashtableManager_GetValueList(containerHidden);\r\n");
    js.append("	var values = HashtableManager_GetKeyList(containerHidden);\r\n");
    js.append("	var selectedIndex = -1;\r\n");
    js.append("	var oldSelectedIndex = parseInt(textBox.getAttribute(\"selectedIndex\"));\r\n");
    js.append("	var dropDownType = parseInt(textBox.getAttribute(\"DropDownType\"));\r\n");
    js.append("	for(var index = 0; index < values.length; index++)\r\n");
    js.append("	{\r\n");
    js.append("		if(values[index] == value)\r\n");
    js.append("		{\r\n");
    js.append("			selectedIndex = index;\r\n");
    js.append("			break;\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("	if(selectedIndex == -1)\r\n");
    js.append("	{\r\n");
    js.append("		if(dropDownType != 0)\r\n");
    js.append("		{\r\n");
    js.append("			textBox.value = texts[0];\r\n");
    js.append("			textHidden.value = texts[0];\r\n");
    js.append("			valueHidden.value = values[0];\r\n");
    js.append("			\r\n");
    js.append("		}\r\n");
    js.append("		else\r\n");
    js.append("		{\r\n");
    js.append("			textBox.value = \"\";\r\n");
    js.append("			textHidden.value = \"\";\r\n");
    js.append("			valueHidden.value = \"\";\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("	else\r\n");
    js.append("	{\r\n");
    js.append("		textBox.value = texts[selectedIndex];\r\n");
    js.append("		textHidden.value = texts[selectedIndex];\r\n");
    js.append("		valueHidden.value = values[selectedIndex];\r\n");
    js.append("	}\r\n");
    js.append("	textBox.setAttribute(\"selectedIndex\", selectedIndex);\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_isSelectedChanged(oldSelectedIndex,  selectedIndex)\r\n");
    js.append("{\r\n");
    js.append("	if(oldSelectedIndex != selectedIndex)\r\n");
    js.append("	{\r\n");
    js.append("		if(oldSelectedIndex == -1 || oldSelectedIndex == 0)\r\n");
    js.append("		{\r\n");
    js.append("			if(selectedIndex == -1 || selectedIndex == 0)\r\n");
    js.append("			{\r\n");
    js.append("				return false;\r\n");
    js.append("			}\r\n");
    js.append("		}\r\n");
    js.append("		return true;\r\n");
    js.append("	}\r\n");
    js.append("	return false;\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_getValue(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var valueHidden = document.getElementById(dropDownId + \"_selectedValue\");\r\n");
    js.append("	return valueHidden.value;\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_getText(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var textHidden = document.getElementById(dropDownId + \"_selectedText\");\r\n");
    js.append("	return textHidden.value;\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_getKeyList(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var hidden = dropDownId + \"_containerValueId\";\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var filterId = textBox.getAttribute(\"filterId\");\r\n");
    js.append("	var filterHiddenId = null;\r\n");
    js.append("	if(filterId != null && filterId != \"\")\r\n");
    js.append("	{\r\n");
    js.append("		filterHiddenId = dropDownId + \"_\" + filterId + \"Hidden\";\r\n");
    js.append("	}\r\n");
    js.append("	if(filterHiddenId != null && document.getElementById(filterHiddenId) != null)\r\n");
    js.append("	{\r\n");
    js.append("		document.getElementById(hidden).value = document.getElementById(filterHiddenId).value;\r\n");
    js.append("	}\r\n");
    js.append("	var keyList = HashtableManager_GetKeyList(document.getElementById(hidden));\r\n");
    js.append("	return keyList;\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_getValueList(dropDownId)\r\n");
    js.append("{\r\n");
    js.append("	var hidden = dropDownId + \"_containerValueId\";\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var filterId = textBox.getAttribute(\"filterId\");\r\n");
    js.append("	var filterHiddenId = null;\r\n");
    js.append("	if(filterId != null && filterId != \"\")\r\n");
    js.append("	{\r\n");
    js.append("		filterHiddenId = dropDownId + \"_\" + filterId + \"Hidden\";\r\n");
    js.append("	}\r\n");
    js.append("	if(filterHiddenId != null && document.getElementById(filterHiddenId) != null)\r\n");
    js.append("	{\r\n");
    js.append("		document.getElementById(hidden).value = document.getElementById(filterHiddenId).value;\r\n");
    js.append("	}\r\n");
    js.append("	var valueList = HashtableManager_GetValueList(document.getElementById(hidden));\r\n");
    js.append("	return valueList;\r\n");
    js.append("	\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_hideElement( elmID, overDiv )\r\n");
    js.append("{\r\n");
    js.append("	for( i = 0; i < document.getElementsByTagName( elmID ).length; i++ )\r\n");
    js.append("	{\r\n");
    js.append("		obj = document.getElementsByTagName(elmID)[i];\r\n");
    js.append("		if( !obj || !obj.offsetParent || obj.id == overDiv.id + \"_select\")\r\n");
    js.append("		{\r\n");
    js.append("			continue;\r\n");
    js.append("		}\r\n");
    js.append("\r\n");
    js.append("		// Find the element's offsetTop and offsetLeft relative to the BODY tag.\r\n");
    js.append("		objLeft   = obj.offsetLeft;\r\n");
    js.append("		objTop    = obj.offsetTop;\r\n");
    js.append("		objParent = obj.offsetParent;\r\n");
    js.append("    \r\n");
    js.append("		while( objParent.tagName.toUpperCase() != \"BODY\" )\r\n");
    js.append("		{\r\n");
    js.append("			objLeft  += objParent.offsetLeft;\r\n");
    js.append("			objTop   += objParent.offsetTop;\r\n");
    js.append("			objParent = objParent.offsetParent;\r\n");
    js.append("		}\r\n");
    js.append("\r\n");
    js.append("		objHeight = obj.offsetHeight;\r\n");
    js.append("		objWidth = obj.offsetWidth;\r\n");
    js.append("\r\n");
    js.append("		if(( overDiv.offsetLeft + overDiv.offsetWidth ) <= objLeft );\r\n");
    js.append("		else if(( overDiv.offsetTop + overDiv.offsetHeight ) <= objTop );\r\n");
    js.append("		else if( overDiv.offsetTop >= ( objTop + objHeight ));\r\n");
    js.append("		else if( overDiv.offsetLeft >= ( objLeft + objWidth ));\r\n");
    js.append("		else\r\n");
    js.append("		{\r\n");
    js.append("			obj.style.visibility = \"hidden\";\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("}\r\n");
    js.append("	\r\n");
    js.append("function DropDown_showElement( elmID )\r\n");
    js.append("{\r\n");
    js.append("	for( i = 0; i < document.getElementsByTagName( elmID ).length; i++ )\r\n");
    js.append("	{\r\n");
    js.append("	    obj = document.getElementsByTagName( elmID )[i];\r\n");
    js.append("        if( !obj || !obj.offsetParent )\r\n");
    js.append("		{\r\n");
    js.append("		continue;\r\n");
    js.append("		}\r\n");
    js.append("        obj.style.visibility = \"\";\r\n");
    js.append("	}\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("\r\n");
    js.append("function DropDown_hidePopDiv(dropDownId, popDiv, event)\r\n");
    js.append("{\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	if (popDiv==null) return;\r\n");
    js.append("	if (popDiv.style.visibility!='hidden')\r\n");
    js.append("	{\r\n");
    js.append("		if((isMouseOnObject(popDiv.id, event)==true) || (document.activeElement == textBox))\r\n");
    js.append("		{\r\n");
    js.append("			return ;\r\n");
    js.append("		}\r\n");
    js.append("		popDiv.style.visibility='hidden';\r\n");
    js.append("	}\r\n");
    js.append("	DropDown_showElement(\"select\");\r\n");
    js.append("	DropDown_showElement(\"applet\");\r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function isMouseOnObject(objName, evt)\r\n");
    js.append("{\r\n");
    js.append("  if (objName != null)\r\n");
    js.append("  {\r\n");
    js.append("    var obj = document.getElementById(objName); \r\n");
    js.append("    var objLeft = DropDown_pageX(obj) - 1; \r\n");
    js.append("    var objTop = DropDown_pageY(obj) - 1; \r\n");
    js.append("    var objRight = objLeft + obj.offsetWidth + 1; \r\n");
    js.append("    var objBottom = objTop + obj.offsetHeight + 1;\r\n");
    js.append("    \r\n");
    js.append("    if ((evt.pageX > objLeft) && (evt.pageX < objRight) && \r\n");
    js.append("        (evt.pageY + 1 > objTop) && (evt.pageY < objBottom))\r\n");
    js.append("      return true; \r\n");
    js.append("    else  \r\n");
    js.append("      return false; \r\n");
    js.append("  }\r\n");
    js.append("  else\r\n");
    js.append("    return false; \r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("function DropDown_pageX(element)\r\n");
    js.append("{\r\n");
    js.append("  var x = 0;\r\n");
    js.append("  do \r\n");
    js.append("  {\r\n");
    js.append("    if (element.style.position == 'absolute') \r\n");
    js.append("    {\r\n");
    js.append("      return x + element.offsetLeft; \r\n");
    js.append("    }\r\n");
    js.append("    else\r\n");
    js.append("    {\r\n");
    js.append("      x += element.offsetLeft;\r\n");
    js.append("      if (element.offsetParent) \r\n");
    js.append("        if (element.offsetParent.tagName == 'TABLE') \r\n");
    js.append("          if (parseInt(element.offsetParent.border) > 0)\r\n");
    js.append("          {\r\n");
    js.append("            x += 1; \r\n");
    js.append("          }\r\n");
    js.append("    }\r\n");
    js.append("  }\r\n");
    js.append("  while ((element = element.offsetParent));\r\n");
    js.append("  return x; \r\n");
    js.append("}\r\n");
    js.append("\r\n");
    js.append("\r\n");
    js.append("function DropDown_pageY(element)\r\n");
    js.append("{\r\n");
    js.append("  var y = 0;\r\n");
    js.append("  do \r\n");
    js.append("  {\r\n");
    js.append("    if (element.style.position == 'absolute') \r\n");
    js.append("    {\r\n");
    js.append("      return y + element.offsetTop; \r\n");
    js.append("    }\r\n");
    js.append("    else\r\n");
    js.append("    {\r\n");
    js.append("      y += element.offsetTop;\r\n");
    js.append("      if (element.offsetParent) \r\n");
    js.append("        if (element.offsetParent.tagName == 'TABLE') \r\n");
    js.append("          if (parseInt(element.offsetParent.border) > 0)\r\n");
    js.append("          {\r\n");
    js.append("            y += 1; \r\n");
    js.append("          }\r\n");
    js.append("    }\r\n");
    js.append("  }\r\n");
    js.append("  while ((element = element.offsetParent));\r\n");
    js.append("  return y; \r\n");
    js.append("}\r\n");
    js.append("       function DropDown_TextBoxKeyDown(dropDownId,event)\r\n");
    js.append("	{\r\n");
    js.append("	        if(event.keyCode == 40)\r\n");
    js.append("	        {\r\n");
    js.append("	                DropDown_dropDown(dropDownId);\r\n");
    js.append("	        }\r\n");
    js.append("	}\r\n");
    js.append("	      \r\n");
    js.append("	      function DropDown_setProperty(dropDownId, property, value)\r\n");
    js.append("	      {\r\n");
    js.append("	              var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	              var ddl = document.getElementById(dropDownId);\r\n");
    js.append("	              var divButton = document.getElementById(dropDownId + \"_divButton\");\r\n");
    js.append("	              if(property.toLowerCase() == \"readonly\")\r\n");
    js.append("	              {\r\n");
    js.append("	                    if(value.toLowerCase() == \"true\")\r\n");
    js.append("	                    {\r\n");
    js.append("	                          textBox.readOnly = true;\r\n");
    js.append("	                          divButton.setAttribute(\"disabled\", \"true\");\r\n");
    js.append("	                          var src = ddl.getAttribute(\"dissrc\");\r\n");
    js.append("	                          divButton.src = src;\r\n");
    js.append("	                    }\r\n");
    js.append("	                    else\r\n");
    js.append("	                    {\r\n");
    js.append("	                          textBox.readOnly = false;\r\n");
    js.append("	                          divButton.setAttribute(\"disabled\", \"false\");\r\n");
    js.append("	                          var src = ddl.getAttribute(\"src\");\r\n");
    js.append("	                          divButton.src = src;\r\n");
    js.append("	                    }\r\n");
    js.append("	              }\r\n");
    js.append("	              else if(property.toLowerCase() == \"necessary\")\r\n");
    js.append("	              {\r\n");
    js.append("	                      if(value.toLowerCase() == \"true\")\r\n");
    js.append("	                      {\r\n");
    js.append("	                              textBox.style.backgroundColor = \"yellow\";\r\n");
    js.append("	                              document.getElementById(dropDownId).setAttribute(\"necessary\",\"true\")\r\n");
    js.append("	                      }\r\n");
    js.append("	                      else if(value.toLowerCase() == \"false\")\r\n");
    js.append("	                      {\r\n");
    js.append("	                              textBox.style.backgroundColor = \"white\";\r\n");
    js.append("	                              document.getElementById(dropDownId).setAttribute(\"necessary\",\"false\")\r\n");
    js.append("	                      }\r\n");
    js.append("	      \r\n");
    js.append("	              }\r\n");
    js.append("	              else if(property.toLowerCase() == \"width\")\r\n");
    js.append("	              {\r\n");
    js.append("	                       textBox.style.width = value - 16;\r\n");
    js.append("	                        ddl.style.width = value;\r\n");
    js.append("	              } \r\n");
    js.append("	      }\r\n");
    js.append("	\r\n");
    js.append("	function DropDown_clearFilter(dropDownId)\r\n");
    js.append("	{\r\n");
    js.append("		var filter = document.getElementById(dropDownId + \"_filters_hidden\");\r\n");
    js.append("		var container = document.getElementById(dropDownId + \"_containerValueId\");\r\n");
    js.append("		container.value = \"\";\r\n");
    js.append("		var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("		textBox.value = \"\";\r\n");
    js.append("		var textHidden = document.getElementById(dropDownId + \"_selectedText\");\r\n");
    js.append("		var valueHidden = document.getElementById(dropDownId + \"_selectedValue\");\r\n");
    js.append("		textHidden.value = \"\";\r\n");
    js.append("		valueHidden.value =\"\";\r\n");
    js.append("		if(filter != null && (filter.value != null || filter.value != \"\"))\r\n");
    js.append("		{\r\n");
    js.append("			for(var index = 0; index < ListManager_Size(filter); index++)\r\n");
    js.append("			{\r\n");
    js.append("				var filterId = ListManager_Get(index, filter);\r\n");
    js.append("				var filterObj = document.getElementById(dropDownId + \"_\" + filterId + \"Hidden\");\r\n");
    js.append("				if(filterObj != null)\r\n");
    js.append("				{\r\n");
    js.append("					filterObj.outerHTML = \"\";\r\n");
    js.append("				}\r\n");
    js.append("			}\r\n");
    js.append("			filter.value = \"\";\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("	\r\n");
    js.append("	\r\n");
    js.append("	function DropDown_setDataSource(dropDownId, filterTypes, texts, values, filterId, selectedIndex)\r\n");
    js.append("	{\r\n");
    js.append("		DropDown_clearFilter(dropDownId);\r\n");
    js.append("		if(filterTypes == null)\r\n");
    js.append("		{\r\n");
    js.append("			for(var index = 0; index<texts.length; index++)\r\n");
    js.append("			{\r\n");
    js.append("				DropDown_setContainer(dropDownId , texts[index], values[index]);\r\n");
    js.append("			}\r\n");
    js.append("			DropDown_setIndex(dropDownId, selelctedIndex);\r\n");
    js.append("		}\r\n");
    js.append("		else\r\n");
    js.append("		{\r\n");
    js.append("			for(var index = 0; index<texts.length; index++)\r\n");
    js.append("			{\r\n");
    js.append("				DropDown_setFilters(dropDownId, filterTypes[index], texts[index], values[index]);\r\n");
    js.append("			}\r\n");
    js.append("			var filter = document.getElementById(dropDownId + \"_filters_hidden\");\r\n");
    js.append("			if(filterId == null)\r\n");
    js.append("			{\r\n");
    js.append("				filterId = ListManager_Get(0, filter);\r\n");
    js.append("			}\r\n");
    js.append("			DropDown_setFilterId(dropDownId, filterId);\r\n");
    js.append("			DropDown_setIndex(dropDownId, selectedIndex);\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("	\r\n");
    js.append("	function DropDown_setContainer(dropDownId, text, value)\r\n");
    js.append("	{\r\n");
    js.append("		var container = document.getElementById(dropDownId + \"_containerValueId\");\r\n");
    js.append("		HashtableManager_Add(value, text, container);\r\n");
    js.append("	}\r\n");
    js.append("	\r\n");
    js.append("	function DropDown_setFilters(dropDownId, filterType, text, value)\r\n");
    js.append("	{\r\n");
    js.append("		var filter = document.getElementById(dropDownId + \"_filters_hidden\");\r\n");
    js.append("		var ddl = document.getElementById(dropDownId);\r\n");
    js.append("		var filterTypeHidden = document.getElementById(dropDownId + \"_\" + filterType + \"Hidden\");\r\n");
    js.append("		if(filterTypeHidden != null)\r\n");
    js.append("		{\r\n");
    js.append("			HashtableManager_Add(value, text, filterTypeHidden);\r\n");
    js.append("		}\r\n");
    js.append("		else\r\n");
    js.append("		{\r\n");
    js.append("			ListManager_Add(filterType, false, filter);\r\n");
    js.append("			var filterHidden = document.createElement(\"input\");\r\n");
    js.append("			filterHidden.type = \"hidden\";\r\n");
    js.append("			filterHidden.id = dropDownId + \"_\" + filterType + \"Hidden\";\r\n");
    js.append("			filterHidden.name = dropDownId + \"_\" + filterType + \"Hidden\";\r\n");
    js.append("			document.getElementById(dropDownId).appendChild(filterHidden);\r\n");
    js.append("			var filterHidden = document.getElementById(dropDownId + \"_\" + filterType + \"Hidden\");\r\n");
    js.append("			HashtableManager_Add(value, text, filterHidden);\r\n");
    js.append("			\r\n");
    js.append("		}\r\n");
    js.append("		\r\n");
    js.append("	}\r\n");
    js.append("	\r\n");
    js.append("	function DropDown_setFilterId(dropDownId, filterId)\r\n");
    js.append("	{\r\n");
    js.append("		var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("		var container = document.getElementById(dropDownId + \"_containerValueId\");\r\n");
    js.append("		var filter = document.getElementById(dropDownId + \"_\" + filterId + \"Hidden\");\r\n");
    js.append("		if(filter != null)\r\n");
    js.append("		{\r\n");
    js.append("			container.value = filter.value;\r\n");
    js.append("		}\r\n");
    js.append("		textBox.setAttribute(\"filterId\", filterId);\r\n");
    js.append("	}\r\n");
    js.append("	\r\n");
    js.append("	function DropDown_setIndex(dropDownId, selectedIndex)\r\n");
    js.append("	{\r\n");
    js.append("		var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("		if(selectedIndex == -1 || selectedIndex == 0)\r\n");
    js.append("		{\r\n");
    js.append("			textBox.setAttribute(\"selectedIndex\",1);\r\n");
    js.append("		}\r\n");
    js.append("		else\r\n");
    js.append("		{\r\n");
    js.append("			textBox.setAttribute(\"selectedIndex\",selectedIndex - 1);\r\n");
    js.append("		}\r\n");
    js.append("		var container = document.getElementById(dropDownId + \"_containerValueId\")\r\n");
    js.append("		var values = HashtableManager_GetKeyList(container);\r\n");
    js.append("		var texts = HashtableManager_GetValueList(container);\r\n");
    js.append("		if(selectedIndex == -1)\r\n");
    js.append("		{\r\n");
    js.append("			selectedIndex = 0;\r\n");
    js.append("		}\r\n");
    js.append("		if(texts.length > 0)\r\n");
    js.append("		{\r\n");
    js.append("			textBox.value = texts[selectedIndex];\r\n");
    js.append("		}\r\n");
    js.append("		DropDown_changeValueByTextBox(dropDownId, false);\r\n");
    js.append("	}	function DropDown_setDropDownIndex(dropDownId, selectedIndex)\r\n");
    js.append("	{\r\n");
    js.append("		var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("		var oldSelectedIndex = textBox.getAttribute(\"selectedIndex\");\r\n");
    js.append("		if(oldSelectedIndex == selectedIndex)\r\n");
    js.append("		{\r\n");
    js.append("			return;\r\n");
    js.append("		}\r\n");
    js.append("		var containerHidden = document.getElementById(dropDownId + \"_containerValueId\");\r\n");
    js.append("		var texts = HashtableManager_GetValueList(containerHidden);\r\n");
    js.append("		var values = HashtableManager_GetKeyList(containerHidden);\r\n");
    js.append("		if(texts[selectedIndex] != null)\r\n");
    js.append("		{\r\n");
    js.append("			textBox.value = texts[selectedIndex];\r\n");
    js.append("			DropDown_changeValueByTextBox(dropDownId, false);\r\n");
    js.append("		}		\r\n");
    js.append("		textBox.setAttribute(\"selectedIndex\", selectedIndex);\r\n");
    js.append("	}\r\n");
    js.append("	\r\n");
    js.append("	function DropDown_setText(dropDownId,  value)\r\n");
    js.append("{	\r\n");
    js.append("	var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("	var containerHidden = document.getElementById(dropDownId + \"_containerValueId\");\r\n");
    js.append("	var texts = HashtableManager_GetValueList(containerHidden);\r\n");
    js.append("	var values = HashtableManager_GetKeyList(containerHidden);\r\n");
    js.append("	var textHidden = document.getElementById(dropDownId + \"_selectedText\");\r\n");
    js.append("       var valueHidden = document.getElementById(dropDownId + \"_selectedValue\");\r\n");
    js.append("	var selectedIndex = -1;\r\n");
    js.append("	var dropDownType = parseInt(textBox.getAttribute(\"DropDownType\"));\r\n");
    js.append("	for(var index = 0; index < texts.length; index++)\r\n");
    js.append("	{\r\n");
    js.append("		if(texts[index] == value)\r\n");
    js.append("		{\r\n");
    js.append("			selectedIndex = index;\r\n");
    js.append("			break;\r\n");
    js.append("		}\r\n");
    js.append("	}\r\n");
    js.append("	if(selectedIndex == -1)\r\n");
    js.append("	{\r\n");
    js.append("		textBox.value = value;\r\n");
    js.append("               textHidden.value = value;\r\n");
    js.append("               valueHidden.value = \"\";\r\n");
    js.append("		DropDown_changeValueByTextBox(dropDownId, false);\r\n");
    js.append("	}\r\n");
    js.append("	else\r\n");
    js.append("	{\r\n");
    js.append("		textBox.value = texts[selectedIndex];\r\n");
    js.append("               textHidden.value = texts[selectedIndex];\r\n");
    js.append("               valueHidden.value = values[selectedIndex];\r\n");
    js.append("		DropDown_changeValueByTextBox(dropDownId, false);\r\n");
    js.append("	}\r\n");
    js.append("	textBox.setAttribute(\"selectedIndex\", selectedIndex);\r\n");
    js.append("}\r\n");
    js.append("      function DropDown_getSelectedIndex(dropDownId)\r\n");
    js.append("      {\r\n");
    js.append("        var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("        return textBox.getAttribute(\"selectedIndex\");\r\n");
    js.append("      }\r\n");
    js.append("\r\n");
    js.append("      function DropDown_setFocus(dropDownId)\r\n");
    js.append("      {\r\n");
    js.append("             var textBox = document.getElementById(dropDownId + \"_textBox\");\r\n");
    js.append("             textBox.focus();\r\n");
    js.append("      }\r\n");
    js.append("      \r\n");
    js.append("      function DropDown_hideDivPop(dropDownId)\r\n");
    js.append("      {\r\n");
    js.append("			var popDivId = dropDownId + \"_popDiv\";\r\n");
    js.append("			var popDiv = document.getElementById(popDivId);\r\n");
    js.append("			if(popDiv.getAttribute(\"popShow\") == \"true\")\r\n");
    js.append("			{\r\n");
    js.append("				popDiv.style.visibility = \"hidden\";\r\n");
    js.append("				popDiv.setAttribute(\"popShow\", \"false\");\r\n");
    js.append("				return;\r\n");
    js.append("			}\r\n");
    js.append("			else\r\n");
    js.append("			{\r\n");
    js.append("				popDiv.setAttribute(\"popShow\", \"true\");\r\n");
    js.append("			}\r\n");
    js.append("      }\r\n");
    js.append("\r\n");
    js.append("");
    jstool.js=js;
    return jstool.getComponentJS();
  }


}