/*
 * �������� 2004-2-11
 *
 * ���������ļ�ģ��Ϊ
 * ���� > ��ѡ�� > Java > ������� > �����ע��
 */
package com.born.insurance.webui.control;

/**
 * Title:FilterSetJS Component<br>
 * Description:ɸѡ������������ű����<br>
 * Copyright: Copyright (c) 2003<br>
 * Company: bornsoft<br>
 * @author �ᴺ��
 * @version 1.0
 */
public class FilterSetJS {
	/**
	 * ���캯��
	 *
	 */
	protected FilterSetJS()
	{
	}
	/**
	 * ��ȡɸѡ���ÿͻ��˽ű�
	 * @return
	 */
	public static String getFilterSetJS()
	{
		JSTool jstool=new JSTool("FilterSetJS.js");
		if(!jstool.util.isUpdateJsEveryTime())
		 {
			 return jstool.getComponentJS() ;//+ HashMapJS.getHashMapJS();
		 }
		 if(true) return jstool.getComponentJS() + HashMapJS.getHashMapJS();
		StringBuffer js = new StringBuffer();
		js.append("var oldFieldName;\r\n");
		js.append("var oldFieldType;\r\n");
		js.append("var oldOperator;\r\n");
		js.append("var oldOperatorId;\r\n");
		js.append("var isGridOnChanged = false;\r\n");
		js.append("var onClickEvent = true;\r\n");
		js.append("\r\n");
		js.append("var selectedIndex = 0;\r\n");
		js.append("var isSTOnChange = false;\r\n");
		js.append("\r\n");
		js.append("var arrDsTexts = new Array();\r\n");
		js.append("var arrDsValues = new Array();\r\n");
		js.append("var arrDsFilter = new Array();\r\n");
		js.append("\r\n");
		js.append("function ddlGoto()\r\n");
		js.append("{\r\n");
		js.append("	if (isSTOnChange)\r\n");
		js.append("	{\r\n");
		js.append("		if (oldFieldName != null)\r\n");
		js.append("		{\r\n");
		js.append("			var stText = _SearchText_getTextBox(oldFieldName + \"_st\");\r\n");
		js.append("			if (stText == null || trim(stText.value) == \"\")\r\n");
		js.append("			{\r\n");
		js.append("				isSTOnChange = false;\r\n");
		js.append("				return false;\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("		listBox.selectedIndex = selectedIndex;\r\n");
		js.append("		isSTOnChange = false;\r\n");
		js.append("		return true;\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//�б��OnChanged�¼�\r\n");
		js.append("function lstFilterField_onchange()\r\n");
		js.append("{	\r\n");
		js.append("	if (ddlGoto()) return;\r\n");
		js.append("	\r\n");
		js.append("	saveCondValue();\r\n");
		js.append("	clearControlsValue();\r\n");
		js.append("	var lblFieldName = document.getElementById('lblFieldName');	 \r\n");
		js.append("	var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("	lblFieldName.title = listBox.value;\r\n");
		js.append("	lblFieldName.innerText = listBox.options[listBox.selectedIndex].text;\r\n");
		js.append("	\r\n");
		js.append("	var hmmFieldType = document.getElementById('hmmFieldType');\r\n");
		js.append("	var fieldType = HashtableManager_Get(listBox.value, hmmFieldType);	\r\n");
		js.append("	filterDdlSelect(fieldType);\r\n");
		js.append("	initControls(listBox.value, fieldType);\r\n");
		js.append("	initGrid();			\r\n");
		js.append("	oldFieldName = listBox.value;\r\n");
		js.append("	oldFieldType = fieldType;	\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("function ddlSelect_onchange()\r\n");
		js.append("{\r\n");
		js.append("	var hiddenFieldType = document.getElementById('hmmFieldType');\r\n");
		js.append("	var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("	var fieldType = HashtableManager_Get(listBox.value, hiddenFieldType);\r\n");
		js.append("	showControls(fieldType, DropDown_getText('ddlSelect'));\r\n");
		js.append("	oldOperatorId = DropDown_getValue('ddlSelect');\r\n");
		js.append("	oldOperator = DropDown_getText('ddlSelect');\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//����ֶ����ͺͲ�������ʾ�ؼ�\r\n");
		js.append("function showControls(strFieldType, operator)\r\n");
		js.append("{\r\n");
		js.append("			hiddenAllControls();\r\n");
		js.append("			switch (operator)\r\n");
		js.append("			{\r\n");
		js.append("				case \"����\":\r\n");
		js.append("				case \"����\":\r\n");
		js.append("					break;\r\n");
		js.append("					\r\n");
		js.append("				case \"��ֵ\":\r\n");
		js.append("				case \"����ֵ\":\r\n");
		js.append("					var lblExplain = document.getElementById('lblExplain');\r\n");
		js.append("					var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("					lblExplain.style.display = \"inline\";\r\n");
		js.append("					lblExplain.title = listBox.options[listBox.selectedIndex].text + \":\" + DropDown_getText('ddlSelect');\r\n");
		js.append("					lblExplain.innerText = listBox.options[listBox.selectedIndex].text + \":\" + DropDown_getText('ddlSelect');\r\n");
		js.append("					break;\r\n");
		js.append("					\r\n");
		js.append("				case \"��\":\r\n");
		js.append("				case \"��\":\r\n");
		js.append("					var lblExplain = document.getElementById('lblExplain');\r\n");
		js.append("					var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("					lblExplain.style.display = \"inline\";\r\n");
		js.append("					lblExplain.title = DropDown_getText('ddlSelect');\r\n");
		js.append("					lblExplain.innerText = DropDown_getText('ddlSelect');\r\n");
		js.append("					break;\r\n");
		js.append("					\r\n");
		js.append("				case \"����\":\r\n");
		js.append("				case \"����\":\r\n");
		js.append("				case \"С��\":\r\n");
		js.append("				case \"���ڵ���\":\r\n");
		js.append("				case \"С�ڵ���\":\r\n");
		js.append("				case \"��ͷ�ַ�Ϊ\":\r\n");
		js.append("				case \"���ַ�\":\r\n");
		js.append("				case \"������\":\r\n");
		js.append("				case \"������\":\r\n");
		js.append("					switch (strFieldType)\r\n");
		js.append("					{\r\n");
		js.append("						case \"currency-amount\":\r\n");
		js.append("						case \"floating-point\":\r\n");
		js.append("						case \"numeric\":\r\n");
		js.append("							var divNumberFrom = document.getElementById(\"divTextBoxNumberFrom\");\r\n");
		js.append("							divNumberFrom.style.display = \"inline\";\r\n");
		js.append("							var txtNumberFrom = document.getElementById(\"txtNumberFrom\");\r\n");
		js.append("							txtNumberFrom.style.width = \"148px\";\r\n");
		js.append("							break;\r\n");
		js.append("						default:\r\n");
		js.append("							var divFrom = document.getElementById(\"divTextBoxFrom\");\r\n");
		js.append("							divFrom.style.display = \"inline\";\r\n");
		js.append("							var txtFrom = document.getElementById(\"txtFrom\");\r\n");
		js.append("							txtFrom.style.width = \"148px\";\r\n");
		js.append("							break;\r\n");
		js.append("					}\r\n");
		js.append("					break;\r\n");
		js.append("					\r\n");
		js.append("				case \"����\":\r\n");
		js.append("				case \"�Զ���\":				\r\n");
		js.append("					var divLabelFrom = document.getElementById(\"divLabelFrom\");\r\n");
		js.append("					divLabelFrom.style.display = \"inline\";\r\n");
		js.append("					var divLabelTo = document.getElementById(\"divLabelTo\");\r\n");
		js.append("					divLabelTo.style.display = \"inline\";\r\n");
		js.append("					\r\n");
		js.append("					switch (strFieldType)\r\n");
		js.append("					{\r\n");
		js.append("						case \"date-time\":\r\n");
		js.append("						case \"date\":\r\n");
		js.append("						case \"time\":						\r\n");
		js.append("							var divCal1 = document.getElementById('divCalendar1');\r\n");
		js.append("							divCal1.style.display = \"inline\";\r\n");
		js.append("							var divCal2 = document.getElementById('divCalendar2');\r\n");
		js.append("							divCal2.style.display = \"inline\";\r\n");
		js.append("							GACalendar_setValue(\"calDataTo\", \"\");\r\n");
		js.append("							GACalendar_setValue(\"calDataFrom\", \"\");\r\n");
		js.append("							break;\r\n");
		js.append("							\r\n");
		js.append("						case \"currency-amount\":\r\n");
		js.append("						case \"floating-point\":\r\n");
		js.append("						case \"numeric\":\r\n");
		js.append("							var divNumberFrom = document.getElementById(\"divTextBoxNumberFrom\");\r\n");
		js.append("							divNumberFrom.style.display = \"inline\";\r\n");
		js.append("							var txtNumberFrom = document.getElementById(\"txtNumberFrom\");\r\n");
		js.append("							txtNumberFrom.style.width = \"137px\";\r\n");
		js.append("							var divNumberTo = document.getElementById(\"divTextBoxNumberTo\");	\r\n");
		js.append("							divNumberTo.style.display = \"inline\";\r\n");
		js.append("							var txtNumberTo = document.getElementById(\"txtNumberTo\");\r\n");
		js.append("							txtNumberTo.style.width = \"137px\";\r\n");
		js.append("							break;\r\n");
		js.append("							\r\n");
		js.append("						default:\r\n");
		js.append("							var divTextBoxFrom = document.getElementById(\"divTextBoxFrom\");\r\n");
		js.append("							divTextBoxFrom.style.display = \"inline\";\r\n");
		js.append("							var divTextBoxTo = document.getElementById(\"divTextBoxTo\");\r\n");
		js.append("							divTextBoxTo.style.display = \"inline\";\r\n");
		js.append("							var txtFrom = document.getElementById(\"txtFrom\");\r\n");
		js.append("							var txtTo = document.getElementById(\"txtTo\");\r\n");
		js.append("							txtFrom.style.width = \"137px\";\r\n");
		js.append("							txtTo.style.width = \"137px\";						\r\n");
		js.append("							break;\r\n");
		js.append("					}\r\n");
		js.append("					break;					\r\n");
		js.append("					\r\n");
		js.append("				case \"ѡ����Ŀ\":\r\n");
		js.append("					var divSearchText = document.getElementById('divSearchText');\r\n");
		js.append("					divSearchText.style.display = \"inline\";\r\n");
		js.append("					var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("					var fieldName = listBox.value;\r\n");
		js.append("					var st = document.getElementById(fieldName);\r\n");
		js.append("					divSearchText.innerHTML = \"\";\r\n");
		js.append("					divSearchText.innerHTML = st.innerHTML;	\r\n");
		js.append("					break;\r\n");
		js.append("				\r\n");
		js.append("			}	\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//�������пؼ�\r\n");
		js.append("function hiddenAllControls()\r\n");
		js.append("{\r\n");
		js.append("	var txtFrom = document.getElementById(\"txtFrom\");\r\n");
		js.append("	txtFrom.style.width = \"148px\";\r\n");
		js.append("	GACalendar_setProperty(\"calDataFrom\", \"width\", \"138\");\r\n");
		js.append("	\r\n");
		js.append("	var divFrom = document.getElementById(\"divTextBoxFrom\");\r\n");
		js.append("	divFrom.style.display = \"none\";				\r\n");
		js.append("	var divTo = document.getElementById(\"divTextBoxTo\");\r\n");
		js.append("	divTo.style.display = \"none\";	\r\n");
		js.append("		\r\n");
		js.append("	var divNumberFrom = document.getElementById(\"divTextBoxNumberFrom\");\r\n");
		js.append("	divNumberFrom.style.display = \"none\";	\r\n");
		js.append("	var divNumberTo = document.getElementById(\"divTextBoxNumberTo\");	\r\n");
		js.append("	divNumberTo.style.display = \"none\";\r\n");
		js.append("		\r\n");
		js.append("	var divLabelFrom = document.getElementById(\"divLabelFrom\");\r\n");
		js.append("	divLabelFrom.style.display = \"none\";\r\n");
		js.append("	var divLabelTo = document.getElementById(\"divLabelTo\");\r\n");
		js.append("	divLabelTo.style.display = \"none\";\r\n");
		js.append("			\r\n");
		js.append("	var divSearchText = document.getElementById('divSearchText');\r\n");
		js.append("	divSearchText.style.display = \"none\";\r\n");
		js.append("	\r\n");
		js.append("	var divCal1 = document.getElementById('divCalendar1');\r\n");
		js.append("	divCal1.style.display = \"none\";\r\n");
		js.append("	var divCal2 = document.getElementById('divCalendar2');\r\n");
		js.append("	divCal2.style.display = \"none\";\r\n");
		js.append("		\r\n");
		js.append("	var lblExplain = document.getElementById('lblExplain');\r\n");
		js.append("	lblExplain.style.display = \"none\";\r\n");
		js.append("	lblExplain.title = \"\";\r\n");
		js.append("	lblExplain.innerText = \"\";	\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("function clearControlsValue()\r\n");
		js.append("{\r\n");
		js.append("	OfbizTextBox_SetValue(\"txtFrom\", \"\");\r\n");
		js.append("	OfbizTextBox_SetValue(\"txtTo\", \"\");\r\n");
		js.append("	OfbizTextBox_SetValue(\"txtNumberFrom\", \"\");\r\n");
		js.append("	OfbizTextBox_SetValue(\"txtNumberTo\", \"\");\r\n");
		js.append("	GACalendar_setValue(\"calDataTo\", \"\");\r\n");
		js.append("	GACalendar_setValue(\"calDataFrom\", \"\");\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//��ʼ�����б����Դ\r\n");
		js.append("function addOptions()\r\n");
		js.append("{	\r\n");
		js.append("	//�ַ���\r\n");
		js.append("	arrDsTexts[0] = \"����\";\r\n");
		js.append("	arrDsValues[0] = \"-1\";\r\n");
		js.append("	arrDsFilter[0] = \"0\";\r\n");
		js.append("	arrDsTexts[1] = \"��ֵ\";\r\n");
		js.append("	arrDsValues[1] = \"0\";\r\n");
		js.append("	arrDsFilter[1] = \"0\";\r\n");
		js.append("	arrDsTexts[2] = \"����\";\r\n");
		js.append("	arrDsValues[2] = \"2\";\r\n");
		js.append("	arrDsFilter[2] = \"0\";\r\n");
		js.append("	arrDsTexts[3] = \"����\";\r\n");
		js.append("	arrDsValues[3] = \"3\";\r\n");
		js.append("	arrDsFilter[3] = \"0\";\r\n");
		js.append("	arrDsTexts[4] = \"С��\";\r\n");
		js.append("	arrDsValues[4] = \"4\";\r\n");
		js.append("	arrDsFilter[4] = \"0\";\r\n");
		js.append("	arrDsTexts[5] = \"������\";\r\n");
		js.append("	arrDsValues[5] = \"5\";\r\n");
		js.append("	arrDsFilter[5] = \"0\";\r\n");
		js.append("	arrDsTexts[6] = \"���ڵ���\";\r\n");
		js.append("	arrDsValues[6] = \"6\";\r\n");
		js.append("	arrDsFilter[6] = \"0\";\r\n");
		js.append("	arrDsTexts[7] = \"С�ڵ���\";\r\n");
		js.append("	arrDsValues[7] = \"7\";\r\n");
		js.append("	arrDsFilter[7] = \"0\"\r\n");
		js.append("	arrDsTexts[8] = \"����\";\r\n");
		js.append("	arrDsValues[8] = \"8\";\r\n");
		js.append("	arrDsFilter[8] = \"0\";\r\n");
		js.append("	arrDsTexts[9] = \"��ͷ�ַ�Ϊ\";\r\n");
		js.append("	arrDsValues[9] = \"9\";\r\n");
		js.append("	arrDsFilter[9] = \"0\";\r\n");
		js.append("	arrDsTexts[10] = \"���ַ�\";\r\n");
		js.append("	arrDsValues[10] = \"10\";\r\n");
		js.append("	arrDsFilter[10] = \"0\";\r\n");
		js.append("	arrDsTexts[11] = \"������\";\r\n");
		js.append("	arrDsValues[11] = \"11\";\r\n");
		js.append("	arrDsFilter[11] = \"0\";\r\n");
		js.append("	\r\n");
		js.append("	//��ֵ��\r\n");
		js.append("	arrDsTexts[12] = \"����\";\r\n");
		js.append("	arrDsValues[12] = \"-1\";\r\n");
		js.append("	arrDsFilter[12] = \"1\";\r\n");
		js.append("	arrDsTexts[13] = \"����ֵ\";\r\n");
		js.append("	arrDsValues[13] = \"1\";\r\n");
		js.append("	arrDsFilter[13] =\"1\";\r\n");
		js.append("	arrDsTexts[14] = \"����\";\r\n");
		js.append("	arrDsValues[14] = \"2\";\r\n");
		js.append("	arrDsFilter[14] = \"1\";\r\n");
		js.append("	arrDsTexts[15] = \"����\";\r\n");
		js.append("	arrDsValues[15] = \"3\";\r\n");
		js.append("	arrDsFilter[15] = \"1\";\r\n");
		js.append("	arrDsTexts[16] = \"С��\";\r\n");
		js.append("	arrDsValues[16] = \"4\";\r\n");
		js.append("	arrDsFilter[16] = \"1\";\r\n");
		js.append("	arrDsTexts[16] = \"������\";\r\n");
		js.append("	arrDsValues[16] = \"5\";\r\n");
		js.append("	arrDsFilter[16] = \"1\";\r\n");
		js.append("	arrDsTexts[17] = \"���ڵ���\";\r\n");
		js.append("	arrDsValues[17] = \"6\";\r\n");
		js.append("	arrDsFilter[17] = \"1\";\r\n");
		js.append("	arrDsTexts[18] = \"С�ڵ���\";\r\n");
		js.append("	arrDsValues[18] = \"7\";\r\n");
		js.append("	arrDsFilter[18] = \"1\";\r\n");
		js.append("	arrDsTexts[19] = \"����\";\r\n");
		js.append("	arrDsValues[19] = \"8\";\r\n");
		js.append("	arrDsFilter[19] = \"1\";\r\n");
		js.append("	arrDsTexts[20] = \"��ͷ�ַ�Ϊ\";\r\n");
		js.append("	arrDsValues[20] = \"9\";\r\n");
		js.append("	arrDsFilter[20] = \"1\";\r\n");
		js.append("	arrDsTexts[21] = \"���ַ�\";\r\n");
		js.append("	arrDsValues[21] = \"10\";\r\n");
		js.append("	arrDsFilter[21] = \"1\";\r\n");
		js.append("	arrDsTexts[22] = \"������\";\r\n");
		js.append("	arrDsValues[22] = \"11\";\r\n");
		js.append("	arrDsFilter[22] = \"1\";\r\n");
		js.append("	\r\n");
		js.append("	//������\r\n");
		js.append("	arrDsTexts[23] = \"����\";\r\n");
		js.append("	arrDsValues[23] = \"-1\";\r\n");
		js.append("	arrDsFilter[23] = \"2\";	\r\n");
		js.append("	arrDsTexts[24] = \"��\";\r\n");
		js.append("	arrDsValues[24] = \"12\";\r\n");
		js.append("	arrDsFilter[24] = \"2\";\r\n");
		js.append("	arrDsTexts[25] = \"��\";\r\n");
		js.append("	arrDsValues[25] = \"13\";\r\n");
		js.append("	arrDsFilter[25] = \"2\";\r\n");
		js.append("	\r\n");
		js.append("	//������\r\n");
		js.append("	arrDsTexts[26] = \"����\";\r\n");
		js.append("	arrDsValues[26] = \"-1\";\r\n");
		js.append("	arrDsFilter[26] = \"3\";\r\n");
		js.append("	arrDsTexts[27] = \"����\";\r\n");
		js.append("	arrDsValues[27] = \"14\";\r\n");
		js.append("	arrDsFilter[27] = \"3\";\r\n");
		js.append("	arrDsTexts[28] = \"����\";\r\n");
		js.append("	arrDsValues[28] = \"15\";\r\n");
		js.append("	arrDsFilter[28] = \"3\";\r\n");
		js.append("	arrDsTexts[29] = \"����������\";\r\n");
		js.append("	arrDsValues[29] = \"16\";\r\n");
		js.append("	arrDsFilter[29] = \"3\";\r\n");
		js.append("	arrDsTexts[30] = \"����\";\r\n");
		js.append("	arrDsValues[30] = \"17\";\r\n");
		js.append("	arrDsFilter[30] = \"3\";\r\n");
		js.append("	arrDsTexts[31] = \"����������\";\r\n");
		js.append("	arrDsValues[31] = \"18\";\r\n");
		js.append("	arrDsFilter[31] = \"3\";\r\n");
		js.append("	arrDsTexts[32] = \"����\";\r\n");
		js.append("	arrDsValues[32] = \"19\";\r\n");
		js.append("	arrDsFilter[32] = \"3\";\r\n");
		js.append("	arrDsTexts[33] = \"������Ѯ\";\r\n");
		js.append("	arrDsValues[33] = \"20\";\r\n");
		js.append("	arrDsFilter[33] = \"3\";\r\n");
		js.append("	arrDsTexts[34] = \"������Ѯ\";\r\n");
		js.append("	arrDsValues[34] = \"21\";\r\n");
		js.append("	arrDsFilter[34] = \"3\";\r\n");
		js.append("	arrDsTexts[35] = \"������Ѯ\";\r\n");
		js.append("	arrDsValues[35] = \"22\";\r\n");
		js.append("	arrDsFilter[35] = \"3\";\r\n");
		js.append("	arrDsTexts[36] = \"����������\";\r\n");
		js.append("	arrDsValues[36] = \"23\";\r\n");
		js.append("	arrDsFilter[36] = \"3\";\r\n");
		js.append("	arrDsTexts[37] = \"������\";\r\n");
		js.append("	arrDsValues[37] = \"24\";\r\n");
		js.append("	arrDsFilter[37] = \"3\";\r\n");
		js.append("	arrDsTexts[38] = \"����������\";\r\n");
		js.append("	arrDsValues[38] = \"25\";\r\n");
		js.append("	arrDsFilter[38] = \"3\";\r\n");
		js.append("	arrDsTexts[39] = \"����\";\r\n");
		js.append("	arrDsValues[39] = \"26\";\r\n");
		js.append("	arrDsFilter[39] = \"3\";\r\n");
		js.append("	arrDsTexts[40] = \"����������\";\r\n");
		js.append("	arrDsValues[40] = \"27\";\r\n");
		js.append("	arrDsFilter[40] = \"3\";\r\n");
		js.append("	arrDsTexts[41] = \"����\";\r\n");
		js.append("	arrDsValues[41] = \"28\";\r\n");
		js.append("	arrDsFilter[41] = \"3\";\r\n");
		js.append("	arrDsTexts[42] = \"����\";\r\n");
		js.append("	arrDsValues[42] = \"29\";\r\n");
		js.append("	arrDsFilter[42] = \"3\";\r\n");
		js.append("	arrDsTexts[43] = \"����\";\r\n");
		js.append("	arrDsValues[43] = \"30\";\r\n");
		js.append("	arrDsFilter[43] = \"3\";\r\n");
		js.append("	arrDsTexts[44] = \"�ϼ���\";\r\n");
		js.append("	arrDsValues[44] = \"31\";\r\n");
		js.append("	arrDsFilter[44] = \"3\";\r\n");
		js.append("	arrDsTexts[45] = \"ȥ��\";\r\n");
		js.append("	arrDsValues[45] = \"32\";\r\n");
		js.append("	arrDsFilter[45] = \"3\";	\r\n");
		js.append("	arrDsTexts[46] = \"ȥ�������ȥ�����\";\r\n");
		js.append("	arrDsValues[46] = \"33\";\r\n");
		js.append("	arrDsFilter[46] = \"3\";\r\n");
		js.append("	arrDsTexts[47] = \"�Զ���\";\r\n");
		js.append("	arrDsValues[47] = \"34\";\r\n");
		js.append("	arrDsFilter[47] = \"3\";\r\n");
		js.append("	\r\n");
		js.append("	//���\r\n");
		js.append("	arrDsTexts[48] = \"����\";\r\n");
		js.append("	arrDsValues[48] = \"-1\";\r\n");
		js.append("	arrDsFilter[48] = \"4\";\r\n");
		js.append("	arrDsTexts[49] = \"ѡ����Ŀ\";\r\n");
		js.append("	arrDsValues[49] = \"35\";\r\n");
		js.append("	arrDsFilter[49] = \"4\";\r\n");
		js.append("	\r\n");
		js.append("	var hmmOpMap = document.getElementById('hmmOpMap');\r\n");
		js.append("	for (var i = 0; i < 50; i++)\r\n");
		js.append("	{\r\n");
		js.append("		HashtableManager_Add(arrDsValues[i], arrDsTexts[i], hmmOpMap);\r\n");
		js.append("	}	\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//����ֶ�������ʾ����������\r\n");
		js.append("function filterDdlSelect(strFieldType)\r\n");
		js.append("{\r\n");
		js.append("	switch(strFieldType)\r\n");
		js.append("	{		\r\n");
		js.append("		case \"id\":\r\n");
		js.append("		case \"id-long\":\r\n");
		js.append("		case \"id-vlong\":\r\n");
		js.append("		case \"very-short\":\r\n");
		js.append("		case \"short-varchar\":\r\n");
		js.append("		case \"long-varchar\":\r\n");
		js.append("		case \"very-long\":\r\n");
		js.append("		case \"comment\":		\r\n");
		js.append("		case \"description\":\r\n");
		js.append("		case \"java.lang.String\":\r\n");
		js.append("		case \"name\":\r\n");
		js.append("		case \"value\":\r\n");
		js.append("		case \"credit-card-number\":\r\n");
		js.append("		case \"credit-card-date\":\r\n");
		js.append("		case \"email\":\r\n");
		js.append("		case \"url\":\r\n");
		js.append("		case \"id-ne\":\r\n");
		js.append("		case \"id-long-ne\":\r\n");
		js.append("		case \"id-vlong-ne\":\r\n");
		js.append("		case \"tel-number\":\r\n");
		js.append("			DropDown_setDataSource('ddlSelect', arrDsFilter, arrDsTexts, arrDsValues, \"0\", 0);	\r\n");
		js.append("			break;\r\n");
		js.append("			\r\n");
		js.append("		case \"currency-amount\":\r\n");
		js.append("		case \"floating-point\":\r\n");
		js.append("		case \"numeric\":		\r\n");
		js.append("			DropDown_setDataSource('ddlSelect', arrDsFilter, arrDsTexts, arrDsValues, \"1\", 0);		\r\n");
		js.append("			break;			\r\n");
		js.append("			\r\n");
		js.append("		case \"indicator\":\r\n");
		js.append("			DropDown_setDataSource('ddlSelect', arrDsFilter, arrDsTexts, arrDsValues, \"2\", 0);				\r\n");
		js.append("			break;\r\n");
		js.append("			\r\n");
		js.append("		case \"date-time\":\r\n");
		js.append("		case \"date\":\r\n");
		js.append("		case \"time\":\r\n");
		js.append("			DropDown_setDataSource('ddlSelect', arrDsFilter, arrDsTexts, arrDsValues, \"3\", 0);				\r\n");
		js.append("			break;\r\n");
		js.append("			\r\n");
		js.append("		case \"relation\":\r\n");
		js.append("			DropDown_setDataSource('ddlSelect', arrDsFilter, arrDsTexts, arrDsValues, \"4\", 0);\r\n");
		js.append("			break;\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//����������趨��ֵ\r\n");
		js.append("function saveCondValue()\r\n");
		js.append("{\r\n");
		js.append("	if (oldOperator == null)\r\n");
		js.append("		return false;\r\n");
		js.append("	if (oldFieldName == null)\r\n");
		js.append("		return false;\r\n");
		js.append("		\r\n");
		js.append("	var hmmCondOp = document.getElementById('hmmCondOp');\r\n");
		js.append("	var hmmCondVal1 = document.getElementById('hmmCondVal1');\r\n");
		js.append("	var hmmCondVal2 = document.getElementById('hmmCondVal2');\r\n");
		js.append("	\r\n");
		js.append("	switch(oldOperator)\r\n");
		js.append("	{		\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"����\":\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal2);\r\n");
		js.append("			\r\n");
		js.append("			if (HashtableManager_ContainsKey(oldFieldName, hmmCondOp))\r\n");
		js.append("			{\r\n");
		js.append("				WebGrid_Delete('condGrid');\r\n");
		js.append("			}\r\n");
		js.append("\r\n");
		js.append("			break;\r\n");
		js.append("					\r\n");
		js.append("		case \"��ֵ\":\r\n");
		js.append("		case \"����ֵ\":\r\n");
		js.append("			if (equals(oldFieldName, hmmCondOp, oldOperatorId) && equals(oldFieldName, hmmCondVal1, oldOperator))\r\n");
		js.append("				break;\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal2);\r\n");
		js.append("			\r\n");
		js.append("			var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("			HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);\r\n");
		js.append("			HashtableManager_Add(oldFieldName, oldOperator, hmmCondVal1);\r\n");
		js.append("			break;\r\n");
		js.append("			\r\n");
		js.append("		case \"��\":\r\n");
		js.append("		case \"��\":\r\n");
		js.append("			if (equals(oldFieldName, hmmCondOp, oldOperatorId) && equals(oldFieldName, hmmCondVal1, oldOperator))\r\n");
		js.append("				break;\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal2);\r\n");
		js.append("			\r\n");
		js.append("			HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);\r\n");
		js.append("			HashtableManager_Add(oldFieldName, oldOperator, hmmCondVal1);			\r\n");
		js.append("			break;\r\n");
		js.append("			\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"С��\":\r\n");
		js.append("		case \"���ڵ���\":\r\n");
		js.append("		case \"С�ڵ���\":\r\n");
		js.append("		case \"��ͷ�ַ�Ϊ\":\r\n");
		js.append("		case \"���ַ�\":\r\n");
		js.append("		case \"������\":\r\n");
		js.append("		case \"������\":\r\n");
		js.append("			switch (oldFieldType)\r\n");
		js.append("			{\r\n");
		js.append("				case \"currency-amount\":\r\n");
		js.append("				case \"floating-point\":\r\n");
		js.append("				case \"numeric\":\r\n");
		js.append("					var numberValue = OfbizTextBox_GetValue(\"txtNumberFrom\");\r\n");
		js.append("					\r\n");
		js.append("					if (numberValue != null && trim(numberValue) != \"\")\r\n");
		js.append("					{					\r\n");
		js.append("						if (equals(oldFieldName, hmmCondOp, oldOperatorId) && equals(oldFieldName, trim(numberValue), hmmCondVal1))\r\n");
		js.append("							break;\r\n");
		js.append("						\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondVal2);\r\n");
		js.append("						\r\n");
		js.append("						HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);\r\n");
		js.append("						HashtableManager_Add(oldFieldName, trim(numberValue), hmmCondVal1);					\r\n");
		js.append("					}\r\n");
		js.append("					break;\r\n");
		js.append("					\r\n");
		js.append("				default:\r\n");
		js.append("					var textValue = OfbizTextBox_GetValue(\"txtFrom\");\r\n");
		js.append("					if (textValue != null && trim(textValue) != \"\")\r\n");
		js.append("					{\r\n");
		js.append("						if (equals(oldFieldName, hmmCondOp, oldOperatorId) && equals(oldFieldName, hmmCondVal1, trim(textValue)))\r\n");
		js.append("							break;\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondVal2);	\r\n");
		js.append("						\r\n");
		js.append("						HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);\r\n");
		js.append("						HashtableManager_Add(oldFieldName, trim(textValue), hmmCondVal1);					\r\n");
		js.append("					}\r\n");
		js.append("					break;\r\n");
		js.append("			}			\r\n");
		js.append("			break;\r\n");
		js.append("			\r\n");
		js.append("		case \"����\":\r\n");
		js.append("			switch (oldFieldType)\r\n");
		js.append("			{				\r\n");
		js.append("				case \"currency-amount\":\r\n");
		js.append("				case \"floating-point\":\r\n");
		js.append("				case \"numeric\":\r\n");
		js.append("					var numFromVal = OfbizTextBox_GetValue(\"txtNumberFrom\");\r\n");
		js.append("					var numToVal = OfbizTextBox_GetValue(\"txtNumberTo\");\r\n");
		js.append("					if (numFromVal != null && trim(numFromVal) != \"\" && numToVal != null && trim(numToVal) != \"\")\r\n");
		js.append("					{\r\n");
		js.append("						if (equals(oldFieldName, hmmCondOp, oldOperatorId) && equals(oldFieldName, hmmCondVal1, trim(numFromVal)) && equals(oldFieldName, hmmCondVal2, trim(numToVal)))\r\n");
		js.append("							break;\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondVal2);\r\n");
		js.append("							\r\n");
		js.append("						HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);				\r\n");
		js.append("						HashtableManager_Add(oldFieldName, trim(numFromVal), hmmCondVal1);\r\n");
		js.append("						HashtableManager_Add(oldFieldName, trim(numToVal), hmmCondVal2);\r\n");
		js.append("					//	alert(numFromVal + \",\" + numToVal);\r\n");
		js.append("					}\r\n");
		js.append("					//OfbizTextBox_SetValue(\"txtNumberFrom\", \"\");\r\n");
		js.append("					//OfbizTextBox_SetValue(\"txtNumberTo\", \"\");\r\n");
		js.append("					break;\r\n");
		js.append("					\r\n");
		js.append("				default:\r\n");
		js.append("					var txtFromVal = OfbizTextBox_GetValue(\"txtFrom\");\r\n");
		js.append("					var txtToVal = OfbizTextBox_GetValue(\"txtTo\");\r\n");
		js.append("					if (txtFromVal != null && trim(txtFromVal) != \"\" && txtToVal != null && trim(txtToVal) != \"\")\r\n");
		js.append("					{\r\n");
		js.append("						if (equals(oldFieldName, hmmCondOp, oldOperatorId) && equals(oldFieldName, hmmCondVal1, trim(txtFromVal)) && equals(oldFieldName, hmmCondVal2, trim(txtToVal)))\r\n");
		js.append("							break;\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("						clearHashtableItem(oldFieldName, hmmCondVal2);	\r\n");
		js.append("						\r\n");
		js.append("						HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);\r\n");
		js.append("						HashtableManager_Add(oldFieldName, trim(txtFromVal), hmmCondVal1);\r\n");
		js.append("						HashtableManager_Add(oldFieldName, trim(txtToVal), hmmCondVal2);				\r\n");
		js.append("					}\r\n");
		js.append("					//OfbizTextBox_SetValue(\"txtFrom\", \"\");\r\n");
		js.append("					//OfbizTextBox_SetValue(\"txtTo\", \"\");					\r\n");
		js.append("					break;\r\n");
		js.append("			}\r\n");
		js.append("			break;\r\n");
		js.append("			\r\n");
		js.append("		case \"�Զ���\":\r\n");
		js.append("			var calFrom = GACalendar_getValue(\"calDataFrom\");\r\n");
		js.append("			var calTo = GACalendar_getValue(\"calDataTo\");\r\n");
		js.append("			if (calFrom != null && trim(calFrom) != \"\" && calTo !=null && trim(calTo) != \"\")\r\n");
		js.append("			{\r\n");
		js.append("				if (equals(oldFieldName, hmmCondOp, oldOperatorId) && equals(oldFieldName, hmmCondVal1, trim(calFrom)) && equals(oldFieldName, hmmCondVal2, trim(calTo)))\r\n");
		js.append("					break;\r\n");
		js.append("				clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("				clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("				clearHashtableItem(oldFieldName, hmmCondVal2);	\r\n");
		js.append("				\r\n");
		js.append("				HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);\r\n");
		js.append("				HashtableManager_Add(oldFieldName, trim(calFrom), hmmCondVal1);\r\n");
		js.append("				HashtableManager_Add(oldFieldName, trim(calTo), hmmCondVal2);					\r\n");
		js.append("			}					\r\n");
		js.append("			break;			\r\n");
		js.append("			\r\n");
		js.append("		case \"����\":				\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"����������\":\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"����������\":\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"������Ѯ\":\r\n");
		js.append("		case \"������Ѯ\":\r\n");
		js.append("		case \"������Ѯ\":\r\n");
		js.append("		case \"����������\":\r\n");
		js.append("		case \"������\":\r\n");
		js.append("		case \"����������\":\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"����������\":\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"����\":\r\n");
		js.append("		case \"�ϼ���\":\r\n");
		js.append("		case \"ȥ��\":\r\n");
		js.append("		case \"ȥ�������ȥ�����\":							\r\n");
		js.append("			if (equals(oldFieldName, hmmCondOp, oldOperatorId))\r\n");
		js.append("				break;\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal2);				\r\n");
		js.append("			HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);\r\n");
		js.append("			\r\n");
		js.append("			break;		\r\n");
		js.append("			\r\n");
		js.append("		case \"ѡ����Ŀ\":			\r\n");
		js.append("			var stValue = SearchText_getValue(oldFieldName + \"_st\");						\r\n");
		js.append("			var stText = SearchText_getText(oldFieldName + \"_st\");			\r\n");
		js.append("			//alert(\"save value:\" + stValue);\r\n");
		js.append("			if (equals(oldFieldName, hmmCondOp, oldOperatorId) && equals(oldFieldName, hmmCondVal1, stValue) && equals(oldFieldName, hmmCondVal2, stText))\r\n");
		js.append("				break;				\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondOp);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal1);\r\n");
		js.append("			clearHashtableItem(oldFieldName, hmmCondVal2);\r\n");
		js.append("			\r\n");
		js.append("			if (stValue != null && trim(stValue) != \"\" && stText != null && trim(stText) != \"\")\r\n");
		js.append("			{					\r\n");
		js.append("				HashtableManager_Add(oldFieldName, oldOperatorId, hmmCondOp);				\r\n");
		js.append("				HashtableManager_Add(oldFieldName, stValue, hmmCondVal1);				\r\n");
		js.append("				HashtableManager_Add(oldFieldName, stText, hmmCondVal2);\r\n");
		js.append("			}				\r\n");
		js.append("			\r\n");
		js.append("			break;\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//ɾ�� Hashtable �е�ĳ��\r\n");
		js.append("function clearHashtableItem(key, hidden)\r\n");
		js.append("{\r\n");
		js.append("	if (HashtableManager_ContainsKey(key, hidden))\r\n");
		js.append("	{\r\n");
		js.append("		HashtableManager_Remove(key, hidden);\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//�ж���������ֵ�Ƿ�ı�\r\n");
		js.append("function equals(fieldName, hidden, tagValue)\r\n");
		js.append("{\r\n");
		js.append("	return HashtableManager_Get(fieldName, hidden) == tagValue;\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//��������õ�������ʼ���ؼ�\r\n");
		js.append("function initControls(fieldName, fieldType)\r\n");
		js.append("{\r\n");
		js.append("	var hmmCondOp = document.getElementById('hmmCondOp');\r\n");
		js.append("	var hmmCondVal1 = document.getElementById('hmmCondVal1');\r\n");
		js.append("	var hmmCondVal2 = document.getElementById('hmmCondVal2');\r\n");
		js.append("	var hmmOpMap = document.getElementById('hmmOpMap');\r\n");
		js.append("	\r\n");
		js.append("	DropDown_setValue('ddlSelect', -1);\r\n");
		js.append("	ddlSelect_onchange();\r\n");
		js.append("	\r\n");
		js.append("	if (HashtableManager_ContainsKey(fieldName, hmmCondOp))\r\n");
		js.append("	{\r\n");
		js.append("		var operatorId = HashtableManager_Get(fieldName, hmmCondOp);\r\n");
		js.append("		var operator = HashtableManager_Get(operatorId, hmmOpMap);\r\n");
		js.append("		\r\n");
		js.append("		DropDown_setValue('ddlSelect', operatorId);\r\n");
		js.append("		ddlSelect_onchange();\r\n");
		js.append("		\r\n");
		js.append("		switch (operator)\r\n");
		js.append("		{\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("				break;\r\n");
		js.append("				\r\n");
		js.append("			case \"��ֵ\":\r\n");
		js.append("			case \"����ֵ\":		\r\n");
		js.append("				break;\r\n");
		js.append("			\r\n");
		js.append("			case \"��\":\r\n");
		js.append("			case \"��\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"С��\":\r\n");
		js.append("			case \"���ڵ���\":\r\n");
		js.append("			case \"С�ڵ���\":\r\n");
		js.append("			case \"��ͷ�ַ�Ϊ\":\r\n");
		js.append("			case \"���ַ�\":\r\n");
		js.append("			case \"������\":\r\n");
		js.append("			case \"������\":\r\n");
		js.append("				switch (fieldType)\r\n");
		js.append("				{\r\n");
		js.append("					case \"currency-amount\":\r\n");
		js.append("					case \"floating-point\":\r\n");
		js.append("					case \"numeric\":						\r\n");
		js.append("						OfbizTextBox_SetValue(\"txtNumberFrom\", HashtableManager_Get(fieldName, hmmCondVal1));\r\n");
		js.append("						break;\r\n");
		js.append("					default:						\r\n");
		js.append("						OfbizTextBox_SetValue(\"txtFrom\", HashtableManager_Get(fieldName, hmmCondVal1));\r\n");
		js.append("						break;\r\n");
		js.append("				}\r\n");
		js.append("				break;\r\n");
		js.append("			\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"�Զ���\":				\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"����������\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"����������\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"������Ѯ\":\r\n");
		js.append("			case \"������Ѯ\":\r\n");
		js.append("			case \"������Ѯ\":\r\n");
		js.append("			case \"����������\":\r\n");
		js.append("			case \"������\":\r\n");
		js.append("			case \"����������\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"����������\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"�ϼ���\":\r\n");
		js.append("			case \"ȥ��\":\r\n");
		js.append("			case \"ȥ�������ȥ�����\":				\r\n");
		js.append("				switch (fieldType)\r\n");
		js.append("				{\r\n");
		js.append("					case \"date-time\":\r\n");
		js.append("					case \"date\":\r\n");
		js.append("					case \"time\":\r\n");
		js.append("						GACalendar_setValue(\"calDataFrom\", HashtableManager_Get(fieldName, hmmCondVal1));\r\n");
		js.append("						GACalendar_setValue(\"calDataTo\", HashtableManager_Get(fieldName, hmmCondVal2));\r\n");
		js.append("						break;\r\n");
		js.append("					\r\n");
		js.append("					case \"currency-amount\":\r\n");
		js.append("					case \"floating-point\":\r\n");
		js.append("					case \"numeric\":\r\n");
		js.append("						OfbizTextBox_SetValue(\"txtNumberFrom\", HashtableManager_Get(fieldName, hmmCondVal1));\r\n");
		js.append("						OfbizTextBox_SetValue(\"txtNumberTo\", HashtableManager_Get(fieldName, hmmCondVal2));\r\n");
		js.append("						break;\r\n");
		js.append("					\r\n");
		js.append("					default:\r\n");
		js.append("						OfbizTextBox_SetValue(\"txtFrom\", HashtableManager_Get(fieldName, hmmCondVal1));\r\n");
		js.append("						OfbizTextBox_SetValue(\"txtTo\", HashtableManager_Get(fieldName, hmmCondVal2));				\r\n");
		js.append("						break;\r\n");
		js.append("				}\r\n");
		js.append("				break;\r\n");
		js.append("				\r\n");
		js.append("			case \"����\":\r\n");
		js.append("				GACalendar_setValue(\"calDataFrom\", HashtableManager_Get(fieldName, hmmCondVal1));\r\n");
		js.append("				break;\r\n");
		js.append("			\r\n");
		js.append("			case \"ѡ����Ŀ\":\r\n");
		js.append("				var hmmSearchText = document.getElementById('hmmSearchText');\r\n");
		js.append("				var divSearchText = document.getElementById('divSearchText');\r\n");
		js.append("\r\n");
		js.append("				SearchText_setValue(fieldName + \"_st\", HashtableManager_Get(fieldName, hmmCondVal1));\r\n");
		js.append("				SearchText_setText(fieldName + \"_st\", HashtableManager_Get(fieldName, hmmCondVal2));\r\n");
		js.append("\r\n");
		js.append("				break;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("//�� Grid �ؼ�����ʾ��������\r\n");
		js.append("function initGrid()\r\n");
		js.append("{\r\n");
		js.append("	onClickEvent = false;\r\n");
		js.append("	var hmmCondOp = document.getElementById('hmmCondOp');\r\n");
		js.append("	var hmmCondVal1 = document.getElementById('hmmCondVal1');\r\n");
		js.append("	var hmmCondVal2 = document.getElementById('hmmCondVal2');\r\n");
		js.append("	var hmmOpMap = document.getElementById('hmmOpMap');\r\n");
		js.append("		\r\n");
		js.append("	var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("	\r\n");
		js.append("	var grid = document.getElementById('condGrid');\r\n");
		js.append("	\r\n");
		js.append("	for (var i = grid.rows.length - 1; i >= 0; i--)	\r\n");
		js.append("	{\r\n");
		js.append("	//grid.deleteRow(i);\r\n");
		js.append("		WebGrid_CustomRowOnclick('condGrid', grid.rows[i]);\r\n");
		js.append("		WebGrid_Delete('condGrid');		\r\n");
		js.append("	}\r\n");
		js.append("	\r\n");
		js.append("	var arr = HashtableManager_GetKeyList(hmmCondOp);\r\n");
		js.append("\r\n");
		js.append("	for (var i = 0; i < arr.length; i++)\r\n");
		js.append("	{		\r\n");
		js.append("		var opId = HashtableManager_Get(arr[i], hmmCondOp);\r\n");
		js.append("		var filterCond = HashtableManager_Get(opId, hmmOpMap);//��������\r\n");
		js.append("		//����ֵ\r\n");
		js.append("		var filterVal  = HashtableManager_Get(arr[i], hmmCondVal1);\r\n");
		js.append("		var filterVal2 = HashtableManager_Get(arr[i], hmmCondVal2);\r\n");
		js.append("		var k;\r\n");
		js.append("		for (k = 0; k < listBox.options.length; k++)\r\n");
		js.append("		{\r\n");
		js.append("			if (arr[i] == listBox.options[k].value)\r\n");
		js.append("				break;\r\n");
		js.append("		}\r\n");
		js.append("		var filterItem;//������Ŀ\r\n");
		js.append("		if (k < listBox.options.length)\r\n");
		js.append("		{\r\n");
		js.append("			filterItem = listBox.options[k].text;\r\n");
		js.append("		}\r\n");
		js.append("		\r\n");
		js.append("		WebGrid_addNewRow(grid, null, i);		\r\n");
		js.append("		WebGrid_insertNewData(grid, i);\r\n");
		js.append("		\r\n");
		js.append("		\r\n");
		js.append("		\r\n");
		js.append("		switch (filterCond)\r\n");
		js.append("		{		\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"����\":\r\n");
		js.append("			case \"С��\":\r\n");
		js.append("			case \"���ڵ���\":\r\n");
		js.append("			case \"С�ڵ���\":\r\n");
		js.append("			case \"��ͷ�ַ�Ϊ\":\r\n");
		js.append("			case \"���ַ�\":\r\n");
		js.append("			case \"������\":\r\n");
		js.append("			case \"������\":			\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterItem', filterItem);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterCond', filterCond + \"  \" + filterVal);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterItemId', arr[i]);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterCondId', opId);\r\n");
		js.append("				break;\r\n");
		js.append("				\r\n");
		js.append("			case \"����\":		\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterItem', filterItem);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterCond', filterCond + \" (\" + filterVal + \",\" + filterVal2 + \")\");\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterItemId', arr[i]);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterCondId', opId);\r\n");
		js.append("				break;\r\n");
		js.append("				\r\n");
		js.append("			case \"ѡ����Ŀ\":\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterItem', filterItem);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterCond', filterVal2);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterItemId', arr[i]);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterCondId', opId);			\r\n");
		js.append("				break;\r\n");
		js.append("				\r\n");
		js.append("			default:				\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterItem', filterItem);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterCond', filterCond);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterItemId', arr[i]);\r\n");
		js.append("				WebGrid_SetGridCellText(\"condGrid\", i, 'filterCondId', opId);				\r\n");
		js.append("				break;			\r\n");
		js.append("		}			\r\n");
		js.append("	}\r\n");
		js.append("	\r\n");
		js.append("	for (var i = 0; i < grid.rows.length; i++)\r\n");
		js.append("	{\r\n");
		js.append("		var itemId = WebGrid_GetGridCellText('condGrid', i,'filterItemId');		\r\n");
		js.append("		if (itemId == listBox.options[listBox.selectedIndex].value)\r\n");
		js.append("		{\r\n");
		js.append("			WebGrid_CustomRowOnclick('condGrid', grid.rows[i]);\r\n");
		js.append("			break;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("\r\n");
		js.append("	onClickEvent = true;		\r\n");
		js.append("}\r\n");
		js.append("function condGridEditRow_onchange()\r\n");
		js.append("{\r\n");
		js.append("	if (!onClickEvent) return false;\r\n");
		js.append("	\r\n");
		js.append("	var grid = document.getElementById('condGrid');\r\n");
		js.append("	var row = WebGrid_getExistEditRow(grid);	\r\n");
		js.append("	\r\n");
		js.append("	var condId = WebGrid_GetGridCellText('condGrid', row.rowIndex,'filterCondId');\r\n");
		js.append("	var itemId = WebGrid_GetGridCellText('condGrid', row.rowIndex,'filterItemId');\r\n");
		js.append("	\r\n");
		js.append("	var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("	for (var i = 0; i < listBox.options.length; i++)\r\n");
		js.append("	{\r\n");
		js.append("		if (listBox.options[i].value == itemId)\r\n");
		js.append("		{\r\n");
		js.append("			listBox.selectedIndex = i;\r\n");
		js.append("			isGridOnChanged = true;\r\n");
		js.append("			lstFilterField_onchange();			\r\n");
		js.append("			isGridOnChanged = false;\r\n");
		js.append("			break;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("//���\r\n");
		js.append("function btnClear_onclick()\r\n");
		js.append("{\r\n");
		js.append("	var hmmCondOp = document.getElementById('hmmCondOp');\r\n");
		js.append("	var hmmCondVal1 = document.getElementById('hmmCondVal1');\r\n");
		js.append("	var hmmCondVal2 = document.getElementById('hmmCondVal2');\r\n");
		js.append("	HashtableManager_RemoveAll(hmmCondOp);\r\n");
		js.append("	HashtableManager_RemoveAll(hmmCondVal1);\r\n");
		js.append("	HashtableManager_RemoveAll(hmmCondVal2);\r\n");
		js.append("	DropDown_setValue('ddlSelect', -1);\r\n");
		js.append("	ddlSelect_onchange();\r\n");
		js.append("	initGrid();\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("function searchTextOnChanged()\r\n");
		js.append("{\r\n");
		js.append("	\r\n");
		js.append("	var stText = _SearchText_getTextBox(oldFieldName + \"_st\");\r\n");
		js.append("	var stValue = SearchText_getValue(oldFieldName + \"_st\");\r\n");
		js.append("	if ((stText.value == null || trim(stText.value) == \"\"))\r\n");
		js.append("	{		\r\n");
		js.append("		isSTOnChange = false;\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	\r\n");
		js.append("	if (stValue != null && trim(stValue) != \"\")\r\n");
		js.append("	{\r\n");
		js.append("		isSTOnChange = false;\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	SearchText_setText(oldFieldName + \"_st\", \"\");\r\n");
		js.append("	var listBox = document.getElementById('lstFilterField');\r\n");
		js.append("	selectedIndex = listBox.selectedIndex;	\r\n");
		js.append("	isSTOnChange = true;\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("function calendar_onchange()\r\n");
		js.append("{\r\n");
		js.append("	var fromDate = GACalendar_getValue(\"calDataFrom\");\r\n");
		js.append("	var toDate = GACalendar_getValue(\"calDataTo\");\r\n");
		js.append("	if (fromDate == null || trim(fromDate) == \"\"){\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	if (toDate == null || trim(toDate) == \"\"){\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	\r\n");
		js.append("	if (toDate < fromDate){\r\n");
		js.append("		GACalendar_setValue(\"calDataTo\", fromDate);\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("\r\n");
		js.append("\r\n");
		js.append("");
		jstool.js=js;
		return jstool.getComponentJS();
	}
}
