package com.born.insurance.webui.control;

public class MenuJsForIE {
/**
 * <p>Description: js����д��MenuJS.js�ļ�����ø��ļ�·��������</p>
 * <P><B>����ƹ�˵�ʱ�˵��仯</B><P>
 * <B>function:vpsnm_itemMsOver(item, subGroup, expandDirection, horAdj, verAdj, expandDelay, effect) </B></p>
 *    param item �˵���
 *    param subGroup �Ӳ˵���
 *    param expandDirection �Ӳ˵���Ը��˵�����չ����
 *    param horAdj ˮƽλ��
 *    param verAdj ��ֱλ��
 *    param expandDelay �Ӳ˵���չ��ʱ
 *    param effect �˾���ֵ
 * <P><B>����Ƴ��˵�ʱ�˵��仯</B></P>
 * <B>function:vpsnm_itemMsOut(item, group, subGroup, expandDelay, effect)</B><P>
 *    param item �˵���
 *    param group ��ǰ�˵���
 *    param subGroup �Ӳ˵���
 *    param expandDelay �Ӳ˵���չ��ʱ
 *    param effect �˾���ֵ
 * <P><B>����ƹ�˵���ʱ�˵��仯</B></P>
 * <B>function:vpsnm_groupMsOver(group)</B><P>
 *    param group ��ǰ�˵���
 * <P><B>����ƹ�˵���ʱ�˵��仯</B></P>
 * <B>function:vpsnm_groupMsOut(group, parentItem, parentGroup, expandDelay, effect)</B><P>
 *    param group ��ǰ�˵���
 *    param parentItem ���˵���
 *    param parentGroup ���˵���
 *    param expandDelay �Ӳ˵���չ��ʱ
 *    param effect �˾���ֵ
 */
  public static String getMenuJs(){
    StringBuffer js = new StringBuffer();
    JSTool jsTools = new JSTool("MenuJS.js");
	js.append("function vpsnm_itemMsOver(item, subGroup, expandDirection, horAdj, verAdj, expandDelay, effect) \r\n");
	js.append("{\r\n");
	js.append("  var newLeft = 0; \r\n");
	js.append("  var newTop = 0; \r\n");
	js.append("  var oItem = document.all[item]; \r\n");
	js.append("  var oSubGroup = document.all[subGroup]; \r\n");
	js.append("\r\n");
	js.append("    \r\n");
	js.append("  if (vpsnm_curItem != item)\r\n");
	js.append("  {\r\n");
	js.append("    vpsnm_curItem = item; \r\n");
	js.append("  \r\n");
	js.append("    switch (expandDirection)\r\n");
	js.append("    {\r\n");
	js.append("      case 'belowleft': \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem); \r\n");
	js.append("        if (newLeft + oSubGroup.offsetWidth > window.document.body.clientWidth)\r\n");
	js.append("          newLeft = vpsnm_pageX(oItem) + oItem.offsetWidth - oSubGroup.offsetWidth; \r\n");
	js.append("        newTop = vpsnm_pageY(oItem) + oItem.offsetHeight; \r\n");
	js.append("        break; \r\n");
	js.append("      case 'belowright': \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem) + oItem.offsetWidth - oSubGroup.offsetWidth; \r\n");
	js.append("        newTop =  vpsnm_pageY(oItem) + oItem.offsetHeight; \r\n");
	js.append("        break; \r\n");
	js.append("      case 'aboveleft': \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem); \r\n");
	js.append("        newTop =  vpsnm_pageY(oItem) - oSubGroup.offsetHeight; \r\n");
	js.append("        break; \r\n");
	js.append("      case 'aboveright': \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem) + oItem.offsetWidth - oSubGroup.offsetWidth; \r\n");
	js.append("        newTop =  vpsnm_pageY(oItem) - oSubGroup.offsetHeight; \r\n");
	js.append("        break; \r\n");
	js.append("      case 'rightdown': \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem) + oItem.offsetWidth; \r\n");
	js.append("        if (newLeft + oSubGroup.offsetWidth > window.document.body.clientWidth)\r\n");
	js.append("          newLeft = vpsnm_pageX(oItem) - oSubGroup.offsetWidth; \r\n");
	js.append("        newTop = vpsnm_pageY(oItem); \r\n");
	js.append("        if (newTop + oSubGroup.offsetHeight > window.document.body.clientHeight)\r\n");
	js.append("          newTop = vpsnm_pageY(oItem) - oSubGroup.offsetHeight + oItem.offsetHeight; \r\n");
	js.append("        break; \r\n");
	js.append("      case 'rightup': \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem) + oItem.offsetWidth; \r\n");
	js.append("        newTop = vpsnm_pageY(oItem) - oSubGroup.offsetHeight + oItem.offsetHeight; \r\n");
	js.append("        break; \r\n");
	js.append("      case 'leftdown': \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem) - oSubGroup.offsetWidth; \r\n");
	js.append("        newTop = vpsnm_pageY(oItem); \r\n");
	js.append("        break; \r\n");
	js.append("      case 'leftup': \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem) - oSubGroup.offsetWidth; \r\n");
	js.append("        newTop = vpsnm_pageY(oItem) - oSubGroup.offsetHeight + oItem.offsetHeight; \r\n");
	js.append("        break; \r\n");
	js.append("      default: \r\n");
	js.append("        newLeft = vpsnm_pageX(oItem) + oItem.offsetWidth; \r\n");
	js.append("        newTop = vpsnm_pageY(oItem); \r\n");
	js.append("        break; \r\n");
	js.append("    }  \r\n");
	js.append("    newLeft += horAdj; \r\n");
	js.append("    newTop += verAdj; \r\n");
	js.append("    if (newTop < 0) newTop = 0; \r\n");
	js.append("    if (newLeft < 0) newLeft = 0; \r\n");
	js.append("    \r\n");
	js.append("    oSubGroup.style.left = newLeft + 'px'; \r\n");
	js.append("    oSubGroup.style.top = newTop + 'px'; \r\n");
	js.append("\r\n");
	js.append("    vpsnm_startExpand(subGroup, expandDelay, effect); \r\n");
	js.append("  }\r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_itemMsOut(item, group, subGroup, expandDelay, effect)\r\n");
	js.append("{\r\n");
	js.append("  if ((!(vpsnm_isMouseOnObject(item))) && subGroup) \r\n");
	js.append("    if (!(vpsnm_isMouseOnObject(subGroup)))\r\n");
	js.append("    {\r\n");
	js.append("      vpsnm_curItem = ''; \r\n");
	js.append("      vpsnm_startCollapse(subGroup, expandDelay, effect);\r\n");
	js.append("    }  \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_groupMsOver(group)\r\n");
	js.append("{\r\n");
	js.append("  if (vpsnm_collapsingAll) vpsnm_restoredGroup = group; \r\n");
	js.append("\r\n");
	js.append("  if (vpsnm_collapsingGroup == group) \r\n");
	js.append("  {\r\n");
	js.append("    vpsnm_stopCollapse(); \r\n");
	js.append("    vpsnm_stopExpand(); \r\n");
	js.append("  }\r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_groupMsOut(group, parentItem, parentGroup, expandDelay, effect)\r\n");
	js.append("{ \r\n");
	js.append("  if (!(vpsnm_isMouseOnObject(group)))\r\n");
	js.append("  {\r\n");
	js.append("    vpsnm_curItem = ''; \r\n");
	js.append("\r\n");
	js.append("    var subGroup = vpsnm_expandedObjects[vpsnm_expandCount]; \r\n");
	js.append("    if (subGroup == group) subGroup = null; \r\n");
	js.append("\r\n");
	js.append("    if (parentItem == null && parentGroup == null && !(vpsnm_isMouseOnObject(group)))\r\n");
	js.append("      vpsnm_startCollapseAll(expandDelay, effect);     \r\n");
	js.append("    else if (vpsnm_isMouseOnObject(group) || vpsnm_isMouseOnObject(subGroup) || vpsnm_isMouseOnObject(parentItem))\r\n");
	js.append("      ; // do nothing \r\n");
	js.append("    else if (vpsnm_isMouseOnObject(parentGroup))\r\n");
	js.append("    {\r\n");
	js.append("      vpsnm_startCollapse(group, expandDelay, effect); \r\n");
	js.append("      vpsnm_startCollapse(subGroup, expandDelay, effect); \r\n");
	js.append("    }\r\n");
	js.append("    else\r\n");
	js.append("      vpsnm_startCollapseAll(expandDelay, effect);     \r\n");
	js.append("  }\r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_startExpand(group, interval, effect)\r\n");
	js.append("{\r\n");
	js.append("  if (group == vpsnm_collapsingGroup) vpsnm_stopCollapse(); \r\n");
	js.append("  if (group != vpsnm_expandingGroup) vpsnm_stopExpand();  \r\n");
	js.append("  \r\n");
	js.append("  vpsnm_restoredGroup = group; \r\n");
	js.append("  \r\n");
	js.append("  vpsnm_expandingGroup = group; \r\n");
	js.append("  if (group) group += '.id'; \r\n");
	js.append("  if (effect) effect = \"'\" + effect + \"'\";  \r\n");
	js.append("  vpsnm_expandTimerID = setTimeout('vpsnm_expand(' + group + ', ' + effect + ')', interval); \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_startCollapse(group, interval, effect)\r\n");
	js.append("{\r\n");
	js.append("  if (group == vpsnm_expandingGroup) vpsnm_stopExpand(); \r\n");
	js.append("\r\n");
	js.append("  if (group) \r\n");
	js.append("    if (document.all[group].style.visibility == 'visible') \r\n");
	js.append("    {\r\n");
	js.append("      vpsnm_collapsingGroup = group; \r\n");
	js.append("      group += '.id'; \r\n");
	js.append("      if (effect) effect = \"'\" + effect + \"'\";  \r\n");
	js.append("      vpsnm_collapseTimerID = setTimeout('vpsnm_collapse(' + group + ', ' + effect + ')', interval); \r\n");
	js.append("    }  \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_startCollapseAll(interval, effect)\r\n");
	js.append("{\r\n");
	js.append("  vpsnm_stopCollapse(); \r\n");
	js.append("  vpsnm_stopExpand(); \r\n");
	js.append("  vpsnm_stopCollapseAll(); \r\n");
	js.append("\r\n");
	js.append("  vpsnm_collapsingAll = true; \r\n");
	js.append("  if (effect) \r\n");
	js.append("  {\r\n");
	js.append("    effect = \"'\" + effect + \"'\";  \r\n");
	js.append("    vpsnm_collapseAllTimerID = setTimeout('vpsnm_collapseAll(' + effect + ')', interval); \r\n");
	js.append("  }\r\n");
	js.append("  else\r\n");
	js.append("    vpsnm_collapseAllTimerID = setTimeout('vpsnm_collapseAll(null)', interval); \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_stopExpand()\r\n");
	js.append("{\r\n");
	js.append("  clearTimeout(vpsnm_expandTimerID); \r\n");
	js.append("  vpsnm_expandingGroup = ''; \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_stopCollapse()\r\n");
	js.append("{\r\n");
	js.append("  clearTimeout(vpsnm_collapseTimerID); \r\n");
	js.append("  vpsnm_collapsingGroup = ''; \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_stopCollapseAll()\r\n");
	js.append("{\r\n");
	js.append("  clearTimeout(vpsnm_collapseAllTimerID); \r\n");
	js.append("  vpsnm_restoredGroup = '';\r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_expand(group, effect)\r\n");
	js.append("{\r\n");
	js.append("  if (document.all[group].style.visibility != 'visible')\r\n");
	js.append("  {\r\n");
	js.append("    vpsnm_hideSelectElements(group); \r\n");
	js.append("    if (effect) \r\n");
	js.append("    {\r\n");
	js.append("      document.all[group].style.filter = effect; \r\n");
	js.append("      document.all[group].filters[0].Apply(); \r\n");
	js.append("    }  \r\n");
	js.append("    document.all[group].style.visibility = 'visible'; \r\n");
	js.append("    vpsnm_makeDropShadow(group); \r\n");
	js.append("    if (effect) document.all[group].filters[0].Play(); \r\n");
	js.append("    vpsnm_expandCount++; \r\n");
	js.append("    vpsnm_expandedObjects[vpsnm_expandCount] = group; \r\n");
	js.append("  }  \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_collapse(group, effect)\r\n");
	js.append("{\r\n");
	js.append("  if (group) \r\n");
	js.append("  {\r\n");
	js.append("    if (document.all[group].style.visibility != 'hidden')\r\n");
	js.append("    {\r\n");
	js.append("      if (effect)\r\n");
	js.append("      {\r\n");
	js.append("        document.all[group].style.filter = effect; \r\n");
	js.append("        document.all[group].filters[0].Apply(); \r\n");
	js.append("      }\r\n");
	js.append("      document.all[group].style.visibility = 'hidden';     \r\n");
	js.append("      if (effect) document.all[group].filters[0].Play(); \r\n");
	js.append("      vpsnm_expandCount--; \r\n");
	js.append("      vpsnm_clearDropShadow(group); \r\n");
	js.append("    }      \r\n");
	js.append("  }\r\n");
	js.append("  if (!(vpsnm_contextUp) && vpsnm_expandCount == 0) \r\n");
	js.append("    vpsnm_restoreSelectElements(); \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_collapseAll(effect)\r\n");
	js.append("{\r\n");
	js.append("  for (var i = vpsnm_expandCount; i >= 1; i--)\r\n");
	js.append("  {\r\n");
	js.append("    if (vpsnm_expandedObjects[i] == vpsnm_restoredGroup) break; \r\n");
	js.append("\r\n");
	js.append("    if (effect)\r\n");
	js.append("    {\r\n");
	js.append("      document.all[vpsnm_expandedObjects[i]].style.filter = effect; \r\n");
	js.append("      document.all[vpsnm_expandedObjects[i]].filters[0].Apply(); \r\n");
	js.append("    }\r\n");
	js.append("    document.all[vpsnm_expandedObjects[i]].style.visibility = 'hidden';\r\n");
	js.append("    vpsnm_clearDropShadow(vpsnm_expandedObjects[i]); \r\n");
	js.append("    if (effect) document.all[vpsnm_expandedObjects[i]].filters[0].Play(); \r\n");
	js.append("  }\r\n");
	js.append("\r\n");
	js.append("  vpsnm_collapsingAll = false; \r\n");
	js.append("  vpsnm_expandCount = i;\r\n");
	js.append("  vpsnm_restoredGroup = ''; \r\n");
	js.append("  if (!(vpsnm_contextUp) && vpsnm_expandCount == 0) \r\n");
	js.append("    vpsnm_restoreSelectElements(); \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_hideAllGroups()\r\n");
	js.append("{\r\n");
	js.append("  vpsnm_curItem = ''; \r\n");
	js.append("  vpsnm_restoredGroup = ''; \r\n");
	js.append("  vpsnm_collapseAll(null); \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_updateCell(Element, NewClassName, LeftImage, LeftImageSrc, RightImage, RightImageSrc, direction)\r\n");
	js.append("{  \r\n");
	js.append("  if (direction == 'out' && vpsnm_isMouseOnObject(Element))    \r\n");
	js.append("    ;   \r\n");
	js.append("  else  \r\n");
	js.append("  {    \r\n");
	js.append("    if (Element != null & NewClassName != '') document.all[Element].className = NewClassName;\r\n");
	js.append("    if (LeftImage != null  && LeftImageSrc != '') document.images[LeftImage].src = LeftImageSrc;     \r\n");
	js.append("    if (RightImage != null && RightImageSrc != '') document.images[RightImage].src = RightImageSrc;   \r\n");
	js.append("  }\r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_isMouseOnObject(objName)\r\n");
	js.append("{\r\n");
	js.append("  if (objName)\r\n");
	js.append("  {\r\n");
	js.append("    var objLeft = vpsnm_pageX(document.all[objName]) - window.document.body.scrollLeft + 1; \r\n");
	js.append("    var objTop = vpsnm_pageY(document.all[objName]) - window.document.body.scrollTop + 1; \r\n");
	js.append("    var objRight = objLeft + document.all[objName].offsetWidth - 1; \r\n");
	js.append("    var objBottom = objTop + document.all[objName].offsetHeight - 1;\r\n");
	js.append("  \r\n");
	js.append("    if ((event.x > objLeft) && (event.x < objRight) && \r\n");
	js.append("        (event.y > objTop) && (event.y < objBottom))\r\n");
	js.append("      return true; \r\n");
	js.append("    else  \r\n");
	js.append("      return false; \r\n");
	js.append("  }\r\n");
	js.append("  else\r\n");
	js.append("    return false; \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_pageX(element)\r\n");
	js.append("{\r\n");
	js.append("  var x = 0;\r\n");
	js.append("  do \r\n");
	js.append("  {\r\n");
	js.append("    if (element.style.position == 'absolute') \r\n");
	js.append("    {\r\n");
	js.append("      return x + element.offsetLeft; \r\n");
	js.append("    }\r\n");
	js.append("    else\r\n");
	js.append("    {\r\n");
	js.append("      x += element.offsetLeft;\r\n");
	js.append("      if (element.offsetParent) \r\n");
	js.append("        if (element.offsetParent.tagName == 'TABLE') \r\n");
	js.append("          if (parseInt(element.offsetParent.border) > 0)\r\n");
	js.append("          {\r\n");
	js.append("            x += 1; \r\n");
	js.append("          }\r\n");
	js.append("    }\r\n");
	js.append("  }\r\n");
	js.append("  while ((element = element.offsetParent));\r\n");
	js.append("  return x; \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_pageY(element)\r\n");
	js.append("{\r\n");
	js.append("  var y = 0;\r\n");
	js.append("  do \r\n");
	js.append("  {\r\n");
	js.append("    if (element.style.position == 'absolute') \r\n");
	js.append("    {\r\n");
	js.append("      return y + element.offsetTop; \r\n");
	js.append("    }\r\n");
	js.append("    else\r\n");
	js.append("    {\r\n");
	js.append("      y += element.offsetTop;\r\n");
	js.append("      if (element.offsetParent) \r\n");
	js.append("        if (element.offsetParent.tagName == 'TABLE') \r\n");
	js.append("          if (parseInt(element.offsetParent.border) > 0)\r\n");
	js.append("          {\r\n");
	js.append("            y += 1; \r\n");
	js.append("          }\r\n");
	js.append("    }\r\n");
	js.append("  }\r\n");
	js.append("  while ((element = element.offsetParent));\r\n");
	js.append("  return y; \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_hideSelectElements(group)\r\n");
	js.append("{\r\n");
	js.append("  if (document.getElementsByTagName) \r\n");
	js.append("  {\r\n");
	js.append("    var arrElements = document.getElementsByTagName('select'); \r\n");
	js.append("    if (vpsnm_hideSelectElems) \r\n");
	js.append("    {\r\n");
	js.append("      for (var i = 0; i < arrElements.length; i++) \r\n");
	js.append("        if (vpsnm_objectsOverlapping(document.all[group], arrElements[i]))\r\n");
	js.append("          arrElements[i].style.visibility = 'hidden';          \r\n");
	js.append("    }\r\n");
	js.append("  }\r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_restoreSelectElements()\r\n");
	js.append("{\r\n");
	js.append("  if (document.getElementsByTagName) \r\n");
	js.append("  {\r\n");
	js.append("    var arrElements = document.getElementsByTagName('select'); \r\n");
	js.append("    if (vpsnm_hideSelectElems) \r\n");
	js.append("      for (var i = 0; i < arrElements.length; i++) \r\n");
	js.append("        arrElements[i].style.visibility = 'visible'; \r\n");
	js.append("  }\r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_objectsOverlapping(obj1, obj2)\r\n");
	js.append("{\r\n");
	js.append("  var result = true; \r\n");
	js.append("  var obj1Left = vpsnm_pageX(obj1) - window.document.body.scrollLeft; \r\n");
	js.append("  var obj1Top = vpsnm_pageY(obj1) - window.document.body.scrollTop; \r\n");
	js.append("  var obj1Right = obj1Left + obj1.offsetWidth; \r\n");
	js.append("  var obj1Bottom = obj1Top + obj1.offsetHeight;\r\n");
	js.append("  var obj2Left = vpsnm_pageX(obj2) - window.document.body.scrollLeft; \r\n");
	js.append("  var obj2Top = vpsnm_pageY(obj2) - window.document.body.scrollTop; \r\n");
	js.append("  var obj2Right = obj2Left + obj2.offsetWidth; \r\n");
	js.append("  var obj2Bottom = obj2Top + obj2.offsetHeight;\r\n");
	js.append("  \r\n");
	js.append("  if (obj1Right <= obj2Left || obj1Bottom <= obj2Top || \r\n");
	js.append("      obj1Left >= obj2Right || obj1Top >= obj2Bottom) \r\n");
	js.append("    result = false; \r\n");
	js.append("  return result; \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_makeDropShadow(objName)\r\n");
	js.append("{\r\n");
	js.append("  if (vpsnm_shadowEnabled) \r\n");
	js.append("  {\r\n");
	js.append("    vpsnm_shadows[objName] = new Array(); \r\n");
	js.append("	  for (var i = vpsnm_shadowOffest; i > 0; i--)\r\n");
	js.append("	  {\r\n");
	js.append("	    var obj = document.all[objName]; \r\n");
	js.append("		  var rect = document.createElement('div');\r\n");
	js.append("		  var rs = rect.style\r\n");
	js.append("		  rs.position = 'absolute';\r\n");
	js.append("		  rs.left = (obj.style.posLeft + i) + 'px';\r\n");
	js.append("		  rs.top = (obj.style.posTop + i) + 'px';\r\n");
	js.append("		  rs.width = obj.offsetWidth + 'px';\r\n");
	js.append("		  rs.height = obj.offsetHeight + 'px';\r\n");
	js.append("		  rs.zIndex = obj.style.zIndex - i;\r\n");
	js.append("		  rs.backgroundColor = vpsnm_shadowColor;\r\n");
	js.append("		  var opacity = 1 - i / (i + 1);\r\n");
	js.append("		  rs.filter = 'alpha(opacity=' + (100 * opacity) + ')';\r\n");
	js.append("		  obj.insertAdjacentElement('afterEnd', rect);\r\n");
	js.append("		  vpsnm_shadows[objName][vpsnm_shadows[objName].length] = rect; \r\n");
	js.append("	  }\r\n");
	js.append("	}\r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("\r\n");
	js.append("function vpsnm_clearDropShadow(objName)\r\n");
	js.append("{\r\n");
	js.append("  if (vpsnm_shadowEnabled) \r\n");
	js.append("  {\r\n");
	js.append("    var curShadow; \r\n");
	js.append("    for (var i = 0; i < vpsnm_shadows[objName].length; i++)\r\n");
	js.append("    {\r\n");
	js.append("      curShadow = vpsnm_shadows[objName][i]; \r\n");
	js.append("      curShadow.style.filter = 'alpha(opacity=0)'; \r\n");
	js.append("      curShadow.removeNode(true); \r\n");
	js.append("    }\r\n");
	js.append("  }  \r\n");
	js.append("}\r\n");
	js.append("\r\n");
	js.append("function vpsnm_positionMenu(menu, alignment, offsetX, offsetY)\r\n");
	js.append("{\r\n");
	js.append("  var scrlLeft = 0; \r\n");
	js.append("  var scrlTop = 0;\r\n");
	js.append("  var clientW = window.document.body.clientWidth; \r\n");
	js.append("  var clientH = window.document.body.clientHeight; \r\n");
	js.append("  var menuWidth = menu.offsetWidth; \r\n");
	js.append("  var menuHeight = menu.offsetHeight; \r\n");
	js.append("  var newLeft = 0; \r\n");
	js.append("  var newTop = 0; \r\n");
	js.append("\r\n");
	js.append("  switch (alignment)\r\n");
	js.append("  {\r\n");
	js.append("    case 'topleft': \r\n");
	js.append("      newLeft = scrlLeft;\r\n");
	js.append("      newTop = scrlTop;\r\n");
	js.append("      break; \r\n");
	js.append("    case 'topmiddle': \r\n");
	js.append("      newLeft = (clientW - menuWidth) / 2 + scrlLeft;\r\n");
	js.append("      newTop = scrlTop;\r\n");
	js.append("      break; \r\n");
	js.append("    case 'topright': \r\n");
	js.append("      newLeft = clientW + scrlLeft - menuWidth;\r\n");
	js.append("      newTop = scrlTop;\r\n");
	js.append("      break; \r\n");
	js.append("    case 'bottomleft': \r\n");
	js.append("      newLeft = scrlLeft;\r\n");
	js.append("      newTop = clientH + scrlTop - menuHeight;\r\n");
	js.append("      break; \r\n");
	js.append("    case 'bottommiddle': \r\n");
	js.append("      newLeft = (clientW - menuWidth) / 2 + scrlLeft;\r\n");
	js.append("      newTop = clientH + scrlTop - menuHeight;\r\n");
	js.append("      break; \r\n");
	js.append("    case 'bottomright': \r\n");
	js.append("      newLeft = clientW + scrlLeft - menuWidth;\r\n");
	js.append("      newTop = clientH + scrlTop - menuHeight;\r\n");
	js.append("      break; \r\n");
	js.append("    default: \r\n");
	js.append("      newLeft = clientW + scrlLeft;\r\n");
	js.append("      newTop = clientH + scrlTop;\r\n");
	js.append("      break; \r\n");
	js.append("  }    \r\n");
	js.append("  \r\n");
	js.append("  newLeft += offsetX; \r\n");
	js.append("  newTop += offsetY; \r\n");
	js.append("  menu.style.left = newLeft; \r\n");
	js.append("  menu.style.top = newTop; \r\n");
	js.append("}\r\n");
	js.append("								\r\n");
	js.append("var vpsnm_expandedObjects = new Array(); \r\n");
	js.append("var vpsnm_expandCount = 0;               \r\n");
	js.append("\r\n");
	js.append("var vpsnm_expandTimerID = 0;         \r\n");
	js.append("var vpsnm_collapseTimerID = 0;       \r\n");
	js.append("var vpsnm_collapseAllTimerID = 0;    \r\n");
	js.append("var vpsnm_expandingGroup = '';       \r\n");
	js.append("var vpsnm_collapsingGroup = '';      \r\n");
	js.append("var vpsnm_restoredGroup = '';        \r\n");
	js.append("var vpsnm_collapsingAll = false;     \r\n");
	js.append("var vpsnm_curItem = '';              \r\n");
	js.append("var vpsnm_hideSelectElems = true;    \r\n");
	js.append("var vpsnm_shadows = new Array();     \r\n");
	js.append("var vpsnm_shadowEnabled = false;     \r\n");
	js.append("var vpsnm_shadowColor = '#777777';   \r\n");
	js.append("var vpsnm_shadowOffest = 4;          \r\n");
	js.append("var vpsnm_contextUp = false;         ");

    jsTools.js = js;
    return jsTools.getComponentJS();
  }

}