package com.born.insurance.webui.control;
/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */
public class WebGridCommonJS
{
	public WebGridCommonJS()
	{
	}
	public static String getWebGridCommonJS()
	{
		JSTool jstool = new JSTool("WebGridCommonJS.js");
		java.lang.StringBuffer js = jstool.js;
		if (!jstool.util.isUpdateJsEveryTime())
		{
			return jstool.getComponentJS();
		}
		js.append("function WebGrid_Confirm(gridId)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("\r\n");
		js.append("		WebGrid_DefaultConfirm(gridId);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_CustomConfirm(gridId);\r\n");
		js.append("	}\r\n");
		js.append("	WebGrid_setErrorEditorFocus(table);\r\n");
		js.append("}\r\n");
		js.append("function  WebGrid_Insert(gridId)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_DefaultInsert(gridId);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_CustomInsert(gridId);\r\n");
		js.append("	}\r\n");
		js.append("	WebGrid_setErrorEditorFocus(table);\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_Delete(gridId)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_DefaultDelete(gridId);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_CustomDelete(gridId);\r\n");
		js.append("	}\r\n");
		js.append("	WebGrid_refleshAutoAcsend(gridId);\r\n");
		js.append("\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_Cancel(gridId)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_DefaultCancel(gridId);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_CustomCancel(gridId);\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_Up(gridId)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var readOnly=table.getAttribute(\"WebGridReadOnly\");\r\n");
		js.append("	var editRow=WebGrid_getExistEditRow(table);\r\n");
		js.append("	if(editRow!=null)\r\n");
		js.append("	{\r\n");
		js.append("		if(readOnly!=\"true\")\r\n");
		js.append("		{\r\n");
		js.append("			if(editRow.rowIndex>0)\r\n");
		js.append("			{\r\n");
		js.append("				WebGrid_RowOnclick(gridId,table.rows[editRow.rowIndex-1]);\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			if(editRow.rowIndex>0)\r\n");
		js.append("			{\r\n");
		js.append("				ListGrid_RowOnSelect(table.rows[editRow.rowIndex-1],gridId);\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_Down(gridId)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var editRow=WebGrid_getExistEditRow(table);\r\n");
		js.append("	var readOnly=table.getAttribute(\"WebGridReadOnly\");\r\n");
		js.append("	if(editRow!=null)\r\n");
		js.append("	{\r\n");
		js.append("		if(readOnly!=\"true\")\r\n");
		js.append("		{\r\n");
		js.append("			WebGrid_Confirm(gridId);\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			if(editRow.rowIndex<table.rows.length-1)\r\n");
		js.append("			{\r\n");
		js.append("				ListGrid_RowOnSelect(table.rows[editRow+1],gridId);\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_setErrorEditorFocus(table)\r\n");
		js.append("{\r\n");
		js.append("	if(table.getAttribute(\"errorEditorIndex\")!=null)\r\n");
		js.append("	{\r\n");
		js.append("		var editorIndex=table.getAttribute(\"errorEditorIndex\");\r\n");
		js.append("		var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("		table.removeAttribute(\"errorEditorIndex\");\r\n");
		js.append("		WebGrid_setFocus(table,Editors[editorIndex]);\r\n");
		js.append("\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_getColumnText(gridId,index)\r\n");
		js.append("{\r\n");
		js.append("	return document.getElementById(gridId+\"_Text_\"+index+\"_hidden\");\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_getColumnValue(gridId,index)\r\n");
		js.append("{\r\n");
		js.append("	return document.getElementById(gridId+\"_Value_\"+index+\"_hidden\");\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_RowOnclick(gridId,rowObj)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_DefaultRowOnclick(gridId,rowObj);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_CustomRowOnclick(gridId,rowObj);\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("//ͨ����ֶβ��ҿɼ�����ʵλ��\r\n");
		js.append("function WebGrid_getColumnRealIndex(gridId,dataField)\r\n");
		js.append("{\r\n");
		js.append("	var index=WebGrid_getColumnIndex(gridId,dataField)\r\n");
		js.append("	return WebGrid_getColumnRealIndexByEditorIndex(gridId,index);\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_getColumnRealIndexByEditorIndex(gridId,index)\r\n");
		js.append("{\r\n");
		js.append("	var _Store_ColumnInfo=document.getElementById(gridId+\"_Store_ColumnInfo_hidden\");\r\n");
		js.append("	var count=ListManager_Size(_Store_ColumnInfo);\r\n");
		js.append("	var realIndex=0;\r\n");
		js.append("	for(var i=0;i<count;i++)\r\n");
		js.append("	{\r\n");
		js.append("		var hiddenIndex=ListManager_Get(i,_Store_ColumnInfo);\r\n");
		js.append("		if(hiddenIndex==\"\")\r\n");
		js.append("		{\r\n");
		js.append("			break;\r\n");
		js.append("        }\r\n");
		js.append("		hiddenIndex=parseInt(hiddenIndex);\r\n");
		js.append("		if(hiddenIndex<index)\r\n");
		js.append("		{\r\n");
		js.append("			realIndex++;\r\n");
		js.append("		}\r\n");
		js.append("		else if(hiddenIndex==index)\r\n");
		js.append("		{\r\n");
		js.append("			return -1;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			break;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	realIndex=index-realIndex;\r\n");
		js.append("	return realIndex;\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_getEditorIndexByColumnRealIndex(gridId,index)\r\n");
		js.append("{\r\n");
		js.append("	var _Store_ColumnInfo=document.getElementById(gridId+\"_Store_ColumnInfo_hidden\");\r\n");
		js.append("	var count=ListManager_Size(_Store_ColumnInfo);\r\n");
		js.append("	var editorIndex=index;\r\n");
		js.append("	for(var i=0;i<count;i++)\r\n");
		js.append("	{\r\n");
		js.append("		var hiddenIndex=ListManager_Get(i,_Store_ColumnInfo);\r\n");
		js.append("		if(hiddenIndex==\"\")\r\n");
		js.append("		{\r\n");
		js.append("			break;\r\n");
		js.append("        }\r\n");
		js.append("		hiddenIndex=parseInt(hiddenIndex);\r\n");
		js.append("		if(hiddenIndex<=editorIndex)\r\n");
		js.append("		{\r\n");
		js.append("			editorIndex++;\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			break;\r\n");
		js.append("		}\r\n");
		js.append("	}	\r\n");
		js.append("	return editorIndex;\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_RowSize(gridId)\r\n");
		js.append("{\r\n");
		js.append("   var table=document.getElementById(gridId);\r\n");
		js.append("   if(WebGrid_getExistEditRow(table)==null)\r\n");
		js.append("   {\r\n");
		js.append("       return table.rows.length;\r\n");
		js.append("   }\r\n");
		js.append("   else\r\n");
		js.append("   {\r\n");
		js.append("      return table.rows.length-1;\r\n");
		js.append("   }\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_getExistEditRow(table)\r\n");
		js.append("{\r\n");
		js.append("	if(table.getAttribute(\"oldItemID\")&&table.getAttribute(\"oldItemID\")!=\"\")\r\n");
		js.append("	{\r\n");
		js.append("		var oldRow=document.getElementById(table.getAttribute(\"oldItemID\"));\r\n");
		js.append("		return oldRow;\r\n");
		js.append("	}\r\n");
		js.append("	return null;\r\n");
		js.append("}\r\n");
		js.append("//��ȡ�༭����\r\n");
		js.append("function WebGrid_getEditorByColumnName(gridId,dataField)\r\n");
		js.append("{\r\n");
		js.append("	var Editors =eval(gridId+\"_Editors\");\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("		if(Editors[i].dataField==dataField)\r\n");
		js.append("		{\r\n");
		js.append("			return Editors[i];\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	return null;\r\n");
		js.append("}\r\n");
		js.append("//��ȡ�е�����\r\n");
		js.append("function WebGrid_getColumnIndex(gridId,dataField)\r\n");
		js.append("{\r\n");
		js.append("	var Editors =eval(gridId+\"_Editors\");\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("		if(Editors[i].dataField==dataField)\r\n");
		js.append("		{\r\n");
		js.append("			return i;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	return -1;\r\n");
		js.append("}\r\n");
		js.append("function EditorOnChange(index,gridId)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var editRow=WebGrid_getExistEditRow(table);\r\n");
		js.append("	if(editRow==null)\r\n");
		js.append("	{\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("	var editor=Editors[index];\r\n");
		js.append("	var control=editor.getChild();\r\n");
		js.append("	var viewtext=\"\";\r\n");
		js.append("	if(control==null)\r\n");
		js.append("	{\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	var getValue=control.getAttribute(\"getValue\");\r\n");
		js.append("	var getText=control.getAttribute(\"getText\");\r\n");
		js.append("	if(editor.dataField!=\"\"&&editor.dataValue==\"\"&&getValue!=null&&!editor.isDrop)\r\n");
		js.append("	{\r\n");
		js.append("		var hidden=WebGrid_getColumnText(table.id,index);\r\n");
		js.append("		viewtext=eval(getValue+\"('\"+control.id+\"')\");\r\n");
		js.append("		ListManager_Set(editRow.rowIndex,viewtext,hidden);\r\n");
		js.append("		WebGrid_runFormula(value,control,editor,editRow.rowIndex,table);\r\n");
		js.append("\r\n");
		js.append("	}\r\n");
		js.append("	else if(editor.dataField!=\"\"&&editor.dataValue==\"\"&&getValue==null)\r\n");
		js.append("	{\r\n");
		js.append("			// var value=contorl.;\r\n");
		js.append("			//ListManager_Set(editRow.rowIndex,value,hidden);\r\n");
		js.append("	}\r\n");
		js.append("	else if(editor.dataField!=\"\"&&editor.dataValue!=\"\"&&getValue!=null&&getText!=null&&!editor.isDrop)\r\n");
		js.append("	{\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,index);\r\n");
		js.append("			viewtext=eval(getText+\"('\"+control.id+\"')\");\r\n");
		js.append("			ListManager_Set(editRow.rowIndex,viewtext,hidden);\r\n");
		js.append("			hidden=WebGrid_getColumnValue(table.id,index);\r\n");
		js.append("			var value=eval(getValue+\"('\"+control.id+\"')\");\r\n");
		js.append("			ListManager_Set(editRow.rowIndex,value,hidden);\r\n");
		js.append("	}\r\n");
		js.append("	else if(editor.isDrop)\r\n");
		js.append("	{\r\n");
		js.append("		var hidden=WebGrid_getColumnText(table.id,index);\r\n");
		js.append("		viewtext=eval(getText+\"('\"+control.id+\"')\");\r\n");
		js.append("		ListManager_Set(editRow.rowIndex,viewtext,hidden);\r\n");
		js.append("		if(editor.dataValue!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			hidden=WebGrid_getColumnValue(table.id,index);\r\n");
		js.append("			var value=eval(getValue+\"('\"+control.id+\"')\");\r\n");
		js.append("			ListManager_Set(editRow.rowIndex,value,hidden);\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		var cellIndex=WebGrid_getColumnRealIndex(table.id,editor.dataField);\r\n");
		js.append("		WebGrid_setCellText(editRow,cellIndex,editor);\r\n");
		js.append("	}\r\n");
		js.append(" if(nextEditorIndex!=-1)\r\n");
		js.append(" {\r\n");
		js.append("		var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("		var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("		editor=Editors[nextEditorIndex];\r\n");
		js.append("		if(editor!=null)\r\n");
		js.append("		{\r\n");
		js.append("			WebGrid_setFocus(table,editor);\r\n");
		js.append("			nextEditorIndex=-1;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");	
		js.append("}\r\n");
		js.append("function WebGrid_refleshAutoAcsend(gridId)\r\n");
		js.append("{\r\n");
		js.append("   var Editors =eval(gridId+\"_Editors\");\r\n");
		js.append("   var table=document.getElementById(gridId);\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("		if(Editors[i].isAutoAscend)\r\n");
		js.append("		{\r\n");
		js.append("			var cellIndex=WebGrid_getColumnRealIndexByEditorIndex(gridId,i);\r\n");
		js.append("			var temp=0;\r\n");
		js.append("			for(var n=0;n<table.rows.length;n++)\r\n");
		js.append("			{\r\n");
		js.append("				var row=table.rows[n];\r\n");
		js.append("				if(row.id!=\"\")\r\n");
		js.append("				{\r\n");
		js.append("					WebGrid_setInnerText(row.cells[cellIndex],n+1-temp);\r\n");
		js.append("				}\r\n");
		js.append("				else\r\n");
		js.append("				{\r\n");
		js.append("					temp=1;\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	 }\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_setCellText(row,cellIndex,editor)\r\n");
		js.append("{\r\n");
		js.append("	var control=editor.getChild();\r\n");
		js.append("	if(control==null)\r\n");
		js.append("	{\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	if(editor.dataField==\"\")\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_setInnerText(row.cells[cellIndex],\"\");\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	var getValue=control.getAttribute(\"getValue\");\r\n");
		js.append("	var getText=control.getAttribute(\"getText\");\r\n");
		js.append("	var viewValue=\"\";\r\n");
		js.append("	if(getValue==null)\r\n");
		js.append("	{\r\n");
		js.append("		viewValue=WebGrid_getInnerText(control);\r\n");
		js.append("	}\r\n");
		js.append("	if(editor.dataField!=\"\"&&editor.dataValue==\"\"&&getValue!=null&&!editor.isDrop)\r\n");
		js.append("	{\r\n");
		js.append("		var value=eval(getValue+\"('\"+control.id+\"')\");\r\n");
		js.append("		if(control.getAttribute(\"IsConvertZero\")==\"true\")\r\n");
		js.append("		{\r\n");
		js.append("			if(value==\"0\")\r\n");
		js.append("			{\r\n");
		js.append("				viewValue=\"\";\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				viewValue=value;\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			viewValue=value;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	else if(editor.dataField!=\"\"&&editor.dataValue!=\"\"&&getValue!=null&&getText!=null&&!editor.isDrop)\r\n");
		js.append("	{\r\n");
		js.append("		var Text=eval(getText+\"('\"+control.id+\"')\");\r\n");
		js.append("		viewValue=Text;\r\n");
		js.append("	}\r\n");
		js.append("	else if(editor.dataField!=\"\"&&editor.dataValue!=\"\"&&setText==null)\r\n");
		js.append(" {\r\n");
		js.append(" 	var hidden=WebGrid_getColumnValue(table.id,i);\r\n");
		js.append(" 	ListManager_Set(row.rowIndex,\"\",hidden);\r\n");
		js.append(" 	WebGrid_setInnerText(control,\"\");\r\n");
		js.append(" }\r\n");
		js.append("	else if(editor.isDrop)\r\n");
		
		
		js.append("	{\r\n");
		js.append("		var Text=eval(getText+\"('\"+control.id+\"')\");\r\n");
		js.append("		viewValue=Text;\r\n");
		js.append("	}\r\n");
		js.append("	if(viewValue==\"\")\r\n");
		js.append("	{\r\n");
		js.append("		row.cells[cellIndex].innerHTML=\"&nbsp;\";\r\n");
		js.append("	}\r\n");
		js.append("	else\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_setInnerText(row.cells[cellIndex],viewValue)\r\n");
		js.append("		row.cells[cellIndex].title=viewValue;\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_SetEditorText(gridId,dataField,viewtext)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var editRow=WebGrid_getExistEditRow(table);\r\n");
		js.append("	if(editRow==null)\r\n");
		js.append("	{\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	var editor=WebGrid_getEditorByColumnName(gridId,dataField);\r\n");
		js.append("	var index=editor.editorIndex;\r\n");
		js.append("	var control=editor.getChild();\r\n");
		js.append("	if(control==null)\r\n");
		js.append("	{\r\n");
		js.append("		var hidden=WebGrid_getColumnText(table.id,index);\r\n");
		js.append("		ListManager_Set(editRow.rowIndex,viewtext,hidden);\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	var setText=control.getAttribute(\"setText\");\r\n");
		js.append("	var setValue=control.getAttribute(\"setValue\");\r\n");
		js.append("	if(setValue==null&&setText==null)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_setInnerText(control,viewtext);\r\n");
		js.append("		var hidden=WebGrid_getColumnText(table.id,index);        \r\n");
		js.append("		ListManager_Set(editRow.rowIndex,viewtext,hidden);\r\n");
		js.append("	}\r\n");
		js.append("	if(editor.dataField!=\"\"&&editor.dataValue==\"\"&&setValue!=null&&!editor.isDrop)\r\n");
		js.append("    {\r\n");
		js.append("        var hidden=WebGrid_getColumnText(table.id,index);\r\n");
		js.append("        eval(setValue+\"('\"+control.id+\"','\"+viewtext+\"')\");\r\n");
		js.append("		ListManager_Set(editRow.rowIndex,viewtext,hidden);\r\n");
		js.append("		WebGrid_runFormula(viewtext,control,editor,editRow.rowIndex,table);\r\n");
		js.append("\r\n");
		js.append("    }\r\n");
		js.append("    else if(editor.dataField!=\"\"&&editor.dataValue!=\"\"&&setValue!=null&&setText!=null&&!editor.isDrop)\r\n");
		js.append("    {\r\n");
		js.append("            var hidden=WebGrid_getColumnText(table.id,index);\r\n");
		js.append("            eval(setText+\"('\"+control.id+\"','\"+viewtext+\"')\");\r\n");
		js.append("            ListManager_Set(editRow.rowIndex,viewtext,hidden);\r\n");
		js.append("    }\r\n");
		js.append("    else if(editor.isDrop)\r\n");
		js.append("    {\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,index);\r\n");
		js.append("			eval(setText+\"('\"+control.id+\"','\"+viewtext+\"')\");\r\n");
		js.append("            ListManager_Set(editRow.rowIndex,viewtext,hidden);\r\n");
		js.append("    }\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_SetGridCellValue(gridId,rowIndex,dataField,hiddenValue)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("\r\n");
		js.append("		WebGrid_SetDefaultGridCellValue(gridId,rowIndex,dataField,hiddenValue);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_SetCustomGridCellValue(gridId,rowIndex,dataField,hiddenValue);\r\n");
		js.append("	}\r\n");
		js.append("\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_GetGridCellValue(gridId,rowIndex,dataField)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("\r\n");
		js.append("		return WebGrid_GetDefaultGridCellValue(gridId,rowIndex,dataField);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		return WebGrid_GetCustomGridCellValue(gridId,rowIndex,dataField);\r\n");
		js.append("	}\r\n");
		js.append("\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_GetGridCellText(gridId,rowIndex,dataField)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		return WebGrid_GetDefaultGridCellText(gridId,rowIndex,dataField);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		return WebGrid_GetCustomGridCellText(gridId,rowIndex,dataField);\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_SetGridCellText(gridId,rowIndex,dataField,viewtext)\r\n");
		js.append("{\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	if(\"0\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_SetDefaultGridCellText(gridId,rowIndex,dataField,viewtext);\r\n");
		js.append("	}\r\n");
		js.append("	else if(\"1\"==gridViewModel)\r\n");
		js.append("	{\r\n");
		js.append("		WebGrid_SetCustomGridCellText(gridId,rowIndex,dataField,viewtext);\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_runFormula(value,control,editor,rowIndex,table)\r\n");
		js.append("{\r\n");
		js.append("	var isClear=true;\r\n");
		js.append("	var gridId=table.id;\r\n");
		js.append("	var Editors =eval(gridId+\"_Editors\");\r\n");
		js.append("	if(control.getAttribute(\"IsNumber\")==\"true\")\r\n");
		js.append("	{\r\n");
		js.append("		if(value==0||value==\"\")\r\n");
		js.append("		{\r\n");
		js.append("			isClear=false;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	else\r\n");
		js.append("	{\r\n");
		js.append("		if(value==\"\")\r\n");
		js.append("		{\r\n");
		js.append("			isClear=false;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	if(editor.isMutex&&isClear)\r\n");
		js.append("	{\r\n");
		js.append("\r\n");
		js.append("		for(var i=0;i<editor.mutexColumn.length;i++)\r\n");
		js.append("		{\r\n");
		js.append("			var mutexEditor=WebGrid_getEditorByColumnName(table.id,editor.mutexColumn[i]);\r\n");
		js.append("			var mutexControl=mutexEditor.getChild();\r\n");
		js.append("			var mutexSetValue=mutexControl.getAttribute(\"setValue\");\r\n");
		js.append("			eval(mutexSetValue+\"('\"+mutexControl.id+\"','')\");\r\n");
		js.append("			var columnIndex=WebGrid_getColumnIndex(table.id,editor.mutexColumn[i]);\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,columnIndex);\r\n");
		js.append("			if(mutexControl.getAttribute(\"IsNumber\")==\"true\")\r\n");
		js.append("			{\r\n");
		js.append("				ListManager_Set(rowIndex,'0',hidden);\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				ListManager_Set(rowIndex,'',hidden);\r\n");
		js.append("			}\r\n");
		js.append("			if(mutexEditor.isTotal)\r\n");
		js.append("			{\r\n");
		js.append("				Formula_runSum(table,mutexEditor.dataField);\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	if(editor.formula!=null&&editor.formula!=\"\")\r\n");
		js.append("	{\r\n");
		js.append("		var formulas=editor.formula;\r\n");
		js.append("		var formula=new Formula(gridId,formulas);\r\n");
		js.append("		formula.exe();\r\n");
		js.append("		for(var j=0;j<formula.sourceCells.length;j++)\r\n");
		js.append("		{\r\n");
		js.append("			if(formula.sourceCells[j].index>=0)\r\n");
		js.append("			{\r\n");
		js.append("				var impressEditor=Editors[formula.sourceCells[j].index];\r\n");
		js.append("				if(impressEditor.isTotal)\r\n");
		js.append("				{\r\n");
		js.append("					Formula_runSum(table,impressEditor.dataField);\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	if(editor.isTotal)\r\n");
		js.append("	{\r\n");
		js.append("		Formula_runSum(table,editor.dataField);\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_refleshSum(table)\r\n");
		js.append("{\r\n");
		js.append("	var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("		var editor=Editors[i];\r\n");
		js.append("		if(editor.isTotal)\r\n");
		js.append("		{\r\n");
		js.append("			var index=WebGrid_getColumnRealIndex(table.id,editor.dataField)\r\n");
		js.append("			if(index>=0)\r\n");
		js.append("			{\r\n");
		js.append("				Formula_runSum(table,editor.dataField);\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_isAllNull(table,rowIndex)\r\n");
		js.append("{\r\n");
		js.append("	var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("		if(Editors[i].dataField!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,i);\r\n");
		js.append("			var valueText=ListManager_Get(rowIndex,hidden);\r\n");
		js.append("			if(valueText!=\"\"&&valueText!=\"0\")\r\n");
		js.append("			{\r\n");
		js.append("				return false;\r\n");
		js.append("			}\r\n");
		js.append("			else if(valueText==\"0\")\r\n");
		js.append("			{\r\n");
		js.append("				var control=Editors[i].getChild();\r\n");
		js.append("				if(control!=null)\r\n");
		js.append("				{\r\n");
		js.append("					if(control.getAttribute(\"IsNumber\")!=\"true\")\r\n");
		js.append("					{\r\n");
		js.append("						return false;\r\n");
		js.append("					}\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	return true;\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_clearRowData(table,row)\r\n");
		js.append("{\r\n");
		js.append("	var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("		var control=Editors[i].getChild();\r\n");
		js.append("		var editor=Editors[i];\r\n");
		js.append("		var index=row.rowIndex;\r\n");
		js.append("		if(control!=null&&editor.isColInitStatus)\r\n");
		js.append("		{\r\n");
		js.append("			var setValue=control.getAttribute(\"setValue\");\r\n");
		js.append("			var setText=control.getAttribute(\"setText\");\r\n");
		js.append("			if(editor.dataField==\"\")\r\n");
		js.append("			{\r\n");
		js.append("				continue;\r\n");
		js.append("			}\r\n");
		js.append("			if(editor.dataField!=\"\"&&editor.dataValue==\"\"&&setValue!=null&&!editor.isDrop)\r\n");
		js.append("			{\r\n");
		js.append("				eval(setValue+\"('\"+control.id+\"','')\");\r\n");
		js.append("			}\r\n");
		js.append("			else if(editor.dataField!=\"\"&&editor.dataValue==\"\"&&setValue==null)\r\n");
		js.append("			{\r\n");
		js.append("					WebGrid_setInnerText(control,\"\");\r\n");
		js.append("			}\r\n");
		js.append("			else if(editor.dataField!=\"\"&&editor.dataValue!=\"\"&&setValue!=null&&setText!=null&&!editor.isDrop)\r\n");
		js.append("			{\r\n");
		js.append("					eval(setText+\"('\"+control.id+\"','')\");\r\n");
		js.append("					var hidden=WebGrid_getColumnValue(table.id,i);\r\n");
		js.append("					eval(setValue+\"('\"+control.id+\"','')\");\r\n");
		js.append("					ListManager_Set(row.rowIndex,\"\",hidden);\r\n");
		js.append("			}\r\n");
		js.append("			else if(editor.isDrop)\r\n");
		js.append("			{\r\n");
		js.append("					eval(setText+\"('\"+control.id+\"','')\");\r\n");
		js.append("					if(!(editor.dataValue==\"\"))\r\n");
		js.append("					{\r\n");
		js.append("					      var hidden=WebGrid_getColumnValue(table.id,i);\r\n");
		js.append("					      ListManager_Set(index,\"\",hidden);\r\n");
		js.append("					}\r\n");
		js.append("          \r\n");
		js.append("			}\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,i);\r\n");
		js.append("			ListManager_Set(index,\"\",hidden);\r\n");
		js.append("			if(editor.isDrop&&editor.isChange)\r\n");
		js.append("			{\r\n");
		js.append("				editor.changeData(0,row.rowIndex,ListManager_Size(hidden));\r\n");
		js.append("			}\r\n");
		js.append("			if(editor.isNoFixFormula)\r\n");
		js.append("			{\r\n");
		js.append("				editor.changeFormula(0,row.rowIndex,ListManager_Size(hidden));\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			if(editor.dataField!=\"\")\r\n");
		js.append("			{\r\n");
		js.append("				var hidden=WebGrid_getColumnText(table.id,i);\r\n");
		js.append("				ListManager_Set(index,\"\",hidden);\r\n");
		js.append("				if(editor.isDrop&&editor.isChange)\r\n");
		js.append("				{\r\n");
		js.append("					Editors[i].changeData(0,row.rowIndex,ListManager_Size(hidden));\r\n");
		js.append("				}\r\n");
		js.append("				if(Editors[i].isNoFixFormula)\r\n");
		js.append("				{\r\n");
		js.append("					Editors[i].changeFormula(0,row.rowIndex,ListManager_Size(hidden));\r\n");
		js.append("				}\r\n");
		js.append("				if(editor.dataValue!=\"\")\r\n");
		js.append("				{\r\n");
		js.append("					var hidden=WebGrid_getColumnValue(table.id,i);\r\n");
		js.append("					ListManager_Set(row.rowIndex,\"\",hidden);\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				continue;\r\n");
		js.append("			}\r\n");
		js.append("\r\n");
		js.append("			var cellIndex=WebGrid_getColumnRealIndex(table.id,editor.dataField);\r\n");
		js.append("			if(cellIndex!=-1)\r\n");
		js.append("			{\r\n");
		js.append("				row.cells[cellIndex].innerHTML=\"&nbsp;\";\r\n");
		js.append("				row.cells[cellIndex].disabled=true;\r\n");
		js.append("				row.cells[cellIndex].className=\"celldisabled\";\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_insertNewData(table,rowIndex)\r\n");
		js.append("{\r\n");
		js.append("	var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("		if(Editors[i].dataField!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,i);\r\n");
		js.append("			ListManager_Insert(rowIndex,\"\",hidden);\r\n");
		js.append("			if(Editors[i].isDrop&&Editors[i].isChange)\r\n");
		js.append("			{\r\n");
		js.append("				Editors[i].changeData(1,rowIndex,ListManager_Size(hidden));\r\n");
		js.append("			}\r\n");
		js.append("			if(Editors[i].isNoFixFormula)\r\n");
		js.append("			{\r\n");
		js.append("				Editors[i].changeFormula(1,rowIndex,ListManager_Size(hidden));\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		if(Editors[i].dataValue!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			var hidden=WebGrid_getColumnValue(table.id,i);\r\n");
		js.append("			ListManager_Insert(rowIndex,\"\",hidden);\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_deleteAllRow(gridId)\r\n");
		js.append("{\r\n");
		js.append("    var table=document.getElementById(gridId);\r\n");
		js.append("    var editRow=WebGrid_getExistEditRow(table);\r\n");
		js.append("    var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("    var length=table.rows.length;\r\n");		
		js.append("    if(\"0\"==gridViewModel)\r\n");
		js.append("    {\r\n");
		js.append("       //index=WebGrid_getRealRowIndex(index,editRow,table);\r\n");
		js.append("       if(editRow!=null)\r\n");
		js.append("       {\r\n");
		js.append("          WebGrid_cancelEditRow(gridId);\r\n");
		js.append("          for(var i=1;i<length-1;i++)\r\n");
		js.append("          {          	\r\n");
		js.append("          	table.deleteRow(1);	\r\n");
		js.append("          }\r\n");
		js.append(" 	   	  WebGrid_deleteAllModel(gridId);	\r\n");
		js.append("           WebGrid_RowOnclick(gridId,table.rows[0]);\r\n");
		js.append("           WebGrid_Cancel(gridId);          \r\n");
		js.append("       }\r\n");
		js.append("       else\r\n");
		js.append("       {\r\n");
		js.append("          for(var i=1;i<length;i++)\r\n");
		js.append("          {          	\r\n");
		js.append("          	table.deleteRow(1);	\r\n");
		js.append("          }\r\n");
		js.append("          for(var j=0;j<table.rows[0].cells.length;j++)\r\n");
		js.append("          {\r\n");
		js.append("              table.rows[0].cells[j].innerHTML=\"&nbsp;\"\r\n");
		js.append("          } \r\n");   
		js.append("          WebGrid_deleteAllModel(gridId);	\r\n");
		js.append("       }\r\n");
		js.append("    }\r\n");
		js.append("    else\r\n");
		js.append("    {\r\n");
		js.append("        for(var i=0;i<length;i++)\r\n");
		js.append("		   {          	\r\n");
		js.append("	  	       table.deleteRow(0);	\r\n");
		js.append("	       }\r\n");
		js.append("		   WebGrid_deleteAllModel(gridId);\r\n");
		js.append("   }\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_deleteAllModel(gridId)\r\n");
		js.append("{\r\n");
		js.append("	var Editors =eval(gridId+\"_Editors\");\r\n");
		js.append("	var table=document.getElementById(gridId);\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("	\r\n");
		js.append("		if(Editors[i].dataField!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,i);						\r\n");
		js.append("			if(Editors[i].isDrop&&Editors[i].isChange)\r\n");
		js.append("			{\r\n");
		js.append("				var length=ListManager_Size(hidden);\r\n");
		js.append("				for(var j=length-1;j>=0;j++)\r\n");
		js.append("				{\r\n");
		js.append("					Editors[i].changeData(-1,j,j+1);\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("			if(Editors[i].isNoFixFormula)\r\n");
		js.append("			{\r\n");
		js.append("				\r\n");
		js.append("				var length=ListManager_Size(hidden);\r\n");
		js.append("				for(var j=length-1;j>=0;j++)\r\n");
		js.append("				{					\r\n");
		js.append("					Editors[i].changeFormula(-1,j,j+1);\r\n");
		js.append("				}\r\n");
		js.append("			}\r\n");
		js.append("			ListManager_RemoveAll(hidden);\r\n");
		js.append("			ListManager_Insert(0, \"\", hidden)\r\n");
		js.append("		}\r\n");
		js.append("		if(Editors[i].dataValue!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			 var hidden=WebGrid_getColumnValue(table.id,i);\r\n");
		js.append("			 ListManager_RemoveAll(hidden);\r\n");
		js.append("			 ListManager_Insert(0, \"\", hidden)\r\n");
		js.append("		}\r\n");
		js.append("	}	\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_deleteRowByIndex(gridId,index)\r\n");
		js.append("{\r\n");
		js.append("    var table=document.getElementById(gridId);\r\n");
		js.append("    var editRow=WebGrid_getExistEditRow(table);\r\n");
		js.append("    var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("    if(\"0\"==gridViewModel)\r\n");
		js.append("    {\r\n");
		js.append("       index=WebGrid_getRealRowIndex(index,editRow,table);\r\n");
		js.append("       if(editRow!=null&&editRow.rowIndex==index)\r\n");
		js.append("       {\r\n");
		js.append("           WebGrid_deleteRow(table,index);\r\n");
		js.append("       }\r\n");
		js.append("       else\r\n");
		js.append("       {\r\n");
		js.append("           table.deleteRow(index);\r\n");
		js.append("       }\r\n");
		js.append("    }\r\n");
		js.append("    else\r\n");
		js.append("    {\r\n");
		js.append("       table.deleteRow(index);\r\n");
		js.append("    }  \r\n");
		js.append("    WebGrid_deleteData(table,index);\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_insertNewRow(gridId,index)\r\n");
		js.append("{\r\n");
		js.append("    var table=document.getElementById(gridId);\r\n");
		js.append("    var editRow=WebGrid_getExistEditRow(table);\r\n");
		js.append("    var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("    if(\"0\"==gridViewModel)\r\n");
		js.append("    {\r\n");
		js.append("       index=WebGrid_getRealRowIndex(index,editRow,table);\r\n");
		js.append("    }\r\n");
		js.append("    var rowObj=WebGrid_addNewRow(table,editRow,index);\r\n");
		js.append("    WebGrid_insertNewData(table,index);\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_addNewRow(table,editRow,addIndex)\r\n");
		js.append("{\r\n");
		js.append("	\r\n");
		js.append("	var gridViewModel=table.getAttribute(\"GridViewModel\");\r\n");
		js.append("	var isExistRow=true;\r\n");
		js.append("	if(editRow==null)\r\n");
		js.append("	{\r\n");
		js.append("		var objheader=document.getElementById(table.id+\"_head\");\r\n");
		js.append("		editRow=objheader.rows[0];\r\n");
		js.append("		isExistRow=false;\r\n");
		js.append("	}\r\n");
		js.append("	if(isExistRow)\r\n");
		js.append("	{\r\n");
		js.append("	   if(addIndex>editRow.rowIndex)\r\n");
		js.append("	   {\r\n");
		js.append("	       addIndex+=1;  \r\n");
		js.append("	   }\r\n");
		js.append("	}\r\n");
		js.append("	var rowObj=table.insertRow(addIndex);\r\n");
		js.append("	for(var i=table.rows.length-1;i>addIndex;i--)\r\n");
		js.append("	{\r\n");
		js.append("		if(\"0\"==gridViewModel)\r\n");
		js.append("		{\r\n");
		js.append("			if(i==editRow.rowIndex&&isExistRow)\r\n");
		js.append("			{\r\n");
		js.append("				editRow.id=table.id+\"_Row_\"+i;\r\n");
		js.append("				table.setAttribute(\"oldItemID\",editRow.id);\r\n");
		js.append("			}\r\n");
		js.append("			else if((i==editRow.rowIndex+1)&&isExistRow)\r\n");
		js.append("			{\r\n");
		js.append("				continue;\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				table.rows[i].id=table.id+\"_Row_\"+(i-1);\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	if(gridViewModel==\"0\")\r\n");
		js.append("	{\r\n");
		js.append("		if(addIndex>editRow.rowIndex&&isExistRow)\r\n");
		js.append("		{\r\n");
		js.append("			rowObj.id=table.id+\"_Row_\"+(addIndex-1);\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			rowObj.id=table.id+\"_Row_\"+addIndex;\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("	else\r\n");
		js.append("	{\r\n");
		js.append("		rowObj.id=table.id+\"_Row_\"+addIndex;\r\n");
		js.append("		\r\n");
		js.append("		\r\n");
		js.append("	}\r\n");
		js.append("	var itemClass=table.getAttribute(\"ItemClass\");\r\n");
		js.append("	rowObj.className=itemClass;\r\n");
		js.append("	rowObj.onclick=function RowOnclickTemp(){WebGrid_RowOnclick(table.id,this);};\r\n");
		js.append("	for(var i=0;i<editRow.cells.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("			var cell=rowObj.insertCell(i);\r\n");
		js.append("			cell.width=editRow.cells[i].width;\r\n");
		js.append("			cell.id=table.id+\"_Row_\"+rowObj.rowIndex+\"_\"+i;\r\n");
		js.append("			if(!isExistRow)\r\n");
		js.append("			{\r\n");
		js.append("				var headerName=editRow.cells[cell.cellIndex].innerHTML;\r\n");
		js.append("				var editor=getEditorByProperty(table.id,\"headerName\",headerName);				\r\n");
		js.append("				if(editor.hAlign!=\"\")\r\n");
		js.append("				   cell.align=editor.hAlign;		\r\n");
		js.append("			}\r\n");
		js.append("			else\r\n");
		js.append("			{\r\n");
		js.append("				cell.align=editRow.cells[i].align;\r\n");
		js.append("			}			\r\n");
		js.append("			if(table.getAttribute(\"noWrap\")==\"true\")\r\n");
		js.append("			{\r\n");
		js.append("				cell.noWrap=true;\r\n");
		js.append("			}\r\n");
		js.append("			cell.innerHTML=\"&nbsp;\";\r\n");
		js.append("	}\r\n");
		js.append("	WebGrid_refleshAutoAcsend(table.id);\r\n");
		js.append("	return  rowObj;\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_deleteData(table,rowIndex)\r\n");
		js.append("{\r\n");
		js.append("	var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("	for(var i=0;i<Editors.length;i++)\r\n");
		js.append("	{\r\n");
		js.append("\r\n");
		js.append("		if(Editors[i].dataField!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,i);\r\n");
		js.append("			ListManager_Remove(rowIndex , hidden);\r\n");
		js.append("			if(Editors[i].isDrop&&Editors[i].isChange)\r\n");
		js.append("			{\r\n");
		js.append("				Editors[i].changeData(-1,rowIndex,ListManager_Size(hidden));\r\n");
		js.append("			}\r\n");
		js.append("			if(Editors[i].isNoFixFormula)\r\n");
		js.append("			{\r\n");
		js.append("				Editors[i].changeFormula(-1,rowIndex,ListManager_Size(hidden));\r\n");
		js.append("			}\r\n");
		js.append("		}\r\n");
		js.append("		if(Editors[i].dataValue!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			var hidden=WebGrid_getColumnValue(table.id,i);\r\n");
		js.append("			ListManager_Remove(rowIndex , hidden);\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_setViewData(editor,table,row,columnRealIndex)\r\n");
		js.append("{\r\n");
		js.append("	var control=editor.getChild();\r\n");
		js.append("	if(control==null)\r\n");
		js.append("	{\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	var setValue=control.getAttribute(\"setValue\");\r\n");
		js.append("	var setText=control.getAttribute(\"setText\");\r\n");
		js.append("	if(setValue==null&&editor.dataField!=\"\")\r\n");
		js.append("	{\r\n");
		js.append("		var hidden=WebGrid_getColumnText(table.id,columnRealIndex);\r\n");
		js.append("		control.innerHTML=ListManager_Get(row.rowIndex,hidden);\r\n");
		js.append("	}\r\n");
		js.append("	if(editor.dataField!=\"\"&&editor.dataValue==\"\"&&setValue!=null&&!editor.isDrop&&setText==null)\r\n");
		js.append("	{\r\n");
		js.append("		var hidden=WebGrid_getColumnText(table.id,columnRealIndex);\r\n");
		js.append("		eval(setValue+\"('\"+control.id+\"','\"+ListManager_Get(row.rowIndex,hidden)+\"')\");\r\n");
		js.append("	}\r\n");
		js.append("	else if(editor.dataField!=\"\"&&editor.dataValue!=\"\"&&setValue!=null&&setText!=null&&!editor.isDrop)\r\n");
		js.append("	{\r\n");
		js.append("\r\n");
		js.append("		var hidden=WebGrid_getColumnText(table.id,columnRealIndex);\r\n");
		js.append("		eval(setText+\"('\"+control.id+\"','\"+ListManager_Get(row.rowIndex,hidden)+\"')\");\r\n");
		js.append("		var hidden=WebGrid_getColumnValue(table.id,columnRealIndex);\r\n");
		js.append("		eval(setValue+\"('\"+control.id+\"','\"+ListManager_Get(row.rowIndex,hidden)+\"')\");\r\n");
		js.append("	}\r\n");
		js.append("	else if(editor.isDrop)\r\n");
		js.append("	{\r\n");
		js.append("		if(editor.dataField!=\"\")\r\n");
		js.append("		{\r\n");
		js.append("			var hidden=WebGrid_getColumnText(table.id,columnRealIndex);\r\n");
		js.append("			eval(setText+\"('\"+control.id+\"','\"+ListManager_Get(row.rowIndex,hidden)+\"')\");\r\n");
		js.append("		}\r\n");
		js.append("		else\r\n");
		js.append("		{\r\n");
		js.append("			hidden=WebGrid_getColumnValue(table.id,columnRealIndex);\r\n");
		js.append("			eval(setValue+\"('\"+control.id+\"','\"+ListManager_Get(row.rowIndex,hidden)+\"')\");\r\n");
		js.append("		}\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_setFocus(table,editor)\r\n");
		js.append("{\r\n");
		js.append("	if(editor==null)\r\n");
		js.append("	{\r\n");
		js.append("		var editorIndex=table.getAttribute(\"firstControl\");\r\n");
		js.append("		\r\n");
		js.append("		if(editorIndex==null)\r\n");
		js.append("		{\r\n");
		js.append("			editorIndex=0;\r\n");
		js.append("		}\r\n");
		js.append("		var Editors =eval(table.id+\"_Editors\");\r\n");
		js.append("		editor=Editors[editorIndex];\r\n");
		js.append("	}\r\n");
		js.append("	var control=editor.getChild();\r\n");
		js.append("	if(control==null)\r\n");
		js.append("	{\r\n");
		js.append("		return;\r\n");
		js.append("	}\r\n");
		js.append("	var setFocus=control.getAttribute(\"setFocus\");\r\n");
		js.append("	if(setFocus!=null&&setFocus!=\"\")\r\n");
		js.append("	{\r\n");
		js.append("		if(control.offsetWidth!=0)\r\n");
		js.append("		eval(setFocus+\"('\"+control.id+\"')\");\r\n");
		js.append("	}\r\n");
		js.append("	else\r\n");
		js.append("	{\r\n");
		js.append("		if(control.offsetWidth!=0)\r\n");
		js.append("		control.select();\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_setInnerText(obj,viewValue)\r\n");
		js.append("{\r\n");
		js.append("	if(document.all)\r\n");
		js.append("	{\r\n");
		js.append("		obj.innerText=viewValue;\r\n");
		js.append("	}\r\n");
		js.append("	else\r\n");
		js.append("	{\r\n");
		js.append("		obj.innerHTML=viewValue;\r\n");
		js.append("	}\r\n");
		js.append("}\r\n");
		js.append("function WebGrid_getInnerText(obj)\r\n");
		js.append("{\r\n");
		js.append("	if(document.all)\r\n");
		js.append("	{\r\n");
		js.append("		return obj.innerText;\r\n");
		js.append("	}\r\n");
		js.append("	else\r\n");
		js.append("	{\r\n");
		js.append("		return obj.innerHTML;\r\n");
		js.append("	}\r\n");
		js.append("}");
		return jstool.getComponentJS() + HashMapJS.getHashMapJS();
	}
}