//package org.gabiz.test;
//package vp3menu;
package com.born.insurance.webui.control;

//import com.bornsoft.core.gaui.component.*;

/**
 * <p>Title: the javascript code of the hashmap manager control</p>
 * <p>Description: the javascript code of the hashmap manager control</p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: bornsoft</p>
 * @author: �ᴺ��
 * @version 1.0
 */

public class XmenuJS {

  /**
   * <p>Description: get the javasrcipt code of the HashMap control</p>
   * @param path: the path of the javascript code file.
   * @return the reference of the javascript code file.
   */
  public static String XmenuJS(){

      JSTool jstool=new JSTool("xmenu.js");
      StringBuffer jsSB = new StringBuffer();
      jsSB.append("var ua = navigator.userAgent;\r\n");
      jsSB.append("var opera = /opera [56789]|opera\\/[56789]/i.test(ua);\r\n");
      jsSB.append("var ie = !opera && /MSIE/.test(ua);\r\n");
      jsSB.append("var ie50 = ie && /MSIE 5\\.[01234]/.test(ua);\r\n");
      jsSB.append("var ie6 = ie && /MSIE [6789]/.test(ua);\r\n");
      jsSB.append("var ieBox = ie && (document.compatMode == null || document.compatMode != \"CSS1Compat\");\r\n");
      jsSB.append("var moz = !opera && /gecko/i.test(ua);\r\n");
      jsSB.append("var nn6 = !opera && /netscape.*6\\./i.test(ua);\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuDefaultWidth			= 130;\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuDefaultBorderLeft		= 1;\r\n");
      jsSB.append("webfxMenuDefaultBorderRight		= 1;\r\n");
      jsSB.append("webfxMenuDefaultBorderTop		= 1;\r\n");
      jsSB.append("webfxMenuDefaultBorderBottom	= 1;\r\n");
      jsSB.append("webfxMenuDefaultPaddingLeft		= 1;\r\n");
      jsSB.append("webfxMenuDefaultPaddingRight	= 1;\r\n");
      jsSB.append("webfxMenuDefaultPaddingTop		= 1;\r\n");
      jsSB.append("webfxMenuDefaultPaddingBottom	= 1;\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuDefaultShadowLeft		= 0;\r\n");
      jsSB.append("webfxMenuDefaultShadowRight		= ie && !ie50 && /win32/i.test(navigator.platform) ? 4 :0;\r\n");
      jsSB.append("webfxMenuDefaultShadowTop		= 0;\r\n");
      jsSB.append("webfxMenuDefaultShadowBottom	= ie && !ie50 && /win32/i.test(navigator.platform) ? 4 : 0;\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuItemDefaultHeight		= 18;\r\n");
      jsSB.append("webfxMenuItemDefaultText		= \"Untitled\";\r\n");
      jsSB.append("webfxMenuItemDefaultHref		= \"javascript:void(0)\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuSeparatorDefaultHeight	= 6;\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuDefaultEmptyText		= \"Empty\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuDefaultUseAutoPosition	= nn6 ? false : true;\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuImagePath				= \"\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("webfxMenuUseHover				= opera ? true : false;\r\n");
      jsSB.append("webfxMenuHideTime				= 200;\r\n");
      jsSB.append("webfxMenuShowTime				= 200;\r\n");
      jsSB.append("\r\n");
      jsSB.append("var webFXMenuHandler = {\r\n");
      jsSB.append("	idCounter		:	0,\r\n");
      jsSB.append("	idPrefix		:	\"webfx-menu-object-\",\r\n");
      jsSB.append("	all				:	{},\r\n");
      jsSB.append("	getId			:	function () { return this.idPrefix + this.idCounter++; },\r\n");
      jsSB.append("	overMenuItem	:	function (oItem) {\r\n");
      jsSB.append("		if (this.showTimeout != null)\r\n");
      jsSB.append("			window.clearTimeout(this.showTimeout);\r\n");
      jsSB.append("		if (this.hideTimeout != null)\r\n");
      jsSB.append("			window.clearTimeout(this.hideTimeout);\r\n");
      jsSB.append("		var jsItem = this.all[oItem.id];\r\n");
      jsSB.append("		if (webfxMenuShowTime <= 0)\r\n");
      jsSB.append("			this._over(jsItem);\r\n");
      jsSB.append("		else\r\n");
      jsSB.append("			this.showTimeout = window.setTimeout(\"webFXMenuHandler._over(webFXMenuHandler.all['\" + jsItem.id + \"'])\", webfxMenuShowTime);\r\n");
      jsSB.append("	},\r\n");
      jsSB.append("	outMenuItem	:	function (oItem) {\r\n");
      jsSB.append("		if (this.showTimeout != null)\r\n");
      jsSB.append("			window.clearTimeout(this.showTimeout);\r\n");
      jsSB.append("		if (this.hideTimeout != null)\r\n");
      jsSB.append("			window.clearTimeout(this.hideTimeout);\r\n");
      jsSB.append("		var jsItem = this.all[oItem.id];\r\n");
      jsSB.append("		if (webfxMenuHideTime <= 0)\r\n");
      jsSB.append("			this._out(jsItem);\r\n");
      jsSB.append("		else\r\n");
      jsSB.append("			this.hideTimeout = window.setTimeout(\"webFXMenuHandler._out(webFXMenuHandler.all['\" + jsItem.id + \"'])\", webfxMenuHideTime);\r\n");
      jsSB.append("	},\r\n");
      jsSB.append("	blurMenu		:	function (oMenuItem) {\r\n");
      jsSB.append("		window.setTimeout(\"webFXMenuHandler.all[\\\"\" + oMenuItem.id + \"\\\"].subMenu.hide();\", webfxMenuHideTime);\r\n");
      jsSB.append("	},\r\n");
      jsSB.append("	_over	:	function (jsItem) {\r\n");
      jsSB.append("		if (jsItem.subMenu) {\r\n");
      jsSB.append("			jsItem.parentMenu.hideAllSubs();\r\n");
      jsSB.append("			jsItem.subMenu.show();\r\n");
      jsSB.append("		}\r\n");
      jsSB.append("		else\r\n");
      jsSB.append("			jsItem.parentMenu.hideAllSubs();\r\n");
      jsSB.append("	},\r\n");
      jsSB.append("	_out	:	function (jsItem) {\r\n");
      jsSB.append("		var root = jsItem;\r\n");
      jsSB.append("		var m;\r\n");
      jsSB.append("		if (root instanceof WebFXMenuButton)\r\n");
      jsSB.append("			m = root.subMenu;\r\n");
      jsSB.append("		else {\r\n");
      jsSB.append("			m = jsItem.parentMenu;\r\n");
      jsSB.append("			while (m.parentMenu != null && !(m.parentMenu instanceof WebFXMenuBar))\r\n");
      jsSB.append("				m = m.parentMenu;\r\n");
      jsSB.append("		}\r\n");
      jsSB.append("		if (m != null)\r\n");
      jsSB.append("			m.hide();\r\n");
      jsSB.append("	},\r\n");
      jsSB.append("	hideMenu	:	function (menu) {\r\n");
      jsSB.append("		if (this.showTimeout != null)\r\n");
      jsSB.append("			window.clearTimeout(this.showTimeout);\r\n");
      jsSB.append("		if (this.hideTimeout != null)\r\n");
      jsSB.append("			window.clearTimeout(this.hideTimeout);\r\n");
      jsSB.append("\r\n");
      jsSB.append("		this.hideTimeout = window.setTimeout(\"webFXMenuHandler.all['\" + menu.id + \"'].hide()\", webfxMenuHideTime);\r\n");
      jsSB.append("	},\r\n");
      jsSB.append("	showMenu	:	function (menu, src, dir) {\r\n");
      jsSB.append("		if (this.showTimeout != null)\r\n");
      jsSB.append("			window.clearTimeout(this.showTimeout);\r\n");
      jsSB.append("		if (this.hideTimeout != null)\r\n");
      jsSB.append("			window.clearTimeout(this.hideTimeout);\r\n");
      jsSB.append("		if (arguments.length < 3)\r\n");
      jsSB.append("			dir = \"vertical\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("		menu.show(src, dir);\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("function WebFXMenu() {\r\n");
      jsSB.append("	this._menuItems	= [];\r\n");
      jsSB.append("	this._subMenus	= [];\r\n");
      jsSB.append("	this.id			= webFXMenuHandler.getId();\r\n");
      jsSB.append("	this.top		= 0;\r\n");
      jsSB.append("	this.left		= 0;\r\n");
      jsSB.append("	this.shown		= false;\r\n");
      jsSB.append("	this.parentMenu	= null;\r\n");
      jsSB.append("	webFXMenuHandler.all[this.id] = this;\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.width			= webfxMenuDefaultWidth;\r\n");
      jsSB.append("WebFXMenu.prototype.emptyText		= webfxMenuDefaultEmptyText;\r\n");
      jsSB.append("WebFXMenu.prototype.useAutoPosition	= webfxMenuDefaultUseAutoPosition;\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.borderLeft		= webfxMenuDefaultBorderLeft;\r\n");
      jsSB.append("WebFXMenu.prototype.borderRight		= webfxMenuDefaultBorderRight;\r\n");
      jsSB.append("WebFXMenu.prototype.borderTop		= webfxMenuDefaultBorderTop;\r\n");
      jsSB.append("WebFXMenu.prototype.borderBottom	= webfxMenuDefaultBorderBottom;\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.paddingLeft		= webfxMenuDefaultPaddingLeft;\r\n");
      jsSB.append("WebFXMenu.prototype.paddingRight	= webfxMenuDefaultPaddingRight;\r\n");
      jsSB.append("WebFXMenu.prototype.paddingTop		= webfxMenuDefaultPaddingTop;\r\n");
      jsSB.append("WebFXMenu.prototype.paddingBottom	= webfxMenuDefaultPaddingBottom;\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.shadowLeft		= webfxMenuDefaultShadowLeft;\r\n");
      jsSB.append("WebFXMenu.prototype.shadowRight		= webfxMenuDefaultShadowRight;\r\n");
      jsSB.append("WebFXMenu.prototype.shadowTop		= webfxMenuDefaultShadowTop;\r\n");
      jsSB.append("WebFXMenu.prototype.shadowBottom	= webfxMenuDefaultShadowBottom;\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.add = function (menuItem) {\r\n");
      jsSB.append("	this._menuItems[this._menuItems.length] = menuItem;\r\n");
      jsSB.append("	if (menuItem.subMenu) {\r\n");
      jsSB.append("		this._subMenus[this._subMenus.length] = menuItem.subMenu;\r\n");
      jsSB.append("		menuItem.subMenu.parentMenu = this;\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("\r\n");
      jsSB.append("	menuItem.parentMenu = this;\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.show = function (relObj, sDir) {\r\n");
      jsSB.append("	if (this.useAutoPosition)\r\n");
      jsSB.append("		this.position(relObj, sDir);\r\n");
      jsSB.append("\r\n");
      jsSB.append("	var divElement = document.getElementById(this.id);\r\n");
      jsSB.append("	divElement.style.left = opera ? this.left : this.left + \"px\";\r\n");
      jsSB.append("	divElement.style.top = opera ? this.top : this.top + \"px\";\r\n");
      jsSB.append("	divElement.style.visibility = \"visible\";\r\n");
      jsSB.append("	this.shown = true;\r\n");
      jsSB.append("	if (this.parentMenu)\r\n");
      jsSB.append("		this.parentMenu.show();\r\n");
      jsSB.append("	if (document.all)\r\n");
      jsSB.append("		cal_hideElementAll(divElement);\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.hide = function () {\r\n");
      jsSB.append("	this.hideAllSubs();\r\n");
      jsSB.append("	var divElement = document.getElementById(this.id);\r\n");
      jsSB.append("	divElement.style.visibility = \"hidden\";\r\n");
      jsSB.append("	this.shown = false;\r\n");
      jsSB.append("	if (document.all) cal_ShowElement(divElement);\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.hideAllSubs = function () {\r\n");
      jsSB.append("	for (var i = 0; i < this._subMenus.length; i++) {\r\n");
      jsSB.append("		if (this._subMenus[i].shown)\r\n");
      jsSB.append("			this._subMenus[i].hide();\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("};\r\n");
      jsSB.append("WebFXMenu.prototype.toString = function () {\r\n");
      jsSB.append("	var top = this.top + this.borderTop + this.paddingTop;\r\n");
      jsSB.append("	var str = \"<div id='\" + this.id + \"' class='webfx-menu' style='\" +\r\n");
      jsSB.append("	\"width:\" + (!ieBox  ?\r\n");
      jsSB.append("		this.width - this.borderLeft - this.paddingLeft - this.borderRight - this.paddingRight  :\r\n");
      jsSB.append("		this.width) + \"px;\" +\r\n");
      jsSB.append("	\"height:\"+ (!ieBox  ?\r\n");
      jsSB.append("	this._menuItems.length*webfxMenuItemDefaultHeight + this._menuItems.length*this.borderBottom:\r\n");
      jsSB.append("	this._menuItems.length*webfxMenuItemDefaultHeight+this._menuItems.length*this.borderBottom)+\"px;\"+\r\n");
      jsSB.append("	(this.useAutoPosition ?\r\n");
      jsSB.append("		\"left:\" + this.left + \"px;\" + \"top:\" + this.top + \"px;\" :\r\n");
      jsSB.append("		\"\") +\r\n");
      jsSB.append("	(ie50 ? \"filter: none;\" : \"\") +\r\n");
      jsSB.append("	\"'>\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("	if (this._menuItems.length == 0) {\r\n");
      jsSB.append("		str +=	\"<span class='webfx-menu-empty'>\" + this.emptyText + \"</span>\";\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("	else {\r\n");
      jsSB.append("		for (var i = 0; i < this._menuItems.length; i++) {\r\n");
      jsSB.append("			var mi = this._menuItems[i];\r\n");
      jsSB.append("			str += mi;\r\n");
      jsSB.append("			if (!this.useAutoPosition) {\r\n");
      jsSB.append("				if (mi.subMenu && !mi.subMenu.useAutoPosition)\r\n");
      jsSB.append("					mi.subMenu.top = top - mi.subMenu.borderTop - mi.subMenu.paddingTop;\r\n");
      jsSB.append("				top += mi.height;\r\n");
      jsSB.append("			}\r\n");
      jsSB.append("		}\r\n");
      jsSB.append("\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("\r\n");
      jsSB.append("	str += \"</div>\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("	for (var i = 0; i < this._subMenus.length; i++) {\r\n");
      jsSB.append("		this._subMenus[i].left = this.left + this.width - this._subMenus[i].borderLeft;\r\n");
      jsSB.append("		str += this._subMenus[i];\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("\r\n");
      jsSB.append("	return str;\r\n");
      jsSB.append("};\r\n");
      jsSB.append("function WebFXMenuItem(sText, sHref, sToolTip, oSubMenu) {\r\n");
      jsSB.append("	this.text = sText || webfxMenuItemDefaultText;\r\n");
      jsSB.append("	this.href = (sHref == null || sHref == \"\") ? webfxMenuItemDefaultHref : sHref;\r\n");
      jsSB.append("	this.subMenu = oSubMenu;\r\n");
      jsSB.append("	if (oSubMenu)\r\n");
      jsSB.append("		oSubMenu.parentMenuItem = this;\r\n");
      jsSB.append("	this.toolTip = sToolTip;\r\n");
      jsSB.append("	this.id = webFXMenuHandler.getId();\r\n");
      jsSB.append("	webFXMenuHandler.all[this.id] = this;\r\n");
      jsSB.append("};\r\n");
      jsSB.append("WebFXMenuItem.prototype.height = webfxMenuItemDefaultHeight;\r\n");
      jsSB.append("WebFXMenuItem.prototype.toString = function () {\r\n");
      jsSB.append("	return	\"<a\" +\r\n");
      jsSB.append("			\" id='\" + this.id + \"'\" +\r\n");
      jsSB.append("			\" href=\\\"\" + this.href + \"\\\"\" +\r\n");
      jsSB.append("			(this.target ? \" target=\\\"\" + this.target + \"\\\"\" : \"\") +\r\n");
      jsSB.append("			(this.toolTip ? \" title=\\\"\" + this.toolTip + \"\\\"\" : \"\") +\r\n");
      jsSB.append("			\" onmouseover='webFXMenuHandler.overMenuItem(this)'\" +\r\n");
      jsSB.append("			(webfxMenuUseHover ? \" onmouseout='webFXMenuHandler.outMenuItem(this)'\" : \"\") +\r\n");
      jsSB.append("			(this.subMenu ? \" unselectable='on' tabindex='-1'\" : \"\") +\r\n");
      jsSB.append("			\">\" +\r\n");
      jsSB.append("			(this.subMenu ? \"<img class='arrow' src=\\\"\" + webfxMenuImagePath + \"arrow.right.png\\\">\" : \"\") +\r\n");
      jsSB.append("			this.text +\r\n");
      jsSB.append("			\"</a>\";\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("\r\n");
      jsSB.append("function WebFXMenuSeparator() {\r\n");
      jsSB.append("	this.id = webFXMenuHandler.getId();\r\n");
      jsSB.append("	webFXMenuHandler.all[this.id] = this;\r\n");
      jsSB.append("};\r\n");
      jsSB.append("WebFXMenuSeparator.prototype.height = webfxMenuSeparatorDefaultHeight;\r\n");
      jsSB.append("WebFXMenuSeparator.prototype.toString = function () {\r\n");
      jsSB.append("	return	\"<div\" +\r\n");
      jsSB.append("			\" id='\" + this.id + \"'\" +\r\n");
      jsSB.append("			(webfxMenuUseHover ?\r\n");
      jsSB.append("			\" onmouseover='webFXMenuHandler.overMenuItem(this)'\" +\r\n");
      jsSB.append("			\" onmouseout='webFXMenuHandler.outMenuItem(this)'\"\r\n");
      jsSB.append("			:\r\n");
      jsSB.append("			\"\") +\r\n");
      jsSB.append("			\"></div>\"\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("function WebFXMenuBar() {\r\n");
      jsSB.append("	this._parentConstructor = WebFXMenu;\r\n");
      jsSB.append("	this._parentConstructor();\r\n");
      jsSB.append("}\r\n");
      jsSB.append("WebFXMenuBar.prototype = new WebFXMenu;\r\n");
      jsSB.append("WebFXMenuBar.prototype.toString = function () {\r\n");
      jsSB.append("	var str = \"<div id='\" + this.id + \"' class='webfx-menu-bar'>\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("	for (var i = 0; i < this._menuItems.length; i++)\r\n");
      jsSB.append("		str += this._menuItems[i];\r\n");
      jsSB.append("\r\n");
      jsSB.append("	str += \"</div>\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("	for (var i = 0; i < this._subMenus.length; i++)\r\n");
      jsSB.append("		str += this._subMenus[i];\r\n");
      jsSB.append("\r\n");
      jsSB.append("	return str;\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("function WebFXMenuButton(sText, sHref, sToolTip, oSubMenu) {\r\n");
      jsSB.append("	this._parentConstructor = WebFXMenuItem;\r\n");
      jsSB.append("	this._parentConstructor(sText, sHref, sToolTip, oSubMenu);\r\n");
      jsSB.append("}\r\n");
      jsSB.append("WebFXMenuButton.prototype = new WebFXMenuItem;\r\n");
      jsSB.append("WebFXMenuButton.prototype.toString = function () {\r\n");
      jsSB.append("	return	\"<a\" +\r\n");
      jsSB.append("			\" id='\" + this.id + \"'\" +\r\n");
      jsSB.append("			\" href=\\\"\" + this.href + \"\\\"\" +\r\n");
      jsSB.append("			(this.target ? \" target=\\\"\" + this.target + \"\\\"\" : \"\") +\r\n");
      jsSB.append("			(this.toolTip ? \" title=\\\"\" + this.toolTip + \"\\\"\" : \"\") +\r\n");
      jsSB.append("			(webfxMenuUseHover ?\r\n");
      jsSB.append("				(\" onmouseover='webFXMenuHandler.overMenuItem(this)'\" +\r\n");
      jsSB.append("				\" onmouseout='webFXMenuHandler.outMenuItem(this)'\") :\r\n");
      jsSB.append("				(\r\n");
      jsSB.append("					\" onfocus='webFXMenuHandler.overMenuItem(this)'\" +\r\n");
      jsSB.append("					(this.subMenu ?\r\n");
      jsSB.append("						\" onblur='webFXMenuHandler.blurMenu(this)'\" :\r\n");
      jsSB.append("						\"\"\r\n");
      jsSB.append("					)\r\n");
      jsSB.append("				)) +\r\n");
      jsSB.append("			\">\" +\r\n");
      jsSB.append("			this.text +\r\n");
      jsSB.append("			(this.subMenu ? \" <img class='arrow' src=\\\"\" + webfxMenuImagePath + \"arrow.down.png\\\" align='absmiddle'>\" : \"\") +\r\n");
      jsSB.append("			\"</a>\";\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("\r\n");
      jsSB.append("/* Position functions */\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getInnerLeft(el) {\r\n");
      jsSB.append("	if (el == null) return 0;\r\n");
      jsSB.append("	if (ieBox && el == document.body || !ieBox && el == document.documentElement) return 0;\r\n");
      jsSB.append("	return getLeft(el) + getBorderLeft(el);\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getLeft(el) {\r\n");
      jsSB.append("	if (el == null) return 0;\r\n");
      jsSB.append("	return el.offsetLeft + getInnerLeft(el.offsetParent);\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getInnerTop(el) {\r\n");
      jsSB.append("	if (el == null) return 0;\r\n");
      jsSB.append("	if (ieBox && el == document.body || !ieBox && el == document.documentElement) return 0;\r\n");
      jsSB.append("	return getTop(el) + getBorderTop(el);\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getTop(el) {\r\n");
      jsSB.append("	if (el == null) return 0;\r\n");
      jsSB.append("	return el.offsetTop + getInnerTop(el.offsetParent);\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getBorderLeft(el) {\r\n");
      jsSB.append("	return ie ?\r\n");
      jsSB.append("		el.clientLeft :\r\n");
      jsSB.append("		parseInt(window.getComputedStyle(el, null).getPropertyValue(\"border-left-width\"));\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getBorderTop(el) {\r\n");
      jsSB.append("	return ie ?\r\n");
      jsSB.append("		el.clientTop :\r\n");
      jsSB.append("		parseInt(window.getComputedStyle(el, null).getPropertyValue(\"border-top-width\"));\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function opera_getLeft(el) {\r\n");
      jsSB.append("	if (el == null) return 0;\r\n");
      jsSB.append("	return el.offsetLeft + opera_getLeft(el.offsetParent);\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function opera_getTop(el) {\r\n");
      jsSB.append("	if (el == null) return 0;\r\n");
      jsSB.append("	return el.offsetTop + opera_getTop(el.offsetParent);\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getOuterRect(el) {\r\n");
      jsSB.append("	return {\r\n");
      jsSB.append("		left:	(opera ? opera_getLeft(el) : getLeft(el)),\r\n");
      jsSB.append("		top:	(opera ? opera_getTop(el) : getTop(el)),\r\n");
      jsSB.append("		width:	el.offsetWidth,\r\n");
      jsSB.append("		height:	el.offsetHeight\r\n");
      jsSB.append("	};\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getDocumentRect(el) {\r\n");
      jsSB.append("	return {\r\n");
      jsSB.append("		left:	0,\r\n");
      jsSB.append("		top:	0,\r\n");
      jsSB.append("		width:	(ie ?\r\n");
      jsSB.append("					(ieBox ? document.body.clientWidth : document.documentElement.clientWidth) :\r\n");
      jsSB.append("					window.innerWidth\r\n");
      jsSB.append("				),\r\n");
      jsSB.append("		height:	(ie ?\r\n");
      jsSB.append("					(ieBox ? document.body.clientHeight : document.documentElement.clientHeight) :\r\n");
      jsSB.append("					window.innerHeight\r\n");
      jsSB.append("				)\r\n");
      jsSB.append("	};\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function getScrollPos(el) {\r\n");
      jsSB.append("	return {\r\n");
      jsSB.append("		left:	(ie ?\r\n");
      jsSB.append("					(ieBox ? document.body.scrollLeft : document.documentElement.scrollLeft) :\r\n");
      jsSB.append("					window.pageXOffset\r\n");
      jsSB.append("				),\r\n");
      jsSB.append("		top:	(ie ?\r\n");
      jsSB.append("					(ieBox ? document.body.scrollTop : document.documentElement.scrollTop) :\r\n");
      jsSB.append("					window.pageYOffset\r\n");
      jsSB.append("				)\r\n");
      jsSB.append("	};\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("/* end position functions */\r\n");
      jsSB.append("\r\n");
      jsSB.append("WebFXMenu.prototype.position = function (relEl, sDir) {\r\n");
      jsSB.append("	var dir = sDir;\r\n");
      jsSB.append("	var piRect;\r\n");
      jsSB.append("	if (!relEl) {\r\n");
      jsSB.append("		var pi = this.parentMenuItem;\r\n");
      jsSB.append("		if (!this.parentMenuItem)\r\n");
      jsSB.append("			return;\r\n");
      jsSB.append("\r\n");
      jsSB.append("		relEl = document.getElementById(pi.id);\r\n");
      jsSB.append("		if (dir == null)\r\n");
      jsSB.append("			dir = pi instanceof WebFXMenuButton ? \"vertical\" : \"horizontal\";\r\n");
      jsSB.append("\r\n");
      jsSB.append("		piRect = getOuterRect(relEl);\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("	else if (relEl.left != null && relEl.top != null && relEl.width != null && relEl.height != null) {	\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("	else\r\n");
      jsSB.append("		piRect = getOuterRect(relEl);\r\n");
      jsSB.append("\r\n");
      jsSB.append("	var menuEl = document.getElementById(this.id);\r\n");
      jsSB.append("	var menuRect = getOuterRect(menuEl);\r\n");
      jsSB.append("	var docRect = getDocumentRect();\r\n");
      jsSB.append("	var scrollPos = getScrollPos();\r\n");
      jsSB.append("	var pMenu = this.parentMenu;\r\n");
      jsSB.append("\r\n");
      jsSB.append("	if (dir == \"vertical\") {\r\n");
      jsSB.append("		if (piRect.left + menuRect.width - scrollPos.left <= docRect.width)\r\n");
      jsSB.append("			this.left = piRect.left;\r\n");
      jsSB.append("		else if (docRect.width >= menuRect.width)\r\n");
      jsSB.append("			this.left = docRect.width + scrollPos.left - menuRect.width;\r\n");
      jsSB.append("		else\r\n");
      jsSB.append("			this.left = scrollPos.left;\r\n");
      jsSB.append("\r\n");
      jsSB.append("		if (piRect.top + piRect.height + menuRect.height <= docRect.height + scrollPos.top)\r\n");
      jsSB.append("			this.top = piRect.top + piRect.height;\r\n");
      jsSB.append("		else if (piRect.top - menuRect.height >= scrollPos.top)\r\n");
      jsSB.append("			this.top = piRect.top - menuRect.height;\r\n");
      jsSB.append("		else if (docRect.height >= menuRect.height)\r\n");
      jsSB.append("			this.top = docRect.height + scrollPos.top - menuRect.height;\r\n");
      jsSB.append("		else\r\n");
      jsSB.append("			this.top = scrollPos.top;\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("	else {\r\n");
      jsSB.append("		if (piRect.top + menuRect.height - this.borderTop - this.paddingTop <= docRect.height + scrollPos.top)\r\n");
      jsSB.append("			this.top = piRect.top - this.borderTop - this.paddingTop;\r\n");
      jsSB.append("		else if (piRect.top + piRect.height - menuRect.height + this.borderTop + this.paddingTop >= 0)\r\n");
      jsSB.append("			this.top = piRect.top + piRect.height - menuRect.height + this.borderBottom + this.paddingBottom + this.shadowBottom;\r\n");
      jsSB.append("		else if (docRect.height >= menuRect.height)\r\n");
      jsSB.append("			this.top = docRect.height + scrollPos.top - menuRect.height;\r\n");
      jsSB.append("		else\r\n");
      jsSB.append("			this.top = scrollPos.top;\r\n");
      jsSB.append("\r\n");
      jsSB.append("		var pMenuPaddingLeft = pMenu ? pMenu.paddingLeft : 0;\r\n");
      jsSB.append("		var pMenuBorderLeft = pMenu ? pMenu.borderLeft : 0;\r\n");
      jsSB.append("		var pMenuPaddingRight = pMenu ? pMenu.paddingRight : 0;\r\n");
      jsSB.append("		var pMenuBorderRight = pMenu ? pMenu.borderRight : 0;\r\n");
      jsSB.append("\r\n");
      jsSB.append("		if (piRect.left + piRect.width + menuRect.width + pMenuPaddingRight +\r\n");
      jsSB.append("			pMenuBorderRight - this.borderLeft + this.shadowRight <= docRect.width + scrollPos.left)\r\n");
      jsSB.append("			this.left = piRect.left + piRect.width + pMenuPaddingRight + pMenuBorderRight - this.borderLeft;\r\n");
      jsSB.append("		else if (piRect.left - menuRect.width - pMenuPaddingLeft - pMenuBorderLeft + this.borderRight + this.shadowRight >= 0)\r\n");
      jsSB.append("			this.left = piRect.left - menuRect.width - pMenuPaddingLeft - pMenuBorderLeft + this.borderRight + this.shadowRight;\r\n");
      jsSB.append("		else if (docRect.width >= menuRect.width)\r\n");
      jsSB.append("			this.left = docRect.width  + scrollPos.left - menuRect.width;\r\n");
      jsSB.append("		else\r\n");
      jsSB.append("			this.left = scrollPos.left;\r\n");
      jsSB.append("	}\r\n");
      jsSB.append("};\r\n");
      jsSB.append("\r\n");
      jsSB.append("var HideElementTemp = new Array();\r\n");
      jsSB.append("\r\n");
      jsSB.append("function cal_hideElementAll(obj){ \r\n");
      jsSB.append("        cal_HideElement(\"SELECT\",obj);\r\n");
      jsSB.append("        cal_HideElement(\"IFRAME\",obj);\r\n");
      jsSB.append("}\r\n");
      jsSB.append("function cal_HideElement(strElementTagName,obj){\r\n");
      jsSB.append("try{\r\n");
      jsSB.append("    var showDivElement = obj;\r\n");
      jsSB.append("    var calendarDiv = obj;\r\n");
      jsSB.append("    var intDivLeft = cal_GetOffsetLeft(showDivElement);\r\n");
      jsSB.append("    var intDivTop = cal_GetOffsetTop(showDivElement);\r\n");
      jsSB.append("    if (strElementTagName == \"SELECT\")\r\n");
      jsSB.append("    {\r\n");
      jsSB.append("    for(i=0;i<window.document.all.tags(strElementTagName).length; i++){\r\n");
      jsSB.append(" var objTemp = window.document.all.tags(strElementTagName)[i];\r\n");
      jsSB.append(" if(!objTemp||!objTemp.offsetParent)\r\n");
      jsSB.append("     continue;\r\n");
      jsSB.append(" var intObjLeft=cal_GetOffsetLeft(objTemp);\r\n");
      jsSB.append(" var intObjTop=cal_GetOffsetTop(objTemp);\r\n");
      jsSB.append(" if(((intObjLeft+objTemp.clientWidth)>intDivLeft)&&\r\n");
      jsSB.append("    (intObjLeft<intDivLeft+calendarDiv.style.posWidth)&&\r\n");
      jsSB.append("    (intObjTop+objTemp.clientHeight>intDivTop)&&\r\n");
      jsSB.append("    (intObjTop<intDivTop+calendarDiv.style.posHeight)){\r\n");
      jsSB.append("     if (objTemp.style.visibility!=\"hidden\")\r\n");
      jsSB.append("     {\r\n");
      jsSB.append("     	HideElementTemp[HideElementTemp.length]=new Array(objTemp,calendarDiv);\r\n");
      jsSB.append("     objTemp.style.visibility=\"hidden\";\r\n");
      jsSB.append("     }\r\n");
      jsSB.append("        }\r\n");
      jsSB.append("    }\r\n");
      jsSB.append("}\r\n");
      jsSB.append("else{\r\n");
      jsSB.append("	for(i=0;i<window.document.all.tags(strElementTagName).length; i++){\r\n");
      jsSB.append(" var objTemp = window.document.all.tags(strElementTagName)[i];\r\n");
      jsSB.append(" var intframeLeft = cal_GetOffsetLeft(objTemp);\r\n");
      jsSB.append(" var intframeTop = cal_GetOffsetTop(objTemp);\r\n");
      jsSB.append(" objTemp = window.frames[i];\r\n");
      jsSB.append(" 	for (j =0;j<objTemp.document.all.tags(\"SELECT\").length;j++){\r\n");
      jsSB.append(" 		var objframeTemp=objTemp.document.all.tags(\"SELECT\")[j];\r\n");
      jsSB.append(" 		if(!objframeTemp||!objframeTemp.offsetParent)\r\n");
      jsSB.append("     continue;\r\n");
      jsSB.append(" var intObjLeft=cal_GetOffsetLeft(objframeTemp);\r\n");
      jsSB.append(" var intObjTop=cal_GetOffsetTop(objframeTemp);\r\n");
      jsSB.append(" if(((intframeLeft+intObjLeft+objframeTemp.clientWidth)>intDivLeft)&&\r\n");
      jsSB.append("    (intframeLeft+intObjLeft<intDivLeft+calendarDiv.style.posWidth)&&\r\n");
      jsSB.append("    (intframeTop+intObjTop+objframeTemp.clientHeight>intDivTop)&&\r\n");
      jsSB.append("    (intframeTop+intObjTop<intDivTop+calendarDiv.style.posHeight)){\r\n");
      jsSB.append("     if (objframeTemp.style.visibility!=\"hidden\")\r\n");
      jsSB.append("     {\r\n");
      jsSB.append("     	HideElementTemp[HideElementTemp.length]=new Array(objframeTemp,calendarDiv);\r\n");
      jsSB.append("     	objframeTemp.style.visibility=\"hidden\";\r\n");
      jsSB.append("     	}\r\n");
      jsSB.append("        }\r\n");
      jsSB.append(" 	}\r\n");
      jsSB.append(" }\r\n");
      jsSB.append("}\r\n");
      jsSB.append("}catch(e){alert(e.message)\r\n");
      jsSB.append("}\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function cal_ShowElement(obj){\r\n");
      jsSB.append("    var i,j;\r\n");
      jsSB.append("    for(i=0;i<HideElementTemp.length; i++){\r\n");
      jsSB.append(" var objTemp = HideElementTemp[i]\r\n");
      jsSB.append(" if(!objTemp[0]||!objTemp[0].offsetParent)\r\n");
      jsSB.append("     continue;\r\n");
      jsSB.append("     if (objTemp[1].id==obj.id)\r\n");
      jsSB.append("     {\r\n");
      jsSB.append(" objTemp[0].style.visibility='visible'\r\n");
      jsSB.append(" j+=1;\r\n");
      jsSB.append(" }\r\n");
      jsSB.append("}\r\n");
      jsSB.append("if (j==HideElementTemp.length)\r\n");
      jsSB.append("    HideElementTemp=new Array();\r\n");
      jsSB.append("}\r\n");
      jsSB.append("function cal_GetOffsetLeft(src){\r\n");
      jsSB.append("    var set=0;\r\n");
      jsSB.append("    if(src && src.name!=\"divMain\"){\r\n");
      jsSB.append("        if (src.offsetParent){\r\n");
      jsSB.append("           set+=src.offsetLeft+cal_GetOffsetLeft(src.offsetParent);\r\n");
      jsSB.append(" }\r\n");
      jsSB.append(" if(src.tagName.toUpperCase()!=\"BODY\"){\r\n");
      jsSB.append("     var x=parseInt(src.scrollLeft,10);\r\n");
      jsSB.append("     if(!isNaN(x))\r\n");
      jsSB.append("            set-=x;\r\n");
      jsSB.append(" }\r\n");
      jsSB.append("    }\r\n");
      jsSB.append("    return set;\r\n");
      jsSB.append("}\r\n");
      jsSB.append("\r\n");
      jsSB.append("function cal_GetOffsetTop(src){\r\n");
      jsSB.append("    var set=0;\r\n");
      jsSB.append("    if(src && src.name!=\"divMain\"){\r\n");
      jsSB.append("        if (src.offsetParent){\r\n");
      jsSB.append("            set+=src.offsetTop+cal_GetOffsetTop(src.offsetParent);\r\n");
      jsSB.append("   }\r\n");
      jsSB.append(" if(src.tagName.toUpperCase()!=\"BODY\"){\r\n");
      jsSB.append("     var y=parseInt(src.scrollTop,10);\r\n");
      jsSB.append("     if(!isNaN(y))\r\n");
      jsSB.append("  set-=y;\r\n");
      jsSB.append(" }\r\n");
      jsSB.append("    }\r\n");
      jsSB.append("    return set;\r\n");
      jsSB.append("}");

    jstool.js=jsSB;
    return jstool.getComponentJS();
  }
}
