/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.daointerface;

// auto generated imports
import com.born.insurance.dal.dataobject.BillPayFeeDetailDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>bill_pay_fee_detail</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/bill_pay_fee_detail.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface BillPayFeeDetailDAO {
	/**
	 *  Insert one <tt>BillPayFeeDetailDO</tt> object to DB table <tt>bill_pay_fee_detail</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into bill_pay_fee_detail(id,settlement_apply_id,business_bill_id,receiver_name,insurance_broker_no,generation_fee,service_fee,pay_fee,withhold_taxes,actual_pay_fee,row_add_time,row_update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param billPayFeeDetail
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(BillPayFeeDetailDO billPayFeeDetail) throws DataAccessException;

	/**
	 *  Update DB table <tt>bill_pay_fee_detail</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update bill_pay_fee_detail set settlement_apply_id=?, business_bill_id=?, receiver_name=?, insurance_broker_no=?, generation_fee=?, service_fee=?, pay_fee=?, withhold_taxes=?, actual_pay_fee=?, row_add_time=?, row_update_time=? where (id = ?)</tt>
	 *
	 *	@param billPayFeeDetail
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(BillPayFeeDetailDO billPayFeeDetail) throws DataAccessException;

	/**
	 *  Query DB table <tt>bill_pay_fee_detail</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, settlement_apply_id, business_bill_id, receiver_name, insurance_broker_no, generation_fee, service_fee, pay_fee, withhold_taxes, actual_pay_fee, row_add_time, row_update_time from bill_pay_fee_detail where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return BillPayFeeDetailDO
	 *	@throws DataAccessException
	 */	 
    public BillPayFeeDetailDO findById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>bill_pay_fee_detail</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from bill_pay_fee_detail where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>bill_pay_fee_detail</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, settlement_apply_id, business_bill_id, receiver_name, insurance_broker_no, generation_fee, service_fee, pay_fee, withhold_taxes, actual_pay_fee, row_add_time, row_update_time from bill_pay_fee_detail where (1 = 1)</tt>
	 *
	 *	@param billPayFeeDetail
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<BillPayFeeDetailDO>
	 *	@throws DataAccessException
	 */	 
    public List<BillPayFeeDetailDO> findByCondition(BillPayFeeDetailDO billPayFeeDetail, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>bill_pay_fee_detail</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from bill_pay_fee_detail where (1 = 1)</tt>
	 *
	 *	@param billPayFeeDetail
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(BillPayFeeDetailDO billPayFeeDetail) throws DataAccessException;

	/**
	 *  Query DB table <tt>bill_pay_fee_detail</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, settlement_apply_id, business_bill_id, receiver_name, insurance_broker_no, generation_fee, service_fee, pay_fee, withhold_taxes, actual_pay_fee, row_add_time, row_update_time from bill_pay_fee_detail where (settlement_apply_id = ?)</tt>
	 *
	 *	@param settlementApplyId
	 *	@return List<BillPayFeeDetailDO>
	 *	@throws DataAccessException
	 */	 
    public List<BillPayFeeDetailDO> findBySettlementApplyId(long settlementApplyId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>bill_pay_fee_detail</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from bill_pay_fee_detail where (settlement_apply_id = ?)</tt>
	 *
	 *	@param settlementApplyId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteBysettlementApplyId(long settlementApplyId) throws DataAccessException;

}