/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.daointerface;

// auto generated imports
import com.born.insurance.dal.dataobject.BusinessBillReinsInfoDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>business_bill_reins_info</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/business_bill_reins_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface BusinessBillReinsInfoDAO {
	/**
	 *  Insert one <tt>BusinessBillReinsInfoDO</tt> object to DB table <tt>business_bill_reins_info</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into business_bill_reins_info(reins_info_id,insurace_company_id,insurace_company_name,premium_amount,poundage_amount,business_bill_id) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param businessBillReinsInfo
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(BusinessBillReinsInfoDO businessBillReinsInfo) throws DataAccessException;

	/**
	 *  Update DB table <tt>business_bill_reins_info</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update business_bill_reins_info set insurace_company_id=?, insurace_company_name=?, premium_amount=?, poundage_amount=?, business_bill_id=? where (reins_info_id = ?)</tt>
	 *
	 *	@param businessBillReinsInfo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(BusinessBillReinsInfoDO businessBillReinsInfo) throws DataAccessException;

	/**
	 *  Query DB table <tt>business_bill_reins_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select reins_info_id, insurace_company_id, insurace_company_name, premium_amount, poundage_amount, business_bill_id from business_bill_reins_info where (reins_info_id = ?)</tt>
	 *
	 *	@param reinsInfoId
	 *	@return BusinessBillReinsInfoDO
	 *	@throws DataAccessException
	 */	 
    public BusinessBillReinsInfoDO findById(long reinsInfoId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>business_bill_reins_info</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from business_bill_reins_info where (reins_info_id = ?)</tt>
	 *
	 *	@param reinsInfoId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long reinsInfoId) throws DataAccessException;

	/**
	 *  Query DB table <tt>business_bill_reins_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select reins_info_id, insurace_company_id, insurace_company_name, premium_amount, poundage_amount, business_bill_id from business_bill_reins_info where (1 = 1)</tt>
	 *
	 *	@param businessBillReinsInfo
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<BusinessBillReinsInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<BusinessBillReinsInfoDO> findByCondition(BusinessBillReinsInfoDO businessBillReinsInfo, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>business_bill_reins_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from business_bill_reins_info where (1 = 1)</tt>
	 *
	 *	@param businessBillReinsInfo
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(BusinessBillReinsInfoDO businessBillReinsInfo) throws DataAccessException;

	/**
	 *  Query DB table <tt>business_bill_reins_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select reins_info_id, insurace_company_id, insurace_company_name, premium_amount, poundage_amount, business_bill_id from business_bill_reins_info where (business_bill_id = ?)</tt>
	 *
	 *	@param businessBillId
	 *	@return List<BusinessBillReinsInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<BusinessBillReinsInfoDO> findBusinessBillReinsInfo(long businessBillId) throws DataAccessException;

}