/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.daointerface;

// auto generated imports
import com.born.insurance.dal.dataobject.ChargeNoticeDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>charge_notice</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/charge_notice.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface ChargeNoticeDAO {
	/**
	 *  Insert one <tt>ChargeNoticeDO</tt> object to DB table <tt>charge_notice</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into charge_notice(id,form_id,business_bill_id,depart,team,notice_date,insurance_no,insurance_type_name,bill_customer_name,premium_amount,recievable_fee,recieved_fee,pay_fee,reserved_scale,notice_no,bill_no,insurance_broker_no,insurance_broker_name,commission_type,persistency_rate_ward,manage_grant,package_fee,insurance_other,row_add_time,row_update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param chargeNotice
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(ChargeNoticeDO chargeNotice) throws DataAccessException;

	/**
	 *  Update DB table <tt>charge_notice</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update charge_notice set form_id=?, business_bill_id=?, depart=?, team=?, notice_date=?, insurance_no=?, insurance_type_name=?, bill_customer_name=?, premium_amount=?, recievable_fee=?, recieved_fee=?, pay_fee=?, reserved_scale=?, notice_no=?, bill_no=?, insurance_broker_no=?, insurance_broker_name=?, commission_type=?, persistency_rate_ward=?, manage_grant=?, package_fee=?, insurance_other=?, row_add_time=?, row_update_time=? where (id = ?)</tt>
	 *
	 *	@param chargeNotice
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(ChargeNoticeDO chargeNotice) throws DataAccessException;

	/**
	 *  Query DB table <tt>charge_notice</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, business_bill_id, depart, team, notice_date, insurance_no, insurance_type_name, bill_customer_name, premium_amount, recievable_fee, recieved_fee, pay_fee, reserved_scale, notice_no, bill_no, insurance_broker_no, insurance_broker_name, commission_type, persistency_rate_ward, manage_grant, package_fee, insurance_other, row_add_time, row_update_time from charge_notice where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return ChargeNoticeDO
	 *	@throws DataAccessException
	 */	 
    public ChargeNoticeDO findById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>charge_notice</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from charge_notice where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>charge_notice</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, business_bill_id, depart, team, notice_date, insurance_no, insurance_type_name, bill_customer_name, premium_amount, recievable_fee, recieved_fee, pay_fee, reserved_scale, notice_no, bill_no, insurance_broker_no, insurance_broker_name, commission_type, persistency_rate_ward, manage_grant, package_fee, insurance_other, row_add_time, row_update_time from charge_notice where (1 = 1)</tt>
	 *
	 *	@param chargeNotice
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<ChargeNoticeDO>
	 *	@throws DataAccessException
	 */	 
    public List<ChargeNoticeDO> findByCondition(ChargeNoticeDO chargeNotice, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>charge_notice</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from charge_notice where (1 = 1)</tt>
	 *
	 *	@param chargeNotice
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(ChargeNoticeDO chargeNotice) throws DataAccessException;

	/**
	 *  Query DB table <tt>charge_notice</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, business_bill_id, depart, team, notice_date, insurance_no, insurance_type_name, bill_customer_name, premium_amount, recievable_fee, recieved_fee, pay_fee, reserved_scale, notice_no, bill_no, insurance_broker_no, insurance_broker_name, commission_type, persistency_rate_ward, manage_grant, package_fee, insurance_other, row_add_time, row_update_time from charge_notice where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return ChargeNoticeDO
	 *	@throws DataAccessException
	 */	 
    public ChargeNoticeDO findByFormId(long formId) throws DataAccessException;

	/**
	 *  Query DB table <tt>charge_notice</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, business_bill_id, depart, team, notice_date, insurance_no, insurance_type_name, bill_customer_name, premium_amount, recievable_fee, recieved_fee, pay_fee, reserved_scale, notice_no, bill_no, insurance_broker_no, insurance_broker_name, commission_type, persistency_rate_ward, manage_grant, package_fee, insurance_other, row_add_time, row_update_time from charge_notice where (business_bill_id = ?)</tt>
	 *
	 *	@param businessBillId
	 *	@return ChargeNoticeDO
	 *	@throws DataAccessException
	 */	 
    public ChargeNoticeDO findByBusinessBillId(long businessBillId) throws DataAccessException;

}