/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.daointerface;

// auto generated imports
import com.born.insurance.dal.dataobject.CommonAttachmentDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>common_attachment</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/common_attachment.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface CommonAttachmentDAO {
	/**
	 *  Insert one <tt>CommonAttachmentDO</tt> object to DB table <tt>common_attachment</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into common_attachment(attachment_id,biz_no,child_id,module_type,check_status,file_name,isort,file_physical_path,request_path,uploader_id,uploader_account,uploader_name,project_code,remark,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param commonAttachment
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(CommonAttachmentDO commonAttachment) throws DataAccessException;

	/**
	 *  Update DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update common_attachment set biz_no=?, child_id=?, module_type=?, check_status=?, file_name=?, isort=?, file_physical_path=?, request_path=?, uploader_id=?, uploader_account=?, uploader_name=?, project_code=?, remark=? where (attachment_id = ?)</tt>
	 *
	 *	@param commonAttachment
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(CommonAttachmentDO commonAttachment) throws DataAccessException;

	/**
	 *  Update DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update common_attachment set check_status=? where ((biz_no = ?) AND (module_type = ?))</tt>
	 *
	 *	@param checkStatus
	 *	@param bizNo
	 *	@param moduleType
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStatusAllSame(String checkStatus, String bizNo, String moduleType) throws DataAccessException;

	/**
	 *  Update DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update common_attachment set check_status=?</tt>
	 *
	 *	@param commonAttachment
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStatusCondition(CommonAttachmentDO commonAttachment) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from common_attachment where (attachment_id = ?)</tt>
	 *
	 *	@param attachmentId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long attachmentId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from common_attachment where (file_physical_path = ?)</tt>
	 *
	 *	@param filePhysicalPath
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByPicpath(String filePhysicalPath) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from common_attachment where ((file_physical_path = ?) AND (check_status <> "CHECK_PASS"))</tt>
	 *
	 *	@param filePhysicalPath
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByPicpathNotCheck(String filePhysicalPath) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from common_attachment where ((biz_no = ?) AND (module_type = ?))</tt>
	 *
	 *	@param bizNo
	 *	@param moduleType
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByBizNoModuleType(String bizNo, String moduleType) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from common_attachment where ((biz_no = ?) AND (module_type = ?) AND (child_id = ?))</tt>
	 *
	 *	@param bizNo
	 *	@param moduleType
	 *	@param childId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByBizNoAndChildIdModuleType(String bizNo, String moduleType, String childId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>common_attachment</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from common_attachment where ((biz_no = ?) AND (module_type = ?) AND (check_status <> "CHECK_PASS"))</tt>
	 *
	 *	@param bizNo
	 *	@param moduleType
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByBizNoModuleTypeNotCheck(String bizNo, String moduleType) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from common_attachment where (attachment_id = ?)</tt>
	 *
	 *	@param attachmentId
	 *	@return CommonAttachmentDO
	 *	@throws DataAccessException
	 */	 
    public CommonAttachmentDO findById(long attachmentId) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from common_attachment where (file_physical_path = ?)</tt>
	 *
	 *	@param filePhysicalPath
	 *	@return List<CommonAttachmentDO>
	 *	@throws DataAccessException
	 */	 
    public List<CommonAttachmentDO> findByPicpath(String filePhysicalPath) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from common_attachment where ((file_physical_path = ?) AND (check_status <> "CHECK_PASS"))</tt>
	 *
	 *	@param filePhysicalPath
	 *	@return List<CommonAttachmentDO>
	 *	@throws DataAccessException
	 */	 
    public List<CommonAttachmentDO> findByPicpathNotCheck(String filePhysicalPath) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from common_attachment where ((file_physical_path = ?) AND (check_status = "CHECK_PASS"))</tt>
	 *
	 *	@param filePhysicalPath
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findCountByPicpathCheckPass(String filePhysicalPath) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from common_attachment where ((biz_no = ?) AND (module_type = ?)) order by isort ASC</tt>
	 *
	 *	@param commonAttachment
	 *	@return List<CommonAttachmentDO>
	 *	@throws DataAccessException
	 */	 
    public List<CommonAttachmentDO> findByBizNoModuleType(CommonAttachmentDO commonAttachment) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from common_attachment where ((biz_no = ?) AND (module_type = ?) AND (child_id = ?)) order by isort ASC</tt>
	 *
	 *	@param commonAttachment
	 *	@return List<CommonAttachmentDO>
	 *	@throws DataAccessException
	 */	 
    public List<CommonAttachmentDO> findByBizNoChildIdModuleType(CommonAttachmentDO commonAttachment) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from common_attachment where (1 = 2) order by isort ASC</tt>
	 *
	 *	@param moduleTypeList
	 *	@param bizNo
	 *	@param childId
	 *	@return List<CommonAttachmentDO>
	 *	@throws DataAccessException
	 */	 
    public List<CommonAttachmentDO> findByManyModuleType(List moduleTypeList, String bizNo, String childId) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from common_attachment</tt>
	 *
	 *	@param commonAttachment
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long searchDataCount(CommonAttachmentDO commonAttachment) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from common_attachment</tt>
	 *
	 *	@param isort
	 *	@param bizNo
	 *	@param childId
	 *	@return List<CommonAttachmentDO>
	 *	@throws DataAccessException
	 */	 
    public List<CommonAttachmentDO> findByIsort(long isort, String bizNo, String childId) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from common_attachment</tt>
	 *
	 *	@param commonAttachment
	 *	@param moduleTypeList
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<CommonAttachmentDO>
	 *	@throws DataAccessException
	 */	 
    public List<CommonAttachmentDO> findCondition(CommonAttachmentDO commonAttachment, List moduleTypeList, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>common_attachment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from common_attachment</tt>
	 *
	 *	@param commonAttachment
	 *	@param moduleTypeList
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findConditionCount(CommonAttachmentDO commonAttachment, List moduleTypeList) throws DataAccessException;

}