/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.daointerface;

// auto generated imports
import com.born.insurance.dal.dataobject.PriceContactLetterCompanyReportPriceDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>price_contact_letter_company_report_price</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/price_contact_letter_company_report_price.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface PriceContactLetterCompanyReportPriceDAO {
	/**
	 *  Insert one <tt>PriceContactLetterCompanyReportPriceDO</tt> object to DB table <tt>price_contact_letter_company_report_price</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into price_contact_letter_company_report_price(id,customer_user_id,customer_user_name,report_price_id,premium_amount,broker_amount,broker_amount_rate,create_date,expense_amount,difference_content,special_agreement,quotation_prerequisite,expiry_date,contactUserId,contactUserName,contactUserMobile,contactUserEmail,remark,version,ext) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param priceContactLetterCompanyReportPrice
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(PriceContactLetterCompanyReportPriceDO priceContactLetterCompanyReportPrice) throws DataAccessException;

	/**
	 *  Update DB table <tt>price_contact_letter_company_report_price</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update price_contact_letter_company_report_price set customer_user_id=?, customer_user_name=?, report_price_id=?, premium_amount=?, broker_amount=?, broker_amount_rate=?, create_date=?, expense_amount=?, difference_content=?, special_agreement=?, quotation_prerequisite=?, expiry_date=?, contactUserId=?, contactUserName=?, contactUserMobile=?, contactUserEmail=?, remark=?, version=?, ext=? where (id = ?)</tt>
	 *
	 *	@param priceContactLetterCompanyReportPrice
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(PriceContactLetterCompanyReportPriceDO priceContactLetterCompanyReportPrice) throws DataAccessException;

	/**
	 *  Query DB table <tt>price_contact_letter_company_report_price</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, customer_user_id, customer_user_name, report_price_id, premium_amount, broker_amount, broker_amount_rate, create_date, expense_amount, difference_content, special_agreement, quotation_prerequisite, expiry_date, contactUserId, contactUserName, contactUserMobile, contactUserEmail, remark, version, ext from price_contact_letter_company_report_price where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return PriceContactLetterCompanyReportPriceDO
	 *	@throws DataAccessException
	 */	 
    public PriceContactLetterCompanyReportPriceDO findById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>price_contact_letter_company_report_price</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from price_contact_letter_company_report_price where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>price_contact_letter_company_report_price</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from price_contact_letter_company_report_price where (1 = 1)</tt>
	 *
	 *	@param priceContactLetterCompanyReportPrice
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<PriceContactLetterCompanyReportPriceDO>
	 *	@throws DataAccessException
	 */	 
    public List<PriceContactLetterCompanyReportPriceDO> findByCondition(PriceContactLetterCompanyReportPriceDO priceContactLetterCompanyReportPrice, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>price_contact_letter_company_report_price</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from price_contact_letter_company_report_price where (1 = 1)</tt>
	 *
	 *	@param priceContactLetterCompanyReportPrice
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(PriceContactLetterCompanyReportPriceDO priceContactLetterCompanyReportPrice) throws DataAccessException;

}