/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.daointerface;

// auto generated imports
import com.born.insurance.dal.dataobject.SalesAreaDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>sales_areas</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sales_areas.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface SalesAreaDAO {
	/**
	 *  Insert one <tt>SalesAreaDO</tt> object to DB table <tt>sales_areas</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sales_areas(id,product_id,province_code,province_name,is_all_province,city_code,city_name,type) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param salesArea
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(SalesAreaDO salesArea) throws DataAccessException;

	/**
	 *  Update DB table <tt>sales_areas</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sales_areas set product_id=?, province_code=?, province_name=?, is_all_province=?, city_code=?, city_name=?, type=? where (id = ?)</tt>
	 *
	 *	@param salesArea
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(SalesAreaDO salesArea) throws DataAccessException;

	/**
	 *  Query DB table <tt>sales_areas</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, product_id, province_code, province_name, is_all_province, city_code, city_name, type from sales_areas where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return SalesAreaDO
	 *	@throws DataAccessException
	 */	 
    public SalesAreaDO findById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sales_areas</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sales_areas where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sales_areas</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sales_areas where ((product_id = ?) AND (type = ?))</tt>
	 *
	 *	@param productId
	 *	@param type
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByProductIdAndType(long productId, String type) throws DataAccessException;

	/**
	 *  Query DB table <tt>sales_areas</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, product_id, province_code, province_name, is_all_province, city_code, city_name, type from sales_areas where (1 = 1)</tt>
	 *
	 *	@param salesArea
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<SalesAreaDO>
	 *	@throws DataAccessException
	 */	 
    public List<SalesAreaDO> findByCondition(SalesAreaDO salesArea, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>sales_areas</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from sales_areas where (1 = 1)</tt>
	 *
	 *	@param salesArea
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(SalesAreaDO salesArea) throws DataAccessException;

}