/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.daointerface;

// auto generated imports
import com.born.insurance.dal.dataobject.SysWebAccessTokenDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>sys_web_access_token</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_web_access_token.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface SysWebAccessTokenDAO {
	/**
	 *  Insert one <tt>SysWebAccessTokenDO</tt> object to DB table <tt>sys_web_access_token</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sys_web_access_token(id,user_id,user_name,user_account,access_token,is_valid,remark,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param sysWebAccessToken
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(SysWebAccessTokenDO sysWebAccessToken) throws DataAccessException;

	/**
	 *  Update DB table <tt>sys_web_access_token</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sys_web_access_token set user_id=?, user_name=?, user_account=?, access_token=?, is_valid=?, remark=? where (id = ?)</tt>
	 *
	 *	@param sysWebAccessToken
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(SysWebAccessTokenDO sysWebAccessToken) throws DataAccessException;

	/**
	 *  Query DB table <tt>sys_web_access_token</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from sys_web_access_token where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return SysWebAccessTokenDO
	 *	@throws DataAccessException
	 */	 
    public SysWebAccessTokenDO findById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>sys_web_access_token</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from sys_web_access_token where (id = ?) for update</tt>
	 *
	 *	@param id
	 *	@return SysWebAccessTokenDO
	 *	@throws DataAccessException
	 */	 
    public SysWebAccessTokenDO findByIdForUpdate(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sys_web_access_token</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sys_web_access_token where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>sys_web_access_token</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sys_web_access_token set is_valid='IS' where (access_token = ?)</tt>
	 *
	 *	@param accessToken
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int validByToken(String accessToken) throws DataAccessException;

	/**
	 *  Update DB table <tt>sys_web_access_token</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sys_web_access_token set is_valid='NO' where (access_token = ?)</tt>
	 *
	 *	@param accessToken
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int invalidByToken(String accessToken) throws DataAccessException;

	/**
	 *  Query DB table <tt>sys_web_access_token</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from sys_web_access_token where (1 = 1)</tt>
	 *
	 *	@param sysWebAccessToken
	 *	@return List<SysWebAccessTokenDO>
	 *	@throws DataAccessException
	 */	 
    public List<SysWebAccessTokenDO> findList(SysWebAccessTokenDO sysWebAccessToken) throws DataAccessException;

}