var _lp = {
	week:{
		'Sun':'星期日', 'Mon':'星期一', 'Tue':'星期二', 'Wed':'星期三', 'Thr':'星期四', 'Fri':'星期五', 'Sat':'星期六'
	},
	des:{
		unit:'单位',
		length:'长度',
		character:'个字符',
		min:'最小值',
		max:'最大值',
		password:'显示密码',
		m_password:'修改密码',		
		none:'空',
		always:'全部',
		everyday:'每天',
		weekly:'每周',
		start:'开始时间',
		end:'结束时间',
		week:'星期',
		note1:'必须小于',
		note2:'开始绘制',
		note3:'停止绘制',
		note4:'删除区域',
		note5:'清除区域',
		note6:'东视设备接入协议',		
		idle:'空闲',
		p_type:'协议类型',
		address:'地址',		
		user:'用户',
		password:'密码',
		mobilephone:'手机号码',
		add_m:'添加手机号码',
		modify_m:'修改手机号码',									
		submit:'提　　交',
		status:{
			success:'接入成功',
			free:'空闲',
			registering:'正在接入',
			reporting:'正在接入:(正在汇报配置)',
			dns_failed:'正在接入:(域名解释失败)',	
			proxy_failed:'正在接入:(连接代理失败)',
			route_failed:'正在接入:(路由失败)',
			unreachable:'正在接入:(地址不可达)',
			no_service:'正在接入:(服务未开启)',
			invalid_puid:'正在接入:(PUID不存在)',
			invalid_password:'正在接入:(接入密码错误)',
			forbidden_puid:'正在接入:(PUID被禁用)',  	
			registered_puid:'正在接入:(PUID已经上线)',
			registered_decid:'正在接入:(设备ID已在线)',		
			puis_full:'正在接入:(达到最大连接数)',
			unkown:'正在接入:(其他错误)'	
		}													
	},		
	y:'是',
	n:'否',
	title:'网络视频监控系统',
	frame:{
		notes:{
			support_title:'您浏览器版本过低可能会导致部分功能使用不正常，强烈建议您升级浏览器IE9及IE9以上版本或者chrome浏览器。',
			waiting_title1:'提示',
			error_title2:'错误',
			reboot_waiting:'设备正在重启,请稍候......',
			reboot_success:'设备正在重启成功！',	
			login_waiting:'正在登录,请稍候......',
			query_waiting:'正在查询,请稍候......',
			error_msg1:'登录失败,请下载插件,安装后重新启动浏览器后,再登录.',
			error_msg2:'登录失败',
			error_msg3:'您的插件版本过低,请重新下载插件,安装后重新启动浏览器后,再登录.',
			pu_online:'设备上线',
			pu_offline:'设备下线'
            	
		},
		pulist:{
			title:'设备列表',
			gr_col:{
				name:'设备名称'
			}
		},
		login:{
			title:'登录',
			btn_login:'登录',
			btn_exit:'退出',
			btn_download:'插件下载',
			ip:{
				fieldLabel: '地址',
				missingMessage: '请输入平台地址,其不可为空'
			},
			port:{
				fieldLabel: '端口',
				missingMessage: '请输入平台端口,不能为空.'
			},
			uid:{
                fieldLabel: '用户名',
                missingMessage: '请输入用户名'
			},
			epId:{
                fieldLabel: '企业ID',
                missingMessage: '请输入企业ID,不能为空'
			},
			password:{
                fieldLabel: '密码',
                missingMessage: '请输入登录密码'
			},
			remember:{
                boxLabel: '记住密码'
			},
			bfix:{
				fieldLabel:'透过网闸'
			}
		},
		navbar:{
			st:{
				title:'系统'
			},
			iv:{
				title:'视频'
			},
			ia:{
				title:'伴音'
			},
			ov:{
				title:'输出视频'
			},
			oa:{
				title:'对讲'
			},
			ptz:{
				title:'云台'
			},
			sp:{
				title:'串口'
			},
			idl:{
				title:'报警输入'
			},
			odl:{
				title:'报警输出'
			},
			sg:{
				title:'存储'
			},
			wifi:{
				title:'WiFi'
			},
			wm:{
				title:'4G/3G'
			},
			dp:{
				title:'显示设备'
			},
			gps:{
				title:'卫星定位'
			}		        
		},
		player:{
			title:'实时监控',
			cameraTitle:'视频头',
			audioOutTitle:'对讲控制',
			alertInTitle:'报警输入',
			alertOutTitle:'报警输出',
			cameralist:{
				streamType:'视频流',
				btns:{
					playall:'全播',
					stopall:'全停',
					play:'播放',
					stop:'停止'
				},
				col:{
					name:'名称',
					op:'操作'
				}
			},
			audioout_list:{
				col:{
					name:'名称',
					status:'状态',
					op:'操作'
				},
				btns:{
					call:'喊话',
					talk:'对讲',
					closecall:'关闭喊话',
					closetalk:'关闭对讲'
				},
				status_map:{
					"Free":"空闲",
					"TeamTalking":"集群对讲中",
					"Talking":"对讲中",
					"Calling":"喊话中"
				}
			},
			alertin_list:{
				col:{
					name:'名称',
					status:'状态',
					op:'操作'
				},
				status_map:{
					"alert":"有报警",
					"noalert":"无报警",
					"valid":"有效",
					"invalid":"无效"
				}
			},
			alertout_list:{
				col:{
					name:'名称',
					connect:'通',
					"break":'断',
					pulse:'闪',
					status:'状态'
				}
			},
			ptzTitle:'云台控制',
			prepostion:{
				lbl:'预置位',
				go:'前往',
				set:'设置',
				rename:'命名',
				renameTitle:'重命名预置位名称',
				name:{
					lbl:'名称'
				}
			},
			adl:{
				renameTitle:'重命名辅助设备名称',
				lbl:'辅助设备',
				open:'开启',
				close:'关闭',
				rename:'命名',
				name:{
					lbl:'名称'
				}
			},
			tour:{
				setTitle:'编辑巡航路线',
				setTitle1:'巡航路线列表',	
				lbl:'巡航路线',
				start:'启动',
				stop:'停止',
				set:'编辑',
				add:'添加预置位',
				up:'向上',
				down:'向下',
				sub:'删除',
				add1:'添加',				
				name:{
					lbl:'名称'
				},
				edit_list:{
					col:{
						id:'编号',
						name:'预置位',
						linger:'停留时间',
						op:'操作'
					}
				}
			},
			autoscan:{
				lbl:'自动扫描',
				start:'启动',
				stop:'停止',
				seta:'设置启点',
				setb:'设置终点'
			},
			
			notes:{
				noVideo:'无视频',
				snapshot:'本地抓图',
				record:'本地录像',
				playaudio:'播放音频',
				playupaudio:'开始喊话',
				playtalk:'开始对讲',
				stopvideo:'关闭视频',
				fullscreen:'全屏',
				connecting:'正在请求视频',
				streambreak:'流已断开',
				buffering:'正在缓冲',
				playing:'正在播放',
				downing:'正在下载',
				recording:'正在录像',
				audioing:'正在播放声音',
				upaudioing:'正在喊话',
				talking:'正在对讲',
				frame:'帧率',
				bite:'码率',
				audioing:'正在播放声音',
				playfailed:'播放失败',
				noteTitle1:'提示',
				note1:'设置成功.',
				noteError1:'设置失败',
				noteError2:'没有选择播放视频的窗口',
				noteError3:'视频已经在播放，请不要重复播放。',
			},
			btns:{
				save:'保存',
				cancel:'取消',
				del:'删除',
				ok:'确定'
			}
		},
		vod:{
			title:'查询下载',
			file_list:{
				col:{
    		        beginTime:'开始时间',
    		        endTime:'结束时间',
    		        reason:'原因',
					path:'路径',
					name:'文件名',
					size:'大小',
					savePath:'保存地址',
					status:'状态',
					downloadLength:'已经下载大小',
					process:'进度',
					op:'操作'
				}
			},
			record:{
				filelist_title:'录像文件',
				camera_title:'资源列表',
				title:'录像',
				fast_index:'快速索引',
				adv_query:'高级查询'
			},
			snapshot:{
				filelist_title:'图片文件',
				title:'图片',
				fast_index:'快速索引',
				adv_query:'高级查询'
			},
			event:{
				title:'事件'
			},
			log:{
				title:'日志'
			}
		},
		configsets:{
			title:'设备配置',
			renameTitle:'修改名称',
			setDescTitle:'设置描述',
			setSchedule:'设置时间',
			notes:{
				noteTitle:'提示',	
				note:'设置成功',
				noteError:'设置失败',
				note1:'设置资源名称成功',
				noteError1:'设置资源名称失败',
				note2:'设置资源描述成功',
				noteError2:'设置资源描述失败',
				note3:'资源使能成功',
				noteError3:'资源使能失败',
				noteTitle1:'确认',
				note4:'您确定要删除这条平台地址信息么？',
				note5:'删除平台地址成功',
				note6:'发送控制命令失败（命令不正确）',
				note7:'发送控制命令成功',
				note8:'发送控制命令失败',
				note9:'您确定重启设备么？',
				note10:'您确定要把设备恢复出厂设置么？',
				note11:'添加IP通道成功',
				note12:'修改IP通道成功',
				note13:'删除IP通道成功',
				note14:'添加手机号码成功',
				note15:'修改手机号码成功',
				note16:'设置备份盘成功',
				note17:'您确定要格式磁盘么？',
				note18:'格式化磁盘成功',
				note19:'添加前端联动成功',
				note20:'修改前端联动成功',
				note21:'删除前端联动成功',	
				note21:'个字符'		
			},			
			btns:{
				rename:'重命名',
				disabled:'禁用',
				enable:'启用',
				set:'设置',
				refresh:'刷新',
				add:'添加',
				modify:'修改',
				clean:'清除',
				del:'删除',
				ok:'提交',
				okall:'提交到所有通道',
				close:'关闭',
				restore:'恢复出厂设置',
				reboot:'重启',
				online:'上线',
				offline:'下线',
				scanAP:'扫描WiFi热点',
				selectedAP:'选用',
				aperture:'自动光圈校正',
				forceDay:'强制白天参数',
				forceNight:'强制夜间参数',
				autoDayNight:'自动日夜参数',
				sendSPData:'发送串口数据',
				inData:'输入数据（十六进制）',
				send:'发送',
				setBackup:'设为备份盘',
				cancelBackup:'取消备份盘',
				formatSD:'格式化',
				resetCounter:'清空计数值',
				resetOnlineTotalTime:'复位在线时间',
				resetSMBytes:'复位数据流量'		
			},
			st:{
				name:{
					lbl:'名称'
				},
				idx:{
					lbl:'索引'
				},
				bEnable:{
					lbl:'是否可用'
				},
				desc:{
					lbl:'描述'
				},
				dt:{
					lbl:'当前时间'
				},
				control:{
					lbl:'控制'
				}
			},
			sg:{
				dk_gr_title:'磁盘列表',
				dk_gr_col:{
					volumeLabel:'卷标',
					letter:'盘符',
					backup:'备份',
					type:'类型',
					fileSystem:'文件系统',
					usableSpace:'剩余空间',
					usedSpace:'已用空间',
					capacity:'容量',
					status:'状态'
				}
			},
			ap:{
				gr_col:{
					ssid:'SSID',
					auth:'认证方式',
					signal:'信号强度',
					isuse:'是否在用',
					y:'是',
					n:'否'
				}
			},
			address_list:{
				col:{
					address:'平台地址',
					status:'接入状态',
					op:'操作'
				}
			},
			session_list:{
				col:{
					userId:'用户名',
					clientType:'客户端类型',
					loginTime:'登录时间',
					sourceAddr:'来源地址'
				}
			},
			stream_list:{
				col:{
					resType:'资源类型',
					stream:'资源索引',
					resIdx:'流ID',
					createTime:'建立时间',
					peerAddr:'来源地址',
					totalBytes:'收发字节数'
				}
			},
			address:{
				lbl:'平台地址',
				addTitle:'添加平台地址',
				modifyTitle:'修改平台地址'			
			
			},
			ipchannelsets_list:{
				addTitle:'添加通道',
				modifyTitle:'修改通道',
				col:{
					producerId:'协议类型',
					addr:'地址',
					userId:'用户',
					password:'密码',
					resIdx:'资源编号',
					connectStatus:'连接状态',
					usedCodeCapability:'消耗编码',
					usedBandwidth:'消耗带宽',
					op:'操作'
				},
				producers:['iCAP','ONVIF','空闲']
			},
			devicelinkactions_list:{
				addTitle:'添加联动',
				modifyTitle:'修改联动',
				col:{
					eventType:'事件类型',
					src:'事件源',
					model:'布防模式',
					models:'模式',	
					modelTime:'布防时间',	
					action:'联动动作',
					actionParams:'动作参数',
					alertOutStream:'报警输出通道',
					alertOutAction:'报警输出动作',
					inputVideoNo:'视频通道',
					recordTime:'录像持续时间',
					snapShotMumber:'抓拍张数',
					snapShotInterval:'抓拍间隔',
					presetPositionNo:'预置位编号',
					recordUnit:'（分钟）',
					snapShotUnit:'（张）',
					snapShotTime:'（毫秒）',											
					op:'操作'
				},
				alertOutStatus:{
					connect:'接通',
					breaks:'断开',
					pulse:'闪烁'
				},		
				eventType:{
					E_ST_EmergentAlert:'紧急报警',
					E_ST_UnusableTimeAlert:'不可用时间报警',	
					E_ST_OverSpeed:'超速报警',	
					E_ST_FatigueDriving:'疲劳驾驶报警',
					E_ST_StationLinger:'公交赖站',
					E_ST_RTCFault:'时间出现错误',	
					E_ST_BatteryOver:'电池耗光报警',	
					E_ST_WirelessAlarmIn:'无线报警器发生报警',	
					E_ST_InfraredBodyAlarm:'内置红外人体感应发生报警',
					E_ST_VehicleBrake:'车辆急刹报警',	
					E_ST_VehicleCollision:'车辆碰撞报警',	
					E_ST_VehicleRollover:'车辆侧翻报警',	
					E_WM_BytesAlarm:'流量预警',
					E_IV_SignalLost:'信号丢失',	
					E_IV_MotionDetected:'侦测到移动',	
					E_IV_CoverDetected:'侦测到遮挡',
					E_IDL_AlertIn:'发生报警',
					E_IDL_HostAlarm:'报警主机发生报警',	
					E_SG_DiskSpaceFull:'磁盘已满',	
					E_SG_StartFileSystemFailed:'加载文件系统失败',	
					E_SG_DiskError:'磁盘出现故障',
					E_GPS_LowSpeed:'怠速报警',	
					E_GPS_InERailAlarm:'进入电子围栏报警',	
					E_GPS_OutERailAlarm:'离开电子围栏报警'								
				},
				action:{
					alertOut:'报警输出',
					sendEmail:'发送电子邮件,并附抓图',	
					ftpUpload:'抓拍上传到FTP服务器',	
					record:'开始前端录像',
					snapShot:'开始前端抓拍',
					moveToPresetPosition:'前往预置位',	
					online:'上线',	
					sendSMS:'发送报警短信',	
					preTransmitVideo:'预传视频',
					preSnapshot:'预抓图',	
					preTransmitAudio:'预传音频',	
					preTransmitGPS:'预传定位信息',	
					uploadAlert:'上传报警信息',
					uploadRecord:'上传录像,实时上传视频和音频',	
					playTipVoice:'播放提示声音'							
				},
				model:{
					None:'空',
					Always:'全部',
					Everyday:'每天',
					Weekly:'每周'
				},
				time:{
					time1:'时间段一',
					time2:'时间段二',
					time3:'时间段三'
				},
				week:{
					Sun:'星期日',
					Mon:'星期一',
					Tues:'星期二',	
					Wed:'星期三',
					Thur:'星期四',
					Fri:'星期五',
					Sat:'星期六'		
				}												
			},			
			recordstatus_list:{
				col:{
					idx:'通道',
					status:'录像状态',
					reason:'录像原因',
					fault:'故障原因',
					op:'操作'
				}
			},
			onlinesmsets_list:{
				col:{
					id:'编号',
					phone:'号码',
					op:'操作'
				}
			}
		},
		map:{
			title:'电子地图'
		},
		decode:{
			title:'视频解码',
			ov_list:'视频源列表:',	
			notes:{
				noteTitle:'刷新视频源列表',	
				note:'视频源列表有修改，您确定不提交修改吗？',
				note1:'启动自动轮跳',
				note2:'添加视频源--登录',
				note3:'添加视频源--选择视频',
				note4:'选择视频源',
				note5:'请选择视频源',
				note6:'修改视频源信息',
				note7:'删除视频源',
				note8:'您确定要删除选择的视频源么？',
				note9:'刷新视频源列表',
				note10:'视频源列表有修改，您确定不提交修改吗？',
				note11:'添加IP通道成功',
				note12:'修改IP通道成功',
				note13:'删除IP通道成功',
				note14:'添加手机号码成功',
				note15:'修改手机号码成功',
				note16:'删除手机号码成功',
				note17:'您确定要格式磁盘么？'
			},
		　　btns:{
			　　rename:'重命名',
			　　disabled:'禁用',
			　　enable:'启用',
			　　set:'设置',
			　　query:'查询',	
			　　refresh:'刷新',
			　　add:'添加',
			　　modify:'修改',
			　　clean:'清除',
			　　del:'删除',
			　　ok:'提交',
			　　confirm:'确定',
			　　canael:'取消',
			　　yes:'是',
　　			no:'否',
　　			setmodify:'保存修改',		
			　　okall:'提交到所有通道',
			　　msg:'从1开始编号',
			　　setdesc:'设置描述'		
			},
			sources_list:{
			　　name:'视频名称',
			　　decname:'设备名称',
			　　idx:'通道',
			　　stream:'视频流',
			　　stream1:'流',	
			　　linger:'停留时间(s)',
			　　linger1:'停留时间',	
			　　addr:'地址',
			　　password:'密码',
			　　remumber:'记住密码',			
			　　userid:'用户名',
			　　autoswitch:'参与轮跳',
			　　status:'状态',
			　　opt:'操作'
			}			
		}
	}
}