/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.ws.order.businessBillBeneficiary;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports

/**
 * A data object class directly models database table <tt>business_bill_beneficiary</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/business_bill_beneficiary.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class BusinessBillBeneficiaryOrder implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long billBeneficiaryId;

	private long beneficiaryUserId;

	private String beneficiaryUserName;

	private String beneficiaryCertType;

	private String beneficiaryCertNo;

	private String beneficiaryVal;

	private String type;
	
	private long letterId;

    //========== getters and setters ==========

	public long getBillBeneficiaryId() {
		return billBeneficiaryId;
	}
	
	public void setBillBeneficiaryId(long billBeneficiaryId) {
		this.billBeneficiaryId = billBeneficiaryId;
	}

	public long getBeneficiaryUserId() {
		return beneficiaryUserId;
	}
	
	public void setBeneficiaryUserId(long beneficiaryUserId) {
		this.beneficiaryUserId = beneficiaryUserId;
	}

	public String getBeneficiaryUserName() {
		return beneficiaryUserName;
	}
	
	public void setBeneficiaryUserName(String beneficiaryUserName) {
		this.beneficiaryUserName = beneficiaryUserName;
	}

	public String getBeneficiaryCertType() {
		return beneficiaryCertType;
	}
	
	public void setBeneficiaryCertType(String beneficiaryCertType) {
		this.beneficiaryCertType = beneficiaryCertType;
	}

	public String getBeneficiaryCertNo() {
		return beneficiaryCertNo;
	}
	
	public void setBeneficiaryCertNo(String beneficiaryCertNo) {
		this.beneficiaryCertNo = beneficiaryCertNo;
	}

	public String getBeneficiaryVal() {
		return beneficiaryVal;
	}
	
	public void setBeneficiaryVal(String beneficiaryVal) {
		this.beneficiaryVal = beneficiaryVal;
	}

	public String getType() {
		return type;
	}
	
	public void setType(String type) {
		this.type = type;
	}

	public long getLetterId() {
		return letterId;
	}

	public void setLetterId(long letterId) {
		this.letterId = letterId;
	}

	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
