/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import com.yjf.common.lang.util.money.Money;
import java.util.Date;

/**
 * A data object class directly models database table <tt>bill_settlement_apply_detail</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/bill_settlement_apply_detail.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class BillSettlementApplyDetailDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long id;

	private long settlementApplyId;

	private long businessBillId;

	private Money recievableFee = new Money(0, 0);

	private Money recievedFee = new Money(0, 0);

	private Money shouldPayFee = new Money(0, 0);

	private Money actualPayFee = new Money(0, 0);

	private Money serviceFee = new Money(0, 0);

	private Money generationFee = new Money(0, 0);

	private Money individualTax = new Money(0, 0);

	private Money payFee = new Money(0, 0);

	private double reservedScale;

	private Date rowAddTime;

	private Date rowUpdateTime;

    //========== getters and setters ==========

	public long getId() {
		return id;
	}
	
	public void setId(long id) {
		this.id = id;
	}

	public long getSettlementApplyId() {
		return settlementApplyId;
	}
	
	public void setSettlementApplyId(long settlementApplyId) {
		this.settlementApplyId = settlementApplyId;
	}

	public long getBusinessBillId() {
		return businessBillId;
	}
	
	public void setBusinessBillId(long businessBillId) {
		this.businessBillId = businessBillId;
	}

	public Money getRecievableFee() {
		return recievableFee;
	}
	
	public void setRecievableFee(Money recievableFee) {
		if (recievableFee == null) {
			this.recievableFee = new Money(0, 0);
		} else {
			this.recievableFee = recievableFee;
		}
	}

	public Money getRecievedFee() {
		return recievedFee;
	}
	
	public void setRecievedFee(Money recievedFee) {
		if (recievedFee == null) {
			this.recievedFee = new Money(0, 0);
		} else {
			this.recievedFee = recievedFee;
		}
	}

	public Money getShouldPayFee() {
		return shouldPayFee;
	}
	
	public void setShouldPayFee(Money shouldPayFee) {
		if (shouldPayFee == null) {
			this.shouldPayFee = new Money(0, 0);
		} else {
			this.shouldPayFee = shouldPayFee;
		}
	}

	public Money getActualPayFee() {
		return actualPayFee;
	}
	
	public void setActualPayFee(Money actualPayFee) {
		if (actualPayFee == null) {
			this.actualPayFee = new Money(0, 0);
		} else {
			this.actualPayFee = actualPayFee;
		}
	}

	public Money getServiceFee() {
		return serviceFee;
	}
	
	public void setServiceFee(Money serviceFee) {
		if (serviceFee == null) {
			this.serviceFee = new Money(0, 0);
		} else {
			this.serviceFee = serviceFee;
		}
	}

	public Money getGenerationFee() {
		return generationFee;
	}
	
	public void setGenerationFee(Money generationFee) {
		if (generationFee == null) {
			this.generationFee = new Money(0, 0);
		} else {
			this.generationFee = generationFee;
		}
	}

	public Money getIndividualTax() {
		return individualTax;
	}
	
	public void setIndividualTax(Money individualTax) {
		if (individualTax == null) {
			this.individualTax = new Money(0, 0);
		} else {
			this.individualTax = individualTax;
		}
	}

	public Money getPayFee() {
		return payFee;
	}
	
	public void setPayFee(Money payFee) {
		if (payFee == null) {
			this.payFee = new Money(0, 0);
		} else {
			this.payFee = payFee;
		}
	}

	public double getReservedScale() {
		return reservedScale;
	}
	
	public void setReservedScale(double reservedScale) {
		this.reservedScale = reservedScale;
	}

	public Date getRowAddTime() {
		return rowAddTime;
	}
	
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}
	
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
