/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;
import com.yjf.common.lang.util.money.Money;

/**
 * A data object class directly models database table <tt>brokerage_fee</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/brokerage_fee.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class BrokerageFeeDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long brokerageId;

	private long businessBillId;

	private double brokerageScale;

	private Money brokerageAmount = new Money(0, 0);

	private Date rawAddTime;

	private Date updateAddTime;

    //========== getters and setters ==========

	public long getBrokerageId() {
		return brokerageId;
	}
	
	public void setBrokerageId(long brokerageId) {
		this.brokerageId = brokerageId;
	}

	public long getBusinessBillId() {
		return businessBillId;
	}
	
	public void setBusinessBillId(long businessBillId) {
		this.businessBillId = businessBillId;
	}

	public double getBrokerageScale() {
		return brokerageScale;
	}
	
	public void setBrokerageScale(double brokerageScale) {
		this.brokerageScale = brokerageScale;
	}

	public Money getBrokerageAmount() {
		return brokerageAmount;
	}
	
	public void setBrokerageAmount(Money brokerageAmount) {
		if (brokerageAmount == null) {
			this.brokerageAmount = new Money(0, 0);
		} else {
			this.brokerageAmount = brokerageAmount;
		}
	}

	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}

	public Date getUpdateAddTime() {
		return updateAddTime;
	}
	
	public void setUpdateAddTime(Date updateAddTime) {
		this.updateAddTime = updateAddTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
