/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>business_bill_correcting</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/business_bill_correcting.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class BusinessBillCorrectingDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long businessBillCorrectingId;

	private long businessBillId;

	private String businessBillCorrectingNo;

	private String insuranceNo;

	private long billCustomerId;

	private String billCustomerName;

	private String correctingType;

	private String correctingStatus;

	private String correctingOpinion;

	private Date rowAddTime;

	private Date rowUpdateTime;

    //========== getters and setters ==========

	public long getBusinessBillCorrectingId() {
		return businessBillCorrectingId;
	}
	
	public void setBusinessBillCorrectingId(long businessBillCorrectingId) {
		this.businessBillCorrectingId = businessBillCorrectingId;
	}

	public long getBusinessBillId() {
		return businessBillId;
	}
	
	public void setBusinessBillId(long businessBillId) {
		this.businessBillId = businessBillId;
	}

	public String getBusinessBillCorrectingNo() {
		return businessBillCorrectingNo;
	}
	
	public void setBusinessBillCorrectingNo(String businessBillCorrectingNo) {
		this.businessBillCorrectingNo = businessBillCorrectingNo;
	}

	public String getInsuranceNo() {
		return insuranceNo;
	}
	
	public void setInsuranceNo(String insuranceNo) {
		this.insuranceNo = insuranceNo;
	}

	public long getBillCustomerId() {
		return billCustomerId;
	}
	
	public void setBillCustomerId(long billCustomerId) {
		this.billCustomerId = billCustomerId;
	}

	public String getBillCustomerName() {
		return billCustomerName;
	}
	
	public void setBillCustomerName(String billCustomerName) {
		this.billCustomerName = billCustomerName;
	}

	public String getCorrectingType() {
		return correctingType;
	}
	
	public void setCorrectingType(String correctingType) {
		this.correctingType = correctingType;
	}

	public String getCorrectingStatus() {
		return correctingStatus;
	}
	
	public void setCorrectingStatus(String correctingStatus) {
		this.correctingStatus = correctingStatus;
	}

	public String getCorrectingOpinion() {
		return correctingOpinion;
	}
	
	public void setCorrectingOpinion(String correctingOpinion) {
		this.correctingOpinion = correctingOpinion;
	}

	public Date getRowAddTime() {
		return rowAddTime;
	}
	
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}
	
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
