/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import com.yjf.common.lang.util.money.Money;

/**
 * A data object class directly models database table <tt>insurance_contact_letter_detail</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/insurance_contact_letter_detail.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class InsuranceContactLetterDetailDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long letterDetailId;

	private long letterId;

	private long productId;

	private String productName;

	private Money insuranceAmount = new Money(0, 0);

	private Money premiumAmount = new Money(0, 0);

	private Money brokerAmount = new Money(0, 0);

	private Money firstPremiumAmount = new Money(0, 0);

	private String period;

    //========== getters and setters ==========

	public long getLetterDetailId() {
		return letterDetailId;
	}
	
	public void setLetterDetailId(long letterDetailId) {
		this.letterDetailId = letterDetailId;
	}

	public long getLetterId() {
		return letterId;
	}
	
	public void setLetterId(long letterId) {
		this.letterId = letterId;
	}

	public long getProductId() {
		return productId;
	}
	
	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return productName;
	}
	
	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Money getInsuranceAmount() {
		return insuranceAmount;
	}
	
	public void setInsuranceAmount(Money insuranceAmount) {
		if (insuranceAmount == null) {
			this.insuranceAmount = new Money(0, 0);
		} else {
			this.insuranceAmount = insuranceAmount;
		}
	}

	public Money getPremiumAmount() {
		return premiumAmount;
	}
	
	public void setPremiumAmount(Money premiumAmount) {
		if (premiumAmount == null) {
			this.premiumAmount = new Money(0, 0);
		} else {
			this.premiumAmount = premiumAmount;
		}
	}

	public Money getBrokerAmount() {
		return brokerAmount;
	}
	
	public void setBrokerAmount(Money brokerAmount) {
		if (brokerAmount == null) {
			this.brokerAmount = new Money(0, 0);
		} else {
			this.brokerAmount = brokerAmount;
		}
	}

	public Money getFirstPremiumAmount() {
		return firstPremiumAmount;
	}
	
	public void setFirstPremiumAmount(Money firstPremiumAmount) {
		if (firstPremiumAmount == null) {
			this.firstPremiumAmount = new Money(0, 0);
		} else {
			this.firstPremiumAmount = firstPremiumAmount;
		}
	}

	public String getPeriod() {
		return period;
	}
	
	public void setPeriod(String period) {
		this.period = period;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
