/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;
import com.yjf.common.lang.util.money.Money;

/**
 * A data object class directly models database table <tt>insurance_contact_letter</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/insurance_contact_letter.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class InsuranceContactLetterDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long letterId;

	private String billNo;

	private long customerUserId;

	private String customerUserName;

	private String customerCertType;

	private String customerCertNo;

	private String customerUserPhone;

	private String customerUserType;

	private String customerUserSex;

	private String customerUserAddress;

	private String customerUserBirth;

	private long businessUserId;

	private String businessUserName;

	private String department;

	private long companyUserId;

	private String companyUserName;

	private long priceContactId;

	private String priceContactName;

	private String priceContactNo;

	private long projectSetupId;

	private String projectSetupName;

	private String project;

	private Date beginDate;

	private Date endDate;

	private long formId;

	private String status;

	private String isInvoice;

	private String remark;

	private String recipients;

	private String company;

	private String address;

	private String mobile;

	private String type;

	private String isQuota;

	private String insuranceType;

	private long productId;

	private String productName;

	private long productLevelId;

	private String productLevelLevel;

	private Money premiumAmount = new Money(0, 0);

	private String isCarSales;

	private String plateNumber;

	private String guaranteePeriod;

	private long creatorId;

	private String creatorName;

	private Date rawAddTime;

	private Date rawUpdateTime;

    //========== getters and setters ==========

	public long getLetterId() {
		return letterId;
	}
	
	public void setLetterId(long letterId) {
		this.letterId = letterId;
	}

	public String getBillNo() {
		return billNo;
	}
	
	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public long getCustomerUserId() {
		return customerUserId;
	}
	
	public void setCustomerUserId(long customerUserId) {
		this.customerUserId = customerUserId;
	}

	public String getCustomerUserName() {
		return customerUserName;
	}
	
	public void setCustomerUserName(String customerUserName) {
		this.customerUserName = customerUserName;
	}

	public String getCustomerCertType() {
		return customerCertType;
	}
	
	public void setCustomerCertType(String customerCertType) {
		this.customerCertType = customerCertType;
	}

	public String getCustomerCertNo() {
		return customerCertNo;
	}
	
	public void setCustomerCertNo(String customerCertNo) {
		this.customerCertNo = customerCertNo;
	}

	public String getCustomerUserPhone() {
		return customerUserPhone;
	}
	
	public void setCustomerUserPhone(String customerUserPhone) {
		this.customerUserPhone = customerUserPhone;
	}

	public String getCustomerUserType() {
		return customerUserType;
	}
	
	public void setCustomerUserType(String customerUserType) {
		this.customerUserType = customerUserType;
	}

	public String getCustomerUserSex() {
		return customerUserSex;
	}
	
	public void setCustomerUserSex(String customerUserSex) {
		this.customerUserSex = customerUserSex;
	}

	public String getCustomerUserAddress() {
		return customerUserAddress;
	}
	
	public void setCustomerUserAddress(String customerUserAddress) {
		this.customerUserAddress = customerUserAddress;
	}

	public String getCustomerUserBirth() {
		return customerUserBirth;
	}
	
	public void setCustomerUserBirth(String customerUserBirth) {
		this.customerUserBirth = customerUserBirth;
	}

	public long getBusinessUserId() {
		return businessUserId;
	}
	
	public void setBusinessUserId(long businessUserId) {
		this.businessUserId = businessUserId;
	}

	public String getBusinessUserName() {
		return businessUserName;
	}
	
	public void setBusinessUserName(String businessUserName) {
		this.businessUserName = businessUserName;
	}

	public String getDepartment() {
		return department;
	}
	
	public void setDepartment(String department) {
		this.department = department;
	}

	public long getCompanyUserId() {
		return companyUserId;
	}
	
	public void setCompanyUserId(long companyUserId) {
		this.companyUserId = companyUserId;
	}

	public String getCompanyUserName() {
		return companyUserName;
	}
	
	public void setCompanyUserName(String companyUserName) {
		this.companyUserName = companyUserName;
	}

	public long getPriceContactId() {
		return priceContactId;
	}
	
	public void setPriceContactId(long priceContactId) {
		this.priceContactId = priceContactId;
	}

	public String getPriceContactName() {
		return priceContactName;
	}
	
	public void setPriceContactName(String priceContactName) {
		this.priceContactName = priceContactName;
	}

	public String getPriceContactNo() {
		return priceContactNo;
	}
	
	public void setPriceContactNo(String priceContactNo) {
		this.priceContactNo = priceContactNo;
	}

	public long getProjectSetupId() {
		return projectSetupId;
	}
	
	public void setProjectSetupId(long projectSetupId) {
		this.projectSetupId = projectSetupId;
	}

	public String getProjectSetupName() {
		return projectSetupName;
	}
	
	public void setProjectSetupName(String projectSetupName) {
		this.projectSetupName = projectSetupName;
	}

	public String getProject() {
		return project;
	}
	
	public void setProject(String project) {
		this.project = project;
	}

	public Date getBeginDate() {
		return beginDate;
	}
	
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getEndDate() {
		return endDate;
	}
	
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public long getFormId() {
		return formId;
	}
	
	public void setFormId(long formId) {
		this.formId = formId;
	}

	public String getStatus() {
		return status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}

	public String getIsInvoice() {
		return isInvoice;
	}
	
	public void setIsInvoice(String isInvoice) {
		this.isInvoice = isInvoice;
	}

	public String getRemark() {
		return remark;
	}
	
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRecipients() {
		return recipients;
	}
	
	public void setRecipients(String recipients) {
		this.recipients = recipients;
	}

	public String getCompany() {
		return company;
	}
	
	public void setCompany(String company) {
		this.company = company;
	}

	public String getAddress() {
		return address;
	}
	
	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return mobile;
	}
	
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getType() {
		return type;
	}
	
	public void setType(String type) {
		this.type = type;
	}

	public String getIsQuota() {
		return isQuota;
	}
	
	public void setIsQuota(String isQuota) {
		this.isQuota = isQuota;
	}

	public String getInsuranceType() {
		return insuranceType;
	}
	
	public void setInsuranceType(String insuranceType) {
		this.insuranceType = insuranceType;
	}

	public long getProductId() {
		return productId;
	}
	
	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return productName;
	}
	
	public void setProductName(String productName) {
		this.productName = productName;
	}

	public long getProductLevelId() {
		return productLevelId;
	}
	
	public void setProductLevelId(long productLevelId) {
		this.productLevelId = productLevelId;
	}

	public String getProductLevelLevel() {
		return productLevelLevel;
	}
	
	public void setProductLevelLevel(String productLevelLevel) {
		this.productLevelLevel = productLevelLevel;
	}

	public Money getPremiumAmount() {
		return premiumAmount;
	}
	
	public void setPremiumAmount(Money premiumAmount) {
		if (premiumAmount == null) {
			this.premiumAmount = new Money(0, 0);
		} else {
			this.premiumAmount = premiumAmount;
		}
	}

	public String getIsCarSales() {
		return isCarSales;
	}
	
	public void setIsCarSales(String isCarSales) {
		this.isCarSales = isCarSales;
	}

	public String getPlateNumber() {
		return plateNumber;
	}
	
	public void setPlateNumber(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	public String getGuaranteePeriod() {
		return guaranteePeriod;
	}
	
	public void setGuaranteePeriod(String guaranteePeriod) {
		this.guaranteePeriod = guaranteePeriod;
	}

	public long getCreatorId() {
		return creatorId;
	}
	
	public void setCreatorId(long creatorId) {
		this.creatorId = creatorId;
	}

	public String getCreatorName() {
		return creatorName;
	}
	
	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}

	public Date getRawUpdateTime() {
		return rawUpdateTime;
	}
	
	public void setRawUpdateTime(Date rawUpdateTime) {
		this.rawUpdateTime = rawUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
