/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>message_received</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/message_received.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class MessageReceivedDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long receivedId;

	private long messageId;

	private String messageTitle;

	private String messageType;

	private String messageSubject;

	private String messageContent;

	private String notificationObject;

	private String viewType;

	private String linkUrl;

	private long messageSenderId;

	private String messageSenderName;

	private long messageReceivedId;

	private Date messageReceivedDate;

	private String messageReceivedName;

	private String messageReceivedAccount;

	private String messageReceivedStatus;

	private Date rawAddTime;

	private Date rawUpdateTime;

    //========== getters and setters ==========

	public long getReceivedId() {
		return receivedId;
	}
	
	public void setReceivedId(long receivedId) {
		this.receivedId = receivedId;
	}

	public long getMessageId() {
		return messageId;
	}
	
	public void setMessageId(long messageId) {
		this.messageId = messageId;
	}

	public String getMessageTitle() {
		return messageTitle;
	}
	
	public void setMessageTitle(String messageTitle) {
		this.messageTitle = messageTitle;
	}

	public String getMessageType() {
		return messageType;
	}
	
	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public String getMessageSubject() {
		return messageSubject;
	}
	
	public void setMessageSubject(String messageSubject) {
		this.messageSubject = messageSubject;
	}

	public String getMessageContent() {
		return messageContent;
	}
	
	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public String getNotificationObject() {
		return notificationObject;
	}
	
	public void setNotificationObject(String notificationObject) {
		this.notificationObject = notificationObject;
	}

	public String getViewType() {
		return viewType;
	}
	
	public void setViewType(String viewType) {
		this.viewType = viewType;
	}

	public String getLinkUrl() {
		return linkUrl;
	}
	
	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

	public long getMessageSenderId() {
		return messageSenderId;
	}
	
	public void setMessageSenderId(long messageSenderId) {
		this.messageSenderId = messageSenderId;
	}

	public String getMessageSenderName() {
		return messageSenderName;
	}
	
	public void setMessageSenderName(String messageSenderName) {
		this.messageSenderName = messageSenderName;
	}

	public long getMessageReceivedId() {
		return messageReceivedId;
	}
	
	public void setMessageReceivedId(long messageReceivedId) {
		this.messageReceivedId = messageReceivedId;
	}

	public Date getMessageReceivedDate() {
		return messageReceivedDate;
	}
	
	public void setMessageReceivedDate(Date messageReceivedDate) {
		this.messageReceivedDate = messageReceivedDate;
	}

	public String getMessageReceivedName() {
		return messageReceivedName;
	}
	
	public void setMessageReceivedName(String messageReceivedName) {
		this.messageReceivedName = messageReceivedName;
	}

	public String getMessageReceivedAccount() {
		return messageReceivedAccount;
	}
	
	public void setMessageReceivedAccount(String messageReceivedAccount) {
		this.messageReceivedAccount = messageReceivedAccount;
	}

	public String getMessageReceivedStatus() {
		return messageReceivedStatus;
	}
	
	public void setMessageReceivedStatus(String messageReceivedStatus) {
		this.messageReceivedStatus = messageReceivedStatus;
	}

	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}

	public Date getRawUpdateTime() {
		return rawUpdateTime;
	}
	
	public void setRawUpdateTime(Date rawUpdateTime) {
		this.rawUpdateTime = rawUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
