/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;
import com.yjf.common.lang.util.money.Money;

/**
 * A data object class directly models database table <tt>person_commission_detail</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/person_commission_detail.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class PersonCommissionDetailDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long settlementPersonId;

	private String serialNumber;

	private long businessUserId;

	private String businessUserName;

	private String businessUserType;

	private long businessBillId;

	private String insuranceNo;

	private Money commissionAmount = new Money(0, 0);

	private Date commissionTime;

	private String commissionType;

	private Money balance = new Money(0, 0);

	private String remark;

	private Date rawAddTime;

	private Date rawUpdateTime;

    //========== getters and setters ==========

	public long getSettlementPersonId() {
		return settlementPersonId;
	}
	
	public void setSettlementPersonId(long settlementPersonId) {
		this.settlementPersonId = settlementPersonId;
	}

	public String getSerialNumber() {
		return serialNumber;
	}
	
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public long getBusinessUserId() {
		return businessUserId;
	}
	
	public void setBusinessUserId(long businessUserId) {
		this.businessUserId = businessUserId;
	}

	public String getBusinessUserName() {
		return businessUserName;
	}
	
	public void setBusinessUserName(String businessUserName) {
		this.businessUserName = businessUserName;
	}

	public String getBusinessUserType() {
		return businessUserType;
	}
	
	public void setBusinessUserType(String businessUserType) {
		this.businessUserType = businessUserType;
	}

	public long getBusinessBillId() {
		return businessBillId;
	}
	
	public void setBusinessBillId(long businessBillId) {
		this.businessBillId = businessBillId;
	}

	public String getInsuranceNo() {
		return insuranceNo;
	}
	
	public void setInsuranceNo(String insuranceNo) {
		this.insuranceNo = insuranceNo;
	}

	public Money getCommissionAmount() {
		return commissionAmount;
	}
	
	public void setCommissionAmount(Money commissionAmount) {
		if (commissionAmount == null) {
			this.commissionAmount = new Money(0, 0);
		} else {
			this.commissionAmount = commissionAmount;
		}
	}

	public Date getCommissionTime() {
		return commissionTime;
	}
	
	public void setCommissionTime(Date commissionTime) {
		this.commissionTime = commissionTime;
	}

	public String getCommissionType() {
		return commissionType;
	}
	
	public void setCommissionType(String commissionType) {
		this.commissionType = commissionType;
	}

	public Money getBalance() {
		return balance;
	}
	
	public void setBalance(Money balance) {
		if (balance == null) {
			this.balance = new Money(0, 0);
		} else {
			this.balance = balance;
		}
	}

	public String getRemark() {
		return remark;
	}
	
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}

	public Date getRawUpdateTime() {
		return rawUpdateTime;
	}
	
	public void setRawUpdateTime(Date rawUpdateTime) {
		this.rawUpdateTime = rawUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
