/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.ibatis;

import com.born.insurance.dal.daointerface.FormMessageTempleteDAO;
import com.born.insurance.dal.dataobject.FormMessageTempleteDO;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;


// auto generated imports
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.FormMessageTempleteDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/form_message_templete.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisFormMessageTempleteDAO extends SqlMapClientDaoSupport implements FormMessageTempleteDAO {
	/**
	 *  Insert one <tt>FormMessageTempleteDO</tt> object to DB table <tt>form_message_templete</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into form_message_templete(templete_id,form_code,type,subject,content_html,content_txt,is_send_site_message,is_send_mail,is_send_sms,with_audit_opinion,base_on,remark,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param formMessageTemplete
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FormMessageTempleteDO formMessageTemplete) throws DataAccessException {
    	if (formMessageTemplete == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-FORM-MESSAGE-TEMPLETE-INSERT", formMessageTemplete);

        return formMessageTemplete.getTempleteId();
    }

	/**
	 *  Update DB table <tt>form_message_templete</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update form_message_templete set form_code=?, type=?, subject=?, content_html=?, content_txt=?, is_send_site_message=?, is_send_mail=?, is_send_sms=?, with_audit_opinion=?, base_on=?, remark=? where (templete_id = ?)</tt>
	 *
	 *	@param formMessageTemplete
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FormMessageTempleteDO formMessageTemplete) throws DataAccessException {
    	if (formMessageTemplete == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-FORM-MESSAGE-TEMPLETE-UPDATE", formMessageTemplete);
    }

	/**
	 *  Query DB table <tt>form_message_templete</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_message_templete where (templete_id = ?)</tt>
	 *
	 *	@param templeteId
	 *	@return FormMessageTempleteDO
	 *	@throws DataAccessException
	 */	 
    public FormMessageTempleteDO findById(long templeteId) throws DataAccessException {
        Long param = new Long(templeteId);

        return (FormMessageTempleteDO) getSqlMapClientTemplate().queryForObject("MS-FORM-MESSAGE-TEMPLETE-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>form_message_templete</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_message_templete where ((form_code = ?) AND (type = ?))</tt>
	 *
	 *	@param formCode
	 *	@param type
	 *	@return FormMessageTempleteDO
	 *	@throws DataAccessException
	 */	 
    public FormMessageTempleteDO findByFormCodeAndType(String formCode, String type) throws DataAccessException {
        Map param = new HashMap();

        param.put("formCode", formCode);
        param.put("type", type);

        return (FormMessageTempleteDO) getSqlMapClientTemplate().queryForObject("MS-FORM-MESSAGE-TEMPLETE-FIND-BY-FORM-CODE-AND-TYPE", param);

    }

	/**
	 *  Delete records from DB table <tt>form_message_templete</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from form_message_templete where (templete_id = ?)</tt>
	 *
	 *	@param templeteId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long templeteId) throws DataAccessException {
        Long param = new Long(templeteId);

        return getSqlMapClientTemplate().delete("MS-FORM-MESSAGE-TEMPLETE-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>form_message_templete</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from form_message_templete where ((form_code = ?) AND (type = ?))</tt>
	 *
	 *	@param formCode
	 *	@param type
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormCodeAndType(String formCode, String type) throws DataAccessException {
        Map param = new HashMap();

        param.put("formCode", formCode);
        param.put("type", type);

        return getSqlMapClientTemplate().delete("MS-FORM-MESSAGE-TEMPLETE-DELETE-BY-FORM-CODE-AND-TYPE", param);
    }

	/**
	 *  Query DB table <tt>form_message_templete</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_message_templete where (1 = 1)</tt>
	 *
	 *	@param formMessageTemplete
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<FormMessageTempleteDO>
	 *	@throws DataAccessException
	 */	 
    public List<FormMessageTempleteDO> findByCondition(FormMessageTempleteDO formMessageTemplete, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException {
    	if (formMessageTemplete == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("formMessageTemplete", formMessageTemplete);
        param.put("sortCol", sortCol);
        param.put("sortOrder", sortOrder);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));

        return getSqlMapClientTemplate().queryForList("MS-FORM-MESSAGE-TEMPLETE-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>form_message_templete</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from form_message_templete where (1 = 1)</tt>
	 *
	 *	@param formMessageTemplete
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(FormMessageTempleteDO formMessageTemplete) throws DataAccessException {
    	if (formMessageTemplete == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-FORM-MESSAGE-TEMPLETE-FIND-BY-CONDITION-COUNT", formMessageTemplete);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}