/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.insurance.dal.daointerface.InsuranceCatalogRelationDAO;


// auto generated imports
import com.born.insurance.dal.dataobject.InsuranceCatalogRelationDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.insurance.dal.daointerface.InsuranceCatalogRelationDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/insurance_catalog_relation.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisInsuranceCatalogRelationDAO extends SqlMapClientDaoSupport implements InsuranceCatalogRelationDAO {
	/**
	 *  Insert one <tt>InsuranceCatalogRelationDO</tt> object to DB table <tt>insurance_catalog_relation</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into insurance_catalog_relation(relation_id,parent_name,parent_id,child_name,child_id,type) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param insuranceCatalogRelation
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(InsuranceCatalogRelationDO insuranceCatalogRelation) throws DataAccessException {
    	if (insuranceCatalogRelation == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-INSURANCE-CATALOG-RELATION-INSERT", insuranceCatalogRelation);

        return insuranceCatalogRelation.getRelationId();
    }

	/**
	 *  Update DB table <tt>insurance_catalog_relation</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update insurance_catalog_relation set parent_name=?, parent_id=?, child_name=?, child_id=?, type=? where (relation_id = ?)</tt>
	 *
	 *	@param insuranceCatalogRelation
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(InsuranceCatalogRelationDO insuranceCatalogRelation) throws DataAccessException {
    	if (insuranceCatalogRelation == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-INSURANCE-CATALOG-RELATION-UPDATE", insuranceCatalogRelation);
    }

	/**
	 *  Query DB table <tt>insurance_catalog_relation</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select relation_id, parent_name, parent_id, child_name, child_id, type from insurance_catalog_relation where (relation_id = ?)</tt>
	 *
	 *	@param relationId
	 *	@return InsuranceCatalogRelationDO
	 *	@throws DataAccessException
	 */	 
    public InsuranceCatalogRelationDO findById(long relationId) throws DataAccessException {
        Long param = new Long(relationId);

        return (InsuranceCatalogRelationDO) getSqlMapClientTemplate().queryForObject("MS-INSURANCE-CATALOG-RELATION-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>insurance_catalog_relation</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from insurance_catalog_relation where (relation_id = ?)</tt>
	 *
	 *	@param relationId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long relationId) throws DataAccessException {
        Long param = new Long(relationId);

        return getSqlMapClientTemplate().delete("MS-INSURANCE-CATALOG-RELATION-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>insurance_catalog_relation</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from insurance_catalog_relation where (child_id = ?)</tt>
	 *
	 *	@param childId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByChildId(long childId) throws DataAccessException {
        Long param = new Long(childId);

        return getSqlMapClientTemplate().delete("MS-INSURANCE-CATALOG-RELATION-DELETE-BY-CHILD-ID", param);
    }

	/**
	 *  Query DB table <tt>insurance_catalog_relation</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select relation_id, parent_name, parent_id, child_name, child_id, type from insurance_catalog_relation where (1 = 1)</tt>
	 *
	 *	@param insuranceCatalogRelation
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<InsuranceCatalogRelationDO>
	 *	@throws DataAccessException
	 */	 
    public List<InsuranceCatalogRelationDO> findByCondition(InsuranceCatalogRelationDO insuranceCatalogRelation, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException {
    	if (insuranceCatalogRelation == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("insuranceCatalogRelation", insuranceCatalogRelation);
        param.put("sortCol", sortCol);
        param.put("sortOrder", sortOrder);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));

        return getSqlMapClientTemplate().queryForList("MS-INSURANCE-CATALOG-RELATION-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>insurance_catalog_relation</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from insurance_catalog_relation where (1 = 1)</tt>
	 *
	 *	@param insuranceCatalogRelation
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(InsuranceCatalogRelationDO insuranceCatalogRelation) throws DataAccessException {
    	if (insuranceCatalogRelation == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-INSURANCE-CATALOG-RELATION-FIND-BY-CONDITION-COUNT", insuranceCatalogRelation);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}