/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.insurance.dal.daointerface.PriceContactLetterSchemeDAO;


// auto generated imports
import com.born.insurance.dal.dataobject.PriceContactLetterSchemeDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.insurance.dal.daointerface.PriceContactLetterSchemeDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/price_contact_letter_scheme.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisPriceContactLetterSchemeDAO extends SqlMapClientDaoSupport implements PriceContactLetterSchemeDAO {
	/**
	 *  Insert one <tt>PriceContactLetterSchemeDO</tt> object to DB table <tt>price_contact_letter_scheme</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into price_contact_letter_scheme(id,letter_demand_id,ask_date,special_req,claim_form,accident_system,discovery_period,accident_claim_system,retrospective_period,version,ext) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param priceContactLetterScheme
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(PriceContactLetterSchemeDO priceContactLetterScheme) throws DataAccessException {
    	if (priceContactLetterScheme == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-PRICE-CONTACT-LETTER-SCHEME-INSERT", priceContactLetterScheme);

        return priceContactLetterScheme.getId();
    }

	/**
	 *  Update DB table <tt>price_contact_letter_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update price_contact_letter_scheme set letter_demand_id=?, ask_date=?, special_req=?, claim_form=?, accident_system=?, discovery_period=?, accident_claim_system=?, retrospective_period=?, version=?, ext=? where (id = ?)</tt>
	 *
	 *	@param priceContactLetterScheme
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(PriceContactLetterSchemeDO priceContactLetterScheme) throws DataAccessException {
    	if (priceContactLetterScheme == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-PRICE-CONTACT-LETTER-SCHEME-UPDATE", priceContactLetterScheme);
    }

	/**
	 *  Query DB table <tt>price_contact_letter_scheme</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, letter_demand_id, ask_date, special_req, claim_form, accident_system, discovery_period, accident_claim_system, retrospective_period, version, ext from price_contact_letter_scheme where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return PriceContactLetterSchemeDO
	 *	@throws DataAccessException
	 */	 
    public PriceContactLetterSchemeDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (PriceContactLetterSchemeDO) getSqlMapClientTemplate().queryForObject("MS-PRICE-CONTACT-LETTER-SCHEME-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>price_contact_letter_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from price_contact_letter_scheme where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-PRICE-CONTACT-LETTER-SCHEME-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>price_contact_letter_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from price_contact_letter_scheme where (letter_demand_id = ?)</tt>
	 *
	 *	@param letterDemandId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByLetterDemandId(long letterDemandId) throws DataAccessException {
        Long param = new Long(letterDemandId);

        return getSqlMapClientTemplate().delete("MS-PRICE-CONTACT-LETTER-SCHEME-DELETE-BY-LETTER-DEMAND-ID", param);
    }

	/**
	 *  Query DB table <tt>price_contact_letter_scheme</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, letter_demand_id, ask_date, special_req, claim_form, accident_system, discovery_period, accident_claim_system, retrospective_period, version, ext from price_contact_letter_scheme where (1 = 1)</tt>
	 *
	 *	@param priceContactLetterScheme
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<PriceContactLetterSchemeDO>
	 *	@throws DataAccessException
	 */	 
    public List<PriceContactLetterSchemeDO> findByCondition(PriceContactLetterSchemeDO priceContactLetterScheme, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException {
    	if (priceContactLetterScheme == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("priceContactLetterScheme", priceContactLetterScheme);
        param.put("sortCol", sortCol);
        param.put("sortOrder", sortOrder);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));

        return getSqlMapClientTemplate().queryForList("MS-PRICE-CONTACT-LETTER-SCHEME-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>price_contact_letter_scheme</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from price_contact_letter_scheme where (1 = 1)</tt>
	 *
	 *	@param priceContactLetterScheme
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(PriceContactLetterSchemeDO priceContactLetterScheme) throws DataAccessException {
    	if (priceContactLetterScheme == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-PRICE-CONTACT-LETTER-SCHEME-FIND-BY-CONDITION-COUNT", priceContactLetterScheme);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}