/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.insurance.dal.daointerface.CustomerProtocolDAO;


// auto generated imports
import com.born.insurance.dal.dataobject.CustomerProtocolDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.insurance.dal.daointerface.CustomerProtocolDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/customer_protocol.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisCustomerProtocolDAO extends SqlMapClientDaoSupport implements CustomerProtocolDAO {
	/**
	 *  Insert one <tt>CustomerProtocolDO</tt> object to DB table <tt>customer_protocol</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into customer_protocol(id,name,no,customer_user_id,customer_user_name,cert_type,cert_no,beginDate,endDate,status,remark,relation_protocol_id,creator_id,creator_name,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param customerProtocol
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(CustomerProtocolDO customerProtocol) throws DataAccessException {
    	if (customerProtocol == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-CUSTOMER-PROTOCOL-INSERT", customerProtocol);

        return customerProtocol.getId();
    }

	/**
	 *  Update DB table <tt>customer_protocol</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update customer_protocol set name=?, no=?, customer_user_id=?, customer_user_name=?, cert_type=?, cert_no=?, beginDate=?, endDate=?, status=?, remark=?, relation_protocol_id=?, creator_id=?, creator_name=? where (id = ?)</tt>
	 *
	 *	@param customerProtocol
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(CustomerProtocolDO customerProtocol) throws DataAccessException {
    	if (customerProtocol == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-CUSTOMER-PROTOCOL-UPDATE", customerProtocol);
    }

	/**
	 *  Query DB table <tt>customer_protocol</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, name, no, customer_user_id, customer_user_name, cert_type, cert_no, beginDate, endDate, status, remark, relation_protocol_id, creator_id, creator_name, raw_add_time, raw_update_time from customer_protocol where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return CustomerProtocolDO
	 *	@throws DataAccessException
	 */	 
    public CustomerProtocolDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (CustomerProtocolDO) getSqlMapClientTemplate().queryForObject("MS-CUSTOMER-PROTOCOL-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>customer_protocol</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from customer_protocol where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-CUSTOMER-PROTOCOL-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>customer_protocol</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, name, no, customer_user_id, customer_user_name, cert_type, cert_no, beginDate, endDate, status, remark, relation_protocol_id, creator_id, creator_name, raw_add_time, raw_update_time from customer_protocol where (1 = 1)</tt>
	 *
	 *	@param customerProtocol
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<CustomerProtocolDO>
	 *	@throws DataAccessException
	 */	 
    public List<CustomerProtocolDO> findByCondition(CustomerProtocolDO customerProtocol, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException {
    	if (customerProtocol == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("customerProtocol", customerProtocol);
        param.put("sortCol", sortCol);
        param.put("sortOrder", sortOrder);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));

        return getSqlMapClientTemplate().queryForList("MS-CUSTOMER-PROTOCOL-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>customer_protocol</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from customer_protocol where (1 = 1)</tt>
	 *
	 *	@param customerProtocol
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(CustomerProtocolDO customerProtocol) throws DataAccessException {
    	if (customerProtocol == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-CUSTOMER-PROTOCOL-FIND-BY-CONDITION-COUNT", customerProtocol);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}