/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.insurance.dal.daointerface.InsuranceCatalogDAO;


// auto generated imports
import com.born.insurance.dal.dataobject.InsuranceCatalogDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.insurance.dal.daointerface.InsuranceCatalogDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/insurance_catalog.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisInsuranceCatalogDAO extends SqlMapClientDaoSupport implements InsuranceCatalogDAO {
	/**
	 *  Insert one <tt>InsuranceCatalogDO</tt> object to DB table <tt>insurance_catalog</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into insurance_catalog(catalog_id,catalog_name,catalog_code,node_path,depth,last_depth,parent_catalog_id,remark,type,is_life_insurance,is_main,abbr1,abbr2,abbr3,creator_id,creator_name,price_template,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param insuranceCatalog
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(InsuranceCatalogDO insuranceCatalog) throws DataAccessException {
    	if (insuranceCatalog == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-INSURANCE-CATALOG-INSERT", insuranceCatalog);

        return insuranceCatalog.getCatalogId();
    }

	/**
	 *  Update DB table <tt>insurance_catalog</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update insurance_catalog set catalog_name=?, catalog_code=?, node_path=?, depth=?, last_depth=?, parent_catalog_id=?, remark=?, type=?, is_life_insurance=?, is_main=?, abbr1=?, abbr2=?, abbr3=?, creator_id=?, creator_name=?, price_template=? where (catalog_id = ?)</tt>
	 *
	 *	@param insuranceCatalog
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(InsuranceCatalogDO insuranceCatalog) throws DataAccessException {
    	if (insuranceCatalog == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-INSURANCE-CATALOG-UPDATE", insuranceCatalog);
    }

	/**
	 *  Query DB table <tt>insurance_catalog</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select catalog_id, catalog_name, catalog_code, node_path, depth, last_depth, parent_catalog_id, remark, type, is_life_insurance, is_main, abbr1, abbr2, abbr3, creator_id, creator_name, price_template, raw_add_time, raw_update_time from insurance_catalog where (catalog_id = ?)</tt>
	 *
	 *	@param catalogId
	 *	@return InsuranceCatalogDO
	 *	@throws DataAccessException
	 */	 
    public InsuranceCatalogDO findById(long catalogId) throws DataAccessException {
        Long param = new Long(catalogId);

        return (InsuranceCatalogDO) getSqlMapClientTemplate().queryForObject("MS-INSURANCE-CATALOG-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>insurance_catalog</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from insurance_catalog where (catalog_id = ?)</tt>
	 *
	 *	@param catalogId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long catalogId) throws DataAccessException {
        Long param = new Long(catalogId);

        return getSqlMapClientTemplate().delete("MS-INSURANCE-CATALOG-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>insurance_catalog</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select catalog_id, catalog_name, catalog_code, node_path, depth, last_depth, parent_catalog_id, remark, type, is_life_insurance, is_main, abbr1, abbr2, abbr3, creator_id, creator_name, price_template, raw_add_time, raw_update_time from insurance_catalog where (1 = 1)</tt>
	 *
	 *	@param insuranceCatalog
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@param certainIds
	 *	@return List<InsuranceCatalogDO>
	 *	@throws DataAccessException
	 */	 
    public List<InsuranceCatalogDO> findByCondition(InsuranceCatalogDO insuranceCatalog, String sortCol, String sortOrder, long limitStart, long pageSize, String certainIds) throws DataAccessException {
    	if (insuranceCatalog == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("insuranceCatalog", insuranceCatalog);
        param.put("sortCol", sortCol);
        param.put("sortOrder", sortOrder);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));
        param.put("certainIds", certainIds);

        return getSqlMapClientTemplate().queryForList("MS-INSURANCE-CATALOG-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>insurance_catalog</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from insurance_catalog where (1 = 1)</tt>
	 *
	 *	@param insuranceCatalog
	 *	@param certainIds
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(InsuranceCatalogDO insuranceCatalog, String certainIds) throws DataAccessException {
    	if (insuranceCatalog == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("insuranceCatalog", insuranceCatalog);
        param.put("certainIds", certainIds);

	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-INSURANCE-CATALOG-FIND-BY-CONDITION-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}