/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.insurance.dal.daointerface.InsuranceContactCertDAO;


// auto generated imports
import com.born.insurance.dal.dataobject.InsuranceContactCertDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.insurance.dal.daointerface.InsuranceContactCertDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/insurance_contact_cert.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisInsuranceContactCertDAO extends SqlMapClientDaoSupport implements InsuranceContactCertDAO {
	/**
	 *  Insert one <tt>InsuranceContactCertDO</tt> object to DB table <tt>insurance_contact_cert</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into insurance_contact_cert(id,letter_id,user_id,cert_id) values (?, ?, ?, ?)</tt>
	 *
	 *	@param insuranceContactCert
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(InsuranceContactCertDO insuranceContactCert) throws DataAccessException {
    	if (insuranceContactCert == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-INSURANCE-CONTACT-CERT-INSERT", insuranceContactCert);

        return insuranceContactCert.getId();
    }

	/**
	 *  Update DB table <tt>insurance_contact_cert</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update insurance_contact_cert set letter_id=?, user_id=?, cert_id=? where (id = ?)</tt>
	 *
	 *	@param insuranceContactCert
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(InsuranceContactCertDO insuranceContactCert) throws DataAccessException {
    	if (insuranceContactCert == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-INSURANCE-CONTACT-CERT-UPDATE", insuranceContactCert);
    }

	/**
	 *  Query DB table <tt>insurance_contact_cert</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, letter_id, user_id, cert_id from insurance_contact_cert where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return InsuranceContactCertDO
	 *	@throws DataAccessException
	 */	 
    public InsuranceContactCertDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (InsuranceContactCertDO) getSqlMapClientTemplate().queryForObject("MS-INSURANCE-CONTACT-CERT-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>insurance_contact_cert</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from insurance_contact_cert where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-INSURANCE-CONTACT-CERT-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>insurance_contact_cert</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, letter_id, user_id, cert_id from insurance_contact_cert where (1 = 1)</tt>
	 *
	 *	@param insuranceContactCert
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<InsuranceContactCertDO>
	 *	@throws DataAccessException
	 */	 
    public List<InsuranceContactCertDO> findByCondition(InsuranceContactCertDO insuranceContactCert, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException {
    	if (insuranceContactCert == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("insuranceContactCert", insuranceContactCert);
        param.put("sortCol", sortCol);
        param.put("sortOrder", sortOrder);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));

        return getSqlMapClientTemplate().queryForList("MS-INSURANCE-CONTACT-CERT-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>insurance_contact_cert</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from insurance_contact_cert where (1 = 1)</tt>
	 *
	 *	@param insuranceContactCert
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(InsuranceContactCertDO insuranceContactCert) throws DataAccessException {
    	if (insuranceContactCert == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-INSURANCE-CONTACT-CERT-FIND-BY-CONDITION-COUNT", insuranceContactCert);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}