/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.insurance.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.insurance.dal.daointerface.BusinessBillUnderInforDAO;


// auto generated imports
import com.born.insurance.dal.dataobject.BusinessBillUnderInforDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.insurance.dal.daointerface.BusinessBillUnderInforDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/business_bill_under_infor.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisBusinessBillUnderInforDAO extends SqlMapClientDaoSupport implements BusinessBillUnderInforDAO {
	/**
	 *  Insert one <tt>BusinessBillUnderInforDO</tt> object to DB table <tt>business_bill_under_infor</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into business_bill_under_infor(under_info_id,product_id,product_name,insurance_amount,permium_rate,premium_amount,money_type,business_bill_id) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param businessBillUnderInfor
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(BusinessBillUnderInforDO businessBillUnderInfor) throws DataAccessException {
    	if (businessBillUnderInfor == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-BUSINESS-BILL-UNDER-INFOR-INSERT", businessBillUnderInfor);

        return businessBillUnderInfor.getUnderInfoId();
    }

	/**
	 *  Update DB table <tt>business_bill_under_infor</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update business_bill_under_infor set product_id=?, product_name=?, insurance_amount=?, permium_rate=?, premium_amount=?, money_type=?, business_bill_id=? where (under_info_id = ?)</tt>
	 *
	 *	@param businessBillUnderInfor
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(BusinessBillUnderInforDO businessBillUnderInfor) throws DataAccessException {
    	if (businessBillUnderInfor == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-BUSINESS-BILL-UNDER-INFOR-UPDATE", businessBillUnderInfor);
    }

	/**
	 *  Query DB table <tt>business_bill_under_infor</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select under_info_id, product_id, product_name, insurance_amount, permium_rate, premium_amount, money_type, business_bill_id from business_bill_under_infor where (under_info_id = ?)</tt>
	 *
	 *	@param underInfoId
	 *	@return BusinessBillUnderInforDO
	 *	@throws DataAccessException
	 */	 
    public BusinessBillUnderInforDO findById(long underInfoId) throws DataAccessException {
        Long param = new Long(underInfoId);

        return (BusinessBillUnderInforDO) getSqlMapClientTemplate().queryForObject("MS-BUSINESS-BILL-UNDER-INFOR-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>business_bill_under_infor</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from business_bill_under_infor where (under_info_id = ?)</tt>
	 *
	 *	@param underInfoId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long underInfoId) throws DataAccessException {
        Long param = new Long(underInfoId);

        return getSqlMapClientTemplate().delete("MS-BUSINESS-BILL-UNDER-INFOR-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>business_bill_under_infor</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select under_info_id, product_id, product_name, insurance_amount, permium_rate, premium_amount, money_type, business_bill_id from business_bill_under_infor where (1 = 1)</tt>
	 *
	 *	@param businessBillUnderInfor
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<BusinessBillUnderInforDO>
	 *	@throws DataAccessException
	 */	 
    public List<BusinessBillUnderInforDO> findByCondition(BusinessBillUnderInforDO businessBillUnderInfor, String sortCol, String sortOrder, long limitStart, long pageSize) throws DataAccessException {
    	if (businessBillUnderInfor == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("businessBillUnderInfor", businessBillUnderInfor);
        param.put("sortCol", sortCol);
        param.put("sortOrder", sortOrder);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));

        return getSqlMapClientTemplate().queryForList("MS-BUSINESS-BILL-UNDER-INFOR-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>business_bill_under_infor</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from business_bill_under_infor where (1 = 1)</tt>
	 *
	 *	@param businessBillUnderInfor
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(BusinessBillUnderInforDO businessBillUnderInfor) throws DataAccessException {
    	if (businessBillUnderInfor == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-BUSINESS-BILL-UNDER-INFOR-FIND-BY-CONDITION-COUNT", businessBillUnderInfor);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

	/**
	 *  Query DB table <tt>business_bill_under_infor</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select under_info_id, product_id, product_name, insurance_amount, permium_rate, premium_amount, money_type, business_bill_id from business_bill_under_infor where (business_bill_id = ?)</tt>
	 *
	 *	@param businessBillId
	 *	@return List<BusinessBillUnderInforDO>
	 *	@throws DataAccessException
	 */	 
    public List<BusinessBillUnderInforDO> findBusinessBillUnderInfo(long businessBillId) throws DataAccessException {
        Long param = new Long(businessBillId);

        return getSqlMapClientTemplate().queryForList("MS-BUSINESS-BILL-UNDER-INFOR-FIND-BUSINESS-BILL-UNDER-INFO", param);

    }

}